### PR TITLE
[MM-57391]: improved error message moving channels

### PR DESCRIPTION
**Pull request by pacop**
#### Summary

The error reported when moving channels and failing has been improved to show that the problem was the repeated name on the team. The error message has been unified with MM-53756

I have not used the message specified on the [issue](https://github.com/mattermost/mattermost/issues/26607), because I have found that there was another message already on the code for the same error (It was added with MM-53756).

This PR produces the following change:
```
mmctl channel move team2 test-team:wow
Error: 1 error occurred:
        * unable to move channel "wow": A channel with that name already exists on the same team., unique constraint: Name
```

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/26607
Jira https://mattermost.atlassian.net/browse/MM-57391

#### Screenshots

Not apply.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by harshilsharma63 — APPROVED** [review]
Looks good!

**Comment by harshilsharma63** [comment]
Great work @pacop 💪 💪 💪

**Comment by lieut-data** [comment]
Apologies, @harshilsharma63: I've been out for a while, and likely won't get to this review.

**Review by M-ZubairAhmed — APPROVED** [review]

**Pull request merged**
