### PR TITLE
MM-57759: Added mockery support for 1.22

### PR DESCRIPTION
**Pull request by agnivade**
Add mockery support for 1.22.

Fixed the hooks.go file which caused issues in master.

https://mattermost.atlassian.net/browse/MM-57759

### CODE REVIEW

**Comment by agnivade** [comment]
Ben clarified my misunderstanding. I thought the entire Go toolchain would get upgraded that might affect building and testing MM. But that's not the case. All good then :+1:

**Review by hanzei — COMMENTED** [review]
Do the mocks in the enterprise repo also need to get updated as part of this PR or can we do that later? Just want to double-check that the PR doesn't break `master`.

**Comment by agnivade** [comment]
Sorry missed that: https://github.com/mattermost/enterprise/pull/1667

**Review by hanzei — APPROVED** [review]

**Review by hanzei — APPROVED** [review]

**Review by isacikgoz — APPROVED** [review]

**Pull request merged**
