### PR TITLE
[MM-53086] Remove SendWelcomePost A/B test and feature

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary
Remove the SendWelcomePost feature, the A/B test did not give conclusive results.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-53086

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Review by yasserfaraazkhan — APPROVED** [review]
thank you @JulienTant 
I've tested this on spinwick and locally. The welcome post in not seen for admin and user.
the commands /help, /marketplace are working as expected.
Screenshot 2023-06-16 at 8 56 56 PM
Screenshot 2023-06-16 at 8 54 11 PM

**Pull request merged**
