### PR TITLE
[MM-56602] Clicking outside the file preview area doesn't close the modal

### PR DESCRIPTION
**Pull request by oOoBenoitoOo**
#### Summary
As a user, I want to quit the preview mode by clicking outside the doc preview. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-56602
#### Screenshots
|  before  |  after  |
|----|----|
| image| image|

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@oOoBenoitoOo can you please sign the CLA by going through the comment above

**Comment by oOoBenoitoOo** [comment]
@M-ZubairAhmed already done :-) 
image

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Thanks for working on this @oOoBenoitoOo. Everything is working well for the most part, but I did come across an issue with scrolling text file previews.

**What I'm seeing with this PR using a plain text VTT file that has to scroll**
image

**Compared to what is on production:**
image

I also tested with a scrolling txt file:

**What I'm seeing in this PR with a different TXT file that has to scroll**
image

**Compared to what is on production with the same file**
image

This seems to happen with other code file previews as well.

Could you look in to this?

**Comment by oOoBenoitoOo** [comment]
Hi @matthewbirtch,
Thanks, I'm able to reproduce, I'm gonna work on it.

**Review by matthewbirtch — APPROVED** [review]
That fixed it @oOoBenoitoOo. Thanks! Looks good now.

**Review by hmhealey — APPROVED** [review]
Thanks for the PR! I also like that the preview is now centred vertically. I never noticed it before, but the previous positioning of the preview looks weird for code files in the example you posted.

Also, this is something minor, but we generally prefer if you merge upstream changes into your branch instead of rebasing because it makes it easier to see what changed between different review comments. I'm just mentioning it though because I was a bit confused when I saw Matt asked for changes and then approved the PR with no changes in between before I realized what happened. It's not really an issue here though since the code changes are small enough to follow

**Comment by hmhealey** [comment]
Skipping Enterprise CI since this doesn't change server code

**Comment by oOoBenoitoOo** [comment]
thanks @hmhealey (my bad, I did the rework asked by Matt, and squashed them in a single commit so I deleted the previous one with the wrong code)

**Pull request merged**
