### PR TITLE
Forbid users from creating DMs and GMs with remote users

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
This change prevents the application from creating new DMs and GMs when remote users are involved, and prevents as well new posts from being created into preexisting DMs and GMs with remote users created in previous versions.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-60971

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by lindy65 — APPROVED** [review]
I'm going to QA-defer on this PR @mgdelacroix and test post merge

**Review by sbishel — APPROVED** [review]
It doesn't appear that the WebApp relays the error information back to the user. It is in the Console and Network tab. However, that is beyond this PR and we can look at the UI later, if necessary.

**Comment by mgdelacroix** [comment]
@sbishel I'm working on a PR with UI improvements for preexisting DMs and GMs, I want to explore adding some feedback for the errors on this PR there, but there are multiple paths to create a new channel so I agree that it might be better to prioritize that for later

**Comment by sbishel** [comment]
> I'm working on a PR with UI improvements for preexisting DMs and GMs

I don't think this is a big worry. My understanding is they never did work, but weren't really tested. So I doubt there are many existing ones. And they would most likely be in test environments. So I wouldn't spend time here, right now.

> but there are multiple paths to create a new channel

Agreed, but I would just look to do something in the most common path. The `Direct Messages` modal. Again...not for this PR.

**Review by calebroseland — APPROVED** [review]

**Comment by mgdelacroix** [comment]
> So I doubt there are many existing ones. And they would most likely be in test environments [...] The Direct Messages modal. Again...not for this PR.

Got a low hanging fruit improvement PR here https://github.com/mattermost/mattermost/pull/28861, and I've created https://mattermost.atlassian.net/browse/MM-61152 to track showing an error on DM/GM creation

**Pull request merged**
