### PR TITLE
[MM-58406] Migrate tooltips of 'components/custom_status/custom_status_text' to WithTooltip

### PR DESCRIPTION
**Pull request by ahmadJT**
#### Summary
- Migrate tooltips of 'components/custom_status/custom_status_text' to WithTooltip

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/27157

#### Screenshots

|  before  |  after  |
|----|----|
| Screenshot 2024-05-27 at 15 30 30 (2) | Screenshot 2024-05-27 at 15 15 54 |

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
Hi @ahmadJT can you please sign the CLA as per https://github.com/mattermost/mattermost/pull/27168#issuecomment-2133644783

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by sinansonmez — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
verified tool tip for custom status on DM list, mention, top nav bar ✅

**Pull request merged**
