### PR TITLE
remove redundant getUser call

### PR DESCRIPTION
**Pull request by mahmoudfarouq**
#### Summary
This PR removes getting the bot owner because we already got it earlier.

```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM, thanks for the contribution @mahmoudfarouq 🎉

**Comment by mahmoudfarouq** [comment]
Hi @agarciamontoro , can you please check this PR so i can merge it?

**Review by agarciamontoro — APPROVED** [review]
It looks good, thanks!

**Comment by agarciamontoro** [comment]
I think we can actually skip the manual QA step if automated tests pass, since the change is small. @isacikgoz, thoughts?

**Comment by isacikgoz** [comment]
@agarciamontoro agreed, I think E2E tests should be fine.

**Comment by agarciamontoro** [comment]
@saturninoabril, could you take a look at the failing tests? I don't think they're related, but I'd love to have a more experienced pair of eyes on them :)

**Comment by saturninoabril** [comment]
@agarciamontoro Yes, not related to this PR. Those are failing from time to time, except for the one in Playbooks which we'll observe.

**Review by saturninoabril — APPROVED** [review]
LGTM, thanks @mahmoudfarouq!

**Pull request merged**
