### PR TITLE
MM-53475 : Migrate 'components/suggestion/emoticon_provider.test.jsx' to TypeScript

### PR DESCRIPTION
**Pull request by nazrul7711**
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/23931
Jira https://mattermost.atlassian.net/browse/MM-53475

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by nazrul7711** [comment]
hey @M-ZubairAhmed  I have made the PR as per your suggestion but there is this line of code which I couldn't migrate to Typescript 
const customEmojisWithBlocklist = new Map<string, CustomEmoji>([
            ...blocklistedEmojis,

            [
                "not-blocklisted",
                {
                    name: "thumbsdown-custom",
                    category: "custom",
                },
            ]
        ]);
        const emojiMapWithBlocklist = new EmojiMap(customEmojisWithBlocklist);

EmojiMap takes a list of mapped objects which is of key value pair of string CustomEmoji but ...blocklistedEmojis is not an array of CustomEmoji the category of the object is "skintone" which doesn't conform with category:'custom' .Guide me about it.
Further I have also migrated Suggestion.jsx to typescript as it was essential .

**Comment by M-ZubairAhmed** [comment]
@nazrul7711 let me take a look but before can you
- please resolve conflicts so we can run CI
- It seems that you deleted `webapp/channels/src/components/suggestion/emoticon_provider.test.jsx` the file and created a new one. That could be the reason git is seeing that as it, a better way would be just to rename that way git shows correctly that file was renamed and we get correct git diff

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
@nazrul7711 let me take a look but before can you

please resolve conflicts so we can run CI
It seems that you deleted webapp/channels/src/components/suggestion/emoticon_provider.test.jsx the file and created a new one. That could be the reason git is seeing that as it, a better way would be just to rename that way git shows correctly that file was renamed and we get correct git diff

**Comment by nazrul7711** [comment]
hey @M-ZubairAhmed i did not delete any file I just modified them from jsx to tsx. I made two commits for this PR in first commit I forgot to add deleted file hence I made a fresh commit to add deleted file. Anyways tell me how to correct it if I made a mistake

**Comment by M-ZubairAhmed** [comment]
> hey @M-ZubairAhmed i did not delete any file I just modified them from jsx to tsx. I made two commits for this PR in first commit I forgot to add deleted file hence I made a fresh commit to add deleted file. Anyways tell me how to correct it if I made a mistake

Huh I don't know why it didn't pick that up. Anyways can you resolve the conflicts

**Comment by nazrul7711** [comment]
hey let me close this pull request and make a fresh one I think I messed it.

**Comment by nazrul7711** [comment]
closing

**Pull request closed without merging**
