### PR TITLE
MM-56784 - Update wrong documentation link

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Updates a bad help link in System Console

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-56784

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]

**Comment by lindy65** [comment]
Hey @sbishel - I'm seeing a blank page and js.console error after clicking on the `trusted internal connection` link logged into the test server in both a normal and incognito browser window. I saw @cwarnermm comment on the Jira ticket - wondering whether the PR Carrie submitted has not yet propogated?

image


image

**Comment by cwarnermm** [comment]
@lindy65 - If ``mattermost.com/pl/default-allow-untrusted-internal-connections`` resolves correctly for you in a browser, that suggests to me that the issue is code-related and not URL related.

**Comment by sbishel** [comment]
@cwarnermm - Without the UTM data, the link redirects correctly. 
`https://docs.mattermost.com/configure/environment-configuration-settings.html#allow-untrusted-internal-connections`
However, if you include any UTM data it redirects to 
`**https://docs.mattermost.com/administration/config-settings.html#allow-untrusted-internal-connections-to**?utm_source=mattermost&utm_medium=in-product&utm_content=abstract_outgoing_webhook&uid=ttdccg1i9tbh9pu513yftqb81w&sid=k94qhb41qpdb5cfgk3xuagygso`

I don't know how the Docs repository works, but this appears to be an issue with the redirects. From the code side, I can change it from a `<ExternalLink>` (which adds the UTM data) to an anchor tag and then it won't add UTM information, but I don't think that is the correct fix.

**Comment by cwarnermm** [comment]
I suspect that we may need to loop @emdecr into this conversation to understand how the UTM parameters work.

We have other instances of help links in-product (like the help link for custom slash commands) that work as expected; I wonder if there's a common pattern among those working that would point us to the correct resolution.

**Comment by emdecr** [comment]
Hey @cwarnermm - sorry about the delay. I think this relates to a few duplicates in our redirect rules. I just a did a prelim sweep and found a few (and mitigated). Do the links work as expected now? TY!

**Comment by cwarnermm** [comment]
``https://docs.mattermost.com/administration/config-settings.html#allow-untrusted-internal-connections-to?utm_source=mattermost&utm_medium=in-product&utm_content=abstract_outgoing_webhook&uid=ttdccg1i9tbh9pu513yftqb81w&sid=k94qhb41qpdb5cfgk3xuagygso`` isn't resolving as I'd expect yet, no, @emdecr.

**Comment by sbishel** [comment]
Oops...that's the wrong link, @cwarnermm 

`https://mattermost.com/pl/default-allow-untrusted-internal-connections?utm_source=mattermost&utm_medium=in-product&utm_content=abstract_outgoing_webhook&uid=ttdccg1i9tbh9pu513yftqb81w&sid=k94qhb41qpdb5cfgk3xuagygso` does now resolve correctly and works now in the Spinwick...

@lindy65 - ready for retest...
Thanks @emdecr

**Comment by cwarnermm** [comment]
HA! Sure was the wrong link! That's what I get for multi-tasking! :) Thanks, @sbishel!

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
