### PR TITLE
Fix 55496

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Fix 55496

#### Ticket Link
Fix https://mattermost.atlassian.net/browse/MM-55496

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by jupenur — APPROVED** [review]
Some stray comments in the test that you might want to remove. Otherwise looks good to me.

**Comment by devinbinnie** [comment]
@yasserfaraazkhan Not sure if this needs QA or not, feel free to defer.

**Pull request merged**
