### PR TITLE
MM-54004 migrate HeaderFooterNotLoggedIn as functional component

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Follow up PR to https://github.com/mattermost/mattermost/pull/24214#discussion_r1289559256

- Migrated the HeaderFooterNotLoggedIn component to functional so it's easier to use `formatMessage` through `useIntl`.
- Migrated the unit test from Enzyme to React testing library

Test steps:
- Go to reset password page and verify that the footer works as is.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-54004

#### Screenshots
Screenshot 2023-08-10 at 1 02 23 PM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by lindy65** [comment]
Thanks @saturninoabril 

1. When clicking on "About" on password reset page, I get a 404
image

2. I also get a 404 when clicking on "Help"
image

Don't think it's related to your PR though as these links also give a 404 on the Log In page
image

**Comment by saturninoabril** [comment]
Thanks and good catch @lindy65! Those are not related to this PR but it's a small fix so I included in the recent commit.

1. "About" link issue was a typo error from https://github.com/mattermost/mattermost/pull/23694, together with "High Availability Cluster" link. (fixed)

2. "Help" link issue seemed to be not related to app but likely to the docs website. @cwarnermm @emdecr Could you please help check?
- The footer linked to `https://mattermost.com/pl/help/?utm_source=mattermost&utm_medium=in-product&utm_content=footer&uid=&sid=kq13tjmwqbbstproc8po8wncqh` seemed to be correct.
- But a redirect to `https://mattermost.com/default-help/?utm_source=mattermost&utm_medium=in-product&utm_content=footer&uid=&sid=kq13tjmwqbbstproc8po8wncqh` resulted to page not found.

**Comment by saturninoabril** [comment]
It's the default value in config and so I think once the server is running, it will use whatever is already in the config.json which is the case here after restarting the server (even with the new default).

Screenshot 2023-08-11 at 11 26 27 AM

Option to verify might be to tear down the test server and spin up a new one again then see if it fixes the issue.

**Comment by saturninoabril** [comment]
About link should be resolved with the newly spun up test server while Help link to be addressed separately. Please file a ticket for Carrie/Emily to address (more likely but let's hear from them).

**Comment by lindy65** [comment]
Ah, I thought that the server would update after the commit.  Thanks for spinning up a new one @saturninoabril 

The "About" link is fixed on the Log in and Password Reset page

I'll wait to see whether Carrie/Emily would like a ticket to fix the "Help" links.

**Comment by emdecr** [comment]
Thanks for the flag y'all. I think I see what's going on.

`https://mattermost.com/pl/help/` is definitely covered under our pl list and updated redirects, but `https://mattermost.com/default-help/` is not and the rule needs to be updated. 

Just updated it and https://mattermost.com/default-help/?utm_source=testing&utm_medium=testing&utm_content=footer&uid=&sid=dummyserver (or the original URL you sent) should work now?

**Comment by lindy65** [comment]
Thanks Carrie and Emily!  

The "Help" links on both the Log in and Password Reset pages work now

I'm seeing though that both "Help" and "About" go to [docs.mattermost.com](https://docs.mattermost.com/?utm_source=mattermost&utm_medium=in-product&utm_content=footer&uid=&sid=fekeyztryiydprrqbjhkjqo8aa)

This seems kinda weird/redundant?  I think "About" should go to a page that speaks about who Mattermost is?  Just my 2c worth 😅

**Review by lindy65 — APPROVED** [review]
Thanks @saturninoabril - looks good to me now 👍

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Comment by saturninoabril** [comment]
> I'm seeing though that both "Help" and "About" go to [docs.mattermost.com](https://docs.mattermost.com/?utm_source=mattermost&utm_medium=in-product&utm_content=footer&uid=&sid=fekeyztryiydprrqbjhkjqo8aa)

> This seems kinda weird/redundant? I think "About" should go to a page that speaks about who Mattermost is? Just my 2c worth 😅

Echoing the same thoughts as Lindy. @cwarnermm @emdecr Please confirm if that's expected.

(I'm merging this now.)

**Comment by cwarnermm** [comment]
It is expected that both Help and About take users to the docs landing page via docs.mattermost.com. I also agree with Lindy that the About link may better serve our customers by going to https://docs.mattermost.com/overview/index.html instead. @emdecr - Is this a pl link change that you can help us with?

**Comment by emdecr** [comment]
Thanks y'all – I just adjusted the `https://mattermost.com/default-about/` to redirect to `https://docs.mattermost.com/overview/index.html`. Lemme know if anything. TY!

**Pull request merged**
