### PR TITLE
Adding automaxprocs to automatically set the GOMAXPROCS based on container limits

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Adding automaxprocs to automatically set the GOMAXPROCS based on container
limits to ensure we are not generating more threads that are really useful to
process the existing load in the application.

#### Ticket Link
Not yet

#### Release Note
```release-note
Added automaxprocs to improve the cpu performance on containerized environments
```

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
I have known about this since the uber blog post came out. My thinking is that our cloud workload is not necessarily what Uber experiences.

First of all, we should verify if there is a visible performance issue with GOMAXPROCS over-allocation. And then measure the impact of this change.

I am hesitant to add this without solid numbers to back it up. Will defer to the cloud platform team for further thoughts.

**Comment by gabrieljackson** [comment]
We can manually alter some test Mattermost instances to reflect the change as a validation step. I believe we won't see any difference with mostly-idle workspaces though, so we would need to devise some sort of test to exercise the change. Another option is to alter the `community` server first if we think that will provide the data you are interested in.

**Comment by agnivade** [comment]
Just saw the convo in hub. I think it would be totally fine if we want to control the `GOMAXPROCS` env var in some pods via the operator and see if there's any benefit or not.

I am a bit hesitant to include this code especially because MM is used in a lot of non-cloud environments as well. And it seems like explicitly setting the `GOMAXPROCS` value is a cleaner solution rather than globally including code that only gets to run in a cloud env.

**Comment by gabrieljackson** [comment]
I will defer to others on whether to include this directly in Mattermost or not. I do think there is a chance that this is a very good default to have in place for containerized Mattermost instances running outside of the Operator, but we can at least review data from some initial testing of the env var if we want.

**Comment by jespino** [comment]
@agnivade I don't have an strong opinion about that, but AFAIK, that code, as you said only affect containerized instances, so it shouldn't have a impact in the on-prem instances,. I don't want on push in any direction about including it or not, I suggested to apply this to our cloud to see if that has any impact, if that is the case we can decide later if we want to expand that to other installations through this approach, through documenting it, through the operator, or any other approach.

**Comment by agnivade** [comment]
Yep, totally agree to run a couple of tests via setting GOMAXPROCS to 2 in the cloud and monitor for any impact. I think that should be the first step here. Then we can see whether to conditionally include this, or document this somewhere as part of the operator.

**Comment by jespino** [comment]
Closing this for now.

**Pull request closed without merging**
