### PR TITLE
Moved some common SQL function to public utils as they are used in plugins

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Moved some common SQL function to public utils as they are used in plugins

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-57122

#### Release Note
```release-note
Moved following functions from server to public utils-

1. ResetReadTimeout
2. AppendMultipleStatementsFlag
3. SetupConnection
4. SanitizeDataSource
```

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
Having a common util bucket for all random things is an anti-pattern. Please create a sub-package called `utils/sql`.

**Comment by harshilsharma63** [comment]
> Having a common util bucket for all random things is an anti-pattern. Please create a sub-package called `utils/sql`.

Done.

**Review by agnivade — APPROVED** [review]
Maybe good to check whether there was any other client using these functions, and give them a heads up that it has moved places.

Also please add it in the release notes that new functions got added. Thanks!

**Comment by harshilsharma63** [comment]
> Maybe good to check whether there was any other client using these functions, and give them a heads up that it has moved places

@agnivade what do you mean by client? A plugin? A 3rd party repo?

**Comment by harshilsharma63** [comment]
> SanitizeDataSource

Done. Looks like its only Focalboard that calls them.

**Review by larkox — APPROVED** [review]

**Pull request merged**
