### PR TITLE
Bump Apps plugin version to 1.2.2

### PR DESCRIPTION
**Pull request by hanzei**
#### Ticket Link
https://github.com/mattermost/mattermost-plugin-apps/pull/473

#### Release Note
```release-note
Include v1.2.2 of Apps plugin
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]

**Comment by DHaussermann** [comment]
@hanzei something a little bit strange is happening. When I test fresh and upgrade paths with the `/cloud` tool. This PR works exactly as expected.

However you can see on the test server ☝️ that I'm still getting `1.2.1`. My best guess is that for some reason on these servers the marketplace release is superseding the pre-packaged release.    

Can we merge https://github.com/mattermost/mattermost-marketplace/pull/377 and then I'll see if this gets resolved?

**Comment by DHaussermann** [comment]
@hanzei https://github.com/mattermost/mattermost-marketplace/pull/377 has now been merged and on other /cloud test servers I can see the affect on the production marketplace...
image
(other server) 

But on the spin-up for this PR https://mattermost-pr-23622.test.mattermost.cloud/ I still see `v1.2.1` Any thoughts about what's happening? 

It seemed to work fine with `/cloud` is there a chance that applying the label here is grabbing the wrong commit?

**Comment by hanzei** [comment]
@DHaussermann The test server in https://mattermost-pr-23622.test.mattermost.cloud/ now correctly shows App v1.2.2 as installable via the Marketplace. As discussed offline, it's not enabled by default as designed. Are we good to merge this PR?

**Review by DHaussermann — APPROVED** [review]
Tested and passed

This PR always worked as expected when testing upgrade, fresh install and installing without remote marketplace access. 
LGTM!

The only issue was the server that git created when the label was applied. This now solved.

Please merge.

**Pull request merged**
