### PR TITLE
Remove remaining references to model.NewXX

### PR DESCRIPTION
**Pull request by agnivade**
And we remove the deprecated functions to force uses
only of the new function.
```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
There are also cases in the test files such as `ptrStr(string)` or similar functions, wondering if we should go after those as well.

**Comment by agnivade** [comment]
Yes definitely. Good call. Will take care of them in a next PR.

**Review by cpoile — APPROVED** [review]
:tada:

**Comment by agnivade** [comment]
Does not need e2e tests. Unit tests are enough for this.

**Pull request merged**
