### PR TITLE
[MM-47821]: fix searchUserCmdF to return proper errors

### PR DESCRIPTION
**Pull request by costa-neto**
#### Summary
Updates `searchUserCmdF ` function to return a non-zero return code if the function fails and write the respective tests.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/21465
Jira https://mattermost.atlassian.net/browse/MM-47821

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by mgdelacroix — APPROVED** [review]
LGTM! Thanks @costa-neto :sparkles:

**Comment by wiggin77** [comment]
@costa-neto it looks like one of the unit tests is failing.

**Comment by costa-neto** [comment]
@wiggin77 I think it's fixed now! Could you please review it again?

**Comment by costa-neto** [comment]
Hi @wiggin77, for some reason when I tried running `make -C server test-mmctl-unit` no Errors were presented. Now it did work, and I guess everything should work.

DONE 705 tests, 1 skipped in 89.816s

**Review by wiggin77 — APPROVED** [review]
Looks great, :+1:   Thanks @costa-neto for sticking with it and getting the unit tests working.

**Pull request merged**
