### PR TITLE
Made emoji size in scale with text size in channel header

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Made emoji size in scale with text size in channel header

#### Ticket Link
Jira https://mattermost.atlassian.net/browse/MM-52992

#### Release Note
```release-note
Made emoji size in scale with text size in channel header
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
.8 wow 👀

**Comment by harshilsharma63** [comment]
> .8 wow 👀

He he, yeah, kept the same ratio of text font size and emoji font size in channel header as in posts. That resulted to font size of 18.8 px (rounded up two decimal places) for 15px text font size.

**Comment by M-ZubairAhmed** [comment]
> > .8 wow 👀
> 
> 
> 
> He he, yeah, kept the same ratio of text font size and emoji font size in channel header as in posts. That resulted to font size of 18.8 px (rounded up two decimal places) for 15px text font size.

In that case would it be easier and more understandable to use calc(font size1/font size 2) ?

**Comment by abhijit-singh** [comment]
@harshilsharma63 I don't see a difference in sizing between what's on community and what's on the test server. Are the changes getting applied?
image

**Comment by harshilsharma63** [comment]
@abhijit-singh there is a 2.2 px difference. The new code makes emoji's 2.2px smaller than before, making them the same scale relative to the font size in center channel. Now emoji size everywhere is 28.5% of font size of text.

Screenshot 2023-06-20 at 12 32 52 PM
Screenshot 2023-06-20 at 12 32 59 PM
Screenshot 2023-06-20 at 12 34 51 PM

**Review by abhijit-singh — APPROVED** [review]

**Pull request merged**
