### PR TITLE
[MM-55096] Introduce generic StoreResult

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
`StoreResult` is the standard way to fetch results asynchronous from the store. Given that it's a tool that works with all store results, it had to use an `interface{}` to store the result.

Since generics are a thing in go now, we can use `StoreResult` in a type-safe way. This PR introduces a generic `GenericStoreResult`. This allows for a gradual migration towards using `GenericStoreResult` without having to do it all at once.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-55096

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM

**Review by agarciamontoro — APPROVED** [review]
Neeeat, thanks! This is really cool, and I like the way you approached it so that we don't have to change the whole thing in one go.

Do we have plans to tackle the rest of the migration so that the period where we have both `StoreResult` and `GenericStoreResult` is as short as possible?

**Comment by hanzei** [comment]
> Do we have plans to tackle the rest of the migration so that the period where we have both `StoreResult` and `GenericStoreResult` is as short as possible?

Surely! I'm going to open a couple of HW tickets and hope the community picks them up. If that doesn't happen, I will tackle the changes myself.

**Comment by agnivade** [comment]
Nice work Ben!

**Pull request merged**
