### PR TITLE
Refactor/migrate/autocomplete database speabase specs to ts

### PR DESCRIPTION
**Pull request by hereje**
#### Summary

Migrate js files in `e2e-tests/cypress/tests/integration/channels/autocomplete/database/` to typescript

- convert js spec files to typescript
- update data types accordingly

#### Ticket Link

#21301

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM, but I'll defer to @saturninoabril for most of the review.
Thanks @hereje!

**Comment by saturninoabril** [comment]
@hereje Thanks for your contribution! It failed on test (`opensearch` / `TestBulkProcessor`) not related to the changes here. Could you update your branch to latest? Then we'll see if it resolves the issue.

**Comment by saturninoabril** [comment]
Hmm, nvm, no action needed for now and seemed to be happening to other PRs.

**Review by saturninoabril — APPROVED** [review]
Thanks @hereje, LGTM!

**Pull request merged**
