### PR TITLE
[mmctl] fix missing parenthesis in webhook list

### PR DESCRIPTION
**Pull request by intrigus-lgtm**
#### Release Note

```release-note

```

### CODE REVIEW

**Review by hanzei — CHANGES_REQUESTED** [review]
Thanks for the fix!

Can a test cover the fix?

**Comment by intrigus-lgtm** [comment]
> Thanks for the fix!
> 
> Can a test cover the fix?

I don't think so, but I'm also not familiar with the code.
I mean it's just a single parenthesis.

**Comment by hanzei** [comment]
@intrigus-lgtm Could you please sign the [CLA](http://www.mattermost.org/mattermost-contributor-agreement/)? Thanks!

**Comment by intrigus-lgtm** [comment]
> @intrigus-lgtm Could you please sign the [CLA](http://www.mattermost.org/mattermost-contributor-agreement/)? Thanks!

Do I really have to sign a CLA for a parenthesis?
I hereby waive any rights to this change and you can do whatever you want with it.

**Comment by hanzei** [comment]
Sorry @intrigus-lgtm, due to legal constraints, every contributor is required to sign the CLA. If you don't want to sign it, feel free to close the PR.

I still appreciate your contribution.

**Pull request closed without merging**
