### PR TITLE
Remove gobom files

### PR DESCRIPTION
**Pull request by esarafianou**
#### Summary
Removing the gobom files as we're deprecating deptrack and moving to Snyk

#### Ticket Link
https://mattermost.atlassian.net/browse/SEC-5808

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by jupenur — APPROVED** [review]

**Comment by esarafianou** [comment]
@lieut-data can I get you as a second approver? We're moving to another solution for dependency vulnerability tracking

**Review by lieut-data — APPROVED** [review]
Thanks for the heads up, @esarafianou!

**Comment by esarafianou** [comment]
@lieut-data Do you think that I can skip the 2 failing checks and merge? They are postgres related which are unrelated to this PR.

**Comment by lieut-data** [comment]
No objection to merging as-is, @esarafianou -- agree they seem unrelated.

**Pull request merged**
