### PR TITLE
Bump prepackage Jira plugin version to 4.1.0

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
Prepackage Jira plugin v4.1.0.

#### Release Note
```release-note
Prepackage Jira plugin version [v4.1.0](https://github.com/mattermost/mattermost-plugin-jira/releases/tag/v4.1.0).
```
Prepackage Jira plugin version [v4.1.0](https://github.com/mattermost/mattermost-plugin-jira/releases/tag/v4.1.0).

### CODE REVIEW

**Review by hanzei — APPROVED** [review]

**Comment by hanzei** [comment]
@raghavaggarwal2308 Please merge `master` into your branch. That should fix the CI issue.

**Comment by raghavaggarwal2308** [comment]
@hanzei Updated

**Comment by mickmister** [comment]
@cwarnermm I don't think so. We usually don't include info about the plugin releases in the product docs. Maybe we can put them in marketing announcements though. Like in the product update videos that @jespino is creating

**Pull request merged**
