### PR TITLE
MM-59854 Fully allow at mentions in message attachment field values and add E2E tests

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
Since we allow Markdown in various fields when rendering message attachments, those fields appear to support at-mentions, but that was misleading because the server didn't know to process them for at mentions, and the client wouldn't always load users properly for those at mentions. Now it does that for the value of message attachment fields as reported in the ticket. I also made sure that at mentions won't appear in some other parts of message attachments to avoid this sort of problem happening in the future.

Supports at mentions:
- Message text
- Message attachment text
- Message attachment pretext
- Message attachment field values

Doesn't support at mentions:
- Message attachment title
- Message attachment field titles

#### Ticket Link
MM-59854

#### Release Note
```release-note
Added full support for at mentions in the values of fields in message attachments
```

### CODE REVIEW

**Review by harshilsharma63 — APPROVED** [review]
Nice!

**Comment by hmhealey** [comment]
@harshilsharma63 I looked into how at-mentions render in message attachments in email notifications, and it turns out that we don't actually render at-mentions differently from plain text in emails, so nothing needs to be done here

**Review by calebroseland — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
verified that the notification is recieved when a bot mentions a user in the message

Screenshot 2024-09-11 at 3 04 55 PM
Screenshot 2024-09-11 at 3 05 19 PM
Screenshot 2024-09-11 at 3 08 58 PM

tagging @DHaussermann to cross verify if any case is missed.

**Comment by hmhealey** [comment]
@DHaussermann Did you want to double check this before it goes in, or are we good to merge it and you test after?

**Comment by DHaussermann** [comment]
Sorry @yasserfaraazkhan I somehow missed the ping. 

Yes, @hmhealey I'd be happy to take a quick look here.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
As a precaution, I took a second look here using the data that came from a 3rd party integration where the issue was first reported. 
Confirmed the payload generated by the integration will now trigger a mention when it hits a webhook thanks to the inclusion of `field.Value`.

LGTM!

**Comment by hmhealey** [comment]
Thanks Dylan, and no worries! I'm glad to get this one thoroughly tested since mentions are important

**Pull request merged**
