### PR TITLE
Move Elasticsearch to source available :tada: :tada: 

### PR DESCRIPTION
**Pull request by agnivade**
```release-note
NONE
```

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
Thanks @agnivade! I'm glad that making this source available will simplify our ongoing efforts to support both Elasticsearch proper and OpenSearch. This is a good change to unblock engineering overhead!

**Comment by agnivade** [comment]
@lieut-data - Question on the license. I see that the license header on enterprise code is different from our open source code, and that is why the vet check is failing.

```
seen:
	// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
	// See ENTERPRISE-LICENSE.txt and SOURCE-CODE-LICENSE.txt for license information.

	expected:
	// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
	// See LICENSE.enterprise for license information.
```

Is it expected to change the license header?

**Comment by lieut-data** [comment]
> Is it expected to change the license header?

Yes, that's correct @agnivade -- we'll need to move these under the source available license framework, which points at that root file to distinguish from primary license on the remaining code.

**Comment by agnivade** [comment]
Gentle ping @cpoile

**Review by cpoile — APPROVED** [review]
Sorry, didn't see this for some reason (head down mode on blogs). This is awesome, thanks!

**Pull request merged**
