### PR TITLE
Mm 24504 api favicon update restore old url path

### PR DESCRIPTION
**Pull request by IronOnet**
#### Summary

This pull request fixes a regression introduced by https://github.com/mattermost/mattermost/issues/24504 by removing the "static" folder in the favicon's url path definition the folder duplication issue stopped occuring in the dev environment but introduced a breaking change in production since the favicon no longer loads in production, I have restored the old favicon url path definition.

#### Ticket Link

 https://mattermost.atlassian.net/browse/MM-54449

#### Screenshots

Cfr Issue: https://github.com/mattermost/mattermost/issues/24504

-->

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
Thanks, @IronOnet. I'm just seeing a /new/ `favicon.ico` file here, vs. a revert of the old path. Can you confirm all the changes you're wanting are here?

**Comment by IronOnet** [comment]
@lieut-data I confirm..

**Comment by lieut-data** [comment]
@IronOnet, hmm, I was expecting to see a revert akin to:

```diff
- <link rel="shortcut icon" href="./favicon.ico">
+ <link rel="shortcut icon" href="./static/favicon.ico">
```

That's what's failing to load:
CleanShot 2023-09-14 at 15 04 08@2x

Or maybe I'm misunderstanding the problem?

**Comment by IronOnet** [comment]
@lieut-data indeed, the third commit reverts back to the old path, I can see from my side that some checks haven't passed yet for the third commit, I don't know if you can see the third commit of this PR from your side

**Comment by lieut-data** [comment]
@IronOnet, so after merging `master` into this branch, it looks like the net diff is empty. Perhaps your origin branch was out of date?

**Comment by IronOnet** [comment]
@lieut-data let me check it out

**Comment by IronOnet** [comment]
@lieut-data  @amyblais I checked out from the wrong branch, I've created a new PR, check it out here https://github.com/mattermost/mattermost/pull/24559

**Pull request closed without merging**
