### PR TITLE
feat: Add tooltips to channel info RHS top buttons

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Add tooltips to the buttons shown in the channel info RHS.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-61528

#### Screenshots
https://github.com/user-attachments/assets/df397b5d-a068-407f-b6e3-6c55acf2345c

#### Release Note
```release-note
Add tooltips to the buttons shown in the channel info RHS.
```

### CODE REVIEW

**Comment by matthewbirtch** [comment]
Hey @lieut-data quick question: most of our tooltips have a delay (300ms I think). Can we add that to these as well?

**Comment by lieut-data** [comment]
Absolutely, thanks @matthewbirtch -- done :)

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by cpoile — APPROVED** [review]
Awesome, nice clear tests too. Thanks @lieut-data!

**Review by matthewbirtch — APPROVED** [review]
Thanks @lieut-data!

**Comment by lieut-data** [comment]
@lindalumitchell, with e2e tests added and passed, anything to do from QA to merge this one?

**Comment by lieut-data** [comment]
Thanks, @lindalumitchell! @matthewbirtch, was there a standard we adopted for the originally proposed text? I could also loop in Carrie to get her feedback?

**Comment by matthewbirtch** [comment]
> Thanks, @lindalumitchell! @matthewbirtch, was there a standard we adopted for the originally proposed text? I could also loop in Carrie to get her feedback?

@lindalumitchell in the channel header context, I think it's more obvious that it applies to the channel since it's right next to the channel name.

The new text I proposed was to bring clarity that the actions in the RHS applied to the active channel since they are a little more disconnected from the channel name in the RHS context. So I opted for `Add this channel to favorites` and `Mute notifications for this channel`, etc.

They do feel a bit long actually now that we're talking about it. @cwarnermm do you have any recommendatinos on this?

**Comment by cwarnermm** [comment]
Great catch, @lindalumitchell! I agree with @matthewbirtch that the 2 tooltips for favorites can differ based on context and UI proximity/relevance.

For all tooltip text, our [standard](https://handbook.mattermost.com/operations/research-and-development/product/technical-writing-team-handbook/user-interface-text-guidelines#guidelines-for-capitalization) is sentence case with no punctuation (where only the first letter of the first word is capitalized). We capitalize terms within the tooltip only when absolutely necessary (for official product names), but not for feature names (such as ``Favorites``).

**Comment by lieut-data** [comment]
Thanks, @cwarnermm, @lindalumitchell & @matthewbirtch! @lindalumitchell, as I read it, these new messages are :+1:, but we might want to revisit other tooltip text to comply going forward. Thoughts?

**Comment by matthewbirtch** [comment]
> Thanks, @cwarnermm, @lindalumitchell & @matthewbirtch! @lindalumitchell, as I read it, these new messages are 👍, but we might want to revisit other tooltip text to comply going forward. Thoughts?

Yep, I think that's right

**Review by lindalumitchell — APPROVED** [review]
Thanks all! This one looks good to me then. 👍

**Pull request merged**
