### PR TITLE
Increased default payload limit from 100 kB to 300 kB

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Increased default payload limit from 100 kB to 300 kB

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-57572

#### Release Note
```release-note
Increased default payload size limit (setting `MaximumPayloadSizeBytes`) from 100 kB to 300 kB
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by esarafianou — APPROVED** [review]

**Comment by amyblais** [comment]
@harshilsharma63 Does this need to be backported?

**Comment by harshilsharma63** [comment]
@amyblais yes, we should cherrypick this.

**Comment by cwarnermm** [comment]
@harshilsharma63 - This config isn't yet documented (docs gap). Is this a ``config.json``-only config setting, or something an admin can expect to access via the System Console too?

**Comment by harshilsharma63** [comment]
> @harshilsharma63 - This config isn't yet documented (docs gap). Is this a `config.json`-only config setting, or something an admin can expect to access via the System Console too?

@cwarnermm its a config only setting. Its not accessible via the system console. Anything I can do to help add docs for this?

**Comment by cwarnermm** [comment]
Thanks, @harshilsharma63! What section in the ``config.json`` can admins find this configuration setting? Looks like the default value is 300 kB?

**Pull request merged**
