### PR TITLE
Use generics in utils.Merge

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
`utils.Merge` is a great place that can benefit from the use of generics. This PR introduces a type save version of `utils.Merge`, which uses less `reflect` code and is easier to read.

#### Ticket Link
None

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
Brilliant

**Review by cpoile — APPROVED** [review]
Nice!

**Pull request merged**
