### PR TITLE
[MM-61693] Only check for LDAP info if LDAP is enabled during Support Packet generation

### PR DESCRIPTION
**Pull request by hanzei**
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-61693

#### Release Note

```release-note
Fixed a warning in the Support Packet about an unreadable LDAP server even if LDAP is disabled
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]

**Review by pvev — APPROVED** [review]
Thanks @hanzei 🎉

**Comment by hanzei** [comment]
@DHaussermann QA test steps are in the ticket. Please take a look. Thanks!

**Comment by DHaussermann** [comment]
@hanzei maybe I see an issue here. 
Once I deployed this branch I no longer see the warning when my LDAP is unreachable. However I can not make the warning return now even if LDAP is active.

image

Can you repro this?
1. Enable the 2 LDAP flags 
2. Ensure the LDAP server is invalid
3. Download the support package
**Observed**: Still no warning of LDAP.

**Comment by hanzei** [comment]
@DHaussermann Hm, that is strange.

Can you please double-check that you saved the LDAP settings? Can you also check that the port is set to something non-sensical, like port 9999?

**Comment by hanzei** [comment]
CI error is unrealted

**Comment by DHaussermann** [comment]
@hanzei I had checked the config file to ensure the save worked and restarted the server.
image

But yes, happy to take another look now.

**Comment by DHaussermann** [comment]
@hanzei some of the testing yesterday was inaccurate. It seems the support package may not reflect the current state of the config if it contains recent changes. It 1 case it seems even after a restart the data in the warning file may not be accuare yet but them after a few min the data had changed.  

Can you tell me a bit more about how the support file is generated? Is there a specific action that prompts the creating of a new one or a certain time interval where it serves you the same support package if one was created recently?

**Pull request merged**
