### PR TITLE
[MM-47306] Migrate /enterprise/integrations e2e tests to TypeScript

### PR DESCRIPTION
**Pull request by hereje**
#### Summary

Migrate incoming webhook spec.js to typescript

- convert js file to ts
- update imports

#### Ticket Link

Fixes: #21321

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by yasserfaraazkhan — APPROVED** [review]
🎉

**Review by M-ZubairAhmed — APPROVED** [review]

**Pull request merged**
