### PR TITLE
integrating WIP-languages

### PR DESCRIPTION
**Pull request by ctlaltdieliet**
#### Summary
Integrating the WIP languages into Shipped
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by ctlaltdieliet** [comment]
cc @lieut-data

**Comment by lieut-data** [comment]
I've fixed an issue with `mmgotool` stumbling over the "empty" `{}` WIP translation files (normally they look like `[{...}, {...}]`, and verified the cloud server just keeps working with the supported languages. Proposing we test this organically on community going forward and will merge now.

**Comment by enahum** [comment]
the server does not seem to start cause of multiple errors in different translation files.. I'll try and submit a PR with the fixes early tomorrow morning if it hasn't been addressed

**Comment by lieut-data** [comment]
Thanks, @enahum! I'm seeing these changes live on community, and I can't currently reproduce locally. Are you able to share the errors in case there's an edge case I missed when I changed the logic to ignore unsupported files with https://github.com/mattermost/mattermost/pull/24308?

**Comment by enahum** [comment]
Ok apparently my problem was that I did not recompile the binary. Now that being said, there are translation files with errors.

for example sl.json
```
{
    "id": "api.post.update_post.permissions_details.app_error",
    "translation": "Že izbrisan id={{. PostId}}"
  },
  ```
  notice that {{. PostId}} should be {{.PostId}}, this is one of many examples

**Comment by lieut-data** [comment]
@enahum, thanks for confirming! @calebroseland, these are WIP languages, so it's "fine" to be iterating, but I seem to recall you had an idea for doing some kind of syntax checking on the weblate side? Maybe there's a way we can enforce this there.

**Pull request merged**
