### PR TITLE
MM-51858 Update Workspace Deletion Telemetry

### PR DESCRIPTION
**Pull request by ConorMacpherson**
#### Summary

During workspace deletion, the front end sends a telemetry event upon successful deletion.
However, the number of deletion notifications and telemetry event counts do not match

See Looker: https://mattermost.looker.com/looks/1033?toggle=fil
See Notifications (current count as of March 31, 2023: 49): https://community.mattermost.com/private-core/pl/3edwkjj9fbypuk19c9wdgqgffy

After investigating, it appears that the front-end telemetry event sometimes does not execute. To resolve this, we are removing the telemetry event (`self_serve_workspace_deletion_completed`) from the front end and will rely on the telemetry event (`delete_workspace_feedback`) in the backend to check for completed workspace deletions. 

#### Ticket Link

[MM-51858](https://mattermost.atlassian.net/browse/MM-51858)

#### Release Note

```release-note
NONE
```

[MM-51858]: https://mattermost.atlassian.net/browse/MM-51858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by neallred — APPROVED** [review]

**Review by AGMETEOR — APPROVED** [review]

**Comment by AGMETEOR** [comment]
@ConorMacpherson might need to tag data engineering team. See https://github.com/mattermost/mattermost-server/pull/22200#discussion_r1144823143

**Comment by ConorMacpherson** [comment]
@catalintomai trying to reach out to the data-eng team here. We're removing this telemetry event and want to make sure that proper procedures are followed here.

The original event when implemented, was on occasion, not executed. Please let me know if there's anything else needed before merging this and removing the event. I didn't see anything covering deletion of events in the telemetry handbook.

**Comment by catalintomai** [comment]
> self_serve_workspace_deletion_completed

Hi @ConorMacpherson , thanks you for reaching out! There are no mentions to event removal workflows in the Telemetry Handbook since there really are no tasks to be done by the product devs other than removing references to the event from the codebase AND from the documentation header in the codebase file (if it has been documented there).
On the data pipeline side, we have opened  https://mattermost.atlassian.net/browse/MM-52502 to address potential clean-up, however, the event being added recently I don't foresee any significant work.

**Pull request merged**
