### PR TITLE
Promote GIF picker, custom groups and message priority out of Beta

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Remove the Beta label for: 

- GIF Picker
- Custom User Groups 
- Message Priority

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-57451
https://mattermost.atlassian.net/browse/MM-56830

#### Release Note

```release-note
Promote GIF picker, custom groups and message priority out of Beta
```

### CODE REVIEW

**Comment by esethna** [comment]
@marianunez can we get rid of the "give feedback" button in the post priority pop-over?

**Review by esethna — APPROVED** [review]
looks good otherwise!

**Comment by marianunez** [comment]
> can we get rid of the "give feedback" button in the post priority pop-over?

Removed

**Comment by marianunez** [comment]
> can we get rid of the "give feedback" button in the post priority pop-over?

@esethna @matthewbirtch Without the Beta label and the `Give Feedback` it does look a bit narrow. Just wanted to double check we are good with that:

Screenshot 2024-07-25 at 8 01 21 PM

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by cwarnermm — APPROVED** [review]
Thanks, @marianunez!

**Comment by cwarnermm** [comment]
Do we have feature discovery modals for any of these in-product?

**Comment by marianunez** [comment]
> Do we have feature discovery modals for any of these in-product?

For these ones we don't because the feature discovery shows when the feature has a section of it's own in the System Console.

**Comment by matthewbirtch** [comment]
> > can we get rid of the "give feedback" button in the post priority pop-over?
> 
> @esethna @matthewbirtch Without the Beta label and the `Give Feedback` it does look a bit narrow (probably because I was used to the wider modal). Just wanted to double check we are good with that:

Thanks @marianunez

1. It looks too narrow in the first image. Menus are supposed to have a `min-width: 144px`, and I think we should add `gap: 24px;` to the `ItemButton` so the checkmark never appears so close to the text like it does here:
image

2. And it looks too wide in the second screenshot. Can we have a`max-width: 320px` on this?

**Comment by marianunez** [comment]
> 1. It looks too narrow in the first image. Menus are supposed to have a `min-width: 144px`

@matthewbirtch it's actually 144.39px (so it was just over the min) but with the change of the gap of the checkbox it's now a bit over 161px. How does this look now?
Screenshot 2024-07-26 at 5 16 31 PM

**Comment by matthewbirtch** [comment]
> > 1. It looks too narrow in the first image. Menus are supposed to have a `min-width: 144px`
> 
> @matthewbirtch it's actually 144.39px (so it was just over the min) but with the change of the gap of the checkbox it's now a bit over 161px. How does this look now? Screenshot 2024-07-26 at 5 16 31 PM

Good with that @marianunez. Thanks! Were you able to update the max-width too?

**Comment by marianunez** [comment]
> Were you able to update the max-width too?

@matthewbirtch  This how it would look for max width 320px. If it's good I can push the changes

Screenshot 2024-07-26 at 5 24 10 PM

**Comment by matthewbirtch** [comment]
> @matthewbirtch This how it would look for max width 320px. If it's good I can push the changes
> 
> Screenshot 2024-07-26 at 5 24 10 PM

Looks better, thanks @marianunez

**Review by Rajat-Dabade — APPROVED** [review]

**Pull request merged**
