### PR TITLE
remove legacy "Build API specification" workflow

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Now that the API source is part of the monorepo, this is already handled by the new api workflow, and can simply be removed.

#### Ticket Link
None.

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by cpoile — APPROVED** [review]
Love the cleanups. :)

**Review by isacikgoz — COMMENTED** [review]
LGTM, wondering whether we should run the vet tool (with the single API spec checker) in the `API` workflow as well.. Currently API check workflow is a two step process and might be confusing to figure out at glance (mostly for contributors). Any thoughts?

**Comment by isacikgoz** [comment]
> @isacikgoz, are you asking about #23974?

Hmm, slightly different actually IIUC that PR. It adds a separate step as `check-mattermost-vet-api` to `workflows/server-ci-template.yml`. My ask was combining the build process of API docs and vet check into `workflows/api.yml`.

**Comment by lieut-data** [comment]
> > @isacikgoz, are you asking about #23974?
> 
> Hmm, slightly different actually IIUC that PR. It adds a separate step as `check-mattermost-vet-api` to `workflows/server-ci-template.yml`. My ask was combining the build process of API docs and vet check into `workflows/api.yml`. But if it was the intention you can ignore my comment, maybe I missed that :p

Oh, I see! Yeah, I could imagine the vet check on the other side of the workflow as you suggest vs. buried in the server. I'll revisit that once we get the API vet checks actually passing. Thank you for the suggestion, @isacikgoz :)

**Review by isacikgoz — APPROVED** [review]

**Pull request merged**
