### PR TITLE
[MM-56854] Add shell completion to mmctl user active|deactivate

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
This PR adds shell completion to `mmctl user active` and `mmctl user deactivate`.

Please note that while the command supports activating more than one user at a time, the shell completion only works for the first user.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-56854

#### Release Note
```release-note
Add shell completion to mmctl user active|deactivate
```

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]

**Review by vish9812 — APPROVED** [review]

**Comment by hanzei** [comment]
@DHaussermann The PR is in sync with `master` now

**Comment by DHaussermann** [comment]
@hanzei I still don't see this working. 
I am certain I know which binary is being referenced when I use `mmctl` and I see the regular completions working. 

Can you think of any other deployment pitfalls here?

**Comment by hanzei** [comment]
@DHaussermann Let's talk about this PR in our next sync

**Comment by DHaussermann** [comment]
@hanzei unfortunately I don't see this functioning in the same way as https://github.com/mattermost/mattermost/pull/25633

Even without local mode, the usernames or IDs do not complete.
I have made sure to rebuild MMCTL for the branch and that he commands are otherwise functional so that I am not hitting unrelated authentication issues.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Both activate and deactivate are functional to fetch the list of users with completion
- The list retrieved with completions is filtered by current user status ex: it will not suggest an already deactivated user when running deactivate
- Ensured that shell completions support username, email and user id

LGTM!

Thanks for the help on this @hanzei

**Pull request merged**
