### PR TITLE
Adds default team to the remote cluster entity

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
A new DefaultTeamId field is added to the RemoteCluster entity and its endpoints, and used when receiving channel invites to choose in which team to create a new channel.

This will be later extended with the ability for the system admin to manually accept invites, choosing which team to create the channel on each. This use case will be triggered when the DefaultTeamId field is empty, which now simply chooses the first team it finds in the database as a fallback.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-59816

#### Release Note
```release-note
* Adds support for a default team on secure connections for incoming channel invites
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
SQL migration looks good

**Comment by mgdelacroix** [comment]
@agnivade do you know why the `migrations.list` check is failing? I've already updated them, and running `make migrations-extract` doesn't seem to change anything in the migrations file

**Comment by agnivade** [comment]
@mgdelacroix - I get this diff:

```diff
diff --git a/server/channels/db/migrations/migrations.list b/server/channels/db/migrations/migrations.list
index 064c9263cc..6a890f3cc1 100644
--- a/server/channels/db/migrations/migrations.list
+++ b/server/channels/db/migrations/migrations.list
@@ -1,4 +1,5 @@
-# Autogenerated file to synchronize migrations sequence in the PR workflow, please do not edit.\n#
+# Autogenerated file to synchronize migrations sequence in the PR workflow, please do not edit.
+#
 channels/db/migrations/mysql/000001_create_teams.down.sql
 channels/db/migrations/mysql/000001_create_teams.up.sql
 channels/db/migrations/mysql/000002_create_team_members.down.sql
```

Is this not happening for you?

**Comment by mgdelacroix** [comment]
@agnivade it's not, and if I apply your patch and rerun the `make` command, it will clean it up and leave the output file as it was. I've sent a commit with the patch, let's see if that fixes CI

**Comment by agnivade** [comment]
Looks like it passed. Perhaps its a difference in bash or sth.

**Comment by mgdelacroix** [comment]
Yup, weird. Thanks for helping with this!!!

**Comment by cwarnermm** [comment]
@mgdelacroix - Are there [shared channels](https://docs.mattermost.com/onboard/shared-channels.html#shared-channels-experimental) product docs updates needed based on the changes in this Engineering PR?

**Pull request merged**
