### PR TITLE
listen on unix socket support

### PR DESCRIPTION
**Pull request by cyberb**
Listen on unix socket support. I need this for Syncloud self hosting platform (https://github.com/syncloud/platform) where I try to avoid any additional tcp port config to reduce potential conflicts as users run varios apps together on a single box.
This is just a bare minimum which works for me, I am ready to spend some reasonable time on refactoring and unit/e2e testing if I am pointed at right direction.

Example:
```
"ListenAddress" : "/path/to/socket"
```

#### Release Note
```release-note
ListenAddress also supports unix socket paths now, example: "ListenAddress" : "/path/to/socket"
```

### CODE REVIEW

**Comment by agnivade** [comment]
Is there an additional proxy running on the same box that forwards requests to Mattermost? If Mattermost listens on unix socket, then nothing outside the box can communicate with it.

**Comment by cyberb** [comment]
Yes, nginx is listening on 443 and managing dns [app].domain to /[app].socket translation.

Even without Syncloud many big web projects support running behind reverse proxy using unix socket which is a bit faster than tcp for backends.

**Comment by agnivade** [comment]
If you are running nginx on the same box, then why not use Mattermost directly as the HTTP server?

If you are running into limits of listening ports, then I'd advise moving Mattermost into a separate box. If you are running into potential port conflicts, I'd suggest to use port 0 to let the OS automatically allocate a port.

**Comment by cyberb** [comment]
> If you are running nginx on the same box, then why not use Mattermost directly as the HTTP server?

Users install more than one app on a box (like on a phone), nginx also does some other things like serving app store web and managing https certs.

If Mattermost does not need it I am fine just wanted to push it upstteam as a useful feature for other users.

**Comment by agnivade** [comment]
Hey @cyberb - apologies for the delay. We had an internal discussion on this. While we agree that this is a very small feature addition, but any new feature must be justified with the additional maintenance costs that it brings. We do not think this is worth the cost, due to the reasons mentioned above.

Sorry about this. Please do feel free to contribute to any other issues that you want, or you can reach out to me on https://community.mattermost.com if you have any other feature suggestions.

**Comment by mazi-wan** [comment]
This feature does work for me, and I'm sure there are others who need it, please reconsider, unix sockets for nginx and matermost can improve performance when running on the same host and can support docker isolation of multiple instances.

For security, we need Docker isolation instances. Unix Sockets is the best choice for reducing the burden of motion and maintenance.

This is an optional configuration that will not add AdDitional Maintenance Costs to ordinary users, and for users who need him, you can reduce many Maintenance Costs
@agnivade

**Comment by agnivade** [comment]
@mazi-wan - Can you clarify the difference of burden of maintenance between tracking port numbers vs tracking the socket file locations? You can run nginx and mattermost in docker in the same host using TCP sockets as well.

**Comment by mazi-wan** [comment]
First of all, thank you for your rigor and carefulness. This is very important for a large -scale project. This is why people trust Mattermost. Below is my brief idea：

we use the nginx upstream directive:
upstream _mm_one {
  server unix:/sock/one.sock;
}
upstream _mm_two {
  server unix:/sock/two.sock;
}

DockerFile:
    volumes:
      - app:/app/mm:ro
      - sock:/sock

mattermost one listen:
listen = /sock/one.sock

mattermost one listen:
listen = /sock/two.sock

**Comment by mazi-wan** [comment]
Thank you for your quick reply. If we can support this, people who need it will be grateful to you, and those who do not need it will not be affected at all.

**Comment by cyberb** [comment]
@agnivade 
> Can you clarify the difference of burden of maintenance between tracking port numbers vs tracking the socket file locations?

for me the difference is tcp ports have to be tracked to prevent port conflicts between the apps while you do not need to track sockets if you follow the rule that every app socket is behind /[app] dir you will never have to think if any other app is using it.

**Comment by agnivade** [comment]
@mazi-wan - If you are using Mattermost for large-scale projects which are critical to your organization, our recommendation would be to use an HA env with multiple Mattermost nodes and a separate nginx proxy node for best reliability.

@cyberb - Thanks for the context. My feeling here is that keeping track of port numbers for small deployments when you have multiple apps in a single box should not be a major problem to overcome. For larger deployments, our recommendation is to use separate, dedicated nodes in an HA setup.

**Comment by vassilit** [comment]
@cyberb I'm using your patches, thank you!
I see that you somehow maintain it (like the updated version 3c67468), rebasing on more up-to-date master. Could you move it to a separate branch on your fork so that we have a reference in the future ?

**Comment by cyberb** [comment]
Sure: https://github.com/cyberb/mattermost/tree/unix-socket

**Pull request closed without merging**
