### PR TITLE
fixed initialism errors in accordance with golang conventions in 7 files.

### PR DESCRIPTION
**Pull request by TealWater**
#### Summary

Fixed all initialism errors in 7 files in accordance with the golang style doc found [here](https://github.com/golang/go/wiki/CodeReviewComments#initialisms).

List of warnings fixed:

1. server/channels/utils
`file.go --> error var SizeLimitExceeded should have name of the form ErrFoo (ST1012)`
`file.go --> error strings should not be capitalized (ST1005)`

2. server/platform/services/httpservice
`client.go --> error var AddressForbidden should have name of the form ErrFoo (ST1012)`

**This is my first PR here, honest feedback is welcomed accompanied by how I can improve as well as any links pertaining to how I can improve and explaining the methodology as to why something is done a certain way.**

#### Ticket Link

Fix for: https://github.com/mattermost/mattermost/issues/16623

#### Release Note

```release-note
none
```

### CODE REVIEW

**Comment by agnivade** [comment]
@TealWater - The way to do this would be to remove `var-naming` in .golangci.yml. Run the linter, and slowly fix the issues. Did this come out of that list? Doesn't look like that from a quick look.

Also, no release notes are necessary. You can place that message in the normal PR body instead.

**Comment by TealWater** [comment]
I did not even think about using the linter, I don't understand how it works..  I can scrap these files are start again once I figure out how to get the linter going.

**Comment by TealWater** [comment]
Ah, I see the issue now. Would it be best to close this PR and open a new one?  I can try to discard the current changes.

**Comment by TealWater** [comment]
@agnivade - I used the linter this time. Let me know if you want me to squash the commits into 1 and force push before a merge.

I omitted the .golangci.yml file.

**Comment by TealWater** [comment]
Screen Shot 2023-08-17 at 4 07 07 AM


The issue:  This is the only error left after listing the entire project. The func shown is not in use but that is not a styling/semantic/convention problem so I did not address it.

**Review by agnivade — APPROVED** [review]
Thanks!

**Review by isacikgoz — APPROVED** [review]
Thanks for the contribution @TealWater 🎉

**Pull request merged**
