### PR TITLE
[MM-54639] Help menu should open correctly aligned

### LINKED ISSUE #24659: Help menu not correctly aligned to the help button in global header
If the screenshots below aren’t visible, click through to the linked Jira ticket to see them.

**Expected:**

**Observed:**

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-54639

### PR DESCRIPTION
**Pull request by otilor**
#### Summary

Cause help menu to open right ways.
#### Ticket Link

Jira https://mattermost.atlassian.net/browse/MM-54639
Fixes #24659

#### Release Note

```release-note
Fixed alignment of help menu in global header
```

### CODE REVIEW

**Review by hmhealey — CHANGES_REQUESTED** [review]
Thanks for the PR, @otilor!

I think we might need to go about this a bit differently. This `Menu` component is used in a bunch of different places throughout the app, so we can't just remove the `openLeft` class from all of them, but we could probably remove it from just this one menu. If it helps, I think that the component in this ticket is the `UserGuideDropdown`

**Comment by otilor** [comment]
Thanks. I've updated it

**Comment by otilor** [comment]
> Thanks for the PR, @otilor!
> 
> I think we might need to go about this a bit differently. This `Menu` component is used in a bunch of different places throughout the app, so we can't just remove the `openLeft` class from all of them, but we could probably remove it from just this one menu. If it helps, I think that the component in this ticket is the `UserGuideDropdown`

Thank you. I've updated the PR

**Review by BenCookie95 — CHANGES_REQUESTED** [review]
Thanks for the PR @otilor, looks like some tests are failing. You may need to run `npm run test:updatesnapshot`

**Review by hmhealey — APPROVED** [review]
Thanks again! I tested this locally as well, and it looks perfect to me

**Review by BenCookie95 — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Thanks @otilor - looks good to me 👍 

cc @hmhealey

**Pull request merged**
