### PR TITLE
[WIP] Mm 52837

### PR DESCRIPTION
**Pull request by jatin33**
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/23423
Jira https://mattermost.atlassian.net/browse/MM-52837

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@jatin33 thank you for opening do let me know when this is open for review 😄

**Comment by jatin33** [comment]
@M-ZubairAhmed needed one help, I am getting type error regarding any icon component imported from @mattermost/compass-icons/components. Basically className prop is missing from types. Can you please guide me in which repo i can make changes for @mattermost/compass-icons/components ?

**Comment by hmhealey** [comment]
Hey @jatin33. Unfortunately, we actually already have an outstanding PR to migrate this file to TS (https://github.com/mattermost/mattermost/pull/22668). We must've opened a duplicate ticket for this by mistake since we had someone on the team working on it already. I'm really sorry about that.

We do really appreciate your work on this, especially because that file's absolutely massive and not written with static typing in mind, but I think we'd better stick with that one since it's further along now

**Comment by jatin33** [comment]
@hmhealey can you please assign me a different issue to work on, i would highly appreciate that

**Comment by hmhealey** [comment]
@M-ZubairAhmed They've taken on https://github.com/mattermost/mattermost/issues/23414 now. 

Thanks for understanding, @jatin33. I always feel bad about having to close a PR that someone put a lot of work into, so I really appreciate that as well

**Pull request closed without merging**
