### PR TITLE
Improves validation in getRolesByName endpoint

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
This PR improves validation when fetching roles by name

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-55094

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by enahum** [comment]
What is the impact in our current clients?

**Comment by mgdelacroix** [comment]
> What is the impact in our current clients?

Discussed offline, doesn't seem to have much impact but I've raised the limit anyways and created a ticket to further investigate if it's worth updating the client's logic

**Review by jupenur — DISMISSED** [review]
LGTM, but please get a second dev reviewer. I don't count.

**Review by jespino — APPROVED** [review]
LGTM, but it is limited also in the client side to not hit this limit accidentally?

**Comment by mgdelacroix** [comment]
Re-requesting reviews as I've implemented a fix for the client as well. A mobile PR will follow this one to have all clients covered

**Review by enahum — APPROVED** [review]

**Review by jespino — APPROVED** [review]
LGTM

**Review by lindy65 — APPROVED** [review]
Thanks @mgdelacroix - tested 103 roles as we chatted about via DM and looks good to me

**Pull request merged**
