### PR TITLE
MM-56994 Used false as default for useMilitaryTime

### PR DESCRIPTION
**Pull request by TheInvincibleRalph**
GitHub issue: https://github.com/mattermost/mattermost/issues/26309
https://mattermost.atlassian.net/browse/MM-56994

```
Description: Changed the logic of useMilitaryTime to false to default to 12-hour time format unless the user's preference from data.Value is "true".

Field affected: When a notification mail is sent to a user, the time should now default to the 12-hour format except otherwise stated by the user.
```

```release-note
Fixed email notifications using 24 hour timestamps by default
```

### CODE REVIEW

**Review by hmhealey — CHANGES_REQUESTED** [review]
Thanks for the PR, @TheInvincibleRalph!

Could you also add a unit test to cover this case in `channes/app/notification_email_test.go`? There's some tests in that file that cover checking for the time zone, but none of them seem to check the preference for whether or not 24 hour time is enabld

**Comment by TheInvincibleRalph** [comment]
Hi, @hmhealey. I have made another pull request for the preference test at https://github.com/mattermost/mattermost/pull/28128/commits/1f85178d27cfc18ef368f2a1a531a6d8eb4dd066

**Review by hmhealey — APPROVED** [review]
Thanks for adding that test. This looks good to me!

**Review by marianunez — APPROVED** [review]

**Comment by marianunez** [comment]
@yasserfaraazkhan heads up we can test this post-merge as it is a simple default change and has a corresponding unit test. I'll add you in the ticket for QA

**Pull request merged**
