### PR TITLE
MM-53092 Fix for Updating SysAdmin user.

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Updates the endpoint for updateUser. Currently, the endpoint checks the user object being passed is a SysAdmin. Updated to retrieve the existing user and check it for SysAdmin.

To update a SysAdmin, the user updating must have ManageSystem Permission (ie. sysadmin)

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-53092

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by nickmisasi — APPROVED** [review]
LGTM!

**Review by hanzei — APPROVED** [review]
LGTM

**Review by esarafianou — APPROVED** [review]
LGTM

**Comment by esarafianou** [comment]
QA in the PR is compete

**Review by lindy65 — APPROVED** [review]
Thank you @esarafianou for QA reviewing this for me! 🤗

**Comment by amyblais** [comment]
@sbishel This looks good to merge.

**Pull request merged**
