### PR TITLE
MM-50594 - fix for group member count using wrong property

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Notification warning for custom group mentions was using the wrong return parameter.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-50594

#### Release Note

```release-note
Fixed issue that displayed wrong count for custom group members on notification warning.
```

### CODE REVIEW

**Review by agarciamontoro — APPROVED** [review]
Thank you! Should we add a test covering the original bug? That is:
1. A group initially contains 10 members
2. Then, 2 of those members accounts are deactivated
3. The warning should show 8 members, not 10

**Review by JulienTant — APPROVED** [review]
Thanks @sbishel

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - looks good to me - I tested user group count as well as notification count and this is fixed.  Just want to confirm that the notification does NOT fire for 5 users in a user group but DOES fire for 6 users and above?  That is what I'm seeing.

**Pull request merged**
