### PR TITLE
Add support for actions in the unreads bar from plugins

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Add support for actions in the new messages seprator bar from plugins (This is needed for the mattermost-plugin-ai)

#### Ticket Link
mattermost/mattermost-plugin-ai#29

#### Screenshots
imagen

#### Release Note
```release-note
Added new frontend plugin extension point for the new messages separator bar
```

### CODE REVIEW

**Comment by jespino** [comment]
@matthewbirtch I added you as a reviewer because I modified the styles of the bar to fit your design. Now the bar height is 8 pixels more. I want you to confirm that that behavior is the expected one.

**Comment by matthewbirtch** [comment]
Tried to get a spinwick server up to test this, but seems to have failed @jespino. I'll see if I can get a local instance running, but have had issues with it recently.

**Comment by matthewbirtch** [comment]
@jespino, based on the screenshot, I'm thinking maybe we can adjust the following
1. Reduce the height of the bar to 36px. 40px is feeling a bit tall now that I see it here in context.
2. Adjust the summarize button to match the font-size of the other text within the toast and adjust the button's height to 24px. And we might need to reduce the size of the icon slightly to match that. Also, add 4px of space between the icon and the label within the button.
3. Maybe while we're here we can adjust 'Jump to new messages' label to just 'Jump to new'
4. 
image

**Comment by crspeller** [comment]
@jespino @matthewbirtch 
Playing around with this I am wondering if we need an additional way to access this functionality. Not exactly sure under what cases that bar appears, but it does not appear to be consistent. If all the unreads appear in view, the bar doesn't seem to appear most of the time. However because of CRT there may actually be a substantial number of unreads.

**Comment by matthewbirtch** [comment]
> @jespino @matthewbirtch Playing around with this I am wondering if we need an additional way to access this functionality. Not exactly sure under what cases that bar appears, but it does not appear to be consistent. If all the unreads appear in view, the bar doesn't seem to appear most of the time. However because of CRT there may actually be a substantial number of unreads.

@crspeller here's my understanding of the conditions for this bar to display:
- open a channel where there are unread messages 
- you have your account settings set to "Start me where I left off" (Settings > Advanced > Scroll position when viewing unread channel) there are more new messages below where you're scrolled
- you land in a scroll position where there are more new messages below the fold
- new messages banner displays

All that said, I agree that we may want to consider an alternative way of engaging this type of AI summary. Just spit-balling, but maybe adding something to the new message line separator would be more appropriate.

**Comment by crspeller** [comment]
@matthewbirtch I like the message line separator because it doesn't disappear under any condition other than you leave the channel with reads. You can also bring it back when you want it. 
How would that look?

**Comment by matthewbirtch** [comment]
@crspeller a super quick first stab at it could look something like the below ([figma link too](https://www.figma.com/file/4Dq6Kl0kq8Zf186Ygf4NWT/AI-Explorations?type=design&node-id=352-116603&mode=design&t=EDcIqa974fTdO4Qt-4))

image

**Comment by crspeller** [comment]
Looks good! @jespino Want to add that other location in this PR?

**Comment by jespino** [comment]
Sure, let's move it. Thanks @matthewbirtch and @crspeller. I think you have found a much better place to put it.

**Review by mickmister — APPROVED** [review]

**Review by crspeller — APPROVED** [review]

**Comment by crspeller** [comment]
@matthewbirtch This is ready for a UX check. @jespino is your screenshot above latest?

**Comment by jespino** [comment]
@matthewbirtch updated the screenshot to the last version. Here is it also:

imagen

**Comment by matthewbirtch** [comment]
> @matthewbirtch updated the screenshot to the last version. Here is it also:

Thanks @jespino, can we adjust the opacity on the background of the button to be 8% opacity and reduce the top and bottom padding of the button by 2px? Looks good other than that

**Comment by jespino** [comment]
@matthewbirtch now better?

imagen

**Comment by matthewbirtch** [comment]
> @matthewbirtch now better?

👌 Looks good now @jespino. Thanks!

**Review by matthewbirtch — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Hi @jespino - as discussed via DM, I'm going to QA-defer this PR and test after merging when it'll be easier to set up a server to test it on as the spinwicks don't allow for plugin uploads.

**Comment by lindy65** [comment]
@jespino - I created Jira ticket to track: https://mattermost.atlassian.net/browse/MM-54239

Also, will this PR need to be cherry-picked to Cloud for 31 Aug release?

**Review by lindy65 — APPROVED** [review]
Thanks @jespino - tested on your test server and this looks good to me 👍

**Pull request merged**
