### PR TITLE
[MM-53149] White Screen when replying to a thread

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
the function `shouldFilterJoinLeavePost` doesn't have any guard inside of it since it is always called before checking the post existence except for one place in `makeGetPostsForThread`. This PR added the post guard before accessing the former function.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-53149

#### Screenshots
n/a

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by marianunez — CHANGES_REQUESTED** [review]
It seems there is another occurence of calling `shouldFilterJoinLeavePost` without a `post` check here: 
https://github.com/mattermost/mattermost/blob/81a1d725a00f3aa9d46168074e318eb2fab3a5e2/webapp/channels/src/packages/mattermost-redux/src/selectors/entities/posts.ts#L339

It only checks for `postId` has something but that doesn't guarantee that it will return a valid `post`. 

Should we just do a check within `shouldFilterJoinLeavePost` and not do anything if `post` is null? This way we are certain that it won't fail if this method is later reused as well

**Comment by M-ZubairAhmed** [comment]
> It only checks for postId has something but that doesn't guarantee that it will return a valid post.

Yes indeed I added the correct check there.

> Should we just do a check within shouldFilterJoinLeavePost and not do anything if post is null? 

Unfortunately, this should not have happened in the first place because those should never have contained post ids that don't exist any more. But that's something for the other day. Either of the approaches is fine by me.

**Comment by harshilsharma63** [comment]
> Should we just do a check within shouldFilterJoinLeavePost and not do anything if post is null?

This makes sense to avoid future issues with this function.

**Comment by marianunez** [comment]
> Unfortunately, this should not have happened in the first place because those should never have contained post ids that don't exist any more.

Agreed that it shouldn't happen but to future-proof would be good to add that check in the fuction and a test here: https://github.com/mattermost/mattermost/blob/81a1d725a00f3aa9d46168074e318eb2fab3a5e2/webapp/channels/src/packages/mattermost-redux/src/utils/post_utils.test.ts#L25

**Comment by M-ZubairAhmed** [comment]
> This makes sense to avoid future issues with this function.

I have added the comment for it. That should be fine.

**Review by fmartingr — APPROVED** [review]
To the best of my knowledge this looks good to me 👍

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
