### PR TITLE
Replace hard-coded HTTP verbs with constants

### PR DESCRIPTION
**Pull request by enzowritescode**
#### Summary
Replace hard-coded HTTP verbs with constants from `net/http`

#### Ticket Link
N/A

#### Screenshots
N/A

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by enzowritescode** [comment]
Sorry for forking. I didn't realize I could have worked directly on the upstream at the time.

**Comment by agnivade** [comment]
Would you like to directly push to an upstream branch? We can create a new PR. The enterprise tests will become easier to trigger that way.

**Comment by enzowritescode** [comment]
Closing in order to create a PR directly on the upstream.

**Pull request closed without merging**
