### PR TITLE
[MM-60821] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/integrations/installed_oauth_app/installed_oauth_app.tsx' with FormattedMessage

### PR DESCRIPTION
**Pull request by Camillarhi**
#### Summary

Replace FormattedMarkdownMessage in `webapp/channels/src/components/integrations/installed_oauth_app/installed_oauth_app.tsx` with FormattedMessage
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28505
Jira https://mattermost.atlassian.net/browse/MM-60821

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @Camillarhi!

**Review by pvev — APPROVED** [review]
LGTM! thanks @Camillarhi 🚀 🎉

**Comment by hanzei** [comment]
@devinbinnie @pvev Can we merge this PR?

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
