### PR TITLE
[MM-58003] Allow setting AdvancedLoggingJSON via mmctl

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
`mmctl` can now be used to set AdvancedLoggingJSON, e.g. using `mmctl config set LogSettings.AdvancedLoggingJSON '{"console1":{"Type":"console","Format":"json","Levels":[{"ID":5,"Name":"debug","Stacktrace":false},{"ID":4,"Name":"info","Stacktrace":false,"color":36},{"ID":3,"Name":"warn","Stacktrace":false},{"ID":2,"Name":"error","Stacktrace":true,"color":31},{"ID":1,"Name":"fatal","Stacktrace":true,"color":31},{"ID":0,"Name":"panic","Stacktrace":true,"color":31},{"ID":10,"Name":"stdlog","Stacktrace":false}],"Options":{"Out":"stdout"},"MaxQueueSize":1000}}'`

I also took the time to add proper unit tests that cover setting config values via mmctl. The tests cover all field types used in `model.Config` except the plugin setting. I didn't want to open this cane of worms of part of this PR.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-58003

#### Release Note
```release-note
Allow setting AdvancedLoggingJSON via mmctl
```

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:   Great work @hanzei

**Comment by hanzei** [comment]
@BenCookie95 wapping you in while @mgdelacroix is out.

**Review by BenCookie95 — APPROVED** [review]
Nice, probably worth putting this one through QA

**Comment by DHaussermann** [comment]
@hanzei I have done a round of testing on this. 
- You can use the commands to successfully write a json value for `AdvancedLoggingJSON` 
- I have verified in both the config and the UI
- Same for "unsetting" the value by passing `{}`
- Tested with both an authenticated use and using `--local` 


I do have an issue with this but it's probably more generally with the `config set` command. 
If I don't use `--local` AND I don't have an authenticated user  logged in, the command should tell me something has failed. 
Instead I get a message about `mmctl` and server version mismatch (likely expected in a PR branch) but then it tells me `Value changed successfully` when no such change has happened.  
I reproed this several times both for setting and unsetting thew value. The `config.json` shows no updated data even though the tool says it worked.   
image
I assume it's related to the auth failing because it works fine when I add a valid auth record or pass in `--local`

Please advise if this requires a separate Jira ticker or PR.

**Comment by hanzei** [comment]
@DHaussermann Are you sure that you don't have a server connection set up? What does `mmctl auth list` report?

**Comment by hanzei** [comment]
@DHaussermann Are you sure you don't have a server connection set up? What does `mmctl auth list` report?

**Comment by DHaussermann** [comment]
@hanzei you're correct. After closer inspection of the MMCTL auth table, this was tester error. There was in fact a set of valid credentials in the table for an irrelevant test server.
This explains why it only started "working" once I added credentials to my local. I was updated the config on a test server I did not know was still functional (also explains the version message).

Sorry. Thanks for the help.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Confirmed I can set the json value for the logging
- Confirmed I can remove the logging value by passing empty `{}`
- Confirmed setting via `--local` is functional
- Confirmed that setting by using a connection set in the auth table is working as expected (despite  my earlier confusion)

LGTM!

Thanks @hanzei please merge.

**Pull request merged**
