### PR TITLE
[MM-58379] Remove playbooks from onboarding

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary
Removes Playbooks from the onboarding tour

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-58379

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by lindy65** [comment]
Hey @JulienTant - not sure who's going to update the video in the onboarding tour but it still contains Playbook info. Also, should Playbooks be available in the Main Menu on the Free Edition if it's being removed from the onboarding tour? Sorry - there isn't much info in the Jira ticket so I'm not aware what other changes there should / should not be?

image

image

image

image

image

image

image

image

**Review by mgdelacroix — APPROVED** [review]

**Comment by JulienTant** [comment]
Hey @lindy65!

Yes playbook should still be available in the Menu if the plugin is installed; we just remove it form the onboarding because it will require an enterprise license so it's not available for everyone.

Not sure who's responsible for the video but it's a good catch, maybe @cwarnermm knows? In any case, because we need to make progress on this I can create a new ticket for the video to prevent blocking this PR!

**Comment by lindy65** [comment]
Thanks @JulienTant - sounds good to me to create a new ticket for video upate - thanks 👍 

@emdecr might also know who owns updating the video

**Review by lindy65 — APPROVED** [review]
Thanks @JulienTant - looks good to me then (apart from the video update needing doing)

**Review by calebroseland — APPROVED** [review]

**Comment by JulienTant** [comment]
@lindy65 ticket created: https://mattermost.atlassian.net/browse/MM-59886

**Comment by lindy65** [comment]
Thank you @JulienTant 🤗

**Comment by emdecr** [comment]
Sorry about the delay y'all - was on PTO. The Marketing team update the videos. I believe editing this video is on the radar of the team already (yet to be queued), but I'll let them know of this ticket and point about the Playbooks exclusion idea.

**Comment by lindy65** [comment]
Thanks @emdecr - for now, I've assigned the Jira ticket to Ashley

**Pull request merged**
