### PR TITLE
Remove bold markdown in trial expiring strings

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Removed bold markdown in translation string for Trial expiring texts. Removed from all language as it doesn't affect the actual message. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-53218

#### Release Note

```release-note
None
```

### CODE REVIEW

**Review by nickmisasi — APPROVED** [review]
LGTM

**Comment by marianunez** [comment]
> Hi @marianunez , the `bold` text is not appearing now as expected✅
> 
> #23957 stripe user: `user-mattermost-pr-23957@example.mattermost.com` I was trying out different languages, and observed the banner text was not changing, would this be existing scenario?
> 
> Screenshot 2023-07-06 at 4 52 10 PM

This is because that text is currently not translated in other languages. The one that was translated that I removed the bold markdown from is `There are {days} days left on your free trial.` text which shows when there is 14 or less days before it expires.

**Review by yasserfaraazkhan — APPROVED** [review]
working as expected. tested on https://github.com/mattermost/mattermost/pull/23957

**Pull request merged**
