### PR TITLE
Chore(cypress): Fix Known flaky test

### PR DESCRIPTION
**Pull request by yasserfaraazkhan**
```release-note
NONE
```

### CODE REVIEW

**Comment by yasserfaraazkhan** [comment]
@saturninoabril how do we remove the `known` tag?

image

**Comment by saturninoabril** [comment]
It will be removed automatically once the test passed.

**Comment by yasserfaraazkhan** [comment]
[report](https://automation-dashboard.vercel.app/cycles/6e138fb0-ec60-447e-bb12-3dc32615bd7a)

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by harshilsharma63 — APPROVED** [review]

**Pull request merged**
