### PR TITLE
[MM-59891] Migrate tooltips of 'components/file_attachment/file_attachment.tsx' to WithTooltip

### PR DESCRIPTION
**Pull request by Gesare5**
#### Summary

Replaces OverlayTrigger and Tooltip, with WithTooltip in file_attachment component

#### Ticket Link

Fixes  [#27790](https://github.com/mattermost/mattermost/issues/27790)
Jira  [https://mattermost.atlassian.net/browse/MM-59891](https://mattermost.atlassian.net/browse/MM-59891)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
This looks good :shipit: Thank you

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by yasserfaraazkhan — APPROVED** [review]

**Review by Rajat-Dabade — APPROVED** [review]

**Pull request merged**
