### PR TITLE
MM-49452 - Updating height of reply input

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-49452 - Updating height of reply input
Enable the formatting separator automatically for the RHS as we have the formatting controls in the RHS automatically at the bottom, so we don't need to dynamically introduce it.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-49452
Fixes https://mattermost.atlassian.net/browse/MM-57138

#### Screenshots
**Before and After comparison**
https://www.loom.com/share/7fc95cc8ff654001a1cf2f12eaa2f50a

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by matthewbirtch** [comment]
@asaadmahmood would you mind showing the before/after comparison in the screenshots?

**Comment by asaadmahmood** [comment]
@matthewbirtch Added a before after video.

**Review by matthewbirtch — APPROVED** [review]
Thanks for the fix @asaadmahmood

**Review by devinbinnie — APPROVED** [review]

**Review by larkox — APPROVED** [review]
LGTM. Just one consideration (probably out of the scope of this PR).

We have to make this `isRHS` check here because there is a difference between how we show the input on the center pane and the RHS.

On the center pane, the buttons show inline with the message until the message is big enough. Then it jumps. On the RHS we always show the buttons below the message.

Is this different behavior something we want to keep?

**Review by lindy65 — APPROVED** [review]
Thanks @asaadmahmood - looks good to me 👍

**Pull request merged**
