### PR TITLE
Remove docker prereq check if MM_NO_DOCKER is set

### PR DESCRIPTION
**Pull request by claytongulick**
#### Summary
This is just a minor tweak to the build process, removing the docker check if the build isn't using docker.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by pfltdv — APPROVED** [review]

**Review by phoinixgrr — APPROVED** [review]

**Review by agnivade — APPROVED** [review]

**Comment by isacikgoz** [comment]
@claytongulick can you please update the PR with current `master`? Please ping me after you do so.

**Pull request closed without merging**
