### PR TITLE
[MM-39053] - A/B test for default notification settings

### PR DESCRIPTION
**Pull request by AGMETEOR**
#### Summary
This PR adds a new feature flag to control the default notification settings for a new user

#### Ticket Link
[MM-39053](https://mattermost.atlassian.net/browse/MM-39053)

#### Release Note

```release-note
Add feature flag, NewAccountNoisy A/B test.
```

### CODE REVIEW

**Comment by marianunez** [comment]
> Please toggle it to the next setting and I'll test it again.

@stevemudie I've toggled the setting to `off` which is the control group. You need to create a new user to have the new default settings applied. Default settings do not affect existing users.

**Comment by AGMETEOR** [comment]
@marianunez I can now copy the flag into prod on splitio or we have to still wait?

**Comment by marianunez** [comment]
> @marianunez I can now copy the flag into prod on splitio or we have to still wait?

We need to wait for the release next week before moving this to prod. This needs to be cherry-picked to `cloud` so it can make it to the release

**Pull request merged**
