### PR TITLE
Fixed actived users and added mau in true up report

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

- Fixed issue with true up report sending daily active users and not activated users. 
- Added Monthly Active Users (MAU) as part of the true up report. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-54870

#### Release Note

```release-note
Fixed issue with true up report sending active users and not activated users. 
Added Monthly Active Users (MAU) as part of the true up report
```

### CODE REVIEW

**Comment by marianunez** [comment]
@nickmisasi @larkox this is a fix for the true up feature, there is some context in the ticket on how it works. 

@yasserfaraazkhan I've tested it with CWS test portal, how do you suggest we do QA review on this? I tested it by temporarily removing the time check in my branch but wondering how you would do this in the release testing?

**Review by nickmisasi — APPROVED** [review]
LGTM

**Review by larkox — APPROVED** [review]
LGTM

**Comment by larkox** [comment]
Do we want to add any tests for this?

**Comment by johndavidlugtu** [comment]
@marianunez do we still retain DAU (active users) while making sure we have the activated user count (aka registered users)?

**Comment by marianunez** [comment]
> @marianunez do we still retain DAU (active users) while making sure we have the activated user count (aka registered users)?

No, this change is correcting activated user count to return the actual registered users (vs DAU) and added the new request to also include MAU. Do we want to add DAU as a separate data point?

**Comment by marianunez** [comment]
> Do we want to add any tests for this?

Test added 🎉

**Comment by johndavidlugtu** [comment]
> Do we want to add DAU as a separate data point? Wondering if DAU is valuable for true up purposes as it will just be the value of the day the true up is sent over while MAU gives a better picture of the last 30 days.

@marianunez yes we'd still want the DAU number (have to be labelled DAU so as not to be confused with "total activated users"). It helps gives us a glance of their usage health during true-up

Total activated users should also be labelled "Total activated users"

**Comment by marianunez** [comment]
> yes we'd still want the DAU number (have to be labelled DAU so as not to be confused with "total activated users"). It helps gives us a glance of their usage health during true-up
> 
> Total activated users should also be labelled "Total activated users"

Added dau and update the name of activated users that will come in telemetry as: 
`"total_activated_users"`
`"daily_active_users"`
`"monthly_active_users"`

**Comment by johndavidlugtu** [comment]
Awesome, thanks @marianunez !

**Pull request merged**
