### PR TITLE
MM-60335: Upgrade to typescript 5.5.4

### PR DESCRIPTION
**Pull request by calebroseland**
#### Summary
Upgrades Typescript to `5.5.4` to support `AbortSignal.any` typings

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-60335

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
@calebroseland I hadn't heard about `AbortController` or `AbortSignal` until now. Want to talk about them in a web guild or dev meeting at some point? The name seems pretty self-explanatory, but I'd be curious to chat about them. Perhaps we could use them to finally get rid of the `XmlHTTPRequest` that we use when uploading file attachments

**Comment by calebroseland** [comment]
@hmhealey that's a great ideal, I'll queue something up for the dev meeting next week.

**Comment by calebroseland** [comment]
After #28098

**Pull request merged**
