### PR TITLE
MM-52959 Update help text

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary

Updates help text on `PrivacySettings.ShowEmailAddress` to include other system roles as well.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-52960

#### Screenshots
Screenshot 2023-08-24 at 2 09 03 PM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by calebroseland — APPROVED** [review]

**Review by esarafianou — COMMENTED** [review]
@sbishel  how are we handling all the languages translation?

**Comment by cwarnermm** [comment]
@esarafianou - String translation would follow our regular release processes where new/changed strings are passed to the Weblate translation server. Community translators would provide string translations across our supported languages. Then the string translations would be merged back into our code base. Product string translations tend to lag behind product releases by a release or two.

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - looks good to me 👍

**Pull request merged**
