### PR TITLE
MM-57863 - Check file attachment settings when sync'ing files for Shared Channels

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary
This PR fixes an issue where remotes can send files larger than the local config allows.  Also blocks attachment sync when attachments are disabled.

Note:  a future task will implement a notice to the sending user that the file attachment was blocked. For now the only indication the attachment was blocked is an error in logs on both servers.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-57863

```release-note
Obey local server configuration for file attachments when synchronizing for Shared Channels
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
Looks good :+1:

**Review by fmartingr — APPROVED** [review]

**Review by esarafianou — APPROVED** [review]

**Pull request merged**
