### PR TITLE
MM-61519 Fix errcheck in channels/app/plugin_api_tests/test_update_user_auth_plugin/main.go

### PR DESCRIPTION
**Pull request by willypuzzle**
#### Summary
- Removed test_update_user_auth_plugin from golangci
- Refactored error handling in channels/app/plugin_api_tests/test_update_user_auth_plugin/main.go for missing errchecks

#### Ticket Link
https://github.com/mattermost/mattermost/issues/29259

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by hanzei — CHANGES_REQUESTED** [review]
Thanks for the PR :+1:

**Review by hanzei — CHANGES_REQUESTED** [review]
The test is failing. Can you please take a look?

```
{"timestamp":"2024-11-15 11:14:45.298 Z","level":"debug","msg":"Advanced logging config not provided for notification logging","caller":"platform/config.go:165"}
    plugin_api_test.go:1296: 
        	Error Trace:	/mattermost/server/channels/app/plugin_api_test.go:1296
        	Error:      	Received unexpected error:
        	            	expected '' got 'saml'
        	Test:       	TestBasicAPIPlugins/test_update_user_auth_plugin
```

**Comment by willypuzzle** [comment]
> The test is failing. Can you please take a look?
> 
> ```
> {"timestamp":"2024-11-15 11:14:45.298 Z","level":"debug","msg":"Advanced logging config not provided for notification logging","caller":"platform/config.go:165"}
>     plugin_api_test.go:1296: 
>         	Error Trace:	/mattermost/server/channels/app/plugin_api_test.go:1296
>         	Error:      	Received unexpected error:
>         	            	expected '' got 'saml'
>         	Test:       	TestBasicAPIPlugins/test_update_user_auth_plugin
> ```

Yes! Sure! I'm just doing it!

**Comment by willypuzzle** [comment]
@hanzei I found the bug and fixed it. Could you rerun the jobs?

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Review by hmhealey — APPROVED** [review]
Thanks for the PR!

I've been a bit unsure if requiring that errors are handled in unit tests is actually helpful since I'd expect something else in the test to fail if the setup fails, but since `expectUserAuth` doesn't doesn't fail the test, we definitely could've missed things breaking with the previous code, so thanks for fixing that!

**Pull request merged**
