### PR TITLE
#24773 Converted ./components/emoji_picker/components/emoji_picker_header.tsx to Function Component

### LINKED ISSUE #24773: Convert ./components/emoji_picker/components/emoji_picker_header.tsx from Class Component to Function Component
We want to move most of our codebase from Class Components to Function Components. This decision is based on [React recommendations](https://react.dev/reference/react/Component).

The task is to update the component to be a functional component, without any difference in functionality. Also, all related tests that fail may need refactoring.

Here are a few examples of the required changes:
https://github.com/mattermost/mattermost/pull/24187
https://github.com/mattermost/mattermost/pull/24210
https://github.com/mattermost/mattermost/pull/24183
https://github.com/mattermost/mattermost/pull/24181

If the tests do not work because they rely on the behavior of Class Components they also have to be migrated to functionaly test the same behavior. We prefer the use of `react-testing-library` for new tests, but it is not required.

When submitting the PR, please make sure to identify where and when the component shows, for QA to properly test the changes.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA LINK: MM-54810

### PR DESCRIPTION
**Pull request by balajik**
#### Summary

In this PR, converted the EmojiPickerHeader component from class component to functional component.

#### Ticket Link

Fixed #24773
Jira ticket: https://mattermost.atlassian.net/browse/MM-54810

#### Release Note

```release-note
Converted EmojiPickerHeader component to functional component
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]
Great work!

**Review by sinansonmez — APPROVED** [review]
LGTM 🚀 thanks

**Comment by larkox** [comment]
@lindy65 :point_up:

**Comment by larkox** [comment]
@lindy65 the three e2e tests that are not passing seem not related, so I will merge.

**Comment by larkox** [comment]
@balajik Thank you for the contribution!

**Pull request merged**
