### PR TITLE
[GH-25022]: Add Academy links to Teams training

### PR DESCRIPTION
**Pull request by umrkhn**
#### Summary
This PR adds Mattermost Academy training video link to the following 3 UI components in Mattermost:

- Team drop-down menu
- Teams Setting modal
- Teams you can join page

Also the link is ready for translation and the icon and styles have been updated according to the provided UI/UX designs.
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/25022
Jira https://mattermost.atlassian.net/browse/MM-55021

#### Screenshots

|  before  |  after  |
|----|----|
| before1 | after3 |

|  before  |  after  |
|----|----|
| before2 | after2 |

|  before  |  after  |
|----|----|
| before3 | after1 |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Thanks for taking this one @umrkhn! A few things from me:

1. Can we remove the underline on hover in the context of the team menu?
    image

2. I don't see the link on the 'Teams you can join' page as described in the [Jira ticket](https://mattermost.atlassian.net/browse/MM-55021). Could you add this as well as part of this PR?
    image

3. Could you also add the link to the Team Settings modal as well as shown here?
    image

In addition, could you add screenshots of the UI changes in the PR description? This helps other reviewers know what to look for when doing QA.

**Comment by umrkhn** [comment]
@matthewbirtch this PR is in the works will update soon, also should I separate it as a component or just copy paste it to other components?

**Comment by matthewbirtch** [comment]
> @matthewbirtch this PR is in the works will update soon, also should I separate it as a component or just copy paste it to other components?

Ok, apologies @umrkhn. I was tagged for review so I assumed it was ready. I'll hold off until you're ready. Thanks for letting me know.

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
@umrkhn a couple minor details:

- in the team menu, when I press `Tab` to tab through the menu items with the keyboard, the text gets underlined rather than showing the standard menu item focus state.
    
- when we show this `Learn about teams` button in the other two contexts though, I think we do need the text underlined on hover since there is no hover state right now. But only show the underline on the text, not on the icon. Could you update this?

**Review by matthewbirtch — APPROVED** [review]
Looks good to me @umrkhn. Thanks for your work on this

**Review by cwarnermm — APPROVED** [review]
Thank you, @umrkhn!

**Review by crspeller — APPROVED** [review]

**Comment by cwarnermm** [comment]
@crspeller - Are you open to help address the failing checks on this PR?

**Review by sbishel — APPROVED** [review]

**Pull request merged**
