### PR TITLE
[MM-53124] Add optional Forgot Password custom link to override the default flow on the login page

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
This change enables server admins to specify a custom Forgot Password link that will override the current implementation. The link will instead open an external tab with whatever URL was provided, if specified. If not specified, users will just see the normal flow.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-53124

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
Code looks 💯 but i guess few e2e would be good :)

**Review by abhijit-singh — APPROVED** [review]
Looks good @devinbinnie! 

The only thing I wanted to ask is if the `Enable/Disable` option that was in the designs would be done as a separate PR?
image

**Comment by devinbinnie** [comment]
> Looks good @devinbinnie!
> 
> The only thing I wanted to ask is if the `Enable/Disable` option that was in the designs would be done as a separate PR? image

Oh I completely missed that...for some reason I thought the design was to either have the link on the Password screen or the customization screen. I'll add it as part of this PR.

**Review by mgdelacroix — APPROVED** [review]
LGTM! :+1:

**Comment by devinbinnie** [comment]
@abhijit-singh @M-ZubairAhmed @mgdelacroix Ready to re-review. Also as a note, I migrated `password_settings` to TypeScript cause it was annoying me :P

**Review by mgdelacroix — APPROVED** [review]
LGTM! :rocket:

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by abhijit-singh — APPROVED** [review]
Thanks @devinbinnie. Looks good but a couple of non-blocking requests:
1. System console > Password > Enable forgot pass link: When you change this setting, but don't save and instead click on the link in the help text (Site config > customization), it takes doesn't throw the `Discard changes?` warning. That warning IS shown if you try to navigate away through the system console LHS. The expected behaviour would be to show the warning if you're navigating away without saving. 
2. The colour for the `Site Configuration > Customization` link seems to be too light. Just changing the opacity for it to 1 should do the trick (only for the link though, not the entire help text). Also noticed this is the case for other links in the help text in system console as well (eg. Web server page). Would be good to fix them too if it's not too difficult.

**Comment by devinbinnie** [comment]
> 1. System console > Password > Enable forgot pass link: When you change this setting, but don't save and instead click on the link in the help text (Site config > customization), it takes doesn't throw the `Discard changes?` warning. That warning IS shown if you try to navigate away through the system console LHS. The expected behaviour would be to show the warning if you're navigating away without saving.

Done!

> 2. The colour for the `Site Configuration > Customization` link seems to be too light. Just changing the opacity for it to 1 should do the trick (only for the link though, not the entire help text). Also noticed this is the case for other links in the help text in system console as well (eg. Web server page). Would be good to fix them too if it's not too difficult.

This one is being set by default by the CSS. I think we should address these issues separately since they're out of scope here and so QA can test more accurately.

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by M-ZubairAhmed** [comment]
Closed https://github.com/mattermost/mattermost/issues/23434 as well

**Pull request merged**
