### PR TITLE
MM-55252 Update RHS Thread View to Use Relative Timestamps

### PR DESCRIPTION
**Pull request by matthewbirtch**
#### Summary
This PR cleans up the RHS thread view by removing the date separators and uses relative timestamps instead. This makes the RHS thread view consistent with the Global Threads view. Before this PR, the two views used different time stamp methods.

#### Ticket Link
Jira https://mattermost.atlassian.net/browse/MM-55252

#### Screenshots
|  before  |  after  |
|----|----|
| image | image |

#### Release Note
```release-note
Updated the RHS Thread view to use relative time stamps to be more consistent with the global Threads view.
```

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]

**Review by abhijit-singh — APPROVED** [review]
Looks good functionally @matthewbirtch! 

I just wanted to mention that this does make the RHS timestamps different from the center channel, which are the two views usually open at the same time. I've actually found value in the exact timestamp at times but 0/5 on what is better for the end user.

**Comment by hmhealey** [comment]
> I've actually found value in the exact timestamp at times but 0/5 on what is better for the end user.

I second this, but I feel like I'd have to try this out to see how it feels. For what it's worth though, I do find I periodically hover over the relative timestamp in the RHS every once in a while. I'll leave the UX stuff to you though

**Review by hmhealey — APPROVED** [review]

**Comment by matthewbirtch** [comment]
> > I've actually found value in the exact timestamp at times but 0/5 on what is better for the end user.
> 
> 
> 
> I second this, but I feel like I'd have to try this out to see how it feels. For what it's worth though, I do find I periodically hover over the relative timestamp in the RHS every once in a while. I'll leave the UX stuff to you though

The @abhijit-singh and @hmhealey for the feedback. The two main things I'm aiming to achieve with this PR are as follows:
1. Reduce clutter and noise in the RHS. I think the date separator is much less important or helpful in the thread context and adds extra noise that is magnified with the new reply count separator. The relative timestamp simplifies that.
2. Consistency with how threads display elsewhere - namely in the global thread view.

In the channel context, a relative timestamp could also be considered, but I wasn't ready to commit to that quite yet. I was worried that would be too big of a shift.

**Comment by matthewbirtch** [comment]
@hmhealey looks like reviews are complete. I don't have access to merge, so if you wouldn't mind merging for me when you have a moment, that would be great.

**Pull request merged**
