### PR TITLE
Add ctx usage in Client4 methods

### PR DESCRIPTION
**Pull request by pmokeev**
#### Summary

Replaced `http.NewRequest` method in `doUploadFile` and `uploadPlugin` functions by `http.NewRequestWithContext` method, so now it uses [context](https://pkg.go.dev/context) variable.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by pmokeev** [comment]
@hmhealey @devinbinnie can you have a look at this PR?

**Comment by hmhealey** [comment]
Thanks for the PR! I'm actually going to reassign the reviewers on this to people who are more familiar with the server-side code

**Comment by agnivade** [comment]
Ben was driving the change around adding contexts. Will defer to him.

**Review by agnivade — COMMENTED** [review]
It seems like there are other places as well where we can apply this change. Let's do all of them at once.

**Comment by pmokeev** [comment]
@agnivade Hi! I've added ctx usage to the rest of the Client4 methods, so now it has zero `NewRequest` methods usage without context
image

Also I have some thoughts about future improvements:
1. Replace all weird string values `"POST"\"GET"` in `NewRequestWithContext` functions calls by using standard [http constant](https://go.dev/src/net/http/method.go) (it would be in another PR, I guess)
2. Make better use of context in another packages, for instance [like this one](https://github.com/mattermost/mattermost/blob/master/server/platform/services/remotecluster/sendmsg.go#L146) — here it uses timeout parameter, but in Go it would be better to pass ctx variable with predefined timeout from parent function.

WDYT?

**Comment by agnivade** [comment]
Thanks. I will defer to @hanzei on the future improvements. They look fine, but there might be other more important ones which he would know about.

**Review by agnivade — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]
Merging this since @hanzei's still out, and skipping QA because this code isn't user-visible and is covered by unit tests

**Pull request merged**
