### PR TITLE
Replacing interface{} with any everywhere (except generated mocks)

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
The changes here are to remove the usage of interface{} and replace it with any that is more semantic. There is a go vet check design for that already, but I added the ignore flag to be able to ingore generated code like mocks. This way we can have a better understanding of the code and the usage of interface{}.

In the short them, when the PR for the mattermost-govet repository is merge, we can update the Makefile to enforce the usage of any instead of interface in any not-generated code.

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by agarciamontoro — APPROVED** [review]
Looks good to me!

**Review by isacikgoz — APPROVED** [review]
I guess we don't want to see `interface{}` ANYwhere 😛

**Pull request merged**
