### PR TITLE
✨ feat(.github/holopin.yml): add holopin configuration file to manage…

### LINKED ISSUE #26807: Add .github/holopin.yml
We want to add [Holopin](https://www.holopin.io/) support to the repository by adding a [`.github/holopin.yml` file](https://github.com/marketplace/holopin) that would allow us to grant badges to contributors via a GitHub integration. The first badge to be added will be for QA contributors.

Example use cases:

> - Rewarding contributors
> - Recognizing helpers
> - Welcoming new members
> - Encouraging good practices, eg. rewarding comprehensive bug reports, error stack traces, fully scoped out feature suggestions

To use:

> Issue the default badge by tagging @holopin-bot @username in conversation, or by alias @holopin-bot @username sticker-alias

Other repositories for us to open issues/PRs in to make the same change:

- https://github.com/mattermost/quality-assurance
- https://github.com/mattermost/mattermost-test-management
- https://github.com/mattermost/docs
- https://github.com/mattermost/mattermost-developer-documentation
- https://github.com/mattermost/mattermost-mobile
- https://github.com/mattermost/desktop
- https://github.com/mattermost/mmctl

cc @lindy65 @iyampaul

### PR DESCRIPTION
**Pull request by azigler**
Fixes #26807 

```release-note
NONE
```

cc @lindy65 @iyampaul

### CODE REVIEW

**Comment by azigler** [comment]
@lindy65 Anyone we can ping to un-stuck this?

**Review by hanzei — APPROVED** [review]

**Comment by lindy65** [comment]
Thanks for your review @hanzei 🎉 

If a 2nd review is required, I was thinking that perhaps @iyampaul could review?

cc// @azigler

**Review by iyampaul — APPROVED** [review]

**Comment by azigler** [comment]
Not sure why these a build check failed, as this is just adding a `.github` files for Holopin. @saturninoabril any ideas here? Can we just re-run the check?

**Comment by saturninoabril** [comment]
@azigler Did the re-run and passed. Now onto the last check (enterprise test). Feel free to merge after.

**Comment by saturninoabril** [comment]
Thanks for the feedback and yes, totally agree. Streamlining the process would be a good next step -- what to run depending on change. We have "path" filters in few places, but definitely something to review as a whole.

**Comment by lindy65** [comment]
Thanks for your help on this! @holopin-bot @azigler Mattermost QA Community Contributors

**Pull request merged**
