### PR TITLE
[MM-54842] Convert LocalizedInput of 'abstract_command.tsx' to regular input component

### PR DESCRIPTION
**Pull request by izruff**
#### Summary

Replaces the `LocalizedInput` component in `webapp/channels/src/components/integrations/abstract_command.tsx` to a regular `input` component.

#### Ticket Link

Fixes [#24829](https://github.com/mattermost/mattermost/issues/24829)
Jira https://mattermost.atlassian.net/browse/MM-54842

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
The component looks good to me however there are few CI failures that you would need to work on. Specifically the test file of this component needs to be updated after the injectIntl hoc addition. You can try to look at other component's test files whose component have that hoc wrapped around them. Let me know if you have questions

**Comment by izruff** [comment]
@M-ZubairAhmed I have updated the affected test cases and snapshots. It should pass all checks except for the type checking in `abstract_command.test.tsx`, the problem is that `wrapper.instance()` returns type `React.Component<{}, {}, any>` so calling a method in the AbstractCommand class by `wrapper.instance().someMethod(...)` results in "property does not exist" error. I'm still trying to fix this, but I'm not very familiar with TS so this might take a while. If you have suggestions on how to fix it please let me know!

Also this is my first time dealing with testing, hopefully I did it right :)

**Comment by M-ZubairAhmed** [comment]
> @M-ZubairAhmed I have updated the affected test cases and snapshots. It should pass all checks except for the type checking in `abstract_command.test.tsx`, the problem is that `wrapper.instance()` returns type `React.Component<{}, {}, any>` so calling a method in the AbstractCommand class by `wrapper.instance().someMethod(...)` results in "property does not exist" error. I'm still trying to fix this, but I'm not very familiar with TS so this might take a while. If you have suggestions on how to fix it please let me know!
> 
> Also this is my first time dealing with testing, hopefully I did it right :)

First of all the work you did is amazing. Thank you so much. This is exactly same scenario another contributor was facing, let me direct you to that PR https://github.com/mattermost/mattermost/pull/24858
please take a look and if you have further question i will be happy to answer 😄

**Comment by izruff** [comment]
Thank you for your help! This commit should fix it.

**Review by M-ZubairAhmed — APPROVED** [review]
Impressive work @izruff thank you so much

**Review by sinansonmez — APPROVED** [review]
LGTM 🚀 thanks

**Review by yasserfaraazkhan — APPROVED** [review]
added a slash command and it functioned as expected. Saw not console errors.

**Pull request merged**
