### PR TITLE
[MM-57738] Added GetPluginID method to Manifest model

### PR DESCRIPTION
**Pull request by willypuzzle**
#### Summary
A new method, GetPluginID, has been added to the Manifest model. This function returns the ID of a plugin. Corresponding unit tests have also been implemented to ensure that this function works as expected. The test cases cover scenarios where IDs are the same and different.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/26710
Jira https://mattermost.atlassian.net/browse/MM-57738

#### Release Note
```release-note
Added: test
```

Related PR:
https://github.com/mattermost/mattermost-plugin-starter-template/pull/199

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by willypuzzle** [comment]
Sorry, I thought that autoassign command was valid even for assigning Assignes

**Comment by willypuzzle** [comment]
@mickmister the check failed for reasons not depending from my PR (as you can see). What is supposed I should? Should I do skip the test even if I haven't introduced such flaky test?

**Comment by mickmister** [comment]
@willypuzzle The tests passed :+1: There's just some issue with reporting test results. I re-ran the failed job to see if the issue is fixed.

image

**Comment by willypuzzle** [comment]
@mickmister the check failed for another reason but I cannot access to the link details. I think it's a privileged zone.

**Review by fmartingr — APPROVED** [review]
LGTM. Unsure about the test that checks a non-equal value, but that doesn't hurt.

Can you merge latest `master` into your branch? It seems some changes came in a day after you submitted your PR and that's why that test is failing.

**Comment by mickmister** [comment]
Hi @willypuzzle, I talked this over with a team member and we think the requirements may have been unclear here. The ask is to add this to the plugin API, rather than a method on the `Manifest` struct. The issue with the implementation in this PR is the plugin still needs to have a way to access the `Manifest`, which is actually the issue to solve here.

So I'm thinking the method we should add to the plugin API is `GetManifest`, which would allow the plugin to access everything from the `Manifest` struct. @willypuzzle I apologize for the confusion here. Would you be up for implementing this requirement?

**Comment by willypuzzle** [comment]
> Hi @willypuzzle, I talked this over with a team member and we think the requirements may have been unclear here. The ask is to add this to the plugin API, rather than a method on the `Manifest` struct. The issue with the implementation in this PR is the plugin still needs to have a way to access the `Manifest`, which is actually the issue to solve here.
> 
> So I'm thinking the method we should add to the plugin API is `GetManifest`, which would allow the plugin to access everything from the `Manifest` struct. @willypuzzle I apologize for the confusion here. Would you be up for implementing this requirement?

@mickmister yes! Sure!

**Comment by hanzei** [comment]
@mickmister is spot on. The intent of the ticket was to add a new method to the plugin API, not to add a getter method to `Manifest`. Given that getter methods are an anti-pattern in go suggest that we revert this PR. @willypuzzle @mickmister What do you think?

**Comment by willypuzzle** [comment]
> @mickmister is spot on. The intent of the ticket was to add a new method to the plugin API, not to add a getter method to `Manifest`. Given that getter methods are an anti-pattern in go suggest that we revert this PR. @willypuzzle @mickmister What do you think?

I think the get method is not strictly necessary but however useful to clarify the use of the API. Anyway for me it's not a problem to revert the changes introduced by this PR. Please, let me know.

**Comment by hanzei** [comment]
The new API method will be used in other library methods to build high-level frameworks. E.g. methods like https://pkg.go.dev/github.com/mattermost/mattermost/server/public@v0.1.4/pluginapi/experimental/flow#NewFlow use `pluginID` as an argument, which is not necessary if an API method exists that allow fetching the pluginID.

**Comment by hanzei** [comment]
Submitted https://github.com/mattermost/mattermost/pull/27540 to revert the changes in this PR

**Pull request merged**
