### PR TITLE
[MM-57711] Convert ./components/latex_inline/latex_inline.tsx from Class Component to Function Component

### PR DESCRIPTION
**Pull request by artemdev9**
#### Summary

Migrated latex_inline.tsx from Class Component to Function Component.

QA Test Steps: 
Paste: e^{i\\pi} + 1 = 0 wrapped by $ into the textarea. The latex inline component will render.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/26679
Jira https://mattermost.atlassian.net/browse/MM-57711

#### Release Note

None

### CODE REVIEW

**Review by larkox — APPROVED** [review]
Great work! LGTM

**Comment by harshilsharma63** [comment]
@artemdev9 can you fix the lint errors for the `Web App CI PR / pr-ci / check-lint (pull_request)` step in checks?

**Comment by artemdev9** [comment]
@harshilsharma63 fixed lint errors.

**Comment by larkox** [comment]
@artemdev9 The change in the test name has broken the snapshots. Just run `npm run test -- -u` and it should solve it.

**Comment by artemdev9** [comment]
I've encountered an issue after running npm `run test -- -u` which updated the snapshots. The new snapshot structure is significantly simplified, rendering the raw LaTeX input within a single span. This is a deviation from the previous snapshots which utilized nested elements and `dangerouslySetInnerHTML`.

I discovered this change aligns with a merged pull request that migrated LatexBlock from a class to a function:
https://github.com/mattermost/mattermost/pull/26967

This specific comment within the PR thread explains the problem well:
https://github.com/mattermost/mattermost/pull/26967#issuecomment-2119165834

Given this context, I seek confirmation on the preferred approach:
- Update the snapshots as per the current test run (npm run test -- -u) and submit the simplified tests.
- Adapt the approach from the LatexBlock pull request and implement similar changes in the codebase (which I believe is the more robust solution).
Please advise on the preferred direction.

**Comment by larkox** [comment]
@artemdev9 If you could change the tests to use `react-testing-library` as the PR you mentioned, that would be great! Thank you!

**Comment by larkox** [comment]
@artemdev9 Are you still working on this?

**Comment by artemdev9** [comment]
@larkox Yes, I will get it done asap. Sorry for the delay.

**Comment by artemdev9** [comment]
@larkox I have changed the tests to use the react-testing-library

**Comment by larkox** [comment]
@artemdev9 There are still a couple of lint checks failing. Can you look at those?

**Comment by larkox** [comment]
@artemdev9 Are you still looking at this?

**Comment by artemdev9** [comment]
@larkox yes

**Comment by harshilsharma63** [comment]
@artemdev9 there are some minor lint issues. Try the auto-fix once and remaining ones should be easy to fix manually.

**Comment by larkox** [comment]
@artemdev9 Are you still looking into this?

**Pull request closed without merging**
