### PR TITLE
RN: Remove code using expandedLink and getRedirectLocation from mobil…

### PR DESCRIPTION
**Pull request by belkhoujaons**

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@belkhoujaons this ticket pertains to removal from the mattermost/mattermost-mobile and not this server repo. Because we have to deprecate the apis before removing them directly.

**Comment by belkhoujaons** [comment]
@M-ZubairAhmed I hope I understood what you meant, if yes please link the PR with  the issue before merging

**Comment by M-ZubairAhmed** [comment]
> @M-ZubairAhmed I hope I understood what you meant, if yes please link the PR with the issue before merging

This pr need to be worked on in https://github.com/mattermost/mattermost-mobile

**Comment by hanzei** [comment]
Closing as the works need to be done on https://github.com/mattermost/mattermost-mobile

**Pull request closed without merging**
