### PR TITLE
[MM-58686] Adjust text alignment on custom status tooltip

### PR DESCRIPTION
**Pull request by Gesare5**
#### Summary

Adjusts text on custom status tooltip for better content alignment
Fixes calculation on the 'Today' status expiry time; to show 'Until Tomorrow' on custom status tootltip on 'Today' selection

#### Ticket Link

Fixes [#27324](https://github.com/mattermost/mattermost/issues/27324)
Jira https://mattermost.atlassian.net/browse/MM-58686

#### Screenshots

| 
original
 | 
Screenshot from 2024-06-14 13-42-00
 |

#### Release Note

```release-note 
NONE
```

### CODE REVIEW

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Thanks for contributing @Gesare5. I had a quick look and I'm still seeing the spacing issue between the emoji and the text. You may not notice it with the text you tested with, but if you use my text below you'll see it.

image

**Comment by Gesare5** [comment]
Okay I'll check it out, what browser are you testing this on? @matthewbirtch

**Comment by matthewbirtch** [comment]
> Okay I'll check it out, what browser are you testing this on? @matthewbirtch

Testing in Chrome

**Review by matthewbirtch — APPROVED** [review]
That did the trick. Thanks @Gesare5. Looks good to me now.

**Review by JulienTant — APPROVED** [review]
I agree that "Until Today" feels wrong, but I'm also not sure how I feel about the arbitrary 8am 🤔 Not a blocker tho, thanks for your contribution!

**Comment by Gesare5** [comment]
You're welcome!! Would it be better to have no time at all? @JulienTant

**Comment by JulienTant** [comment]
> You're welcome!! Would it be better to have no time at all? @JulienTant

I think I'd prefer to have no time, but again it's not a big deal :)

**Review by mgdelacroix — APPROVED** [review]
LGTM! Thanks for the contribution @Gesare5! :sparkles:

**Comment by lindy65** [comment]
Thanks @Gesare5 - I'm seeing alignment I'm not sure is correct so I'm tagging @matthewbirtch to check. The Jira ticket did not mention how exactly the text should be aligned (e.g. left / centered / etc) so is what I've pasted below correct?

image

**Comment by Gesare5** [comment]
Should be all centered, so that is okay @lindy65

**Comment by lindy65** [comment]
Ah, I went back to the issue https://github.com/mattermost/mattermost/issues/27324#issuecomment-2163742627 and saw that the lines of text should be centered so I believe what I am seeing is correct. Thanks @Gesare5

**Review by lindy65 — APPROVED** [review]
Thanks @Gesare5 - looks good to me 👍

**Comment by lindy65** [comment]
Thanks @matthewbirtch 🤗

**Comment by marianunez** [comment]
@matthewbirtch is this good to merge?

**Pull request merged**
