### PR TITLE
[MM-53204] Wont show "reset password" link if only LDAP/AD enabled

### PR DESCRIPTION
**Pull request by Emil-Carlsson**
#### Summary
A users should not have the option to reset a password if only LDAP/AD is enabled. I made a small change in login.jsx checking for this in the condition for displaying the forgot password link. 

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/23860
https://mattermost.atlassian.net/browse/MM-53204

#### Release Note
```release-note
Forget password link wont be displayed if only LDAP/AD is enabled.
```

### CODE REVIEW

**Review by enahum — APPROVED** [review]

**Review by jespino — APPROVED** [review]
It looks good to me. Thanks @Emil-Carlsson! :partying_face:

**Review by lindy65 — APPROVED** [review]
Thanks @Emil-Carlsson - looks good to me 👍 

cc @jespino

**Pull request merged**
