### PR TITLE
[MM-54791]: Convert email icon component to function component

### PR DESCRIPTION
**Pull request by 0xJamin**
#### Summary
This PR converts the email icon widget from a class component to function component

#### Ticket Link

If applicable, please include both or either of the following links:

Fixes https://github.com/mattermost/mattermost/issues/24755
Jira https://mattermost.atlassian.net/browse/MM-54791

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by jespino — APPROVED** [review]
LGTM

**Comment by jespino** [comment]
@larkox can you assign the right person for QA on this?

**Comment by larkox** [comment]
Thank you very much for the contribution!

**Pull request merged**
