### PR TITLE
[MM-58511] Migrate tooltips of "components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx" to WithTooltip

### PR DESCRIPTION
**Pull request by Aryakoste**
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27235
Jira https://mattermost.atlassian.net/browse/MM-58511

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@Aryakoste can you look at the failing CI

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
It looks like one ci is still failing can you please check

**Comment by M-ZubairAhmed** [comment]
@Aryakoste you might have to update the snapshots

**Comment by Aryakoste** [comment]
I have run the ci test locally and it's showing PASS there.

**Comment by Aryakoste** [comment]
Test which has failed here which I ran locally and PASS:- src/utils/performance_telemetry/reporter.test.ts

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by Rajat-Dabade — APPROVED** [review]

**Review by yasserfaraazkhan — CHANGES_REQUESTED** [review]
@M-ZubairAhmed 

only on this PR spinwick seeing a black icon when clicked on the help icon

Screenshot 2024-06-24 232318

**Comment by M-ZubairAhmed** [comment]
CI For this will be fixed once https://github.com/mattermost/mattermost/pull/27597 is merged in master and this is rebased

**Comment by M-ZubairAhmed** [comment]
> @M-ZubairAhmed
> 
> only on this PR spinwick seeing a black icon when clicked on the help icon
> 


This is fixes

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
