### PR TITLE
Migrate `./components/admin_console/team_channel_settings/channel/channel_settings.tsx`  from class to function component

### PR DESCRIPTION
**Pull request by aditipatelpro**
#### Summary

Migrate `./components/admin_console/team_channel_settings/channel/channel_settings.tsx` from class to function component

#### Ticket Link
Fixes: https://github.com/mattermost/mattermost/issues/25604

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by hanzei** [comment]
@aditipatelpro Would you be open to signing the [CLA](http://www.mattermost.org/mattermost-contributor-agreement/)?

**Comment by aditipatelpro** [comment]
> @aditipatelpro Would you be open to signing the [CLA](http://www.mattermost.org/mattermost-contributor-agreement/)?

Surely! I signed it.

**Comment by aditipatelpro** [comment]
Hi @hanzei, can you please review this PR?

**Comment by aditipatelpro** [comment]
@hanzei, I have created another PR for the same issue, here #25634. 
Sorry for opening up redundant PRs I just realized I was working on a different branch.

**Comment by hanzei** [comment]
No problem @aditipatelpro Thank you very much for the contribution 🚀

**Pull request closed without merging**
