### PR TITLE
Fix MM 56723

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Fix MM 56723

#### Ticket Link
Fix https://mattermost.atlassian.net/browse/MM-56723

#### Related PRs:
Mobile: https://github.com/mattermost/mattermost-mobile/pull/7883
Push Proxy: https://github.com/mattermost/mattermost-push-proxy/pull/119

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by enahum — APPROVED** [review]

**Review by jupenur — APPROVED** [review]

**Review by agarciamontoro — COMMENTED** [review]
Do we have an idea of how expensive running `SignedString` is?

**Comment by larkox** [comment]
@agarciamontoro Not really, and not sure how would you like to check it. I can try a quick go benchmark running it (for example) 1000 times, but not sure if that gives you a good idea of how expensive it is.

**Review by yasserfaraazkhan — APPROVED** [review]
notifications did not show with New mobile app, New server, New proxy changes as expected.

Screenshot from 2024-04-12 18-21-16

**Comment by agarciamontoro** [comment]
> Not really, and not sure how would you like to check it. I can try a quick go benchmark running it (for example) 1000 times, but not sure if that gives you a good idea of how expensive it is.

@larkox, I'd love to see a CPU profile with the changes and without them, so that we can assess if the load has increased a lot. You can get the profile while running the benchmark with and without the changes, probably. Does that sound reasonable?

**Comment by agarciamontoro** [comment]
Summarizing here what @larkox and I discussed in a DM.

He implemented the following new benchmark and ran it with and without the changes in this PR:
```go
func BenchmarkSendPushNotificationToAllSessions(b *testing.B) {
    th := Setup(b).InitBasic()
    defer th.TearDown()
    _, _ = th.App.CreateSession(th.Context, &model.Session{
        UserId:    th.BasicUser.Id,
        DeviceId:  "test",
        ExpiresAt: model.GetMillis() + 100000,
    })

    for i := 0; i < b.N; i++ {
        _ = th.App.sendPushNotificationToAllSessions(&model.PushNotification{}, th.BasicUser.Id, "")
    }
}
```

He ran the benchmark 1000 times in each case, getting [two CPU profiles](https://github.com/mattermost/mattermost/files/15078991/pprofs.zip).

Comparing both profiles and focusing on the call to `th.App.sendPushNotificationToAllSessions`, we can see that the call took even less percentage of time in the new code (from 24.08% to 20.30%)
image
We clearly see the addition of `jwt.SignedString` in the flamegraph, but overall it took slightly less time to compute the whole thing, so the overhead seems to be negligible.

I think this is safe to merge, but I'd love to have another pair of eyes on this. @agnivade, could you double-check this as well?

**Comment by agnivade** [comment]
I haven't looked at the code, but if `jwt.SignedString` is added newly, do we know why it runs faster?

**Comment by agarciamontoro** [comment]
There's some more overhead in the garbage collection runtime, which may explain the slighty lower percentage in the function itself.
image

**Comment by agarciamontoro** [comment]
Another data point that is missing is the total time of the benchmark, which gives me some peace of mind:
- Without change, 1000 iterations -> 102.243s
- With the change, 1000 iterations -> 102.364s

**Comment by agnivade** [comment]
Well, if the jwt signing is something we have to add anyways, then there's not really much to do here. And push notifications are always handled in a separate goroutine, so it does not block the main API response. So should be good from a performance side.

**Review by agarciamontoro — APPROVED** [review]
All good from our side, @larkox. Thanks for looping me in :)

**Comment by larkox** [comment]
@amyblais Let me know if I need to do anything to manage the backport for this fix.

**Comment by amyblais** [comment]
@larkox This seems to need a manual cherry-pick PR for ``release-9.8`` branch.

**Comment by amyblais** [comment]
@larkox Since this needs manual cherry-picks, please also submit cherry-pick PRs for ``release-9.7``, ``release-9.6``, ``release-9.5`` and ``release-8.1`` branches (but not merge them quite yet).

**Comment by larkox** [comment]
@amyblais All cherrypicks should be done. I put the "Do not merge" label in all of them (i think) just in case. Feel free to remove the label and merge when it is ok on your side.

**Pull request merged**
