### PR TITLE
Update Prepackaged GitLab plugin to 1.7.0

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

https://github.com/mattermost/mattermost-plugin-gitlab/pull/380

#### Release Note

```release-note
GitLab plugin v1.7.0 is now available via prepackaged plugins
```

### CODE REVIEW

**Review by hanzei — CHANGES_REQUESTED** [review]
Should we really push this version out to all customers? Maybe we wait a few months until we ensure it's stable.

**Comment by mickmister** [comment]
@hanzei I was mainly trying to converge on the marketplace deprecation efforts, which makes it so the remote marketplace will be opt-in and not available on Cloud, making it so prepackage plugins are the only way to install this plugin. I figured many customers want the fix at https://github.com/mattermost/mattermost-plugin-gitlab/pull/378, since we've gotten a lot of feedback on that.

All that being said, I'm fine with holding off merging this. The plugin is available for both on-prem and cloud at the moment via the marketplace already.

**Comment by hanzei** [comment]
If we merge this change now, it will go live mid of October. That seems fine with me. We should just be vigilant about any bug reports we get.

**Review by hanzei — APPROVED** [review]

**Comment by DHaussermann** [comment]
@mickmister or @hanzei, I'm having a tooling issue here I need help with. 

I successfully did the 1st part of the test where I ensure the pre-packeged plugin will upgrade when the server code is deployed 👍 

I think this technically validates the change but there is a second portion where I disable remote access to the marketplace and ensure the plugin can still be re-installed from local storage.
I can't test this anymore. It seems like all `/cloud` servers now hide this (along with marketplace URL) from the UI. This happens regardless of what license I have when the server is created. 
image

There use to be the following:
image
 
Do either of you have any thoughts what's happening here? Is this part of recent changes perhaps? cc @lindy65  in case this sounds familiar with recent changes from your team.

**Comment by mickmister** [comment]
@DHaussermann This likely has to do with changes to deprecate the the marketplace. Do you mind bringing this up in https://community.mattermost.com/private-core/channels/deprecation-planning?

Is this PR good to merge?

**Comment by DHaussermann** [comment]
Yes, @mickmister seeing as how the upgrade works, the bundle would be available. I'm good to merge this PR.

I did post in the channel here https://community.mattermost.com/private-core/pl/q3uizto3gffitbq5iymp1j5t5a to get some clarity on this.

**Review by DHaussermann — APPROVED** [review]
Tested and passed as per comments above.

**Comment by lindy65** [comment]
I see you got clarification in-channel @DHaussermann :)

**Pull request merged**
