### PR TITLE
MM-51528 Fix new messages line overlapping date lines

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
The changes to unify the post component caused an extra div to be introduced between the `post-row__padding` (`PostListRow`) and the `post` itself (`PostComponent`) which caused the old CSS that handled positioning the New Messages and date lines to apply to posts so then it got removed. That extra div only applied to posts in the search results, so I moved it to a new `SearchResultsItem` and reverted the changes to the CSS so that those lines wouldn't overlap each other any more. And then I decided to change the CSS to be a bit more self-explanatory and not get affected by this sort of change in the future.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51528

#### Screenshots
Screen Shot 2023-05-26 at 3 24 06 PM
Screen Shot 2023-05-26 at 3 23 50 PM

#### Release Note
```release-note
Fixed the New Messages line overlapping date lines in the post list
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by calebroseland — COMMENTED** [review]
There's some height differences between center channel and RHS
CleanShot 2023-05-30 at 16 41 52@2x

**Comment by hmhealey** [comment]
Good catch, Caleb. I didn't realize the `.new-separator` had a `.Separator` one level below it, so we were doubling up on the padding. Here's a comparison with 7.0 to confirm that it now looks the same as it did before
Screen Shot 2023-06-01 at 5 19 25 PM

**Comment by yasserfaraazkhan** [comment]
@hmhealey @calebroseland 
on the spinwick, that long channel name might not be a case, but just sharing a UI scenario where it looks little overlapped
Screenshot 2023-06-09 at 10 35 40 PM

**Comment by calebroseland** [comment]
@yasserfaraazkhan with #23649 now merged and reflected here, I think this is working now. The date separators in your screenshot were ghost instances that should be gone now.

**Comment by hmhealey** [comment]
Yeah, I can confirm I'm not seeing those any more on the test server. There's been quite a few fixes to this same area of the code recently all addressing similar cases that are all slightly different, and that PR was for another one of them

**Review by yasserfaraazkhan — APPROVED** [review]
thank you Harrison 🎉

**Pull request merged**
