### PR TITLE
[MM-39597] Implement ConfigDiffs.Sanitize()

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

They say _never two without three_  so we implement a new `Sanitize()` function that we call before logging config diffs.

This is currently achieved by having a prepared map of sensitive config paths that we compare.  This can be later improved by using something more dynamic, maybe struct tags or something else. Also to be reviewed is the sanitization of specific config settings that can contain a mixture of sensitive and non-sensitive portions like DSNs and plugin configs. Right now we replace those as a whole.

#### Ticket

https://mattermost.atlassian.net/browse/MM-39597

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by amyblais** [comment]
@streamer45 Is this needed for 6.0.x?

**Comment by streamer45** [comment]
> @streamer45 Is this needed for 6.0.x?

I am guessing so but I've asked Security to confirm.

**Comment by streamer45** [comment]
@amyblais Confirmed this needs backporting up to (and including) ESR.

**Comment by streamer45** [comment]
@amyblais I need to do those manually as well. Will do it in the morning.

**Pull request merged**
