### PR TITLE
MM-57511: Allow warn_metric post type to be imported

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-57511
```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
I really think we shouldn't be doing this, given that we are approaching v10 soon. The better way would be to simply ask users to export from a newer version.

LMK what you guys think.

**Review by isacikgoz — APPROVED** [review]
Deprecating this for `v10` sound good to me. Approving if this is a blocker for an ongoing issue.

**Comment by streamer45** [comment]
> I really think we shouldn't be doing this, given that we are approaching v10 soon. The better way would be to simply ask users to export from a newer version.
> 
> LMK what you guys think.

Unless we backport/cherry-pick, this PR will be scheduled for v10. I think this fix may make more sense in v9.11 ESR if we can still include it; otherwise, we could probably consider a more explicit approach that simply doesn't allow an import from unsupported (outdated) export formats. To do that we'd likely need to start versioning these exports properly. Something to think about @isacikgoz @nab-77

**Comment by agnivade** [comment]
Yes, adding versions to exports sound like the right approach. As per my understanding, this came up merely from an internally generated export, so there isn't any urgency. So if we all agree that we should impose minimum export version, then we can simply drop this PR.

**Comment by streamer45** [comment]
> Yes, adding versions to exports sound like the right approach. As per my understanding, this came up merely from an internally generated export, so there isn't any urgency. So if we all agree that we should impose minimum export version, then we can simply drop this PR.

Sounds good. Let's bring this up at planning later today.

**Comment by agnivade** [comment]
As discussed in the planning, closing this one out.

**Pull request closed without merging**
