### PR TITLE
[MM-60964] Update permissions banner button text and dismiss behaviour

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Ticket Link

Jira https://mattermost.atlassian.net/browse/MM-60964

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@abhijit-singh should the CTA for the banner be also changed from 'ENable notifications"?

**Comment by abhijit-singh** [comment]
@M-ZubairAhmed Yes, the recommendation is to change the CTA label to `Manage notification preferences`.

**Comment by M-ZubairAhmed** [comment]
> @M-ZubairAhmed Yes, the recommendation is to change the CTA label to `Manage notification preferences`.

CTA changed. please check the behavior for this PR

**Review by devinbinnie — APPROVED** [review]

**Review by abhijit-singh — APPROVED** [review]
Looks good to me!

**Review by hmhealey — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
