### PR TITLE
MM-55736 Add Request Context to TeamStore.SaveMember

### LINKED ISSUE #26027: Add Request Context to TeamStore.SaveMember
#### Summary

To improve logging, we want to replace the global logger with a request-specific one (which will add the request ID to the log message). The request context therefore contains a logger which is already pre-configured with the appropriate information. The task remains to pass the context to all methods used in fulfilling the request.

#### Tasks

- [ ] Change the `SaveMember` method in `server/channels/store/sqlstore/team_store.go` to receive `rctx request.CTX` as the first argument [1].
- [ ] Update the `TeamStore` interface in `server/channels/store/store.go`.
- [ ] Make sure all functions calling the changed methods pass along the context.
- [ ] Update the generated interfaces with `make generated`.
- [ ] Update the tests.

#### Hints

- These changes tend to change a lot of files. Don't be afraid to ask for guidance when you feel it's getting out of control. Since a lot of these methods call each other, it's common to have to change 10 or more files.
- Some methods already contain a `c *request.Context`. You can replace it with `rctx request.CTX`. `request.Context` implements the interface `request.CTX,` so there should be no problem passing a `*Context` to a `CTX` parameter.
- The tests often work with a "TestHelper" (`th`) struct, which contains a `th.Context`. If it's missing, you can use a test helper from another package for ideas on how to add it.
- `api4` has its own separate context struct. That context contains the `request.CTX` we need. You can use `c.AppContext` to pass it to `App` methods.

Follow up on [https://github.com/mattermost/mattermost/pull/25468](https://github.com/mattermost/mattermost/pull/25468|smart-link) 

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-55736

### PR DESCRIPTION
**Pull request by compiledsound**
Fixes #26027

#### Summary
Add Request Context to TeamStore.SaveMember

#### Ticket Link
JIRA: https://mattermost.atlassian.net/browse/MM-55736

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Nice work :+1:

**Review by isacikgoz — APPROVED** [review]
Neat 👍

**Pull request merged**
