### PR TITLE
MM-54123 Add group slash command

### PR DESCRIPTION
**Pull request by sbishel**
replacement PR for https://github.com/mattermost/mattermost/pull/24517

#### Summary
Adds the ability to invite user groups via `/invite`

Combines same errors for multiple users into a single message depending on user count.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-54123

#### Screenshots
Screenshot 2023-09-08 at 11 10 40 AM

#### Release Note
```release-note
invite slash command now supports custom user groups
```

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by lindy65** [comment]
Hi @sbishel - I'm seeing an issue where, no matter which team I am in, the ephemeral message is using the name of `test` team

image

**Comment by sbishel** [comment]
@lindy65 - Thank you...I had placeholder code as I hadn't retrieved the team yet.  Should be working now.

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - looks good to me now 👍

**Pull request merged**
