### PR TITLE
MM-24276 Added "User joined and left" system messages

### PR DESCRIPTION
**Pull request by AsisRout**
#### Summary

This PR is for handling 'joined-left' events

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/24276
Jira https://mattermost.atlassian.net/browse/MM-53141

#### Screenshots

|  before  |  after  |
|----|----|
| Screenshot 2023-08-22 at 6 09 23 PM| Screenshot 2023-08-22 at 6 08 55 PM | 
Screenshot 2023-08-22 at 7 40 12 PM | Screenshot 2023-08-22 at 7 39 48 PM | 
Screenshot 2023-08-22 at 7 40 07 PM | Screenshot 2023-08-22 at 7 39 53 PM |

#### Release Note

```release-note
UI Changes for combining 'joined-left' events
```

### CODE REVIEW

**Comment by AsisRout** [comment]
@esethna Is there anything else I would need to add ?

**Comment by AsisRout** [comment]
@hmhealey sure..will add some unit tests

**Comment by hmhealey** [comment]
Yep, I'll take a look. Sorry for the delay since I was out sick for a bit last week

**Review by hmhealey — APPROVED** [review]
Taking a look at the code to me, it looks good to me. The code is a bit complicated, but that's to be expected given what we're trying to do here.

Thanks for adding those tests as well. They cover all the cases we discussed perfectly. I've added a few extra tests for edge cases, but that's mostly because it was easier for me to write tests than to manually double check how they worked in the browser

**Review by pvev — APPROVED** [review]
LGTM! thanks @AsisRout 👍

**Review by abhijit-singh — APPROVED** [review]
Looks good!

**Comment by hmhealey** [comment]
@yasserfaraazkhan Just a heads up with this, there's a few cases where multiple users are joining and leaving the channel around the same time where those messages don't quite combine fully. Definitely let us know if there's any cases that seem wrong to you, but I think we can accept that certain combinations of events aren't 100% perfect since the way we'd detect that can be very complicated

**Review by yasserfaraazkhan — APPROVED** [review]
I've used a script to have multiple users join and leave. All the Joined/left messages appeared as expected

**Comment by hmhealey** [comment]
Thanks again for the PR, @AsisRout!

**Pull request merged**
