### PR TITLE
[MM-52793] - When selecting a date on the calendar when searching, th…

### PR DESCRIPTION
**Pull request by hchorfispiria**
#### Summary
When searching for posts, if the calendar is displayed with on, before, after, etc. and a date is selected, the date one day before the selected date will be selected.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/23370
JIRA https://mattermost.atlassian.net/browse/MM-52793

#### Screenshots
Screen Shot 2023-06-04 at 11 02 49 PM
Screen Shot 2023-06-04 at 11 03 01 PM

#### Release Note

```release-note
The time zone should not affect date selection
```

### CODE REVIEW

**Review by harshilsharma63 — APPROVED** [review]

**Review by yasserfaraazkhan — CHANGES_REQUESTED** [review]
tested this by changing system's date & timezone.

the `on, after, before` are rightly displaying the selected date.

minor observation: @harshilsharma63 

the search params contains a trailing space, I think B.E is handling it, but I wonder if the F.E should also trim and send the request.


Screenshot 2023-07-18 at 6 10 47 PM

**Comment by M-ZubairAhmed** [comment]
> tested this by changing system's date & timezone.
> 
> the `on, after, before` are rightly displaying the selected date.
> 
> minor observation: @harshilsharma63
> 
> the search params contains a trailing space, I think B.E is handling it, but I wonder if the F.E should also trim and send the request.
> 
> Screenshot 2023-07-18 at 6 10 47 PM

This is ok because server parses them correctly example `on:2023-07-19 sdsd` and the case you mentioned is for empty search query

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by amyblais** [comment]
@M-ZubairAhmed Can you help cherry-pick this to the ``cloud`` branch?

**Pull request merged**
