### PR TITLE
Add config setting to set default User Setting for filter join/leave message

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Adds a new config setting `EnableJoinLeaveMessageByDefault` that sets the default value for User Setting: 

`Preferences.ADVANCED_FILTER_JOIN_LEAVE`

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-49015

#### Screenshots
Screenshot 2023-08-25 at 4 23 24 PM

#### Release Note

```release-note
Adds a new config setting TeamSettings.EnableJoinLeaveMessageByDefault that sets the default value for UserSetting, ADVANCED_FILTER_JOIN_LEAVE.

```

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]
LGTM!

**Review by crspeller — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - tested as per description in Jira ticket and this is working as expected 👍

**Pull request merged**
