### PR TITLE
[MM-57085] Remove UseNewSAMLLibrary experimental setting

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
The docs already state that it got removed: https://docs.mattermost.com/configure/deprecated-configuration-settings.html#use-new-saml-library

This PR updates the docs to reflect that.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-57085

#### Release Note
```release-note
Remove UseNewSAMLLibrary experimental setting
```

### CODE REVIEW

**Review by sbishel — APPROVED** [review]
Thanks for doing this.

**Comment by hanzei** [comment]
@DHaussermann I'm not sure if this PR requires smoke testing. It's a cleanup with no function changes.

**Comment by DHaussermann** [comment]
@hanzei there may be an issue here. When I ensure that I have a working SAML setup locally on `master` branch and then switch to this branch and then switch to this branch, I can no longer start my server with `enterprise` repo in place. 

I see the following
`# github.com/mattermost/enterprise/saml
../../enterprise/saml/saml.go:42:6: undefined: app.RegisterNewSamlInterface`

Perhaps there is a supporting `enterprise` PR for this that I am not seeing or maybe something else has been overlooked?

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Regression tested SAML login / logout
- No issues found
- I also see the E2E tests were updated. Thannks @hanzei 

LGTM!

**Pull request merged**
