### PR TITLE
[MM-56400] Allow mmctl to download a Support Packet using --local mode

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Follow up on https://github.com/mattermost/mattermost/pull/25419

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-56400

#### Release Note
```release-note
Allow mmctl to download a Support Packet using --local mode
```

### CODE REVIEW

**Review by JulienTant — APPROVED** [review]
Nice change, thanks @hanzei

**Review by mgdelacroix — APPROVED** [review]
Awesome! :rocket:

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Confirmed this now works with `--local`
- As a precaution, checked the bundle that was dowloaded
- As a precaution tested using a logged in user instead of using `--local`

LGTM!

**Comment by DHaussermann** [comment]
@hanzei please merge when you have a chance

**Pull request merged**
