### PR TITLE
[MM-56661] Fix: When deleting a draft you have to move your cursor away from the card and back to activate the buttons

### PR DESCRIPTION
**Pull request by gourav-varma**
#### Summary

As mentioned by @hmhealey, onMouseOver did the job.

Chrome ✅
Firefox ✅
Edge ✅

#### Ticket Link

Jira: [MM-56661](https://mattermost.atlassian.net/browse/MM-56661)
Issue: #26114 

#### Screenshots
Chrome Screen Recording:

https://github.com/mattermost/mattermost/assets/64647858/617f80bc-2ff7-40f3-b2ca-d9ed6f45c4c2

#### Release Note

```release-note
NONE
```

[MM-56661]: https://mattermost.atlassian.net/browse/MM-56661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by M-ZubairAhmed** [comment]
@gourav-varma can you fix the CI

**Comment by M-ZubairAhmed** [comment]
@hmhealey gentle nudge on this one

**Comment by hmhealey** [comment]
Sorry about that. I'm not sure how I missed this one.

This looks good to me minus the snapshots being out of date. If you run `npm test -- -u`, it'll rerun the unit tests and update the snapshots for you

**Comment by gourav-varma** [comment]
Updated the snapshots. CI should be fixed now.

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
