### PR TITLE
[MM-61213] Limit file size for slack import file uploads

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Add an `io.LimitedReader` to the uploads for slack imports.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-61213

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by esarafianou — APPROVED** [review]

**Comment by esarafianou** [comment]
@isacikgoz we need a second dev reviewer too. I don't count as one.

**Review by agnivade — CHANGES_REQUESTED** [review]
We need to check for error in the io.Copy line in L787, for us to be able to bubble up the error.

Also, let's add a test for this.

**Review by agnivade — APPROVED** [review]
Thanks

**Pull request merged**
