### PR TITLE
MM-56630 Scroll Fix of center panel

### PR DESCRIPTION
**Pull request by Aryakoste**
#### Summary

This fixes the problem where we were not able to scroll the center channel with page up/down button.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/26120
Jira https://mattermost.atlassian.net/browse/MM-56630

#### Release Note

```release-note
Now we can scroll the center channel with page up/down buttons.
```

### CODE REVIEW

**Comment by hmhealey** [comment]
Thanks for the PR! I like the idea of this, especially since it makes the `PostList` behave more like the `ThreadViewer`, and it'd be nice to have those use the same code eventually. Unfortunately, I've found a few issues with this so far:

1. Most importantly, if the channel has more than a few hundred posts, scrolling back far enough causes the post textbox to be unmounted and disappear. 
2. On Firefox and Safari, the post list allows overscrolling for some reason. I'm not sure why that works fine on Chrome, but maybe that could be fixed by adding `overscroll-behaviour` to the CSS for whichever element of the post list scrolls.
3. The page up/page down hotkeys also don't work on Firefox and Safari. I'm not sure if that's related to the overscrolling or not.

If you need any help figuring those out or want to discuss anything about this, please let me know

**Comment by Aryakoste** [comment]
@hmhealey I have looked into your points. I have been experimenting ways to solve them optimally. Will let you know when I find the solutions to all.

**Comment by hmhealey** [comment]
Sounds good. As before, let me know if there's anything I can help with with this. This is a pretty complicated area of the code, so I can try to help with it when possible

**Comment by lindy65** [comment]
Hi @Aryakoste 👋 

How are things going with your investigation into this issue?  As @hmhealey mentioned, it's a complex code area so please reach out to him in need.

Thank you for your hard work looking into this 🎉

**Comment by Aryakoste** [comment]
Hii Sorry for the delay. I will take deeper look into this issue this week and will update if I need any help.

**Comment by Aryakoste** [comment]
@hmhealey The thread virualized list has the same issue with firefox it doesnt scroll on pageup/pagedown. I took look into the point where you told if we put few hundred posts. There is a thing i think it can be doing of DynamicSizeList. If we scroll above certain posts the posts below gets converted into a div with some styles means its no longer listitem and its content is removed. This happens to posts below when we keep scrolling.

**Comment by Aryakoste** [comment]
Before:-
image

After:-
image

**Comment by Aryakoste** [comment]
The renderRow method isnt getting called for this posts. It is dynamicSizeList / dynamic-virtualized-list component which does this i think. I will keep experimenting with the props passed into it. Do you have any suggestions @hmhealey

**Comment by hmhealey** [comment]
> If we scroll above certain posts the posts below gets converted into a div with some styles means its no longer listitem and its content is removed. This happens to posts below when we keep scrolling.

That's expected for the post list. ["Virtualizing" the list](https://www.patterns.dev/vanilla/virtual-lists/) means that rows are only rendered when they're visible on the screen. The problem currently is that the virtualized list thinks the post textbox isn't visible, but that's wrong because you made it sticky to keep it visible.

Perhaps there's a way to tell the `DynamicSizeList` that the row containing the post textbox is always visible? If that doesn't exist, we might be able to add it to the library since the code for that is in https://github.com/mattermost/dynamic-virtualized-list

**Comment by lindy65** [comment]
Hi @Aryakoste - what do you think about `@hmhealey's` suggestions?

**Comment by Aryakoste** [comment]
So should I make the change in dynamic virtualized list repo and submit PR there or someone will make that change. @hmhealey @lindy65

**Comment by lindy65** [comment]
Hi @Aryakoste - if you're up for making the change in the dynamic virtualized list repo it'll be greatly appreciated! I'm sure @hmhealey will be able to help if you get stuck.

**Comment by Aryakoste** [comment]
Ok will do that and let you know. @lindy65

**Comment by lindy65** [comment]
Hi @Aryakoste - are you still working on this?

**Comment by Aryakoste** [comment]
Yeah @lindy65 I just had some questions related to dynamic virtualized repo code. I will post them here by tomorrow or EOD. Sorry for the delay.

**Comment by lindy65** [comment]
No worries @Aryakoste - thanks for your response :)

**Comment by Aryakoste** [comment]
What do you think @lindy65 @hmhealey

**Comment by lindy65** [comment]
Thanks @Aryakoste - I'll have to defer to `@hmhealey` on the code side of things :)

**Comment by hmhealey** [comment]
Thanks for the explanation of that. It's been a long time since we've really looked at that code. 😅

It sounds then like we'd need to add a similar prop to that component like `loaderId` which would let us pass in the ID of the textbox row and make that always render. Is that what you're thinking?

**Comment by Aryakoste** [comment]
@hmhealey Yeah like in frontend we render the textbox when the itemId is 'create-comment' text so we can pass it as props in dynamic virtualized list we will have to take in the props in DynamicSizeList. And in the renderitems function of DynamicSizeList. we can put that if the itemId is the prop we pass in then render it as normal element. We will have to put the condition in below code as shown in above comment.

if (
          (index >= startIndex && index < stopIndex + 1) ||
          isItemInLocalPosts ||
          isLoader
        ) {
          const item = createElement(children, {
            data: itemData,
            itemId,
          });

          // Always wrap children in a ItemMeasurer to detect changes in size.
          items.push(
            createElement(ItemMeasurer, {
              direction,
              handleNewMeasurements: this._handleNewMeasurements,
              index,
              item,
              key: itemId,
              size,
              itemId,
              width,
              onUnmount: this._onItemRowUnmount,
              itemCount,
            })
          );
        } else {
          items.push(
            createElement('div', {
              key: itemId,
              style,
            })
          );
        }

**Comment by marianunez** [comment]
@hmhealey @M-ZubairAhmed gentle ping on this review

**Comment by Aryakoste** [comment]
@hmhealey should i make this change in dynamicVirtualizedList repo ?.

**Comment by hmhealey** [comment]
@Aryakoste Yeah, please do. Once that's submitted, you can also update the package.json here to point to your branch so we can test it with the other changes for this PR

**Comment by Aryakoste** [comment]
I have made changes in dynamicVirtualizedList and pointed to by branch but somehow the change its not working. I will debug and let you know.

**Comment by Aryakoste** [comment]
When i pass in the id which i pushed in postIds to show the input or the advanceCreatePost. to the loaderId prop everything is working as it should be. But when i pass in new prop in the check of dynamicVirtualizedList renderItems, its not working idk why because it should. I thought my dynamicVirtualizedCode isnt getting updated but i checked in node_modules folder.

**Comment by Aryakoste** [comment]
In the latest commit. I have passed the CREATE_COMMENT as loaderId prop. But when i pass in only visibleId its not working the both props do same work. If the postId being equal to them render item normally. @hmhealey

**Comment by hmhealey** [comment]
I think the problem is that you only updated the source files in that repo, but it also has the compiled files checked in as well. You'll need to run `yarn run build` in it as well and check in the updated `dist` folder too.

I noticed that the the `build` script in the `package.json` starts with `del dist` which might need to be changed to `rm -rf dist` instead depending on your OS. Apparently the guy who made that library used Windows when working on it 😅

**Comment by Aryakoste** [comment]
Ok understood. Thanks. I will make the changes.

**Comment by Aryakoste** [comment]
Now the prop is working. Now createPost or input stays visible at all times regardless of scroll. @hmhealey

**Comment by hmhealey** [comment]
Awesome!

Unfortunately, we added some stuff to the `ChannelView` which should now be in the `PostList` with your changes, and that's causing some Git conflicts. Would you mind resolving those so that we can fully test this out?

Could you also submit a PR to https://github.com/mattermost/dynamic-virtualized-list with your changes to that repo as well?

**Comment by Aryakoste** [comment]
Yeah I will resolve the conflicts and will submit a PR a dynamic virtualized list.

**Comment by Aryakoste** [comment]
We can also implement this in threads virtualized list because there the input goes to the bottom as we scroll up. If we implement this there it will stay fixed at bottom.

**Comment by hmhealey** [comment]
The post lists in the RHS and the Threads view have actually been changed recently to behave like the centre channel, so those should all behave the same now. They work like the version of the centre channel without your changes though because their textboxes are outside of the virtualized list

**Comment by Aryakoste** [comment]
PR for dynamic-virtualized-list:- https://github.com/mattermost/dynamic-virtualized-list/pull/29

**Comment by Aryakoste** [comment]
I have resolved conflicts @hmhealey

**Comment by Aryakoste** [comment]
Working on it

**Comment by Aryakoste** [comment]
@hmhealey Not able to replicate the 4th point you mentioned.

**Comment by Aryakoste** [comment]
Regarding the point 2. The inner list div has been given bottom padding by us, it was the gap between the input and post list but now as the post list is the part of input we can remove it which will solve this issue.

**Comment by Aryakoste** [comment]
Regarding point 3 we will have to apply border-radius to post list now as text input is part of it.

**Comment by Aryakoste** [comment]
@hmhealey I have made changes.

**Comment by hmhealey** [comment]
Thanks! I'll take another look and see if I can still reproduce that issue with the textbox unmounting. Hopefully that was just a weird, temporary issue

**Comment by Aryakoste** [comment]
@hmhealey

**Comment by hmhealey** [comment]
I'm really sorry for the delays on reviewing this. I've been busy lately, so it's been hard to set aside the time to thoroughly test this out and finish reviewing it, especially since my normal keyboard doesn't actually have Page Up and Down keys on it  😅

I'm definitely going to take a look at this tomorrow morning, and I can also resolve the conflicts that I caused by taking so long

**Review by hmhealey — CHANGES_REQUESTED** [review]
I spent a couple of hours playing around with this, and I'm not sure any more if this approach is going to work.

First off, even with the overscrolling fixed, this still doesn't work in Firefox or Safari which makes me think we're doing something wrong here. We've taken a larger focus on accessibility lately, and the fact that the browser doesn't respond correctly indicates that there may be other issues with this approach that we haven't found yet.

I'm also still able to make the post textbox disappear in a couple cases: when scrolled near the top of the channel (point 4 above) and in a channel with new posts (like a newly created DM channel). I'm not sure how this never happened when the thread list behaved the same way, but it's now been changed to behave the same way as the centre channel does.

Finally, the post list scrollbar goes down past the post textbox which is definitely a bit of weird UX. I'm not sure if we can fix that without implementing a fake scroll bar.

---

After that, I took some more time looking at some other apps to see how they worked for comparison. I tested in Firefox. What I found was:
- Slack scrolls the post list manually although, at least on Firefox, it doesn't scroll smoothly like the browser would. It seems like they have a key handler on the textbox or somewhere above it that just scrolls the post list by a fixed amount when triggered.
- Teams doesn't support this. When you use page up/down with the post list focused, it scrolls like MM does, but it's incredibly janky.
- WhatsApp's web app scrolls the list of messages, and it does it with the regular browser animation and everything. It definitely seems like whatever they're doing is ideal here.

As best as I can tell, the way that WhatsApp supports this is that there's a key handler in their textbox that, when you press page up or page down, it focuses on the post list before the browser processes the default behaviour for to scroll the browser.

I played around with it a bit locally, and I needed to find a focusable element in the post list, but it seems like this idea might work.

Would you want to take a look at that method to see if it works? Sorry for leaving you waiting so long and then asking you to change how this all works. This is unfortunately a much more complicated fix than we'd even imagined previously

**Comment by Aryakoste** [comment]
Yeah, I will take a look into this and will let you know @hmhealey

**Comment by Aryakoste** [comment]
@hmhealey So i took a look into this. Firstly i would need to revert whole code that i did. Then in the textbox/AdvancedCreatePost component i would need to add keydownhandler for pagedown/up key. I will take this event in parent component/channel_view component. Then i could pass props upto post_list to find the focusable element or what i could do is create a function which would go child to child until it finds an element with overflow. In this case the element is inside dynamic_virtualized_list (post_list__dyanamic) so i think we would need to do that. Then focus on it and scroll. But i wanted to ask that normally too the scroll doesnt work in firefox even when i am focused on post_list.

**Comment by Aryakoste** [comment]
what do you think @hmhealey

**Comment by hmhealey** [comment]
Yeah, that sounds like it would work, but I have a couple thoughts about the specific details

> @hmhealey So i took a look into this. Firstly i would need to revert whole code that i did. Then in the textbox/AdvancedCreatePost component i would need to add keydownhandler for pagedown/up key.

I think the best place for that would be in the `AdvancedTextEditor`'s `useKeyHandler` hook. That takes a `location` prop which will tell you if the textbox is in the centre channel or RHS.

> I will take this event in parent component/channel_view component. Then i could pass props upto post_list to find the focusable element or what i could do is create a function which would go child to child until it finds an element with overflow. In this case the element is inside dynamic_virtualized_list (post_list__dyanamic) so i think we would need to do that.

If that ends up being to difficult to get working, I think it'd also be fine to have the `PostListVirtualized` pass a hardcoded ID into the list so that the `useKeyHandler` could just call something like `document.getElementById('someid').focus()` when `location` is in the centre channel. It's a bit of a boring solution, but I think that could be easier than finding the right element programatically

**Comment by Aryakoste** [comment]
Thanks. Will make this change.

**Comment by Aryakoste** [comment]
i was resetting all commits PR got closed @hmhealey

**Pull request closed without merging**
