### PR TITLE
[MM-52445] Fix double url encoding of oauth redirect URI params

### PR DESCRIPTION
**Pull request by m1lt0n**
#### Summary

The fix introduced as part of https://mattermost.atlassian.net/browse/MM-46216 URL encodes code and state parameters of the oauth2 callback url twice ( relevant PR: https://github.com/mattermost/mattermost-server/pull/20854 ) , leading to issues with some third-party apps where state is a URI with query parameters (which is not uncommon).

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-52445

#### Release Note

```release-note
Fix double url encoding of oauth redirect URI params
```

### CODE REVIEW

**Comment by trilopin** [comment]
Thanks for the test 🎉

**Review by mickmister — APPROVED** [review]

**Comment by m1lt0n** [comment]
cc: @DHaussermann

**Comment by hanzei** [comment]
@DHaussermann Heads up that the PR is ready for review

**Comment by hanzei** [comment]
@DHaussermann Heads up that the PR is ready for your review. Please let me know if you need assistance with testing it.

**Comment by mickmister** [comment]
@hanzei @DHaussermann I'm wondering about the current relevance of this PR. If this is particularly urgent, maybe we can seek help from the QA team on reviewing this

**Comment by hanzei** [comment]
The PR is still valid, even though I'm unsure about the priority.

**Comment by DHaussermann** [comment]
This task would take a fair amount of effort to test. After previous discussions with @wiersgallak I believe the decision was to nor support this case where Mattermost is the oAuth authority. 

At this point, aside from the setup time I would need to spend, there are a couple other concerns.   
1. Moving ahead with this could put us in a position where we need to continue supporting this in the future and spend additional bandwidth on maintenance 
2. There is a risk here that the way the encoding is currently function is "working as expected" for a different customer so, there could be risk in making a change.

Do we need to revisit if more than the 1 know customer is impacted by this? 
Should we close this PR? And if so, can we officially deprecate this use case and inform the customer who is waiting on it?

**Comment by DHaussermann** [comment]
@ewwollesen I have some time this week to try and validate this PR. I have Moodle running in Docker and can try to configure Mattermost as an oAuth service provider. I'm curious if you've ever attempted to set this up.

To my understanding - I'm configuring Moddle to use Mattermost as the provider which will issue a token back when a request is sent from Moodle. Does this sound correct?

There is some useful documentation from Moodle here which is helping
https://docs.moodle.org/403/en/OAuth_2_services
https://docs.moodle.org/403/en/OAuth_2_authentication

I have a couple points of confusion.
1. Where in Mattermost would I configure the callback URL?

image

3. Would I need to Obtain a client name and client secret from Mattermost somehow

image

cc @Willyfrog also curious if there is a dev familiar with this that may also be able to help as a technical resource.

**Comment by ewwollesen** [comment]
@DHaussermann I'll paste some screenshots below, but you set up the OAuth app from the Integrations menu. You also need to ensure that `ServiceSettings.EnableOAuthServiceProvider` is set to `true`.

But just go to the Integrations menu:
Screenshot 2023-11-08 at 12 57 46 PM

And then select OAuth 2.0 Applications
Screenshot 2023-11-08 at 1 00 55 PM

From there you can set up the app and get the secret, setup the callback URLs etc.
Screenshot 2023-11-08 at 1 01 34 PM

Let me know if you have any more questions though, I'm more than happy to help.

**Comment by DHaussermann** [comment]
Thanks @ewwollesen! For some reason I didn't think just creation an oAuth2 app there would work for what I need but, it makes sense that it does. 👍 

I have now created the oAuth2 App in Mattermost as you have demonstrated above. But, I do have another question if you can help... Does the oAuth2 app created in Mattermost expose an end point that should be reachable by Moodle? This does not seem to be working. 
image

note: To reduce potential connectivity issues, I have both apps exposed with their own ngrok tunnels. 
It seems like Moodle will just let me point to an end point in the config but I don't know what it would be on the Mattermost side.     
 
image

**Comment by DHaussermann** [comment]
I have a working test environment now!
After much help from Wayne yesterday, I got oAuth running on Moodle such that it would attempt to use Mattermost as the provider.
After deploying the PR the error was replaced by a new error regarding user info being returned from Mattermost.
After adding email and username fields to user field mappings on the Moodle side I see this working and users can login to Moodle successfully. 

Tested and passed
- Existing Moodle users that are created as oAuth users can login using Mattermost
- User that only exist in Mattermost can login and be created in Moodle where they are directed to the profile page to populate their fist name and last name.
- if the user is deactivated in Mattermost and tries to login to Moodle, the login flow stops on the Mattermost login page as expected. 

In terms of regression risk I can't think of anything regarding using Mattermost as a provider. Once we have this packaged in an RC, as a precaution, I would ensure there are no issues with regular release testing where Mattermost login still works in the case where another provider is used such as Google oAuth to login to Mattermost.

LGTM!
 
Huge thanks to @ewwollesen on this for all the help with Moodle oAuth setup 🎉

**Review by DHaussermann — APPROVED** [review]
Tested and passed based on testing above 👆

**Comment by cpatulea** [comment]
We hit this as well, we built an integration with Mattermost OAuth service provider (https://github.com/FOULAB/matterid) and this stopped working due to the double-escaping (our OAuth app needs the `state` parameter and the value is now invalid due to the double-escaping).

It was working with version 6.5.2, we upgraded to 8.1.7, and it stopped working. We would like to stay on the 8.1 series because it's an Extended Support Release. Are there any plans to backport the fix to the 8.1 series?

**Comment by hanzei** [comment]
@amyblais A community member is asking to cherry-pick this change into 8.1. Given that this PR fixes a regression I'm in favour of that. What do you think?

**Comment by amyblais** [comment]
@hanzei A kind note that this needs a manual cherry-pick to ``release-8.1`` branch. cc @mickmister

**Comment by mickmister** [comment]
Thanks @amyblais, I'll take of this today

**Comment by mickmister** [comment]
@amyblais It seems the automated cherry-pick failed for a reason unrelated to git merge conflicts (also, locally I see no conflicts when running `git cherry-pick`). Giving it another try here

**Pull request merged**
