### PR TITLE
Admin console definition to typescript

### PR DESCRIPTION
**Pull request by jespino**
#### Summary

This is exactly the same PR than #24870 but I recreating it to fix the Spinwicks in order to get it through QA.

As part of the effort of migrating to Typescript, this was one of the stoppers
because migrating such a big file can be painful. I wrote the original version,
so I had good understanding of the reasons behind the current implementation,
so I was in good position to migrate it.

I migrated it with very small change in the approach about subsections, using a
specific field for that (making the typing better).

Reopened from #24658 to get through QA (was accidentally merged without QA and we reverted it)

#### Ticket Link
[MM-54855](https://mattermost.atlassian.net/browse/MM-54855)

#### Release Note
```release-note
NONE
```

[MM-54855]: https://mattermost.atlassian.net/browse/MM-54855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jespino** [comment]
@larkox @hmhealey @M-ZubairAhmed This PR is exactly the same that you already reviewed, I'm recreating it to fix the problem with the Spinwicks to get this properly through QA

**Review by larkox — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Hi @jespino - looks good to me 👍 

I confirm that the issue I reported in the [closed PR](https://github.com/mattermost/mattermost/pull/24870) where syscons > environment > web server was giving a blank page is fixed.  No other issues found during the smoke test of the system console.

**Review by M-ZubairAhmed — APPROVED** [review]
I think we already have two dev reviews, do you want another one @jespino

**Comment by jespino** [comment]
@M-ZubairAhmed not needed, I just wanted to included everybody involved before, but I going to proceed with the merge

**Pull request merged**
