### PR TITLE
Remove some usage of changeCss and some unused CSS

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
I took some time today to remove some stuff from `applyTheme`. I inlined some of the rules, removed some rules that were overwritten by the CSS, and removed a bunch of CSS I found that wasn't used. Some of the CSS rules apply to Bootstrap or React Bootstrap classes, so I tried my best to double check that "unused" CSS didn't apply to those.

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by hmhealey** [comment]
For testing this, feel free to skim since there's a lot of different things here. I did it line-by-line, so I hope each change is straightforward on its own, and I'm hoping any theming issues are easily visible with a smoketest🤞

@asaadmahmood Could you check over the CSS that I removed to double check if it might apply to something I missed? You don't need to review the rest of it unless you want to

**Review by M-ZubairAhmed — APPROVED** [review]
good cleanup

**Review by asaadmahmood — APPROVED** [review]
Nothing seems to be standing out too much, but any particular reason we're removing global classes like `shadow--2`. Wouldn't it be easier to apply them even if they were defined globally somewhere in a css file? So that we can call them whenever we want and control them from one place.

**Review by larkox — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
