### PR TITLE
Fixed errcheck issues in server/channels/app/notification_test.go

### PR DESCRIPTION
**Pull request by Aryakoste**
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/29033
Jira https://mattermost.atlassian.net/browse/MM-61445
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Great work :rocket:

**Review by streamer45 — APPROVED** [review]
Looks good!

**Comment by hanzei** [comment]
@Aryakoste can you please fix the merge conflict?

**Comment by Aryakoste** [comment]
@hanzei Done

**Pull request merged**
