### PR TITLE
MM-46697 Fix out of office alignment on user menu and update confirmation modal button text

### PR DESCRIPTION
**Pull request by matthewbirtch**
#### Summary
Adds an icon to the out of office status in the user menu to improve alignment and consistency. Also adds a checkmark to this menu item when its active.

In addition, this PR also updates the button labels for the status change confirmation modal to make them more succinct.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/21398
Jira https://mattermost.atlassian.net/browse/MM-46697

#### Screenshots
|  before  |  after  |
|----|----|
| image | image |
| image | image |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by calebroseland — APPROVED** [review]

**Review by cwarnermm — APPROVED** [review]
Recommendation: Match button text case to UI, where "Out of office" and "Do not disturb" become sentence case via button text.

**Review by enahum — APPROVED** [review]

**Comment by matthewbirtch** [comment]
> Recommendation: Match button text case to UI, where "Out of office" and "Do not disturb" become sentence case via button text.

Thanks @cwarnermm. I've updated the casing now in a number of places.

**Comment by lindy65** [comment]
@matthewbirtch - should clicking on "Out of Office" in the profile icon menu open up the `Your status is set to "Out of office"` modal?  It doesn't for me...

image

**Comment by matthewbirtch** [comment]
> @matthewbirtch - should clicking on "Out of Office" in the profile icon menu open up the `Your status is set to "Out of office"` modal? It doesn't for me...
> 
> image

@lindy65 I think that's a good idea, but it currently doesn't do anything. I'm inclined to leave it as is in this PR and create a separate ticket to address that. You ok with that approach?

**Review by lindy65 — APPROVED** [review]
Yep @matthewbirtch - I'm fine with that approach. I asked because the Figma design mentioned the modal should open when clicking on Out of Office.  Otherwise all looks good to me 👍

**Comment by matthewbirtch** [comment]
@lindy65 you're right - I somehow forgot about that. If I can figure this out easily enough I'll try to incorporate in to this PR. If not, I may need help from a dev.

**Comment by matthewbirtch** [comment]
@lindy65 @enahum @calebroseland I added an action to the OOO menu item now that triggers the confirmation modal to switch status to online. Another quick review would be good.

**Review by enahum — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Retested including clicking on "Out of office" in Profile icon menu and it all looks good @matthewbirtch 👍

**Review by calebroseland — APPROVED** [review]

**Comment by matthewbirtch** [comment]
Thanks for the reviews @calebroseland @lindy65 @enahum. When one of you has a chance, please hit the merge button for me.

**Pull request merged**
