### PR TITLE
[MM-55100] Replace usage of LocalizedIcon in 'create_user_groups_modal/create_user_groups_modal.tsx' with i/span tags

### PR DESCRIPTION
**Pull request by Vinecreeper888**
Removed LocalizedIcon in create_user_groups_modal.tsx
Replaced it with i tag and used injectIntl hook of react-intl for the aria label in create_user_groups_modal.tsx as it is a class component
Resolves https://github.com/mattermost/mattermost/issues/25110
Ticket Link
Github : https://github.com/mattermost/mattermost/issues/25110

Screenshots
BEFORE
old_1

old_2

AFTER
new_1

new_2

new_3

```release-note
NONE
```

### CODE REVIEW

**Comment by marianunez** [comment]
@Vinecreeper888 There are some lint issues that need to be fixed and then I can create a test server to add the license. Let me know when you push those changes and I can run the pipeline again

**Comment by marianunez** [comment]
@Vinecreeper888 thanks for the lint fixes! I ran the pipeline again and there is still some type issues that need to be fixed

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
let me know if you have questions

**Comment by M-ZubairAhmed** [comment]
@Vinecreeper888 gentle ping on this one

**Comment by Vinecreeper888** [comment]
@M-ZubairAhmed, please let me know if there are any other modifications to be done to the test cases. I used channel.filter.test.tsx as a reference.

**Comment by Vinecreeper888** [comment]
@marianunez can you run the pipeline and let me know if there are any visible changes in the UI?

**Comment by Vinecreeper888** [comment]
@M-ZubairAhmed for the test case with name 'should match snapshot with back button', is reverting to shallow from shallowWithIntl, sufficient? If not, is it possible to get the actual screenshot? Based on the test case failure, the back button should be missing. Just want to confirm this.

Also, having a hard time understanding the other 3 failed test cases without seeing the UI. Is it possible to get any insights like why it could be deviating from the expected results?

**Comment by marianunez** [comment]
> Mattermost test server created! 🎉
> 
> Access here: https://mattermost-pr-25617.test.mattermost.cloud
> 
> Account Type	Username	Password
> Admin	sysadmin	Sys@dmin123
> User	user-1	User-1@123


@Vinecreeper888 I added a trial license to this test server. You can now find the User Groups in the main menu on the top left and then you can click on Create Group to see the modal you are changing here
Screen Shot 2023-12-12 at 6 48 13 PM

Screen Shot 2023-12-12 at 6 48 24 PM

**Review by M-ZubairAhmed — APPROVED** [review]
@Vinecreeper888 yes this looks good to me along with the snapshots. And yes shallowWithIntl is the correct replacement here as well

**Review by yasserfaraazkhan — APPROVED** [review]

**Review by larkox — APPROVED** [review]
Great work!

**Pull request merged**
