### PR TITLE
Fixes for admins when LastBoardID doesn't exist

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
When deleting a board, clear the LastBoardID, otherwise we attempt to load it and an Admin user gets into the bad loop. Also, if Joining a board fails for an admin, send to board not found error.

#### Ticket Link

  Fixes https://mattermost.atlassian.net/browse/MM-51282 

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by sbishel** [comment]
@wuwinson - Please test on the cloud server and make sure it handles the issue you were seeing.

**Comment by wuwinson** [comment]
Looks good to me @sbishel!

**Review by calebroseland — CHANGES_REQUESTED** [review]
When deleting the current board, I think we should probably clear the ID from the route/path as well—although you're not stuck in the loop anymore, on refresh it still tries to fetch the deleted board for me.

**Review by calebroseland — APPROVED** [review]

**Review by BenCookie95 — APPROVED** [review]

**Comment by lindy65** [comment]
Hi @sbishel - I'm having a problem setting up a spinwick on this PR. Can you help?

**Comment by sbishel** [comment]
@lindy65 - works now, not sure,

**Comment by lindy65** [comment]
Thanks so much @sbishel 🤗

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - this is fixed. Tested as per steps in Jira description.

**Pull request merged**
