### PR TITLE
MM-59947: Get rid of special casing of **model.User in cache

### PR DESCRIPTION
**Pull request by agnivade**
https://mattermost.atlassian.net/browse/MM-59947

```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
This inconsistency is what I was talking about. I think this should be acceptable. The only concern remains that if someone does pass a `**model.User` again in future, it will fall back to the slow path. Maybe we can set a unit test for that, but not sure how. :thinking: Ideas welcome :smile:

**Review by streamer45 — APPROVED** [review]
Looks much cleaner!

**Review by agarciamontoro — APPROVED** [review]
Neat!

**Comment by agnivade** [comment]
Actually, I'd prefer to have some QA in an HA env to absolutely confirm that there are no regressions. Often there are nasty regressions in the cache path, and I'd like to be sure.

@DHaussermann - Just some general smoke testing in an HA spinwick should be good. Thanks.

**Comment by agnivade** [comment]
Hey @DHaussermann - did you get a chance at this?

**Comment by DHaussermann** [comment]
@agnivade I'm sorry I wasn't able to get to this before PTO. I can start testing this now and take another quick look if you can bring the branch current.

**Comment by agnivade** [comment]
Yep sure

**Comment by DHaussermann** [comment]
@agnivade I'm not entirely sure what smoke testing cover the user cache but seem like it would likely be many actions?

That said, I did some smoke testing around this in HA. 
- Logged in as user and opened various channels including DM and GMs
- Invited new users and had them join
- Added removed users from various channels and teams 
No issues found. 

Please advise if there's maybe something more specific I should explore. I'll take a look as a sanity check once the branch is current.

**Comment by agnivade** [comment]
@DHaussermann - Those cases are enough. But I found another bug in this area. I am going to hold off on this PR for now.

**Comment by hanzei** [comment]
@DHaussermann removing your review per https://github.com/mattermost/mattermost/pull/27830#issuecomment-2330600906

**Comment by agnivade** [comment]
This is partially superceded by https://github.com/mattermost/mattermost/pull/28181. I will fully fix it in another PR.

**Pull request closed without merging**
