### PR TITLE
MM-53564 : Multi-line channel header preview is narrow on web

### PR DESCRIPTION
**Pull request by veronicadip**
#### Summary

Fixed the channel header preview, making sure that the text is shown at full width, with the container being as wide as the bullet points block.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/23998
https://mattermost.atlassian.net/browse/MM-53564

#### Screenshots

|  before  |  after  |
|----|----|
| 
Screen Shot 2023-07-13 at 8 04 29 PM
 | 
Screen Shot 2023-07-13 at 6 47 57 PM
 |

#### Release Note

```release-note
Changed UI, deleting the `max-width` styling that was making the channel header preview narrow.
```

### CODE REVIEW

**Review by larkox — CHANGES_REQUESTED** [review]
Thank you for your contribution! Wonder why that`max-width` was there in the first place...

**Review by yasserfaraazkhan — APPROVED** [review]

**Review by larkox — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]

**Pull request merged**
