### PR TITLE
[MM-56890] Expose allocs and mutex pprof profiling data

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
This PR exposes two pprof profiling data via 
- `allocs` contains information about past memory allocations
- `mutex` contains the trace logs of the holders of contended mutexes

Both all already listed in http://localhost:8067/debug/pprof/, so this PR ensures no link on that page errors.

The PR also adds some basic testing for the metrics router.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-56890

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM, is CI error related to this?

**Review by agarciamontoro — APPROVED** [review]
Neat! Thanks for the thorough test :tada:

**Comment by cwarnermm** [comment]
@hanzei - Are there any product or dev documentation updates needed for this PR?

**Comment by hanzei** [comment]
Good question, @cwarnermm! We indeed need to update the list of endpoints in https://docs.mattermost.com/scale/performance-monitoring.html#standard-go-metrics. Is that something could would be open to taking care of?

**Comment by cwarnermm** [comment]
@hanzei - Yes, happy to take a first run at a docs PR; I'll include you as a reviewer. Thanks!

**Comment by hanzei** [comment]
Thanks, @cwarnermm :+1:

**Pull request merged**
