### PR TITLE
[MM-52851]: Migrate "components/channel_notifications_modal/components/extra_info.test.jsx" to Typescript

### PR DESCRIPTION
**Pull request by tejaskarelia17**
#### Summary
In this PR, completes migration of `components/channel_notifications_modal/components/extra_info.test.jsx` to TypeScript.

#### Ticket Link
Fixes [GitHub issue #23409](https://github.com/mattermost/mattermost-server/issues/23409)
https://mattermost.atlassian.net/browse/MM-52851

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by M-ZubairAhmed** [comment]
@tejaskarelia17 can you update your fork from mattermost-server to `mattermost`

**Comment by M-ZubairAhmed** [comment]
@tejaskarelia17 it still shows your fork is not synced

image

**Comment by tejaskarelia17** [comment]
> @tejaskarelia17 it still shows your fork is not synced and please check the changes, it now shows 87 file changed image

Hi @M-ZubairAhmed, Sorry I did a mistake while performing the sync. It should be fixed now.

**Comment by tejaskarelia17** [comment]
Hi @M-ZubairAhmed, I think the merging is blocked due to the [Do Not Merge] and [Awaiting Submitter Action] labels on the PR.

**Pull request merged**
