### PR TITLE
[MM-54793] Convert ./components/widgets/separator/notification-separator.tsx  to Function Component

### LINKED ISSUE #24757: Convert ./components/widgets/separator/notification-separator.tsx from Class Component to Function Component
We want to move most of our codebase from Class Components to Function Components. This decision is based on [React recommendations](https://react.dev/reference/react/Component).

The task is to update the component to be a functional component, without any difference in functionality. Also, all related tests that fail may need refactoring.

Here are a few examples of the required changes:
https://github.com/mattermost/mattermost/pull/24187
https://github.com/mattermost/mattermost/pull/24210
https://github.com/mattermost/mattermost/pull/24183
https://github.com/mattermost/mattermost/pull/24181

If the tests do not work because they rely on the behavior of Class Components they also have to be migrated to functionaly test the same behavior. We prefer the use of `react-testing-library` for new tests, but it is not required.

When submitting the PR, please make sure to identify where and when the component shows, for QA to properly test the changes.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA LINK: MM-54793

### PR DESCRIPTION
**Pull request by dipandhali2021**
#### Summary
This PR converts notification separator to function component

#### Ticket Link
Fixes #24757

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by jespino — APPROVED** [review]
Nice! This looks good to me. Thank you @dipandhali2021! :tada:

My only concern is that you are doing the exact expected migration but there is a wrong typing from the original code.

`React.PropsWithChidren<any>` should be `React.PropsWithChildren<{}>` or `{children?: React.ReactNode}` But that is going to lead to the need to remove the `id={this.props.separatorId}` from the `NewMessageSeparator` component that is using the `NotificationSeparator`. And that change leads to remove the `separatorId` property from the `NewMessageSeparator` Props, and that again leads to removing the `separatorId` attribute where the `NewMessageSeparator` is used.

So... for me this PR is perfect because solves what was asked for. But if you want to go for an extra mile, feel free to do the changes proposed. If not, let me know and I can add the changes here in the PR or in another PR later.

**Comment by dipandhali2021** [comment]
> Nice! This looks good to me. Thank you @dipandhali2021! 🎉
> 
> My only concern is that you are doing the exact expected migration but there is a wrong typing from the original code.
> 
> `React.PropsWithChidren<any>` should be `React.PropsWithChildren<{}>` or `{children?: React.ReactNode}` But that is going to lead to the need to remove the `id={this.props.separatorId}` from the `NewMessageSeparator` component that is using the `NotificationSeparator`. And that change leads to remove the `separatorId` property from the `NewMessageSeparator` Props, and that again leads to removing the `separatorId` attribute where the `NewMessageSeparator` is used.
> 
> So... for me this PR is perfect because solves what was asked for. But if you want to go for an extra mile, feel free to do the changes proposed. If not, let me know and I can add the changes here in the PR or in another PR later.


Hey, @jespino .Thank you for reviewing the pull request and providing your feedback and suggestions. However, I am writing to request a bit more time to incorporate the proposed changes effectively.


Sure, I understand your request. To summarize the changes you'd like to make in the code:

1.Replace `React.PropsWithChildren<any>` with either` React.PropsWithChildren<{}> or { children?: React.ReactNode }` in notification Seperator file.

2.Remove the `id={this.props.separatorId}` prop from the `NewMessageSeparator` component that is using the `NotificationSeparator`.

3.Remove the `separatorId` property from the NewMessageSeparator component's props.

4.Update every file using `NewMessageSeparator` to remove the `separatorId` prop.

For example:
`post_list_row.tsx` is using `NewMessageSeparator` 
```tsx

        if (PostListUtils.isStartOfNewMessages(listId)) {
            return (
                <NewMessageSeparator
                    separatorId={listId}
                    newMessagesSeparatorActions={this.props.newMessagesSeparatorActions}
                    channelId={this.props.channelId}
                    lastViewedAt={this.props.lastViewedAt}
                />
            );
        }
```
I should remove `separatorId={listId}` from this code block.This change should be applied consistently across all files using the NewMessageSeparator component.

**Review by larkox — APPROVED** [review]
LGTM, great work!

**Review by lindy65 — APPROVED** [review]
Thanks @dipandhali2021 - looks good to me 👍 

cc @larkox

**Comment by larkox** [comment]
Thanks for the contribution!

**Pull request merged**
