### PR TITLE
[MM-57719] Convert `./components/form_error.tsx` from Class Component to Function Component

### PR DESCRIPTION
**Pull request by Syed-Ali-Abbas-Zaidi**
#### Summary

Convert `./components/form_error.tsx` from Class Component to Function Component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/26687
Jira https://mattermost.atlassian.net/browse/MM-57719

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]
LGTM

**Comment by harshilsharma63** [comment]
@Syed-Ali-Abbas-Zaidi can you fix the tests? I see some snapshots failing.

**Review by harshilsharma63 — APPROVED** [review]

**Comment by larkox** [comment]
@Syed-Ali-Abbas-Zaidi The tests on this are failing.

**Comment by larkox** [comment]
Closing due to lack of activity

**Pull request closed without merging**
