### PR TITLE
Fix errcheck issues in server/channels/jobs/resend_invitation_email/worker.go

### PR DESCRIPTION
**Pull request by AulakhHarsh**
#### Summary
Fix errcheck issues in server/channels/jobs/resend_invitation_email/worker.go

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/28763
Jira https://mattermost.atlassian.net/browse/MM-61090

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @AulakhHarsh!

**Comment by AulakhHarsh** [comment]
@hanzei A flaky test is failing. Can you rerun the job to fix it? Seems like I don't have the permission to rerun it.

**Comment by AulakhHarsh** [comment]
@hanzei now Postgres job is failing. Looks like a flaky test to me as the error is same to the previous one.

**Comment by hanzei** [comment]
Yeah, there is some flakiness in the tests. Will look into that separately.

**Pull request merged**
