### PR TITLE
Replace `fmt.Sprint` usages with faster alternatives such as `strconv.FormatBool`

### PR DESCRIPTION
**Pull request by catenacyber**
#### Summary

Optimizes server code by replacing `fmt.Sprint` usages with faster alternatives such as `strconv.FormatBool`
cf https://github.com/catenacyber/gostrconv

#### Ticket Link

No ticket, just optimization...

#### Screenshots

No UI changes (only server)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by agarciamontoro** [comment]
Thanks for this, @catenacyber, this is quite cool :) Before diving into the review, do you have any benchmarks we could analyze on the performance improvement of the alternatives you provide?

**Comment by catenacyber** [comment]
> Before diving into the review, do you have any benchmarks we could analyze on the performance improvement of the alternatives you provide?

Sure, you can run `make bench` in https://github.com/catenacyber/perfsprint 
There are others available cf https://dev.to/mavensingh/strconvitoa-vs-strconvformatint-vs-fmtsprintf-which-is-good-to-convert-int-to-string-in-golang-3iol

**Review by agarciamontoro — APPROVED** [review]
Just ran the benchmarks in your repo and compared them and the performance improvement looks great, thanks for this! `replacement.bench` is the proposed alternative in the PR, while `print.bench` corresponds to `fmt.Sprint` and `printf.bench` to `fmt.Sprintf`:
```
                        │ replacement.bench │               print.bench                │               printf.bench               │
                        │      sec/op       │    sec/op      vs base                   │    sec/op      vs base                   │
StringFormatting              0.2262n ±  0%   33.5100n ± 2%  +14714.32% (p=0.000 n=10)   35.7500n ± 2%  +15704.60% (p=0.000 n=10)
ErrorFormatting                1.341n ±  3%    78.600n ± 4%   +5763.48% (p=0.000 n=10)    82.540n ± 4%   +6057.40% (p=0.000 n=10)
BoolFormatting                0.2266n ±  1%   35.9300n ± 1%  +15756.13% (p=0.000 n=10)   38.1800n ± 1%  +16749.07% (p=0.000 n=10)
HexEncoding                    16.59n ±  3%    113.50n ± 4%    +584.15% (p=0.000 n=10)     94.98n ± 5%    +472.51% (p=0.000 n=10)
IntFormatting                  41.28n ±  5%     74.23n ± 8%     +79.83% (p=0.000 n=10)     75.78n ± 5%     +83.58% (p=0.000 n=10)
IntConversionFormatting        28.27n ±  8%     61.97n ± 2%    +119.19% (p=0.000 n=10)     64.43n ± 1%    +127.91% (p=0.000 n=10)
UintFormatting                 42.70n ± 27%     75.85n ± 3%     +77.61% (p=0.000 n=10)     76.19n ± 4%     +78.40% (p=0.000 n=10)
geomean                        4.778n           62.55n        +1209.33%                    63.09n        +1220.65%
```

**Review by isacikgoz — APPROVED** [review]

**Comment by agarciamontoro** [comment]
I think the changes here are small enough to defer QA until post-merge. Thoughts, @isacikgoz?

**Comment by isacikgoz** [comment]
Sounds good cc @agarciamontoro

**Comment by agarciamontoro** [comment]
Thank you for this, @catenacyber!

**Comment by catenacyber** [comment]
Glad you liked it

**Pull request merged**
