### PR TITLE
MM-51463 Only use RhsSuggestionList for RHS advanced text editor

### PR DESCRIPTION
**Pull request by thinkGeist**
#### Summary
This change addresses an issue where the LHS (Post) Advanced Text Editor suggestion box would ocassionally grow "downwards" causing the suggestion box to be hidden by the end of the document.

To address this I have adjusted the `AdvancedTextEditor` component to **only use the RhsSuggestionList component if we're on the RHS** (By checking against the `location` prop provided to the text editor)

With this change the main "post" view only ever grows upwards, while the RHS view retains the logic to conditionally grow down or up depending on available space.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/22526
Jira https://mattermost.atlassian.net/browse/MM-51463

#### Screenshots
These are taken on the smallest supported device size (320x460 - taken from [here](https://mattermost-docssandrospadaro.readthedocs.io/it/latest/developer/fx-guidelines.html#screen-and-content-dimensions))

|  before  |  after  |
|----|----|
| MM-51463_Before | MM-51463_After | 

#### Release Note
```release-note
Corrects an issue where post mentions would grow outside the viewport on small devices
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by hmhealey** [comment]
Thanks for the PR, @thinkGeist! You're right that this the centre channels and RHS versions of this used different components at some point, but it was changed in https://github.com/mattermost/mattermost-webapp/pull/11030 to be used everywhere so that the autocomplete would go downwards in the RHS and not overlap the channel header.

I'm trying to figure out why the test server is failing to generate at the moment, but I think we should confirm that the menu:
1. In mobile view, the suggestion list opens upwards in both the centre channel (which you've shown), when viewing a thread in a channel, and when viewing a thread on the Threads screen.
2. In desktop view, the suggestion list opens upwards in the centre channel.
3. In desktop view, the suggestion list opens upwards in the RHS and on the Threads screen if there's available space above. If there's not enough space above the textbox, it opens downwards.

I'll take a look myself if we can get the test server working or once I can get my development environment back to where I can run this PR locally.

**Comment by thinkGeist** [comment]
Thanks for taking a look @hmhealey, seeing as there's a conflict now I can take this back, address the conflict and verify the cases you mentioned beforehand. I'll update here once I have results.

**Comment by hmhealey** [comment]
Thanks for the super thorough testing there! Interesting that it only happens on smaller devices since that'd make it even less likely for us to have run into this before. For reference, I just found that the minimum screen size we design for on mobile is `320 x 568` (https://mattermost-docssandrospadaro.readthedocs.io/it/latest/developer/fx-guidelines.html#mobile-app).

> - More aggressive checks that force it to grow upwards on mobile (will need to determine how best to make this distinction on whether or not user is on mobile)

That'd probably be the easiest option assuming that the suggestion list doesn't get cut off too much on those smaller devices. We may even be able to make it so that the dropdown always opens upwards in mobile view. To check that, you can probably use the `getIsMobileView` selector which'll return true any time the app is in mobile view, even on a desktop browser.

> - Reduce the `Constants.SUGGESTION_LIST_SPACE_RHS` value somewhat to make sure the smallest device still behaves as expected

If the "always open upwards in mobile view" route doesn't work, we could perhaps make this more dynamic based on screen size. Maybe we could use `Constants.SUGGESTION_LIST_SPACE_RHS` or some percentage of the vertical height of the screen, whichever is lower, when checking the required vertical space? It shouldn't affect desktop or larger mobile devices, but it should help improve the behaviour on smaller screens then

**Comment by thinkGeist** [comment]
@hmhealey 

Good suggestion! I was hoping a selector or something might exist to make this easier, so thanks for the reference. I've made some adjustments to the RhsSuggestionList component to now only grow "up" on mobile, while retaining the conditional behavior based on free space for desktop. 

However I found that while working with the smallest device (320x568) that when interacting with a thread with 1 message we will still try to grow "up" which doesn't look/feel great on a mobile device (see below for example).

MM-51463_After-RHS-mobile-up-bad

I think this could be mitigated by keeping the conditional logic but making the "required space above" less on mobile so we will start growing up sooner. I found that on the smallest device size that the free space with one thread is `~209px` and as such I've added a new constant `MOBILE_SUGGESTION_LIST_SPACE_RHS = 220`.

With this change I think the behaviour on mobile is a little more natural, for a new thread we'll grow down for a bit:

MM-51463_After-RHS-mobile-down-good


Once the thread reaches enough messages we'll start to grow up:
MM-51463_After-RHS-mobile-up


The rest of the cases mentioned above in the table remain unchanged. Let me know what you think of this solution, if you're okay with the simpler solution I can also remove the "mobile" breakpoint I added and only key off the `getIsMobileView` selector

**Comment by hmhealey** [comment]
Yeah, that change in your screenshots looks great. I forgot that the RHS textbox isn't pinned to the bottom on mobile web like it is on the mobile app which is why I'd proposed having it always open upwards.

One other thing to check, does it also work when you have multiple lines of text in the textbox as well? I can't remember if the logic to have the autocomplete move with the keyboard caret ever worked on mobile view

**Comment by hmhealey** [comment]
@thinkGeist Hey, were there more changes you wanted to make on this, or is it ready for review again? No rush on this, but I want to make sure you're not stuck waiting on me for something 😛

**Comment by thinkGeist** [comment]
@hmhealey Sorry! Not waiting on you, just had my hands full the last couple weeks. Only thing outstanding was your comment here

> One other thing to check, does it also work when you have multiple lines of text in the textbox as well? I can't remember if the logic to have the autocomplete move with the keyboard caret ever worked on mobile view

I think based on what you said it _does_ work, but I'll let you be the judge - here's a clip I captured today:

https://github.com/mattermost/mattermost/assets/9254315/30c49301-c5a0-4340-a523-036128a01387

**Comment by hmhealey** [comment]
No worries at all! I just wanted to check in in case I forgot something or there was something we could help with.

That looks like it's probably okay. I'd just confirm that the autocomplete appears further up in the textbox if the cursor isn't at the end of the text since the autocomplete follows the cursor

**Comment by thinkGeist** [comment]
I get what you mean, I think that works as expected too. Here's that behavior:



https://github.com/mattermost/mattermost/assets/9254315/1ae70919-fb34-44c9-9d35-f1e165629ff3

**Comment by hmhealey** [comment]
Cool, that looks perfect

**Comment by thinkGeist** [comment]
Sorry for the delay on getting this branch back up to date, 

I have addressed the conflicts that were present on this branch, and confirmed that the fix presented beforehand is still working as expected.

**Review by hmhealey — APPROVED** [review]
Thanks for updating that! I always appreciate when people keep an older branch up to date since it's easy to lose motivation when a PR requires back and forth, especially if you're busy with other things.

I did a retest to remind myself that everything was working, but still looks good to me!

**Review by yasserfaraazkhan — APPROVED** [review]
image

image

**Comment by hmhealey** [comment]
Thanks again for the PR, @thinkGeist!

**Pull request merged**
