### PR TITLE
[MM-55307] Make AdminConsole/TeamFilterDropdown use AsyncSelect instead of LegacyInfiniteScroll

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
This pr replaces the InfiniteScroll in team filter dropdown as seen below with a async react select component. The components supports infinite loading when the user scrolls to the bottom of the dropdown. This component is used in admin console at "user management/channels" and "data retentions policies/add new policy/assigned channels" team filter.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-55307

#### Screenshots

|  before  |  after  |
|----|----|
| image | image |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@abhijit-singh the deploy preview is now up

**Review by abhijit-singh — APPROVED** [review]
Thanks @M-ZubairAhmed, looks good!

**Review by fmartingr — APPROVED** [review]
More lines deleted than added, same functionality. <3 Thank you!

**Review by yasserfaraazkhan — CHANGES_REQUESTED** [review]
@M-ZubairAhmed 
I check the changes, the searching channel name is a bit different.
- when I search for team that doesnt exist, it shows 'No teams found' as expected. but when i search again with same string it doesn't show the matching suggestion. We have to reload the screen
- When use searched for a channel that doesnt exist and then deletes few characters the UI doesnt show matching suggestion 

https://github.com/mattermost/mattermost/assets/15979783/274cc9be-372d-4d57-a339-e450a9ac1e88


image

image

https://github.com/mattermost/mattermost/assets/15979783/1509474a-ab0e-4b69-88f2-c05c43ae8999

**Review by hmhealey — APPROVED** [review]
Looks good pending any major changes based on Yasser's feedback! Always nice to remove a component that's specific to just one area in favour of a more generic one, especially because the generic one looks nicer from what I can see

**Review by yasserfaraazkhan — APPROVED** [review]
thank you @M-ZubairAhmed works as expected after the fixes

**Pull request merged**
