### PR TITLE
[GH-21566] Add request context and logger to all public methods in server/channels/app/authentication.go

### PR DESCRIPTION
**Pull request by Kimbohlovette**
**Summary**
Added request context `rctx request.CTX` to all public methods in server/channels/app/authentication.go file.
Updated all the parameter list of these methods where there are called
Regenerated the AppIface interface.
```release-note
NONE
```

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM :+1: 

Thanks for the contribution @Kimbohlovette

**Review by fmartingr — APPROVED** [review]
Looking good :)

Thanks for your contribution @Kimbohlovette !

**Comment by Kimbohlovette** [comment]
> LGTM 👍
> 
> Thanks for the contribution @Kimbohlovette

Many thanks @hanzei

**Comment by Kimbohlovette** [comment]
> Looking good :)
> 
> Thanks for your contribution @Kimbohlovette !

Many thanks to you 😊

**Comment by hanzei** [comment]
We need some accompanying changes in the closed-source enterprise code. I've submitted them via https://github.com/mattermost/enterprise/pull/1585. The PRs will be merged together.

**Comment by Kimbohlovette** [comment]
> We need some accompanying changes in the closed-source enterprise code. I've submitted them via https://github.com/mattermost/enterprise/pull/1585. 
The PRs will be merged together.
Hello @hanz
Understood! Can I go ahead and pick another ticket?

**Comment by hanzei** [comment]
Sure, please do so and let me know in that issue @Kimbohlovette :+1:

**Comment by Kimbohlovette** [comment]
> Sure, please do so and let me know in that issue @Kimbohlovette 👍

Okay I'll

**Pull request merged**
