### PR TITLE
MM-53609 - remove channels from archived teams during search

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
This PR adds the logic to filter channels belonging to a archived teams from the list shown during the channels search using the cmd/ctrl + K command.

*Missing unit test, I want to receive early feedback before moving forward.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-53609

#### Screenshots
Before:

https://github.com/mattermost/mattermost/assets/10082627/dca1d8d2-6e52-4dbe-affd-aa5000ead3b6

After:

https://github.com/mattermost/mattermost/assets/10082627/9aeac901-50ab-4ea5-ab33-f9bf27c014ec

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
Functionality wise it looks good. But i am not sure if we were to always exclude the archived channels from recent viewed channels in channel search from product point of view. For that I will defer to

Also can you write some e2e as well :)

**Comment by pvev** [comment]
> Functionality wise it looks good. But i am not sure if we were to always exclude the archived channels from recent viewed channels in channel search from product point of view. For that I will defer to @johndavidlugtu
> 
hey @M-ZubairAhmed thanks for the review. So, the problem here reported by the customer is that what is being shown are channels from an archived team, that once you find them in the channels search list and try to click them, it will redirect you to the not found channel screen.
cc: @johndavidlugtu

**Comment by M-ZubairAhmed** [comment]
> > Functionality wise it looks good. But i am not sure if we were to always exclude the archived channels from recent viewed channels in channel search from product point of view. For that I will defer to @johndavidlugtu
> 
> hey @M-ZubairAhmed thanks for the review. So, the problem here reported by the customer is that what is being shown are channels from an archived team, that once you find them in the channels search list and try to click them, it will redirect you to the Team not found screen. cc: @johndavidlugtu
> 
>  Screen.Recording.2023-07-20.at.11.00.51.mov

Thank you for your explanation. it makes perfect sense

**Comment by johndavidlugtu** [comment]
> Mattermost test server created! 🎉
> 
> Access here: https://mattermost-pr-24053.test.mattermost.cloud
> 
> Account Type	Username	Password
> Admin	sysadmin	Sys@dmin123
> User	user-1	User-1@123

Tried using the test server here and it looks like the the archived channel due to archived team is still accessible. I take the test server isn't updated? @pvev 
Screenshot 2023-07-20 at 2 08 39 PM

**Comment by larkox** [comment]
@pvev Is this something that is also happening on mobile?

**Comment by pvev** [comment]
> @pvev Is this something that is also happening on mobile?

let me verify it @larkox

**Comment by pvev** [comment]
> > @pvev Is this something that is also happening on mobile?
> 
> let me verify it @larkox

@larkox yes it is happening, and it is also allowing to join to the channel from an archived team.
See attached video how the webapp (with the fix applied in this PR) do not show the "archived" channel and the mobile do.

https://github.com/mattermost/mattermost/assets/10082627/f0c1210e-682d-420f-8a6f-7e356e726ab2

**Review by BenCookie95 — APPROVED** [review]
Is there a reason we don't archive the channels when we archive a team? Seems like something we should do

**Comment by pvev** [comment]
> @pvev I see two issues on what you showed regarding mobile.
> 
> 1. The client should not show the channels of a archived team, and much less being able to navigate to those channels.
> 2. The server shouldn't allow at an API level join a channel on an archived team, right? I am not sure if there is any reason to keep that logic that way, but seems wrong.
> 
> With all that being said, up to you whether to create new tickets to deal at least with the mobile situation.

yeah, 100% agree with the two mobile issues. I will create a new ticket to handle this for mobile.

**Comment by pvev** [comment]
> > @pvev I see two issues on what you showed regarding mobile.
> > 
> > 1. The client should not show the channels of a archived team, and much less being able to navigate to those channels.
> > 2. The server shouldn't allow at an API level join a channel on an archived team, right? I am not sure if there is any reason to keep that logic that way, but seems wrong.
> > 
> > With all that being said, up to you whether to create new tickets to deal at least with the mobile situation.
> 
> yeah, 100% agree with the two mobile issues. I will create a new ticket to handle this for mobile.

https://mattermost.atlassian.net/browse/MM-53849

**Comment by pvev** [comment]
@johndavidlugtu could you please validate that this PR implements the expected behavior? Thanks!

**Comment by pvev** [comment]
> Is there a reason we don't archive the channels when we archive a team? Seems like something we should do

Thanks for the comment Ben. Not sure if there is an specific reason for it, but will investigate about it.

**Comment by larkox** [comment]
> > Is there a reason we don't archive the channels when we archive a team? Seems like something we should do
> 
> Thanks for the comment Ben. Not sure if there is an specific reason for it, but will investigate about it.

If you archive the channels when you archive the team, the moment you unarchive the team, you cannot get back the previous state. You would have a team with all its channels archived. I think the main purpose is that whenever you unarchive a team, you get to the previous state.

Similar happens when leaving a team. When a user leaves the team, the user don't leave all channels (if I remember correctly). It just leaves the team. That way, when the user rejoins, the channels they used to be on will be still there.

**Comment by pvev** [comment]
> > > Is there a reason we don't archive the channels when we archive a team? Seems like something we should do
> > 
> > 
> > Thanks for the comment Ben. Not sure if there is an specific reason for it, but will investigate about it.
> 
> If you archive the channels when you archive the team, the moment you unarchive the team, you cannot get back the previous state. You would have a team with all its channels archived. I think the main purpose is that whenever you unarchive a team, you get to the previous state.
> 
> Similar happens when leaving a team. When a user leaves the team, the user don't leave all channels (if I remember correctly). It just leaves the team. That way, when the user rejoins, the channels they used to be on will be still there.

that makes perfect sense, thanks @larkox for the answer. cc: @BenCookie95 👍

**Comment by pvev** [comment]
@johndavidlugtu friendly reminder on validating the behavior implemented in this PR. Thanks!

**Comment by johndavidlugtu** [comment]
@pvev thanks for pinging! I previously had issues with the test server, but seems to be okay now.

> I think the main purpose is that whenever you unarchive a team, you get to the previous state.

This is correct.

> Similar happens when leaving a team. When a user leaves the team, the user don't leave all channels (if I remember correctly). It just leaves the team. That way, when the user rejoins, the channels they used to be on will be still there.

For this one, I'm not sure this is what happens, but would like to get confirmation/correction on this one. There's a similar [customer feature request](https://docs.google.com/document/d/14LQMyJavUDE3J4fmSTYi6wazficQ2qoA9g4oWZSURsg/edit) that might be related to this

**Review by johndavidlugtu — APPROVED** [review]

**Comment by pvev** [comment]
Merging it now to move forward the solution to the customer. Pending E2E tests for this functionality. Ticket for tracking the effort of adding the e2e https://mattermost.atlassian.net/browse/MM-53867 .

**Comment by pvev** [comment]
@yasserfaraazkhan could you please help with a post merge review? you can find the  QA steps in the ticket. Thanks!

**Pull request merged**
