### PR TITLE
[MM-53699] : Remove channel header limit message when user adjusts to valid length

### PR DESCRIPTION
**Pull request by aqurilla**
#### Summary

This updates `EditChannelHeaderModal` to show the header limit message when the header exceeds the configured limit. The message is removed when the user adjusts the header to within the acceptable length.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/24108
Jira https://mattermost.atlassian.net/browse/MM-53699

#### Screenshots

demo

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Thanks for the PR, @aqurilla, and sorry that got a bit lost since you submitted it. This looks good to me though assuming CI passes

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by hmhealey** [comment]
Thanks again for the PR, @aqurilla!

**Comment by aqurilla** [comment]
@hmhealey thankyou!

**Pull request merged**
