### PR TITLE
MM-56273 - Update prepackaged calls to v0.22.2

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Prepackage Calls v0.22.2

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-56273

#### Release Note

```release-note
Prepackage Calls version v0.22.2
```

### CODE REVIEW

**Comment by cpoile** [comment]
I'll manually test

**Comment by cpoile** [comment]
Tested and new version is installed and working, good to go.

**Review by amyblais — APPROVED** [review]

**Review by streamer45 — APPROVED** [review]

**Comment by cpoile** [comment]
@amyblais This includes the bug fixes Claudio mentioned and should go into 9.4

**Comment by cpoile** [comment]
Adding the tags myself since I didn't realize Amy was away and she pre-approved in chat last week.

**Pull request merged**
