### PR TITLE
MM-53088 - remove auto-show linked board

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
This PR removes the AB test for the auto-show linked board, feature added by https://github.com/mattermost/mattermost/pull/22201

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-53088

#### Screenshots
n/a

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by marianunez — APPROVED** [review]
Thanks @pvev!

**Review by yasserfaraazkhan — APPROVED** [review]
HI @pvev ,
I checked creating teams and channels that there's no board attached to it.

Screenshot 2023-06-20 at 5 13 49 PM


can you confirm if the e2e tests are not caused by this change ? (I'll merge master and re-trigger it one )

 Screenshot 2023-06-20 at 5 10 20 PM

**Review by JulienTant — APPROVED** [review]
Thanks Pablo!

**Pull request merged**
