### PR TITLE
MM51728-prevent menu click to bubble to channel anchor and exec default click behavior.

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
There was an issue when clicking any of the items in the sidebar menu for the channel items list, instead of doing what was expected it was redirecting to the channel. The root cause seems to be a default behavior existing in MUI modal where it creates or attaches the modal to the body but somehow keeps the reference of the place where the menu was created and sends the syntetic event that way making it imposible to prevent the default or stop the propagation since it would occur after the first click loop cycle. To prevent that to happen  the click behavior of the menu is the one that needs to have the event bubbling and the default behavior prevented.

Root cause: https://github.com/mui/material-ui/issues/32064

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51728

#### Screenshots
 Before:
 

https://github.com/mattermost/mattermost/assets/10082627/a9eaa06a-9724-48d8-a6d4-e793cf0d1a43

 
 After:
 

https://github.com/mattermost/mattermost/assets/10082627/a2cc7770-04b2-437f-90c4-b4aa3a373919

 

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@pvev thank you for deep diving this in detail and mentioning the mui ticket as well. Please don't mind I will merge this in my PR, as I am changing few things there which could cause conflicts. :)

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by pvev** [comment]
> @pvev thank you for deep diving this in detail and mentioning the mui ticket as well. Please don't mind I will merge this in my PR, as I am changing few things there which could cause conflicts. :) And we can do complete QA for all of it in single PR

ok, perfect @M-ZubairAhmed thanks for merging, I'm glad that these changes help in the general purpose. I am surprised how this could happen and didn't get catch by the tests. I guess e2e tests will be better to cover these scenarios.

**Pull request merged**
