### PR TITLE
MM-52476 Fix guest users access to playbooks.

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary
Fix guest users access to playbooks.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-52476

#### Release Note

```release-note
NONE

```

### CODE REVIEW

**Review by sbishel — APPROVED** [review]

**Review by calebroseland — APPROVED** [review]

**Comment by esarafianou** [comment]
@crspeller when locally testing it, playbooks look broken (it was ok in master), so I can't test it. One thing I'm not sure is if the PR also includes restricting a guest from the PermissionPublicPlaybookManageProperties which is needed both for deleting/archiving a playbook and for updating it.

**Comment by esarafianou** [comment]
It seems like listing the playbooks is still available for guests. 

https://github.com/mattermost/mattermost-server/assets/17114347/ea7e3402-5f5f-4911-b066-4183341ec098

**Comment by crspeller** [comment]
@esarafianou Should be good to go now.

**Review by esarafianou — APPROVED** [review]
LGTM!

**Review by lindalumitchell — APPROVED** [review]
Second test server creation picked up the correct version, and I verified guest user cannot view or interact with or import playbooks. e2es had a couple unrelated failures only. LGTM!

**Pull request merged**
