### PR TITLE
Mm 16623 fix all initialism errors in channels/app and channels/api4 and  /store dir

### PR DESCRIPTION
**Pull request by TealWater**
#### Summary

Fixed all initialism errors in 14 files in accordance with the golang style doc found [here](https://github.com/golang/go/wiki/CodeReviewComments#initialisms).

List of warnings fixed:

variable naming conventions --> abbreviations like ID need to be capitalized

```
var-naming: var user_ID should be useID (revive)
var-naming: var teanId should be teamID (revive)
```
#### Ticket Link

Fix for: https://github.com/mattermost/mattermost/issues/16623

#### Release Note

```release-note
none
```

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Another one :tada: :rocket:

**Review by isacikgoz — APPROVED** [review]
LGTM, sorry for the late review it was due to holidays. Thanks!

**Comment by hanzei** [comment]
Thanks for the contribution @TealWater :tada:

**Pull request merged**
