### PR TITLE
Weblate 20230912

### PR DESCRIPTION
**Pull request by Willyfrog**
Fixing weblate status
```release-note
NONE
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@Willyfrog sorry i dont have context on this but why did we had to do this manually?

**Comment by Willyfrog** [comment]
> @Willyfrog sorry i dont have context on this but why did we had to do this manually?

weblate sometimes doesn't catch up with master and needs a bit of help figuring out where each part goes.

**Review by hmhealey — APPROVED** [review]

**Comment by cwarnermm** [comment]
@Willyfrog - What's the next step to getting this PR merged into the codebase? I see a few checks haven't passed yet. CC @ctlaltdieliet

**Comment by Willyfrog** [comment]
let's tryto update again, if not, we'll need help from the team as these changes shouldn't affect.

**Comment by hmhealey** [comment]
@Willyfrog Is this PR still relevant, or should it be closed?

**Comment by ctlaltdieliet** [comment]
I think it can be closed as we did a hard reset on Weblate after integrating the WIP languages

**Pull request closed without merging**
