### PR TITLE
[MM-59333] Migrate tooltips of "components/sidebar/mobile_sidebar_header/contents/contents.tsx" to WithTooltip

### PR DESCRIPTION
**Pull request by shaon72**
#### Summary

Replaces OverlayTrigger and Tooltip, with WithTooltip in the sidebar component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27559
Jira https://mattermost.atlassian.net/browse/MM-59333

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
Can you please the failing CI, you might have to update some jest snapshots

**Comment by M-ZubairAhmed** [comment]
@shaon72 any update on this one

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
