### PR TITLE
[MM-52836] : Migrate "components/admin_console/admin_definition_constants.jsx" to TypeScript

### PR DESCRIPTION
**Pull request by tejaskarelia17**
#### Summary
In this PR, completes migration of `components/admin_console/admin_definition_constants.jsx` to TypeScript.

#### Ticket Link
Fixes [GitHub issue #23424](https://github.com/mattermost/mattermost-server/issues/23424)
https://mattermost.atlassian.net/browse/MM-52836

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by yasserfaraazkhan** [comment]
@M-ZubairAhmed the e2e test have been blocked due to some infra challenges. no ETA on when it'll be fixed.

this is just a file name change, if you feel okay we can merge this one.

**Comment by M-ZubairAhmed** [comment]
Thank you @saturninoabril for rerunning the e2e with fixed CI. @yasserfaraazkhan yes for this PR it can certainly be skipped. However, I am seeing 2 failed test are those flaky as well?

**Comment by yasserfaraazkhan** [comment]
@M-ZubairAhmed from the previous runs of those tests, these seem flaky.

**Comment by M-ZubairAhmed** [comment]
> @M-ZubairAhmed from the previous runs of those tests, these seem flaky.

Thank you @yasserfaraazkhan can you please give a thumbs up for this PR then

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
