### PR TITLE
Various improvements to preferences code

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
These are a bunch of misc improvements I made a while back and never got around to submitting. They are:

1. https://github.com/mattermost/mattermost/commit/01ade8da0cff275c0c4c5429bef889469ce81dda - Adds a `isPostFlagged` selector to simplify how those preferences are used a bit.
2. https://github.com/mattermost/mattermost/commit/c3bec0cb435b128f0e587923b2259981486cd492 - Removes some now-unused code for tutorials that seem to have previously been removed.
3. https://github.com/mattermost/mattermost/commit/2008effd3343028e7e401e637f080fe1c6f42c60 - Fix the types so that the `get` selector always returns a string to clean up some typing.
4. https://github.com/mattermost/mattermost/commit/11a8248e7005d115c0bb73b5f4497ef90c9efacf - (MM-58111) This one actually should improve some stuff. It makes it so that we don't use `makeGetCategory` in places we only need a single preference, and it makes it so that we reuse instances of `getCategory` anywhere that we select a category of preferences multiple times. Both of those make it so that it's easier to correctly use those selectors without having to figure out how to use them correctly with `useMemo`.
5. https://github.com/mattermost/mattermost/commit/7dc4fa8c9071b6c408b5fee4b0dd102573d656b1 - This should also have some performance improvements since it fixes all the places where heavy selectors like `getMostRecentPostIdInChannel` and `makeGetPostsAroundPost` or frequently used ones like `getTeammateNameDisplaySetting` would recalculate any time any preferences changed. It does that by only passing a single preference into the selector where we previously passed all selectors.
6. https://github.com/mattermost/mattermost/commit/1db43954c90425f90afc2c81e84732677c639fb9 - This changes `makeGetCategory` from using the basic `createSelector` to `createIdsSelector` which has some extra memoization that checks if a new result is shallowly equal to the previous one

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-58111

#### Release Note
```release-note
Made various improvements to code involving user preferences
```

### CODE REVIEW

**Review by harshilsharma63 — APPROVED** [review]

**Comment by harshilsharma63** [comment]
Note to QA - because this deals with preferences code, please test and verify that the feature where admin can modify someone else's settings also works fine.

**Review by BenCookie95 — APPROVED** [review]
LGTM!

**Comment by hmhealey** [comment]
@yasserfaraazkhan This covers some random areas, but I'd expect E2E tests to cover most of that. Like Harshil mentioned though, it's definitely a good idea to ensure that this doesn't immediately break the newly added ability for admins to modify other users' settings though

**Review by yasserfaraazkhan — APPROVED** [review]
executed this to verify messaging, desktop notifications, convertion to private channel, manage user's settings, file attachments. [Test cycle](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testPlayer/MM-R9359)

**Pull request merged**
