### PR TITLE
Fix mark as unread websocket and race condition

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
There was a problem with the websocket event sent by the server, that not always added the msg_root_count field. This created that other clients, when receiving the message, did not see the count, resulting in the channel not getting highlighted when marked as unread.

There was also a problem with a race condition, where if the websocket was handled before the local action to update the msg count would work fine, but otherwise, it would not show the highlight.

I added the root count to all websocket messages, since I don't think there is any downside of doing so.

#### Ticket Link
NONE

#### Release Note
```release-note
Fix issue where marking as unread a channel may not show properly immediately in other clients.
```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]
LGTM

**Review by devinbinnie — APPROVED** [review]
Nice catch :)

**Comment by larkox** [comment]
@yasserfaraazkhan There are two things you can test here:

1. Websocket message is sent fine
  - Open two clients with the same user
  - Have CRT enabled (important!)
  - Mark as unread on one client
  - Check that it is marked as unread in the other client
2. Websocket and local behave properly
  - In one client
  - CRT is enabled
  - Mark the channel as unread several times
  - Check that there is no "flicker" (setting it as unread and read again) in the LHS when you do so

**Pull request merged**
