### PR TITLE
Fixes errcheck in email_test.go

### PR DESCRIPTION
**Pull request by HarshitVashisht11**
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28813

#### Release Note

```release-note

```

### CODE REVIEW

**Review by hanzei — CHANGES_REQUESTED** [review]
Thanks for the PR!

There are a couple of compiler issues with the proposed code. Please check out https://github.com/mattermost/mattermost/actions/runs/11482302724/job/31993226394?pr=28910.


If you need any help setting up a dev environment, please let me know.

**Comment by HarshitVashisht11** [comment]
Hi @hanzei , can you review this pr please

**Comment by HarshitVashisht11** [comment]
Hi @hanzei can you review this PR also , Thank You

**Review by hanzei — APPROVED** [review]
LGMT :+1:

**Review by larkox — APPROVED** [review]

**Pull request merged**
