### PR TITLE
[MM-57857] Update prepackage calls to v0.27.0

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Prepackage Calls v0.27.0

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-57857

#### Release Note

```release-note
Prepackage Calls version v0.27.0
```

### CODE REVIEW

**Comment by cpoile** [comment]
I'll manually test

**Review by streamer45 — APPROVED** [review]
Thanks!

**Comment by cpoile** [comment]
The new plugin is getting installed, but I can't ensure that it works because of rtcd connection issues: 
image

I'll approve since the goal is to get the new version installed. Just fyi.

**Comment by cpoile** [comment]
Works now!

**Pull request merged**
