### PR TITLE
MM-51984 - Fixing footer bar in system console

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-51984 - Fixing footer bar in system console

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51984

#### Screenshot
Screenshot 2023-06-13 at 6 32 56 PM

#### Release Note
<!--
Add a release note for each of the following conditions:

* Config changes (additions, deletions, updates).
* API additions—new endpoint, new response fields, or newly accepted request parameters.
* Database changes (any).
* Schema migration changes. Use the [Schema Migration Template](https://docs.google.com/document/d/18lD7N32oyMtYjFrJKwsNv8yn6Fe5QtF-eMm8nn0O8tk/edit?usp=sharing) as a starting point to capture these details as release notes. 
* Websocket additions or changes.
* Anything noteworthy to a Mattermost instance administrator (err on the side of over-communicating).
* New features and improvements, including behavioral changes, UI changes, and CLI changes.
* Bug fixes and fixes of previous known issues.
* Deprecation warnings, breaking changes, or compatibility notes.

If no release notes are required, write NONE. Use past-tense. Newlines are stripped.

Examples:

```
Added new API endpoints POST /api/v4/foo, GET api/v4/foo, and GET api/v4/foo/:foo_id.
```

```
Added a new config setting ServiceSettings.FooBar. Added a new column Foo to the Users table.
```

```
NONE
```

```release-note
Fixed an issue where the footer with Save/Cancel buttons did not get anchored properly in the System Console.
```

### CODE REVIEW

**Comment by amyblais** [comment]
@asaadmahmood Please help add dev reviewers.

**Comment by asaadmahmood** [comment]
@calebroseland Have a look at it right now.

**Comment by amyblais** [comment]
I've changed the second dev reviewer as Caleb is out of office for the next few weeks.

**Review by crspeller — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Thanks @asaadmahmood - looks good to me 👍

**Comment by amyblais** [comment]
@mgdelacroix Kind reminder to review this.

**Comment by mgdelacroix** [comment]
Closing and reopening to unblock CI

**Pull request merged**
