### PR TITLE
Fix errcheck issues in server/channels/jobs/batch_report_worker.go

### PR DESCRIPTION
**Pull request by azadDsync**
#### Summary

Fix errcheck issues in server/channels/jobs/batch_report_worker.go
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28758

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by hanzei** [comment]
@azadDsync Heads up  that there is a merge conflict to resolve

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @azadDsync!

**Pull request merged**
