### PR TITLE
Update prepackaged calls to v0.23.1

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Prepackage Calls v0.23.1

#### Ticket Link
- none

#### Release Note

```release-note
Prepackage Calls version v0.23.1
```

### CODE REVIEW

**Comment by cpoile** [comment]
I'll do testing

**Review by amyblais — APPROVED** [review]

**Review by streamer45 — APPROVED** [review]
Thanks!

**Comment by cpoile** [comment]
Tested, works.

**Comment by esethna** [comment]
@amyblais quick note, for PRs regarding updating pre-packaged plugins, can we label them as "docs needed" by default, and then Carrie can ping PM to determine if doc updates are needed?


cc// @cwarnermm

**Pull request merged**
