### PR TITLE
Prepackage Calls v1.3.1 in v10.1

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

Prepackaging Calls v1.3.1 in the upcoming v10.1 dot release.

#### Release Note

```release-note
Prepackage Calls v1.3.1
```

### CODE REVIEW

**Review by cpoile — APPROVED** [review]

**Review by amyblais — APPROVED** [review]

**Comment by amyblais** [comment]
@streamer45 Please help take a look at the failing tests.

**Comment by streamer45** [comment]
Looks like pre-existing flaky tests.

**Comment by amyblais** [comment]
@streamer45 @hanzei @agnivade Do you know what would need to be cherry-picked to fix the ``release-10.1`` branch?

**Pull request merged**
