### PR TITLE
server: Force local mode when launching test-data target

### PR DESCRIPTION
**Pull request by KuSh**
#### Summary

A one liner that save me from always searching why the test-data make target fails inevitably until I remember local mode should be enabled

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM, nice QoL imorovement!

**Comment by agarciamontoro** [comment]
Actually, we can probably skip QA here and merge directly. I've tested it locally and it works as expected. @isacikgoz, thoughts?

**Comment by isacikgoz** [comment]
Sounds good to me 👍  @agarciamontoro

**Comment by agarciamontoro** [comment]
Thanks for this, @KuSh, I always love this kind of PRs :)

**Pull request merged**
