### PR TITLE
MM-51849 - some non latin words were not getting highlighted

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
Some non latin words were not getting highlighted. This PR enhances the regex used to validate other non-latin languages so the highlight works well for those scenarios.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51849

#### Screenshots
Before:

https://github.com/mattermost/mattermost/assets/10082627/82f10a42-75d1-423a-8495-e8ca9c0cb2be

After:

https://github.com/mattermost/mattermost/assets/10082627/27bb11bf-1690-4664-8362-36d99c3dbc38

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
thank you for fixing this Pablo

**Review by BenCookie95 — APPROVED** [review]

**Comment by pvev** [comment]
@lindalumitchell @yasserfaraazkhan this PR is ready for QA, could you please help us with it or help us assign someone else that could help with the QA process? thanks!

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
