### PR TITLE
MM 60583 Update message after continuing

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Removes the error and update the message after continuing with an invalid URL

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-60583

#### Screenshots
Before -

Screenshot 2024-10-02 at 1 39 17 PM

After -
Screenshot 2024-10-14 at 9 46 25 AM

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by JulienTant — APPROVED** [review]

**Review by calebroseland — APPROVED** [review]
Approving, but I think there was some discussion on whether or not the red should be removed as well. https://hub.mattermost.com/private-core/pl/xu4541ieyjry8yoz48r87mxaxr

**Comment by sbishel** [comment]
> Approving, but I think there was some discussion on whether or not the red should be removed as well.

Oh, I didn't pick up on that...but 0/5...adding @asaadmahmood for verification.

**Comment by asaadmahmood** [comment]
Yes @sbishel, we will be removing the red error, and should update the text to:
`This may not be a valid link: http://[url]/.`

**Review by asaadmahmood — CHANGES_REQUESTED** [review]
See comment above.

**Comment by lindy65** [comment]
@sbishel - bookmarks bar is behind a feature flag. Are you able to turn it on in the spinwick?  If not, I'll QA-defer this PR and test post merge.

**Comment by sbishel** [comment]
@lindy65 - The feature flag is turned on. I'm seeing it on the test server above.

Screenshot 2024-10-14 at 10 57 29 AM

**Comment by lindy65** [comment]
Thanks @sbishel - just waiting for the spinwick to update and I'll test

**Review by calebroseland — APPROVED** [review]

**Comment by lindy65** [comment]
@sbishel - I added one invalid link quite fine (it had no spaces in the link).  Then I added an invalid link with spaces in it. Is it expected that I will then get the error below?
image

I'm guessing it is expected as URLs don't have spaces in them and people should try to add links with spaces

**Comment by calebroseland** [comment]
Odd seeing the green check, but minor and maybe not an issue
Arc 2024-10-14 12 31 45

**Comment by lindy65** [comment]
> Odd seeing the green check, but minor and maybe not an issue Arc 2024-10-14 12 31 45

I think it's quite nice to get the verification green check :)

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - looks good to me

**Comment by sbishel** [comment]
@asaadmahmood - Gentle ping.

**Review by asaadmahmood — APPROVED** [review]
I thought I already accepted it. Apologies @sbishel

**Pull request merged**
