### PR TITLE
MM 56929 Dont allow guests to be set via channel API 

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Do not allow the `UpdateChannelMemberSchemeRoles` to update a channel member to a "guest". This alters the user for a single channel and does not demote them properly.

This is a follow up to the following PR.
https://github.com/mattermost/mattermost/pull/26286

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-56929

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by enahum — APPROVED** [review]
Lgtm

**Review by jupenur — APPROVED** [review]

**Review by hanzei — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - this will be tested post-merge

**Pull request merged**
