### PR TITLE
chore(api): replace redoc-cli with @redocly/cli

### PR DESCRIPTION
**Pull request by tnir**
#### Summary

[redoc-cli](https://www.npmjs.com/package/redoc-cli), used for API docs under /api, was deprecated in favor of [@redocly/cli](https://www.npmjs.com/package/@redocly/cli) in 2023. cf. https://github.com/Redocly/redoc/pull/2172.

#### Ticket Link

- n/a

#### Screenshots

```
$ cd api; make build
Getting dependencies using npm
npm install
npm warn deprecated @types/handlebars@4.1.0: This is a stub types definition. handlebars provides its own type definitions, so you do not need this installed.
npm warn deprecated @types/chokidar@2.1.3: This is a stub types definition. chokidar provides its own type definitions, so you do not need this installed.

added 310 packages, removed 233 packages, and audited 369 packages in 3s

30 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (3 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
touch node_modules
Fetching Playbooks OpenAPI spec
cd playbooks && node extract.js
(node:84629) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
fetched Playbooks OpenAPI spec
wrote file paths.yaml
wrote file schemas.yaml
wrote file responses.yaml
wrote file securitySchemes.yaml
(node:84628) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
cd playbooks && node merge-definitions.js /src/github.com/tnir/mattermost/api//v4/source/definitions.yaml
read file /src/github.com/tnir/mattermost/api//v4/source/definitions.yaml
read file schemas.yaml
read file responses.yaml
read file securitySchemes.yaml
wrote file merged-definitions.yaml
cd playbooks && node merge-tags.js /src/github.com/tnir/mattermost/api//v4/source/introduction.yaml
read file /src/github.com/tnir/mattermost/api//v4/source/introduction.yaml
read file tags.yaml
wrote file merged-tags.yaml
Building mattermost openapi yaml for v4
Extracting code samples
cd server && go run . /src/github.com/tnir/mattermost/api//v4/html/static/mattermost-openapi-v4.yaml
/src/github.com/tnir/mattermost/api//v4/html/static/mattermost-openapi-v4.yaml is valid
(node:84865) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Prerendering docs

🎉 bundled successfully in: ./v4/html/index.html (7277 KiB) [⏱ 2.215s]
Complete
```

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by tnir** [comment]
@jasonblais @jfrerich Could you help me assign the PR to someone?

**Comment by tnir** [comment]
@jasonblais @jfrerich Could you take a look?

**Comment by tnir** [comment]
@marianunez Thanks.

**Review by agnivade — APPROVED** [review]
Thanks!

**Review by streamer45 — APPROVED** [review]
Works well, thanks!

**Comment by tnir** [comment]
@streamer45 @agnivade Thanks, but how can I help you get this merged? Some tests look like failing to me.

**Comment by streamer45** [comment]
@tnir Once CI is green I'll merge.

**Comment by tnir** [comment]
Thank you so much @streamer45! :tada:

**Pull request merged**
