### PR TITLE
MM-59024 - Update code to handle column headers without text

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Fixes an issue where passing a null value into `FormatMessage` caused a crash, updated unit test to match real columnHeaders.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-59024

#### Screenshots

|  before  |  after  |
|----|----|
| Screenshot 2024-06-20 at 12 02 36 AM | Screenshot 2024-06-20 at 12 07 52 PM |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by JulienTant — APPROVED** [review]
LGTM

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - this is fixed - no crash observed

**Review by hmhealey — APPROVED** [review]
Thanks for fixing that since that looks like something I might've broken. Sorry about that! 😅

**Pull request merged**
