### PR TITLE
MM-54181 : Clean up code around deprecated Gfycat

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
This PR removes any leftover Gfycat gif picker pieces from the app.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-54181

#### Screenshots
n/a

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@yasserfaraazkhan I tried to find out if there are any existing e2e linked with gif picker, but I couldn't find one. let me know if there are any

**Review by larkox — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
I think there were no e2e test for gfycat.

**Review by hmhealey — APPROVED** [review]
Very nice! That's a lotta deleted code

**Pull request merged**
