### PR TITLE
MM-58527 - Fixing overflow issue for autocomplete

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-58527 - Fixing overflow issue for autocomplete

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-58527

#### Screenshots
CleanShot 2024-06-27 at 20 49 34@2x

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by matthewbirtch** [comment]
@asaadmahmood could you also look at the case when you're in the Threads view with the the RHS also open?
image

**Comment by asaadmahmood** [comment]
@matthewbirtch I don't think we can fix that with the css fix because the postbox scrolls in the center content in the threads view, so we the container gets an overflow-y scroll and with that we can't apply overflow-x: visible.

In the channel content, since the postbox is fixed at the bottom, we don't need it in a scrolling or overflow hidden container so that works.

**Comment by matthewbirtch** [comment]
> @matthewbirtch I don't think we can fix that with the css fix because the postbox scrolls in the center content in the threads view, so we the container gets an overflow-y scroll and with that we can't apply overflow-x: visible.
> 
> In the channel content, since the postbox is fixed at the bottom, we don't need it in a scrolling or overflow hidden container so that works.

Maybe we need to do what we do when the RHS is closed and just anchor the autocomplete to the right side of the input field when the `@` trigger character is beyond a certain x position. 
image

**Review by calebroseland — APPROVED** [review]
A step in the right direction—but long term it would be to move the positioning/mounting logic over to floating-ui or mount to root, like you were mentioning in the ticket.

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by yasserfaraazkhan — CHANGES_REQUESTED** [review]
- fixed on the center post message text box ✅ 
image

- the thread View might still need a fix as mentioned in ticket
image


- Similar issue in the Edit Message text box in Channel center text box and in Threads view as well
image


let me know if you feel a separate ticket is needed for edit message mode.

**Comment by asaadmahmood** [comment]
@yasserfaraazkhan Yup, we would can mention that edit state issue in the same threads view ticket, because it is the same problem of content being inside a scroll and supporting overflow.

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
