### PR TITLE
Fix draft sent to show and rise errors

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Fix draft screen send to use the same logic as the post input.

#### Ticket Link
Fix https://mattermost.atlassian.net/browse/MM-60298

#### Release Note
```release-note
Improve errors when sending from the draft screen
```

### CODE REVIEW

**Comment by larkox** [comment]
@abhijit-singh Adding you to this just to verify how the errors are shown. Here a screenshot of how I made them look for now.
Screenshot from 2024-09-16 15-40-11

**Comment by larkox** [comment]
@harshilsharma63 We have talked about this PR before. Let me know if you need any changes to make the conflicts with your branch as simple as possible.

**Review by harshilsharma63 — APPROVED** [review]
Overall the changes look nice! I see I'll have to be careful rebasing this in scheduled posts 😛

**Review by hmhealey — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]
Approving again because GitHub doesn't seem to like my first approval

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by abhijit-singh — COMMENTED** [review]
@larkox I see the error in a modal as shown in the Jira ticket and that looks good, but in what scenario would the error message appear below the drafts? Like the screenshot you shared?

**Comment by larkox** [comment]
@abhijit-singh The error would appear mainly when it is the server the one returning the error. A couple of options here would be, if I am not mistaken:
- Message too long
- Plugin reject the message
- Server unreachable

**Comment by abhijit-singh** [comment]
@larkox I don't see the error message in the case of `message too long` and `server unreachable`. 

https://github.com/user-attachments/assets/b79679ea-45f1-40af-9d85-e9ce6917577a

https://github.com/user-attachments/assets/f02619bd-247c-493b-8408-7538ecd2dd8d

I do agree it makes sense for us to show errors for those though, and I don't mind the UI. Any specific reason why you went with an error below the draft instead reusing the modal as in the original case (root message deleted)?

**Comment by larkox** [comment]
@abhijit-singh I may have missed something, I will double check.

The reason to have it in below the draft is because that is how it works on the post input box.

**Review by yasserfaraazkhan — CHANGES_REQUESTED** [review]
Hi @larkox ,
Can you check the delete Draft flow ? It was not occuring on this instance, but working in 10.0

If the root post is delete, the `Edit` Icon will open a empty RHS panel. (this might be known behaivour)

https://github.com/user-attachments/assets/7469a379-c537-4028-83b0-563da16fd82b

https://github.com/user-attachments/assets/08ba20cd-73b7-4642-a3a7-8d78c34e0377

**Comment by abhijit-singh** [comment]
@larkox I don't want to increase scope here, but I was talking to @asaadmahmood since he's working on similar things right now with Scheduled Messages. He made a great point that in case of long messages, the bottom of the message is not visible so in the UI you have right now, there's a high chance that the user might not see the error message.

There are two types of errors I believe, and they probably should to be handled slightly differently — 
1. Errors that get triggered when the user clicks on the `Send` button (For example - root message deleted, server unreachable) — For these, we should trigger a more prominent message outside of the message itself, just like the modal we have for the first case. 

Another recommendation here is to use a toast that @asaadmahmood is probably going to pitch as a part of the scheduled messages effort. Sharing what that can look like but @asaadmahmood can correct me if I'm wrong.

https://github.com/user-attachments/assets/21f85c92-3797-4100-8095-be94e73d2cc9

2. Errors that should always be shown (For example message is too long and exceeds limit) — For these, we already have a pattern designed to show error messages in close proximity to the action buttons. It looks something like this:
image

Let me know what you think. If any of this is too much effort, happy to discuss and land on a more feasible solution for the purposes of this PR and do the polish later.

**Comment by larkox** [comment]
@yasserfaraazkhan @abhijit-singh Most of the reported errors should be now addressed. Please take another look.

@harshilsharma63 @hmhealey @M-ZubairAhmed I am going to also re-request the review from you, since I had to make changes in the code that are not really trivial, so it would help having an extra pair of eyes on that.

**Review by harshilsharma63 — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Comment by larkox** [comment]
@abhijit-singh @yasserfaraazkhan Friendly reminder for re-review.

**Review by yasserfaraazkhan — APPROVED** [review]
The drafts under deleted post wont be sent.

just 1 small observation. In dark more, these button appear clickable. Visibly can't make out if these are disabled buttons.

Screenshot 2024-09-24 at 3 38 06 PM

(Had tested this a while ago, forgot to submit review.)

**Review by abhijit-singh — CHANGES_REQUESTED** [review]
@larkox Sorry one request on the UI side - Can we add a red border to any drafts with errors? Here's the [Figma mockup](https://www.figma.com/design/er6ehzVOduwRqEMjPNlvNY/MM-23881-Global-Drafts?node-id=2313-43995&t=j2a16YDAxn6bMSAA-4) showing it.

image

Also, for the disabled buttons not being visibly different (great catch @yasserfaraazkhan!), can we just remove the icon buttons that are disabled? I just checked and that's what we're [planning to do for scheduled messages](https://www.figma.com/design/VbEx15Tpvi9mXhs9IEjJtq/MM-45558-Drafts-%26-Schedule-Messages?node-id=1932-131124&t=XI62GNogBsuqijZv-4) as well.

**Comment by abhijit-singh** [comment]
For the text in the error tag, we need something short so that it works in smaller screens. For example, taking cues from what we're doing in scheduled messages, if the user is no longer in a channel that the message was scheduled in, we show `Not in the channel` as the error tag, if the channel becomes read only we show `Channel is read only`.

For the two cases identified in this PR, here's what I propose: 
1. Your message is too long. Character count: 17213/16383 — `Message too long`
(I think it is not important to show the character count here since the user cannot edit the message on this screen. )
2. This draft was created for a post that cannot be found. — `Thread cannot be found`

cc @cwarnermm for a review of the error tag copy. The previous comment here as a mockup of where it'll be shown. You can also see in [Figma here](https://www.figma.com/design/er6ehzVOduwRqEMjPNlvNY/MM-23881-Global-Drafts?node-id=2313-43995&t=j2a16YDAxn6bMSAA-4). 

@larkox Please let me know if I'm missing any error case here.

**Comment by cwarnermm** [comment]
Updated [Figma](https://www.figma.com/design/er6ehzVOduwRqEMjPNlvNY/MM-23881-Global-Drafts?node-id=2313-43995&node-type=frame&t=EnuchkDP72Rk0Otu-0) designs with the following copy proposals (intended to be shorter & ideal for mobile):

- Message too long
- Thread not found

Are there other strings I've missed?

**Comment by hmhealey** [comment]
I removed my review request since I'll defer to Harshil and Zubair on this, and they've already both approved it 🙂

**Review by abhijit-singh — APPROVED** [review]
Looks great, thanks @larkox! Just one quick thing - `Thread cannot be found` can be changed to `Thread not found` as per Carrie's recommendation above. Thanks!

**Pull request merged**
