### PR TITLE
MM-56822 Update logic around permissions and sanitization

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
This PR changes the logic for Team Sanitization. It ensures that all users Including Team Administrators have model.PermissionInviteUser before returning inviteId on the team object.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-56822

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by enahum — APPROVED** [review]

**Review by esarafianou — APPROVED** [review]

**Review by streamer45 — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - QA-deferring and will test post-merge

**Comment by amyblais** [comment]
@sbishel Can you help open a manual cherry-pick PR for ``release-9.6`` branch?

**Comment by amyblais** [comment]
> @sbishel Can you help open a manual cherry-pick PR for `release-9.6` branch?

cc @sbishel A kind reminder on this.

**Pull request merged**
