### PR TITLE
Fixes #24653 - Use getFileDownloadUrl for file_search_result_item

### LINKED ISSUE #24653: Download URL in channel file search is missing the `Site URL` path
#### Summary
The path in the value of [Site URL](https://docs.mattermost.com/configure/environment-configuration-settings.html#site-url) setting does not affect the download address in channel file searches.

#### Steps to Reproduce
1. In Mattermost settings configure the `Site URL` to a value that contains path. For example: `https://example.com/company/mattermost`.
2. Conduct a file search within a channel.
3. Attempt to download a file.

#### Expected Behavior
The download URL should include the path of `Site URL` setting, following this format: `${site_url_path}/api/v4/files/${fileID}?download=1`.

#### Observed Behavior
The download URL lacks the path of `Site URL` parameter, appearing as `/api/v4/files/ID?download=1`, which is not correct.

#### Possible Fix
Modify `webapp/channels/src/components/file_search_results/file_search_result_item.tsx:194` ([link](https://github.com/mattermost/mattermost/blob/460fa05eb9e87278def9ac9f493a587481bebb78/webapp/channels/src/components/file_search_results/file_search_result_item.tsx#L194C33-L194C33)) to utilize the `getFileDownloadUrl` function from `mattermost-redux/utils/file_utils`.

### PR DESCRIPTION
**Pull request by danialkeimasi**
#### Summary
The path in the value of [Site URL](https://docs.mattermost.com/configure/environment-configuration-settings.html#site-url) setting does not affect the download address in channel file searches.

1. In Mattermost settings configure the `Site URL` to a value that contains path. For example: `https://example.com/company/mattermost`.
2. Conduct a file search within a channel.
3. Attempt to download a file.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/24653

#### Release Note

```release-note
Fixes download link in channel file search items, when you have path in "Site URL" setting.
```

### CODE REVIEW

**Review by jespino — APPROVED** [review]
Nice one! Thanks @danialkeimasi! :confetti_ball:

**Comment by danialkeimasi** [comment]
Reordered the import statement to fix the linter error in force push.

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
Thanks for the PR, @danialkeimasi, and sorry that I missed it earlier. This looks perfect.

I'm going to skip QA review on this since I tested it locally

**Comment by danialkeimasi** [comment]
Thank you, that's not an issue.

Just a reminder, I don't have access to the "Enterprise CI/tests" log.

**Comment by hmhealey** [comment]
That's not a problem. That failure is caused by the branch being slightly out of date with master. We really need to figure out how to not have that break constantly, but I can fix it by updating the branch

**Pull request merged**
