### PR TITLE
MM-52503- Fix E2E Test for link customization

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
mattermost.com links get `utm_` data added. Therefore instead of an exact match in the test, need to use regex to allow for query parameters.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-52503

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by toninis** [comment]
You can always trigger the tests manually from https://github.com/mattermost/enterprise/actions/workflows/mattermost-ci.yml if they are not triggered . 

Use the proper commit sha and branch

**Review by saturninoabril — APPROVED** [review]
Thanks Scott!
Screenshot 2023-06-28 at 9 38 16 AM

**Review by calebroseland — APPROVED** [review]

**Pull request merged**
