### PR TITLE
Move .editorconfig to repo root

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
I noticed at some point that VS Code had sometimes stopped properly auto formatting files, but I only realized last week that it was because the [EditorConfig](https://editorconfig.org/) extension wasn't finding that file correctly for code outside of `server` and `webapp/channels`. I combined those and moved it to the root so that it'll apply to the other folders in the repo

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:   It would be nice if there was an entry for yaml.

**Review by agnivade — COMMENTED** [review]
Would this still work for users (like me) who start the editor from inside the `server` directory?

**Comment by hmhealey** [comment]
Yeah, I just checked, and it does work.

@wiggin77 What would we want to add for .yaml? Two space tabbing and a newline at the end? I can add it, or you can feel free to add it to the branch if you want

**Comment by wiggin77** [comment]
> Two space tabbing and a newline at the end?

@hmhealey yes, that would be great.

**Review by agnivade — APPROVED** [review]

**Pull request merged**
