### PR TITLE
[MM-54766] Fix RHS Search/Info screens width for Mobile Web View 

### LINKED ISSUE #24875: Mobile Web View shows empty space in RHS Search/Info screens
Reproduction steps:

1. Narrow to mobile web view in browser or desktop app
2. Click the Search icon or the `i` info icon

Observed: View slides left to accommodate a RHS that is empty and not needed
Expected: Search and Info screens are full-width in mobile view

- Note: Clicking the three-bar menu slides view to the left to accommodate the menu, as expected. But the other two views should not behave this way

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-54766

### PR DESCRIPTION
**Pull request by Paul-vrn**
#### Summary

Modified CSS properties in webapp/channels/src/sass/layout/_sidebar-right.scss

#### Ticket Link

Fixed #24875 
Jira [https://mattermost.atlassian.net/browse/MM-54766](https://mattermost.atlassian.net/browse/MM-54766)

##### Before:
Attachments in [Jira#MM-54766](https://mattermost.atlassian.net/browse/MM-54766)
##### After:
https://github.com/mattermost/mattermost/assets/78180340/65198d6b-c052-41a6-9fc4-ef9d15775054

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]
Thanks for the contribution! LGTM.

**Review by M-ZubairAhmed — APPROVED** [review]
Thank you for finding this out

**Comment by yasserfaraazkhan** [comment]
Screenshot 2023-10-16 at 2 48 20 PM
Screenshot 2023-10-16 at 2 48 15 PM

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by larkox** [comment]
Thank you for the contribution!

**Pull request merged**
