### PR TITLE
 [MM-58512] Migrate tooltips of "components/status_dropdown/status_dropdown.tsx" to WithTooltip

### PR DESCRIPTION
**Pull request by Aryakoste**
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27234
Jira https://mattermost.atlassian.net/browse/MM-58512
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@Aryakoste can you look at the failing CI

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
