### PR TITLE
[MM-54138] Remove code involving getRedirectLocation and state.entities.posts.expandedURLs

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Ticket Link
Jira https://mattermost.atlassian.net/browse/MM-54138

#### Screenshots
n/a

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
We might want to skip QA review because this is just dead code removal. If something does break from this that wasn't cause by CI, I'd be really worried about our code 😛

**Review by yasserfaraazkhan — APPROVED** [review]
the permalink to post with attachment is working.

**Pull request merged**
