### PR TITLE
fixing filenames

### PR DESCRIPTION
**Pull request by ctlaltdieliet**
#### Summary
This is being caused due to a discrepancy between the filename being created by translate (en_AU.json) and the expected locale used in the server and webapp (en-AU). (Underscore vs Dash) 

The file name will be updated in Weblate, then this import will need updated.

New version of https://github.com/mattermost/mattermost/pull/26127
#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-54003

#### Release Note

```release-note
Fixed issue that didn't allow en-AU language selection.
```

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
Thanks, @ctlaltdieliet!

@sbishel - This PR replaces https://github.com/mattermost/mattermost/pull/26127

**Comment by ctlaltdieliet** [comment]
@lindy65 
Should we better smoke test this?
Thank you

**Comment by lindy65** [comment]
Hi @ctlaltdieliet - yes, I think so - thanks for the ping... I'll test it as soon as the spinwick is up

**Review by lindy65 — APPROVED** [review]
Thanks @ctlaltdieliet - looks good to me 👍

**Review by sbishel — APPROVED** [review]
Awesome...thanks.

**Pull request merged**
