### PR TITLE
[GH-25023] Add in-product Academy link to Search training

### PR DESCRIPTION
**Pull request by heisdinesh**
#### Summary

- Added in product academy link to search training

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/25023

#### Screenshots

image

```release-note
NONE
```

### CODE REVIEW

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
@heisdinesh one minor detail: can we add an underline on hover to the 'Learn about search' text (not the lightbulb icon though)

**Review by crspeller — APPROVED** [review]

**Comment by heisdinesh** [comment]
> @heisdinesh one minor detail: can we add an underline on hover to the 'Learn about search' text (not the lightbulb icon though)

Sure sir, i shall do that

**Comment by heisdinesh** [comment]
@crspeller I have added underline on hover

**Review by matthewbirtch — APPROVED** [review]
Thanks @heisdinesh, this looks good to go

**Review by cwarnermm — APPROVED** [review]
Thank you so much for your help with this, @heisdinesh!!

**Comment by cwarnermm** [comment]
@crspeller - Are you open to helping address merge conflicts for this PR? Thank you!

**Comment by heisdinesh** [comment]
> Thank you so much for your help with this, @heisdinesh!!

Anytime

**Comment by crspeller** [comment]
@cwarnermm There are no merge conflicts. 

@heisdinesh You have some test failures. You need to run `npm run updatesnapshot` to fix the tests. Then it looks like you added a newline at the end of the en.json that the linter does not like.

**Comment by heisdinesh** [comment]
Sure sir i shall do it now

**Comment by heisdinesh** [comment]
@crspeller May I know how to fix this 
image

**Comment by heisdinesh** [comment]
> @heisdinesh A quick google suggests that this is a jest bug. Running with `--runInBand` is a workaround.

Screenshot 2023-12-03 215559
Screenshot 2023-12-03 215625

@crspeller Sir I did try it but again I am getting same error

**Comment by heisdinesh** [comment]
> > @heisdinesh A quick google suggests that this is a jest bug. Running with `--runInBand` is a workaround.
> 
> Screenshot 2023-12-03 215559 Screenshot 2023-12-03 215625
> 
> @crspeller Sir I did try it but again I am getting same error

@crspeller could you please help me in this, I have found the issue, when I run test cases it consumes 100% of CPU and as a result of which the test cases is getting terminated , I have tried the below strategies
- using --runInBand for temporary fix
- using --max-old-space-size=4096 flag 
The problem is with the CPU resource, May I know how can  I proceed forward.

**Comment by cwarnermm** [comment]
Thank you, @M-ZubairAhmed!!

**Pull request merged**
