### PR TITLE
MM-60869 Change Get() to use Master

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Changes the shared_channel_store, Get() method to use Master rather than Replica.

When creating and then retrieving the shared channel in `InviteRemoteToChannel`, the Get() returns Not Found in a cloud environment.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-60869

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by calebroseland — APPROVED** [review]

**Comment by calebroseland** [comment]
https://shared-channels-a.test.mattermost.cloud/ is now running this PR. Login: https://hub.mattermost.com/abc/pl/zmuki8896brmfmekz9w7ckduxe

**Comment by calebroseland** [comment]
Did one test of this and working on `shared-channels-a`

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - I've QA-deferred to test post merge on 10.2-rc2

**Review by mgdelacroix — APPROVED** [review]
LGTM! Great catch!!

**Comment by mgdelacroix** [comment]
Tested in cloud and consistently checked that the issue is gone after applying the fix

**Pull request merged**
