### PR TITLE
Adds ConnectedWorkspacesSettings configuration block

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
The Connected Workspaces related configuration properties were located in the `ExperimentalSettings` config block. Now that the feature is going to get out of beta, and foreseeing more configuration properties being added to it, we're moving them to a block of its own.

If the properties were set in the old location, their values should be carried over to the new ones. The old properties are left in place and marked as deprecated not to cause issues with the model.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-59366

#### Release Note
```release-note
* Moves the Shared Channel related configuration properties out of the Experimental section.
```

### CODE REVIEW

**Review by sbishel — APPROVED** [review]

**Comment by lindy65** [comment]
Hey @mgdelacroix - I'm still seeing "Shared channels" in Experimental Features section. Is this because the front-end UI hasn't been done yet?

image

**Comment by mgdelacroix** [comment]
@lindy65 thanks for pointing this out! I've updated the System Console to include a new section under "Environment" called "Server Federation", and moved the configuration parameter there.

@esethna @asaadmahmood please take a look and let me know if we prefer to use a different structure for the System Console

**Review by lindy65 — APPROVED** [review]
Thanks @mgdelacroix - looks good to me now with "Server Federation" under "Environment"

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by sbishel — APPROVED** [review]

**Pull request merged**
