### PR TITLE
update for guest demotion and sysadmin edits

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
When user is demoted to GUEST, remove all other system/custom roles.
Only allow a SysAdmin to edit another SysAdmin. This is handled at the API layer and results in errors if attempted, but this updates to UI to reflect they cannot be edited.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-53369

#### Screenshots

As System Admin - other System Admins editable
Screenshot 2023-07-06 at 11 48 05 AM

As System/User Manager - System Admins NOT editable
Screenshot 2023-07-06 at 11 49 20 AM

#### Release Note
```release-note
Update UI so System Admins no longer appear editable by System/User managers
```

### CODE REVIEW

**Review by jespino — APPROVED** [review]
LGTM

**Review by calebroseland — APPROVED** [review]
LGTM 👍, only a very minor styling difference when a system manager has `Users: Read Only`

Read Only:
CleanShot 2023-07-10 at 10 35 18@2x

Can Edit:
CleanShot 2023-07-10 at 10 35 53@2x

**Comment by sbishel** [comment]
@calebroseland - Actually, based your comment, I investigated the issue and I think it is better to use the existing `isDisabled` flag for this. I did wrap the caret in this as well, so the down arrow doesn't display if it is disabled.

Nice catch.

**Review by calebroseland — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - tested as per description and this is working as expected.

**Pull request merged**
