### PR TITLE
MM-58025 Resolved automatic tz not reflecting without refresh by listening to app visibility event

### PR DESCRIPTION
**Pull request by fasal26**
#### Summary
Resolved automatic tz not reflecting without refresh by listening to app visibility event

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/26911

#### Release Note
```release-note
Added visibilitychange js browser event for updating user's current timeZone
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]
Apart of the linting issues, look good to me.

**Comment by fasal26** [comment]
> Apart of the linting issues, look good to me.

@larkox 
linting issues resolved

**Comment by hmhealey** [comment]
Some of the issues have been resolved, but the linter that you used reorganized the imports in a way that don't match our linting rules. Would you mind fixing those as well?

You can run the linter with the rules that we use by running `npm run check` in the `webapp` folder

**Comment by fasal26** [comment]
> Some of the issues have been resolved, but the linter that you used reorganized the imports in a way that don't match our linting rules. Would you mind fixing those as well?
> 
> ESLint should be able to fix those automatically if you run `npm run fix`

Resolved

**Review by hmhealey — APPROVED** [review]
Thanks for fixing that! This looks good to me now

**Review by yasserfaraazkhan — APPROVED** [review]
verified changing timezone from MM setting and locally.
the posts timestamps show appropriate time.

**Pull request merged**
