### PR TITLE
[MM-59340] Migrate tooltips of "components/widgets/inputs/input/input.tsx" to WithTooltip 

### PR DESCRIPTION
**Pull request by Camillarhi**
#### Summary

Migrate tooltips to use WithTooltip in "components/widgets/inputs/input/input.tsx"

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27552
Jira https://mattermost.atlassian.net/browse/MM-59340

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
@Camillarhi can you please check the failing CI

**Comment by M-ZubairAhmed** [comment]
@Camillarhi can you recheck again its failing again :)

**Comment by Camillarhi** [comment]
@M-ZubairAhmed  the test currently failing is not part of the files I worked on, should I fix that? Also I will look into the failed linting.

**Comment by Camillarhi** [comment]
@M-ZubairAhmed  the lint error has been fixed

**Review by M-ZubairAhmed — COMMENTED** [review]
This looks good :shipit: Thank you

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by Rajat-Dabade — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
