### PR TITLE
MM-56876: Draft: Add Redis

### PR DESCRIPTION
**Pull request by agnivade**
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-56876

TODO:
- Figure out Role cache problem
- Add permissions for system console
- Add System console UI

### CODE REVIEW

**Comment by streamer45** [comment]
A couple of general questions:

1. How do we test any of this on CI?
2. How do we enable local development?

I understand we are trying to target AWS ElastiCache here, but I feel we should still develop a strategy for the above, especially the first one.

**Comment by agnivade** [comment]
With docker. Similar to our Opensearch strategy. I just haven't added the Redis docker setup to this PR.

**Comment by amyblais** [comment]
v9.11 release branch was cut last Friday, so this PR is now safe to merge any time.

**Pull request closed without merging**
