### PR TITLE
[GH-23759] Fixed missing zoneinfo (#23759)

### PR DESCRIPTION
**Pull request by 3kami3**
* added tzdata
* set noninteractive installation

#### Summary
Added missing zoneinfo.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/23759

#### Release Note
```release-note
Bug fix: Added missing zoneinfo.
```
#### Additional Information
The log output now also reflects the time zone.
```json
{"timestamp":"2023-06-15 13:50:38.925 Z","level":"info","msg":"Server stopped","caller":"app/server.go:736"}
{"timestamp":"2023-06-15 22:51:08.470 +09:00","level":"info","msg":"Server is initializing...","caller":"platform/service.go:169","go_version":"go1.18.1"}
```

### CODE REVIEW

**Comment by 3kami3** [comment]
Add release-note block.
/remove-kind do-not-merge/release-note-label-needed

**Review by mvitale1989 — APPROVED** [review]

**Review by toninis — APPROVED** [review]

**Review by saturninoabril — APPROVED** [review]
Thanks @3kami3 for your contribution!

**Comment by 3kami3** [comment]
@mvitale1989 Thanks for the merge.
It has been merged into `master`. However, I would like to see a cherry pick on the `release-7.8` as ESR and `release-7.10` branches affected by the issue #23759.

**Comment by amyblais** [comment]
@3kami3 We will be doing some internal testing for this, and then we'll schedule the backports for upcoming dot releases for v7.8, v7.10, and v8.0.

**Pull request merged**
