### PR TITLE
MM-53855 - Handle serverError undefined or null

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Check server error to be falsy, rather than null. 
This was causing JS error and not allowing the state to update correctly. That fix is in this file.
webapp/channels/src/components/admin_console/system_roles/system_role/system_role.tsx

There was also an issue when bot accounts were added to a system roles. Bots are now removed when adding system roles. The rest of the changes are fixes for that and unit tests for those areas.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-54193
Fixes https://mattermost.atlassian.net/browse/MM-53855

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by harshilsharma63 — APPROVED** [review]

**Comment by lindy65** [comment]
Hey @sbishel 

I have a question about adding a user manager (or other role) in System Console > System Roles:

image
----------------------

image
----------------------

image
----------------------
Other than this question, functionality for https://mattermost.atlassian.net/browse/MM-54193 is working as expected.

----------------------

For https://mattermost.atlassian.net/browse/MM-53855 I'm seeing odd behavior (see screenshot) and even after a refresh, pre-existing user manager as well as other users I added at the same time as this user are not displayed.

image
----------------------

image

The above scenario repeats itself as I remove users from being user managers.  It seems perhaps that this section of the modal is not scrollable?  Or area to display users added is too small and displays only 1 user manager at a time?  To add, the "< >" arrows to the right of user count do not work / are not functional.

**Comment by sbishel** [comment]
Thanks Lindy.  Returning to the list of Roles after "Save" is done intentionally. After, fixing, I thought this was a bit weird as well, but it is the same way that "Teams" and "Channels" works, so I left it.

The other one is weird. Some type of display issue. Because if you type a "missing" user in search. It displays...not sure. I'll take a look today.

**Comment by lindy65** [comment]
Hey @sbishel - Thanks for your explanation on https://mattermost.atlassian.net/browse/MM-54193.  As a user, it doesn't make much sense to me to have to go back to the view I was just in to a) either add more users or b) check that the user was added/removed correctly.  Perhaps @esethna can weigh in here and maybe it's something we can look at in the future?  4/5

Yep, the issue for https://mattermost.atlassian.net/browse/MM-53855 is weird.  Perhaps it's a UI design issue where the display block/box is not big enough and/or isn't scrollable?  Thanks for looking into it.

**Comment by lindy65** [comment]
Thanks @esethna 👍

**Comment by sbishel** [comment]
@lindy65 - I've check in a fix. Its a separate issue, that exists today, It exists specifically with Bot accounts. That why I wasn't seeing it locally. One query returned bots, but the count query excludes bots. That's what screwed up the paging.

I will need to add some tests and get the code re-reviewed as the fix is bigger than the original issue.

**Comment by lindy65** [comment]
Thanks @sbishel - can I go ahead and retest or do you want to get dev reviews done again first?

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - retested as per both Jira tickets and looks good to me 👍

**Comment by sbishel** [comment]
@harshilsharma63 @M-ZubairAhmed - Asking for a re-review since I fixed the other issue that Lindy found.

**Review by harshilsharma63 — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]

**Pull request merged**
