### PR TITLE
[MM-58778] Fixing white screen for GM conversion

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
The system message assumes we will find the user for convertedByUserId but there are edge cases where that user may not be found such as when we permanently delete a user

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-58778

#### Release Note

```release-note
Fix GM to private channel conversion edge cases
```

### CODE REVIEW

**Review by pvev — APPROVED** [review]
Changes LGTM! thanks @BenCookie95

**Comment by harshilsharma63** [comment]
Thanks for the fix @BenCookie95 !

**Review by DHaussermann — APPROVED** [review]
Tested and passed 
- Got simple repo step from @BenCookie95 to recreated the condition by invalidating references to to the user ID in the post props for the user that converted the channel.
- Confirmed I could repro the bug consistently 
- Confirmed webapp crash with `TypeError: Cannot read properties of undefined (reading 'username')` no longer occurs if the user id is invalid now
- Confirmed this PR brach will resolve existing cases where the crash is happening because of invalid user ID
- Not related but, briefly regression tested GM to private channel conversion as a precaution 

LGTM!

**Pull request merged**
