### PR TITLE
[MM-56012] Convert ./components/admin_console/team_channel_settings/channel/channel_settings.tsx from Class Component to Function Component

### PR DESCRIPTION
**Pull request by aditipatelpro**
#### Summary
Migrate `./components/admin_console/team_channel_settings/channel/channel_settings.tsx` from class to function component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/25604

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @aditipatelpro!

**Review by M-ZubairAhmed — COMMENTED** [review]
amazing work @aditipatelpro 💯

**Review by yasserfaraazkhan — APPROVED** [review]
team settings page works as expected.

**Pull request merged**
