### PR TITLE
[MM-32576] Text copied from Microsoft OneNote pastes as an image

### PR DESCRIPTION
**Pull request by akaravashkin**
#### Summary
Added ability to paste plain text while copy-pasting from MS Office products on Mac, not only picture.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/16858
https://mattermost.atlassian.net/browse/MM-32576

#### Screenshots
image

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — COMMENTED** [review]
Thanks for the PR, @akaravashkin!

Testing this out locally, I'm now seeing the text posted which is good, but I'm still seeing the image posted as well which I wouldn't have expected. I realize that's not quite clear in the original ticket though.

I'm also trying to understand how this fixes the text not appearing. Before, I'd either expect it to have returned on the first if statement, in which case the browser should've handled pasting the text automatically, or it would've continued into the end of this function, in which case `formatMarkdownMessage` would handle pasting the plain text as well. There must be something in the original code that I don't understand because the flow of it is a bit convoluted

**Comment by hmhealey** [comment]
Oh okay, I think I might know what's going on now that I've played with this a bit more. The original issue is actually because of the handler for pasting files interfering with pasting the text.

When you paste content from OneNote, `pasteHandler` returns at the first if statement which I would've thought lets the browser handle pasting the text itself. Instead, `FileUpload.pasteUpload` handler is called, and that calls `preventDefault` because it sees the file on the clipboard, so the browser never pastes the text.

With the changes on this PR, we run through the rest of `pasteHandler` which manually handles pasting the text, so it still happens even though `preventDefault` is called by both handlers.

I'm trying to figure out what the behaviour I'd expect from this since, if you're copying a single piece of text, I feel like I'd prefer it to be plain text, but if I copied multiple notes at once, an image might be more helpful. Comparing against other apps, Slack always pastes the plain text, and Discord always pastes the image. I'm not a regular OneNote user though, so I don't know what would be more helpful here. Do you have any thoughts on how you'd want it to work?

**Comment by akaravashkin** [comment]
Hello @hmhealey, my idea was to copy behavior of Telegram https://web.telegram.org/a/ It accepts both image and text. I think it's fair. If MS Office provides you such feature and you don't want it, just discard a picture and keep text.

Now I have complaints from users that they have copied text and received an image. It is frustrating.

**Comment by akaravashkin** [comment]
@hmhealey sorry for delay. I tried to implement your idea and made another PR that modifies `FileUpload.pasteUpload`. I ignore file paste handler for `text/html` and plain text pastes like always. https://github.com/mattermost/mattermost-server/pull/23530

**Comment by akaravashkin** [comment]
Close in favor of https://github.com/mattermost/mattermost/pull/23530

**Pull request closed without merging**
