### PR TITLE
Fix test for invite modal error

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
The error string for when a user is not a guest was wrong. Updated the string to show the correct copy.

#### Ticket Link
Fix https://mattermost.atlassian.net/browse/MM-57861

#### Screenshots
Screenshot from 2024-05-03 12-57-15

#### Release Note
```release-note
Improve error text when inviting guests to a team.
```

### CODE REVIEW

**Comment by larkox** [comment]
@abhijit-singh Adding you mostly to verify the text.

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by abhijit-singh — COMMENTED** [review]
Thanks for looping me in @larkox. 

Can I suggest we update the error message to say that this person is a member of another team? Will this always be true when this error is shown?

Here's the error message I'm proposing— "This person is already a member of another team. Please invite them as a regular user."

**Comment by larkox** [comment]
@abhijit-singh On 99% of the cases you are right, this person probably belongs to another team. If we are nitpicky, it could be a member that has not joined yet any team (like a recently created account, or someone that has been kicked out of all teams).

**Comment by abhijit-singh** [comment]
Good point, maybe we can cover all cases by modifying the message to say— 

"This person is already a member of the workspace. Please invite them as a regular user."

cc @cwarnermm

**Comment by cwarnermm** [comment]
Great modification, @abhijit-singh! Building on your proposal:

"This person is already a member of the workspace. Invite them as a member instead of a guest."

Thoughts? Your approach is shorter whereas I'm trying to teach the distinction between member and guest in a Mattermost system. Open to going with your preference, Abhijit.

**Review by abhijit-singh — APPROVED** [review]
@cwarnermm Sounds good.

@larkox Could you please update the error to match Carrie's suggestion, thanks!

"This person is already a member of the workspace. Invite them as a member instead of a guest."

**Review by yasserfaraazkhan — APPROVED** [review]
working as expected.
image

**Pull request merged**
