### PR TITLE
fix: change "Twitter" to "𝕏 (Twitter)" in README.md Get the latest news Section

### PR DESCRIPTION
**Pull request by BandhiyaHardik**
#### Summary

Twitter is now known as 𝕏. I changed Name of Twitter to 𝕏 (Twitter) in README.md Get the latest news section.
#### Ticket Link 

This fixes https://github.com/mattermost/mattermost/issues/25204

#### Screenshots
Before:
image

Suggested Change: 
image

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by BandhiyaHardik** [comment]
[Contributors community channe](https://pre-release.mattermost.com/core/channels/tickets)   this link is not working

**Comment by BandhiyaHardik** [comment]
I have one suggestion.

How about adding YouTube link in Get the latest news section:

image

**Comment by jasonblais** [comment]
@azigler are you open to reviewing the suggested changes?

**Comment by BandhiyaHardik** [comment]
Yes

**Comment by jasonblais** [comment]
> [Contributors community channe](https://pre-release.mattermost.com/core/channels/tickets) this link is not working

Indeed, it looks like the link would need to be

https://community.mattermost.com/core/channels/tickets instead

**Comment by BandhiyaHardik** [comment]
> > [Contributors community channe](https://pre-release.mattermost.com/core/channels/tickets) this link is not working
> 
> Indeed, it looks like the link would need to be
> 
> https://community.mattermost.com/core/channels/tickets instead

Yes, now link is working

**Comment by azigler** [comment]
@jasonblais This change would conflict with https://github.com/mattermost/mattermost/pull/25206 which also addresses this issue.

However, I like the idea of using 𝕏.

**Comment by BandhiyaHardik** [comment]
> @jasonblais This change would conflict with #25206 which also addresses this issue.
> 
> However, I like the idea of using 𝕏.

should we add YouTube Channel in it ? will my other PR will get Merged ?
I have one suggestion.

How about adding YouTube link in Get the latest news section:

image

**Comment by azigler** [comment]
Just got some feedback on this approach here:

> I don't think the actual X character would be good for accessibility as it's not recognised yet... like by the accessibility systems. Ie. Not fully supported in Markdown

https://github.com/mattermost/mattermost/pull/25206#issuecomment-1786168233

So perhaps just going with the simple "X" is best. Can you link your other PR you're referring to @BandhiyaHardik?

Also, I think adding the YouTube channel would be great. I think it should say "Subscribe to Mattermost" as the text.

**Comment by BandhiyaHardik** [comment]
> Just got some feedback on this approach here:
> 
> > I don't think the actual X character would be good for accessibility as it's not recognised yet... like by the accessibility systems. Ie. Not fully supported in Markdown
> 
> [#25206 (comment)](https://github.com/mattermost/mattermost/pull/25206#issuecomment-1786168233)
> 
> So perhaps just going with the simple "X" is best. Can you link your other PR you're referring to @BandhiyaHardik?
> 
> Also, I think adding the YouTube channel would be great. I think it should say "Subscribe to Mattermost" as the text.

so can i open PR for this ?

**Pull request closed without merging**
