### PR TITLE
[MM-52869] Update and fix links in the system console

### PR DESCRIPTION
**Pull request by fmartingr**
#### Summary
Updates to most links in the system console that wasn't using a permalink at the moment, along with some broken and outdated link. I've tried to add new constants for the links on every change, so they will be easier to maintain.

This are changes over a manual sweep of the system console we did, I have not manually searched for links in the code directly.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-52869

#### Release Note

```release-note
Updated links to documentation in the system console
```

### CODE REVIEW

**Comment by pvev** [comment]
thank you @fmartingr the changes looks good to me so far, however during my smoke test review I found some links in the system console that do not have the permalink associated. Do all and every link need to have the PL associated as stated in the ticket description or for some reason some do not/ can not have it?

Attached below:

Screenshot 2023-06-14 at 12 31 15
Screenshot 2023-06-14 at 12 35 39
Screenshot 2023-06-14 at 12 28 24
BTW, in edition and license page, both privace policy link do not have the PL

**Comment by fmartingr** [comment]
> Do all and every link need to have the PL associated as stated in the ticket description or for some reason some do not/ can not have it?

All links should be permalinks in the system console, either I missed the links while making changes or I missed them in the initial sweep. I'm going to check those and made the changes in the PR. Thank you!

**Comment by fmartingr** [comment]
I only updated two missing links in the about modal, the rest were ok in code. The latest spinwick update with the latest commit seems to have gotten those alright. Any ideas what could have happened? Maybe spinwick didn't use the last commit at that time? 🤔

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:   Great work!

**Comment by pvev** [comment]
> I only updated two missing links in the about modal, the rest were ok in code. The latest spinwick update with the latest commit seems to have gotten those alright. Any ideas what could have happened? Maybe spinwick didn't use the last commit at that time? 🤔

I have noticed that recently with spinwicks not taking the latest code... 🤔

**Review by pvev — APPROVED** [review]
LGTM! thank you @fmartingr :shipit:

**Review by cwarnermm — APPROVED** [review]
Thank you for leading this effort, @fmartingr!

**Pull request merged**
