### PR TITLE
[MM-58296] Update prepackage calls to v0.28.1 for MM v9.10

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Prepackage Calls v0.28.1

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-58296

#### Release Note

```release-note
Prepackage Calls version [v0.28.1](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v0.28.1)
```

Calls [v0.28.1](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v0.28.1)

### CODE REVIEW

**Comment by cpoile** [comment]
I'll manually test.

**Review by amyblais — APPROVED** [review]

**Review by streamer45 — APPROVED** [review]

**Comment by cpoile** [comment]
Got it to install, works now.

**Pull request merged**
