### PR TITLE
MM-53028 - Swap out todo plugin with snow in onboarding

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Replaces the todo plugin with the ServiceNow plugin in the onboarding flow.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-53028

#### Screenshots

On-Prem
Screenshot 2023-06-08 at 2 34 02 PM

Cloud
Screenshot 2023-06-08 at 2 34 02 PM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@scottleedavis Looks good, but the name needs to be `ServiceNow`, so we can just remove the space in the middle.

**Review by asaadmahmood — APPROVED** [review]
LGTM apart from the space.

**Comment by sbishel** [comment]
I have updated the screenshots with the most recent changes to svg and removed name from space.

**Review by calebroseland — APPROVED** [review]

**Comment by lindy65** [comment]
Hi @sbishel - I'm not seeing onboarding screens on the spinwick (might be PTO brain!) Does onboarding need to be turned on for the screens to show?

**Comment by sbishel** [comment]
@lindy65 - It should show first time. It did when I spun up a using cloud plugin. I removed the test server and will spin it up again. If not, try this command. 
```
/cloud create _sbishel-test_ --size miniHA --database aws-multitenant-rds-postgres-pgbouncer --image mattermostdevelopment/mm-ee-test --version 2a8d04f
```

**Comment by lindy65** [comment]
Thanks @sbishel - onboarding doesn't seem to show on the spinwicks - perhaps it's been disabled via spinwick config.  I spun up a `/cloud` server using your command above and it worked.  Onboarding is shown with the updated tools listed as per your screenshot.

**Review by lindy65 — APPROVED** [review]
Looks good to me, thanks Scott!

**Comment by amyblais** [comment]
@sbishel There are some conflicts to resolve here.

**Pull request merged**
