### PR TITLE
[MM-43252] Fix flaky TestPreparePostListForClient

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Given that the logs in the JIRA ticket are no longer accessible, I was a bit puzzled about what's going wrong here.

The test broke in https://github.com/mattermost/mattermost/issues/22603 as the `channelID` no longer gets set.

The flaky part of the test was in `Reactions`. The reactions returned by the store are ordered by `CreatedAt` (https://github.com/mattermost/mattermost/blob/1e206381c608f3deacb3730781c9724b21e520f2/server/channels/store/sqlstore/reaction_store.go#L94). This could lead to a mixup in the order of returned reactions. Using `assert.ElementsMatch` avoides the issue by ignoring the returned order.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43252

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Looks good to me! I guess anything that needs `assert.Eventually` is bound to be somewhat flaky, but that's the nature of async code

**Review by agnivade — COMMENTED** [review]
It was the `reactions` subtest that was failing. We seem to only have changed the `files` subtest. Are we sure we are fixing the right thing?

In retrospect, I should have captured the full logs and pasted them in the ticket. My bad on that.

**Comment by hanzei** [comment]
Thanks for the hint, @agnivade :+1:  Now I know where to look specifically.

Do we run the test in CI with a DB replicate? Replication is the only reason I could see the `reactions` test failing.

**Comment by agnivade** [comment]
We don't.

**Comment by hanzei** [comment]
Thanks for the extra Context, Agniva. I think I found the root cause. PTAL.

**Review by agnivade — APPROVED** [review]
Yeah, this can fail if all reactions get added in the same ms. Thanks Ben.

**Pull request merged**
