### PR TITLE
Bump prepackage Jira plugin version to 4.1.1

### PR DESCRIPTION
**Pull request by Kshitij-Katiyar**
#### Summary
Prepackage Jira plugin v4.1.1.

#### Release Note
```release-note
Prepackage Jira plugin version [v4.1.1](https://github.com/mattermost/mattermost-plugin-jira/releases/tag/v4.1.1).
```
Prepackage Jira plugin version [v4.1.1](https://github.com/mattermost/mattermost-plugin-jira/releases/tag/v4.1.1).

### CODE REVIEW

**Review by hanzei — CHANGES_REQUESTED** [review]
LGTM, but the changes conflict

**Review by hanzei — APPROVED** [review]

**Review by fmartingr — APPROVED** [review]

**Comment by Kshitij-Katiyar** [comment]
@mickmister Should I merge this?

**Comment by mickmister** [comment]
@toninis Some pending workflow jobs are preventing this from being mergeable. Any thoughts on this?

**Comment by toninis** [comment]
> @toninis Some pending workflow jobs are preventing this from being mergeable. Any thoughts on this?

Should be ok now for merge

**Pull request merged**
