### PR TITLE
MM-39041: expose TotalsOnly option

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

Sending a request to GetThreadsForUser for a TotalsOnly
returns just the counts without any threads.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by amyblais** [comment]
@koox00 @agnivade Is there any specific server version that this should go to?

**Comment by agnivade** [comment]
This is mostly tied with the webapp change(https://github.com/mattermost/mattermost-webapp/pull/9206), but we haven't seen any major perf improvement with this. So I don't think there's any need to backport this specifically.

There are however, 2 more changes related to CRT which @koox00 is planning to do (exclude_totals and exclude_totals_count). Those might need backports to 5.37.

**Comment by amyblais** [comment]
> This is mostly tied with the webapp change([mattermost/mattermost-webapp#9206](https://github.com/mattermost/mattermost-webapp/pull/9206)), but we haven't seen any major perf improvement with this. So I don't think there's any need to backport this specifically.
> 
> There are however, 2 more changes related to CRT which @koox00 is planning to do (exclude_totals and exclude_totals_count). Those might need backports to 5.37.

@koox00 Is there a PR open for the 5.37 backport?

**Comment by koox00** [comment]
> @koox00 Is there a PR open for the 5.37 backport?

no, there is no PR yet

**Pull request merged**
