### PR TITLE
Updated the user limit to make it easier for community forks

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Updated the user limit logic to not have limits by default, making it easier for community forks to stay updated with upstream.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-56551

#### Release Note
```release-note
None
```

### CODE REVIEW

**Comment by harshilsharma63** [comment]
Note - DO NOT MERGE this until we have the variable added in out build pipeline.

**Review by larkox — APPROVED** [review]

**Comment by harshilsharma63** [comment]
We're closing this PR.

The motive behind this change was to make it easier for maintainers of forks to remove the limit, however, to comply with AGPL license, the maintainer must intentionally make a change to get rid of the limit. So, we're closing this PR and the limit can be very easily removed up setting the variable at https://github.com/mattermost/mattermost/blob/4ac345cc56aac077dcb8507dbbf98dd073406f26/server/channels/app/limits.go#L12 to 0.

**Comment by ThiefMaster** [comment]
I don't understand how the AGPL license is relevant in this context...

**Comment by rdelaage** [comment]
@it33 is mentioning this change in [a post on the Mattermost forum](https://forum.mattermost.com/t/feedback-on-collaboration-for-mission-critical-work/17563/16) but I see that it was not merged because of a problem with the license. I do not understand the problem with AGPL, can you explain please? If there is no problem, can you please merge this change?

**Comment by it33** [comment]
Hi @rdelaage, thanks for the questions, while I'm not super deep on this ticket I think the reason for closing it was this: 

>So, we're closing this PR and the limit can be very easily removed up setting the variable at [mattermost/server/channels/app/limits.go](https://github.com/mattermost/mattermost/blob/4ac345cc56aac077dcb8507dbbf98dd073406f26/server/channels/app/limits.go#L12)

There was some commentary on the reciprocal open source license and I would maybe phrase it without the technical terms as "if you're compiling yourself to remove the limit you're welcome to do that, and Mattermost, Inc. is going to make it straight forward (see link above), at the same time you're going to be responsible for the full open source system including making the full source code of the derivative work available to anyone using it," 

Would that less technical phrasing be helpful?

**Comment by rdelaage** [comment]
I still not convinced... If I understand correctly, here there is no technical problem with the AGPL license as this license doesn't prohibit a change at compilation time. You want to be sure that the user understands what the change involves by requiring a hard change to the source code, making it less easy to change the product as you see see it.

**Comment by it33** [comment]
>I still not convinced... 

Really appreciate your feedback and engagement. I probably need a little help understanding the underlying issue. 

Could you maybe restate your note with a) what you expect, and b) what you observe? 

This PR was to make it easier for people to maintain a self-compiled version of Mattermost's open source code base, and there's been a change in a different PR for a setting in the open source code to configure thing as people like ([mattermost/server/channels/app/limits.go](https://github.com/mattermost/mattermost/blob/4ac345cc56aac077dcb8507dbbf98dd073406f26/server/channels/app/limits.go#L12)), so this PR seems less necessary to me, but I might be missing something,

**Comment by marianunez** [comment]
> I do not understand the problem with AGPL, can you explain please?
>  (ideally without having to recompile i.e. with a configuration directive or something like that, but at least without having to patch Mattermost)

@rdelaage we decided to keep the change required to be explicitly a as a code change to avoid any gray areas around AGPL of just making a compilation change and/or without having to recompile as you've stated. You can easily change [one variable](https://github.com/mattermost/mattermost/blob/4ac345cc56aac077dcb8507dbbf98dd073406f26/server/channels/app/limits.go#L12) in the code to 0 and it will ensure you are agreeing to the AGPL license by modifying the code. This wouldn't be much different than having to make a change to adjust a variable in a makefile.

**Comment by it33** [comment]
Thanks @marianunez that makes sense. Sorry, I was wrong, it looks like making build-time variables isn't going to be the right approach for the design here.  

>a) I would like to be able to disable the limits in the Team Edition easily (ideally without having to recompile i.e. with a configuration directive or something like that, but at least without having to patch Mattermost)

@rdelaage so I think the answer here is that if the intention is to user Mattermost Team Edition (designed for one team) in a way that circumvents the safety limits at 11,000 users (way, way, way beyond the intended design), and if you're a non-profit and deciding not to participate in the Mattermost non-profit program to receive the version of Mattermost design to be used beyond one team, or if you're a commercial entity with hundreds of millions of dollars in revenue (which is the minimum you'd need to employ 11,000 people) and you're choosing not to spend a penny on Mattermost Enterprise (which supports the security, reliability, quality and innovation of our open source work), then you're going to need to modify the open source code base, re-compile, create a derivate work, and then be under a reciprocal open source license (instead of MIT license of Mattermost Team Edition) so that at the very least the people using whatever you're doing with the Mattermost code base have a right to see the source code. 

Please let us know your thoughts here? We'll update the forum post on this as well,

**Comment by rdelaage** [comment]
Hi @marianunez and @it33. Thanks for your answers and your time.

I do not agree with you on the gray area around the AGPL as the source code is under AGPL (only binaries provided by Mattermost Inc. are under MIT). Moreover AGPL applies to source code but also to services provided using these sources, so a sysadmin that compiles Mattermost from sources using modified build arguments have to provide the service under the terms of AGPL.

> You can easily change one variable in the code to 0 and it will ensure you are agreeing to the AGPL license by modifying the code. This wouldn't be much different than having to make a change to adjust a variable in a makefile.

The main difference between a patch and a compile-time variable is that we have to maintain the patch over the time to ensure that it remains compatible with changes in the source code. A modified compile-time variable is pretty-easy to integrate in a Dockerfile for example.

> way, way, way beyond the intended design

This was not clearly stated a few years ago, some of your communication talked about deployments with thousands of users.

> Mattermost non-profit program to receive the version of Mattermost design to be used beyond one team

We promise our users to do our best to process their data on free and privacy-friendly pieces of software to ensure transparency, we cannot use a proprietary version of Mattermost with pieces of code that are not free and auditable.

**Comment by it33** [comment]
Thanks @rdelaage for your input and your thoughtful and open feedback, and clearly having the best of intentions to engage in a constructive dialog, 

The most important thing to communicate is at the top of the link you'd previously shared [from December 2023](https://forum.mattermost.com/t/feedback-on-collaboration-for-mission-critical-work/17563)--which is that Mattermost, Inc. is focusing its priorities on a specific segment of our user and customer base, which is critical infrastructure organizations: 

>In 2024, we are focusing Mattermost’s priorities towards accelerating the world’s mission-critical work, building the most secure, reliable collaboration platform for defense, government, enterprise & critical infrastructure organizations.

This focus means is there is less bandwidth for Mattermost, Inc. to invest in other areas. 

While you could potentially be 100% right about your points above, there isn't bandwidth to re-open a PR that was closed two months ago for a nice-to-have feature that doesn't align with the priorities we've announced.

Our focus is on the success of critical infrastructure enterprises--organizations who's success impacts public safety and national security. Even a single failing Mattermost server is too many, and so we're making changes to aligned to that priority. 

One thought additional thought, is that there are many PRs related to this topic and an option for discussing more, with more visibility and community awareness, would be to continue the discussion on the forum thread both of us had referenced (link above). 

There are over 300,000 views a month on our forum, and we can consolidate input and integrate the context of past discussions on this topic into one place?

The forum supports login using GitHub SSO to keep continuity among discussion participants. 

If not, that's totally okay, just an option for benefit of visibility.

**Pull request closed without merging**
