### PR TITLE
loading_spinner.tsx converted to functional component.

### PR DESCRIPTION
**Pull request by mozi47**
#### Summary
Converted ./components/widgets/loading/loading_spinner.tsx from Class Component to Function Component

#### Ticket Link
Fixes: #24771
Jira ticket: https://mattermost.atlassian.net/browse/MM-54808

### CODE REVIEW

**Comment by mozi47** [comment]
@larkox please review the PR

**Review by larkox — APPROVED** [review]

**Review by sinansonmez — APPROVED** [review]
LGTM :rocket:

**Comment by larkox** [comment]
@mozi47 There has been changes in this file. Do you mind merging the changes?

**Comment by mozi47** [comment]
> @mozi47 There has been changes in this file. Do you mind merging the changes?

no problem go ahead.

**Comment by mozi47** [comment]
is there anything I am missing?

**Comment by hanzei** [comment]
@mozi47 The is a merge conflict in `webapp/channels/src/components/widgets/loading/loading_spinner.tsx`. Would you please resolve that?

**Comment by mozi47** [comment]
Conflict resolved

**Comment by hanzei** [comment]
@larkox Would you mind giving the PR a final review?

**Review by larkox — APPROVED** [review]
Great work!

**Comment by larkox** [comment]
@mozi47 seems like the last changes still have some test issues. Would you mind looking into that? Probably a `npm run test -- -u` will solve them.

**Comment by mozi47** [comment]
Let try it again

**Comment by mozi47** [comment]
image

**Review by lindy65 — APPROVED** [review]
Thanks @mozi47 - looks good to me 👍 

cc @larkox

**Pull request merged**
