### PR TITLE
MM-52646: Fix data race on product notices

### PR DESCRIPTION
**Pull request by agnivade**
The UpdateProductNotices method runs in a separate goroutine
which modifies a global structure called noticesCache.
This creates race condition when one test finishes
but the goroutine hasn't finished running.

To fix this, we simply prevent the spawning of the goroutine
by disabling the feature in the config.

Ideally, we'd not have global state in the first place.
But that's a separate matter.

https://mattermost.atlassian.net/browse/MM-52646

```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — COMMENTED** [review]
Could we solve this issue by simply handling the go routine by ourselves?
```Go
if *s.platform.Config().AnnouncementSettings.AdminNoticesEnabled || *s.platform.Config().AnnouncementSettings.UserNoticesEnabled {
	s.platform.Go(func() {
		appInstance := New(ServerConnector(s.Channels()))
		if err := appInstance.UpdateProductNotices(); err != nil {
			mlog.Warn("Failed to perform initial product notices fetch", mlog.Err(err))
		}
	})
}
```

**Comment by agnivade** [comment]
Can you explain what do you mean by "handling the goroutine"?

**Comment by isacikgoz** [comment]
I see the product notices goroutine is spawned here: 
https://github.com/mattermost/mattermost-server/blob/f3a9f166bba4f30855dbb1a9e2ffffd495a2970e/server/channels/app/server.go#L465
Maybe we could handle it by our `s.platform.Go` function. It would be bound to server start/stop sequence.

**Comment by agnivade** [comment]
Ahh got it. I missed that you added a `s.platform.Go`. Yes, that could work, although the core issue is the global variable.

Let me add that, but I'll keep the config disable part to reduce unnecessary code execution.

**Review by isacikgoz — APPROVED** [review]
> I'll keep the config disable part to reduce unnecessary code execution.

LGTM, thanks!

**Review by agarciamontoro — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
