### PR TITLE
[MM-60168] Migrate tooltips of "components/widgets/menu/menu_items/restricted_indicator.tsx" to WithTooltip 

### PR DESCRIPTION
**Pull request by Camillarhi**
#### Summary

Migrate tooltips of `components/widgets/menu/menu_items/restricted_indicator.tsx` to WithTooltip 
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27928
Jira https://mattermost.atlassian.net/browse/MM-60168
#### Screenshots

image

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
Can you please screenshot this UI change for easy review

**Comment by Camillarhi** [comment]
> Can you please screenshot this UI change for easy review

image

Here it is

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Comment by Camillarhi** [comment]
> This looks good :shipit: Thank you

Thanks

**Review by Rajat-Dabade — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
