### PR TITLE
Across team channel autocomplete

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Across team channel auto complete

#### Related Pull Requests
- Has server changes https://github.com/mattermost/mattermost-webapp/pull/10890

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-server/issues/20606

#### Release Note
```release-note
Channel autocompletion will now return results across all teams.
```

### CODE REVIEW

**Comment by agnivade** [comment]
Congrats on opening your first server PR!

This looks like a great start, but our first task at hand is to add some tests :) Were you planning to add that by yourself, or would you rather someone else from your team take over?

**Comment by AshishDhama** [comment]
@agnivade Thanks I will try to do it myself with some help from the team.

**Comment by agnivade** [comment]
Please feel free to request a review when this is ready. Thanks :)

**Comment by esethna** [comment]
@AshishDhama did you want to finish this or should we open it for hacktoberfest?

**Comment by AshishDhama** [comment]
@esethna work is done on this we just need to add a test and little polishing on the frontend. So will take care of that soon.

**Comment by unode** [comment]
Does this PR also introduce a syntax for `~channel` links that works across teams? I can't tell how this is implemented.

**Comment by AshishDhama** [comment]
@unode Yes it does, but I am not sure if this is a priority now. But I am happy to take it to the finish line. cc// @esethna @agnivade

**Comment by agnivade** [comment]
Happy to review if you want to revive this one @AshishDhama ! I can get someone from the webapp to take a look as well.

**Comment by AshishDhama** [comment]
@agnivade Closing this in favour of https://github.com/mattermost/mattermost/pull/24137

**Pull request closed without merging**
