### PR TITLE
MM-52536 Webpack unification part 2

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
This is based on https://github.com/mattermost/mattermost-server/pull/23543 since they both make a bunch of changes to the package-lock.json, and it's also a followup to https://github.com/mattermost/mattermost-server/pull/23322.

I ended up not going down the rabbit hole of `babel-loader`/`ts-loader` for the time being since it may not be needed in the future. Similarly, we won't be sharing Webpack configs between packages because we don't know where that code will end up in the future. We can always reevaluate that down the line though.

In the end, this ends up being mostly just removing unused dependencies which I'm always a very big fan of

##### Updated and shared

- `@types/webpack-env` - Technically, this is only needed in Channels since it's the only one that uses the global values defined by Webpack, but I figured we might end up using it elsewhere
- `eslint-import-resolver-webpack`
- `style-loader`

##### Unused dependencies that were removed

- `bundle-loader`
- `webpack-live-reload-plugin` - This was somewhat used, but it was missing some other configuration required for it to work
- `terser-webpack-plugin`
- `dotenv-webpack`
- `@pmmmwh/react-refresh-webpack-plugin`
- `@webpack-cli/serve` - We technically use this, but as a dependency of `webpack-cli`
- `stream`
- `image-webpack-loader` - Only removed from Boards since Channels actually uses it

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-52536

#### Related Pull Requests
#23322 
#23543

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by crspeller — APPROVED** [review]
I wish this could be like go where you don't have to think about unused stuff. It will just delete it for you :)

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Comment by hmhealey** [comment]
Of the 2 failures, one doesn't repro for me locally and I can't even get the other to run locally on master, so I think it's just flaky

**Pull request merged**
