### PR TITLE
[MM-56512] Impossible to set a custom reminder on the same day of following months

### LINKED ISSUE #25867: Impossible to set a custom reminder on the same day of following months
#### Summary
Impossible to set a custom reminder on the same day of following months.

#### Steps to reproduce
1. Hover some message and click `More` to show the menu
2. Select `Remind` → `Custom`
3. In the `Set a reminder` dialog, set `Date` to the same day of the following months (supposing today is Jan 9, set the date to either Feb 9, Mar 9, ..., or Dec 9)
4. Click `Time` entry. You can see that only the following times are selectable in the popover (supposing it's 10:00 PM, you can only see `10:30 PM`, `11:00 PM`, `11:30 PM`)
5. Choose a time from the popover. You should see `Date` changed to today automatically.
6. Repeating the operation from 3. will result in the same situation, which means you can't set a custom reminder on the same day of following months.

#### Expected behavior
- In the step 4 above, you can see and select any time from 12:00 AM to 11:30 PM
- In the step 5 above, `Date` is not changed unexpectedly and thus you can set a custom reminder on the same day of following months

#### Observed behavior (that appears unintentional)
- In the step 4 above, you can only see and select the following times
- In the step 5 above, `Date` is changed to today unexpectedly, which results you can't set a custom reminder on the same day of following months

Screencast:

https://github.com/mattermost/mattermost/assets/156086581/afd1a3b7-5e47-4ddf-9a0c-e1fe3985a17b

### Platform information
- Mattermost Version: 9.5.0 (Mattermost Community Server)
- OS: macOS Sonoma 14.2.1 (23C71)
- Client: Google Chrome 120.0.6099.199 and Mattermost Desktop App 5.6.0 (commit: 1f6924c)

### PR DESCRIPTION
**Pull request by VishalB98**
**What does this PR do?**
Bug Fix : Let you select the same day for different month without resetting to current day.

**Ticket Link**
Fixes #25867 
JIRA https://mattermost.atlassian.net/browse/MM-56512
```release-note
NONE
```

https://github.com/mattermost/mattermost/assets/72154969/a3ac42e2-47d9-4929-ac51-6f51e212871a

### CODE REVIEW

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
How does it handle the case where the date is not available in the next month. Lets say you selected 31 jan and then move to feb which doesnt have 31st

**Comment by VishalB98** [comment]
> How does it handle the case where the date is not available in the next month. Lets say you selected 31 jan and then move to feb which doesnt have 31st

Thanks for the review @M-ZubairAhmed ,
The resolved issue related to #25867 selecting the same date of subsequent months when the user is initially on today's date, for example, January 14th. Previously, when choosing the same date in other months, such as February 14th, March 14th, or April 14th, the time slots available were restricted to the current date and time.

The issue has been fixed by implementing a check to verify if the selected date matches the current date. Now, when selecting a date like February 14th, the time slots appropriately consider the chosen date rather than defaulting to the current date and time.

Additionally, I ensured that the datepicker does not allow the selection of dates that are not available in the specific month. For instance, if a user attempts to select February 31st, which is not a valid date, it won't be selectable in the datepicker.

Please review the changes @M-ZubairAhmed @calebroseland , and let me know if there are any further considerations or if anything needs clarification. Thank you!

**Review by M-ZubairAhmed — APPROVED** [review]
Thanks it fixes the underlying issue

**Review by yasserfaraazkhan — APPROVED** [review]

**Review by calebroseland — APPROVED** [review]

**Pull request merged**
