### PR TITLE
Fix MM-54027

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Fix MM-54027

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-54027

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by esarafianou — APPROVED** [review]
LGTM. Can we also add a test for it?

**Review by marianunez — APPROVED** [review]
LGTM - pending unit test as requested. Thanks @larkox!

**Comment by larkox** [comment]
@esarafianou tests added

**Comment by larkox** [comment]
@esarafianou Should this go through QA review, or are we fine with your review?

**Comment by esarafianou** [comment]
I haven't QAed it myself. I usually do that in the cloud and self-hosted releases. Let me know if you'd like me to do it now.

**Review by yasserfaraazkhan — APPROVED** [review]
Tested this locally! User is not able to see the Prema-link from archived channel if the 'Allow users to view archived channels' is false

**Pull request merged**
