### PR TITLE
[MM-59335] Migrate tooltip of "components/widgets/public-private-selector/public-private-selector.tsx" to WithTooltip

### LINKED ISSUE #27557: Migrate tooltips of "components/widgets/public-private-selector/public-private-selector.tsx" to WithTooltip
The purpose of this ticket is to eliminate the usages of OverlayTrigger of “components/overlay_trigger” and Tooltip of “components/tooltip” in the file `components/widgets/public-private-selector/public-private-selector.tsx`. These should be replaced with the WithTooltip component from “components/with_tooltip”. For reference, please follow this PR https://github.com/mattermost/mattermost/pull/27145

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-59335

### PR DESCRIPTION
**Pull request by ZubairImtiaz3**
#### Summary
The changes ensure that the tooltip in "components/widgets/public-private-selector/public-private-selector.tsx" now utilizes the WithTooltip component, replacing the previous usage of OverlayTrigger and Tooltip.

#### Ticket Link
Fixes #27557
Jira: [MM-59335]( https://mattermost.atlassian.net/browse/MM-59335)

#### Screenshot
<a href="https://ibb.co/jT2kG0n">Screenshot-2024-07-18-022635</a>

#### This Tooltip text is a testing placeholder text.

The PublicPrivateSelector component is only used in the "new_channel_modal.tsx" file (line 276). The tooltip prop for the buttons within PublicPrivateSelector is optional, and currently, no tooltip text is being passed to the component means the tooltip is not actively used.

I temporarily passed placeholder text to ensure that the migration to the WithToolTip component works correctly.

#### Release Note

```release-note
NONE
```

[MM-59335]: https://mattermost.atlassian.net/browse/MM-59335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by yasserfaraazkhan — CHANGES_REQUESTED** [review]
@ZubairImtiaz3 @M-ZubairAhmed 
the tooltip isnt showing up on the spinwick instance, can you check once?

**Comment by ZubairImtiaz3** [comment]
> @ZubairImtiaz3 @M-ZubairAhmed the tooltip isnt showing up on the spinwick instance, can you check once?

@yasserfaraazkhan The tooltip text in the images I've attached is just a placeholder for testing purposes, as mentioned in the PR description. It is not visible in the SpinWick instance since it's not actively used in the current setup.

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
