### PR TITLE
[MM-55629] SystemConsole: Unable to make HTTP request to get SAML metadata

### PR DESCRIPTION
**Pull request by vish9812**
#### Summary

Current system is stuck in a cyclic dependency to make the SAML metadata fetch request and saving the config.

This allows to fetch the metadata without a need of a saved config state.

For reference, previous PR which may have introduced this issue:
JIRA - https://mattermost.atlassian.net/browse/MM-42316
PR - https://github.com/mattermost/mattermost-webapp/pull/9950

#### Ticket Link

JIRA - https://mattermost.atlassian.net/browse/MM-55629

#### Release Note

```release-note
Resolved issue preventing retrieval of SAML metadata.
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by BenCookie95 — APPROVED** [review]

**Comment by vish9812** [comment]
@DHaussermann Please review this.

**Comment by vish9812** [comment]
@DHaussermann a gentle reminder on this one.

**Comment by DHaussermann** [comment]
Hi @vish9812,
Sorry for the delay. I'm blocked on this I think. The Okta instance we use to test SAML does not make use of `IdpMetadataURL` as far as I can tell. 

Can you please help with test setup for this?
1. It seems like this is not testable without a **valid** value in `IdpMetadataURL` is this correct?
2. Can you provide any other suggestions for how to setup a test without using out Okta test instance?

**Comment by vish9812** [comment]
@DHaussermann Unfortunately, I'm not sure either how it can be tested.
To test it myself I had to set up Keycloak with my local MM instance.

@BenCookie95 Do you know, if it's testable in any way with our cloud-test instances?

**Comment by DHaussermann** [comment]
Using the tool provided here https://github.com/coltoneshaw/CS-Repro-Mattermost I was able to use the open SAML included which make use of the SAML metadata. I could then use the latest commit from this PR to test the change.

Huge thanks @coltoneshaw for putting this together. It was extremely useful.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Confirmed with this change I am able to use the UI to retrieve the metada 
image
- This **now** works when SAML is enabled and the page is an unsaved state. 
- Briefly regression tested other CRUD operations on the SAML config page
- No issues found

LGTM!

Sorry for the delay on this @vish9812. Please merge when you have a chance.

**Pull request merged**
