### PR TITLE
Refactor server runJobs function.

### PR DESCRIPTION
**Pull request by dkkb**
#### Summary

We can move below function into `runJobs` to make it clear.
```
s.Go(func() {
	appInstance := New(ServerConnector(s.Channels()))
	s.runLicenseExpirationCheckJob()
	runDNDStatusExpireJob(appInstance)
	runPostReminderJob(appInstance)
})
```

#### Ticket Link

N/A
#### Screenshots

N/A
#### Release Note
N/A

```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]

**Review by streamer45 — APPROVED** [review]
Thanks @dkkb , looks cleaner indeed :+1: 

@isacikgoz It feels like this code may benefit from a deeper review at least to have a good understanding of any inter dependencies between these jobs and also figure out what really needs to run asynchronously. Thoughts?

**Comment by agnivade** [comment]
@isacikgoz @streamer45 - Is there anything blocking this PR from merging?

**Comment by isacikgoz** [comment]
@agnivade I don't think so, merging.

**Pull request merged**
