### PR TITLE
Cypress/E2E: Upgrade Cypress to 13.6.2 and its dependencies

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
- Upgraded Cypress to 13.6.2 and its dependencies

#### Ticket Link
none

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
Most of the upgrades are of minor/patch updates except for following major updates
- chai
- knex
- mime

Assuming these didnt have had any breaking version changes

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
