### PR TITLE
MM-54238 Add WebSocket broadcast hook and don't broadcast when other users were mentioned (8.1)

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
This is a backport of https://github.com/mattermost/mattermost/pull/24641.

The reason this is being manually cherry-picked is because:
1. There was a git conflict with some import statements in one file
2. After cherry-picking, I found out that I was using a newer utility function. It was added in https://github.com/mattermost/mattermost/pull/24262, but since that PR includes more changes to use that function everywhere, I manually copied it over instead of cherry-picking the whole thing. 

Outside of those two things, everything else is as it was on the original PR.

#### Ticket Link
MM-54328

#### Release Note
```release-note
Added new way to modify WebSocket messages sent to individual connections
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
Ideally the first commit hash should be [ef66f7b](https://github.com/mattermost/mattermost/commit/ef66f7beabb2429ef714720dee12d11847684204) right?

**Comment by hmhealey** [comment]
> Ideally the first commit hash should be [ef66f7b](https://github.com/mattermost/mattermost/commit/ef66f7beabb2429ef714720dee12d11847684204) right?

It changed because I had to resolve a git conflict when I cherry-picked it onto release-8.1

**Review by yasserfaraazkhan — APPROVED** [review]
just did a smoke test with 4 users joining call in channel, gm, posts, mentioning users in call threads.
working as expected.

**Pull request merged**
