### PR TITLE
[MM-61439] New Users: Change default setting for mobile push notifications to 'online, away, or offline'

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
Changed the default value of user's notify prop's push_status to "online" from "offline" for all new users. In UI, all the new users will have the following option as below:
CleanShot 2024-11-06 at 12 59 23@2x

#### Ticket Link
Jira https://mattermost.atlassian.net/browse/MM-61439

#### Screenshots

None

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by cpoile — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
Verified same settings are shown in the mobile.
User revieves the notification on mobile device.

**Pull request merged**
