### PR TITLE
Revert "Prepackage calls v1.3.1 in 10.3"

### PR DESCRIPTION
**Pull request by amyblais**
Reverts mattermost/mattermost#29462

### CODE REVIEW

**Comment by amyblais** [comment]
@agnivade Would you be able to help manually re-trigger the failing test here?

**Comment by agnivade** [comment]
It's already running. Let's check after it finishes.

**Comment by amyblais** [comment]
Thank you! Just need one approval to be able to merge.

**Review by agnivade — APPROVED** [review]

**Pull request merged**
