### PR TITLE
[MM-54512] Fix style regression for add channel member modal

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
https://mattermost.atlassian.net/browse/MM-54512

#### Release Note

```release-note
None
```

### CODE REVIEW

**Review by JulienTant — APPROVED** [review]

**Review by pvev — APPROVED** [review]
LGTM! thanks @BenCookie95  :shipit: ... side note: this just reminded me why I don't get that excited about styled components 😢

**Comment by DHaussermann** [comment]
@BenCookie95 no functional testing would be needed on this.
Please merge when you have a chnace.

**Pull request merged**
