### PR TITLE
E2E Tests: unify compose files, support Opensearch

### PR DESCRIPTION
**Pull request by mvitale1989**
#### Summary

Add support for Opensearch, and unify docker-compose files. I will follow this up with a PR to add support for the `MM_SERVICE_OVERRIDES` argument to the E2E testing slash command (e.g. `/e2e-test MM_SERVICE_OVERRIDES=-elasticsearch,+opensearch`).

- Delete the `gitlab-dc.*` files that were used for E2E tests: we use the same docker-compose as the `make run` used by developers now
- Support Opensearch for automated E2E test runs. Preliminary support for Redis
- Add workflow variable: `MM_SERVICE_OVERRIDES` to let you use `-elasticsearch,+opensearch`)
- Add workflow variables: `RUN_CYPRESS` and `RUN_PLAYWRIGHT` booleans, to let you selectively run cypress/playwright/both/neither. Also adapt the feedback comments posted back to the PR, accordingly.
- Better description for E2E Full Run workflow variables
- Fix some E2E testcases

#### Ticket Link

https://mattermost.atlassian.net/browse/CLD-8147

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by mvitale1989** [comment]
Skipping either kind of test works fine, testing the actual runs now

**Review by toninis — APPROVED** [review]
Amazing progress mate 🚀

**Comment by saturninoabril** [comment]
This is awesome, thanks @mvitale1989!

**Comment by streamer45** [comment]
@mvitale1989 FYI, this PR has caused Calls e2e tests pipeline to fail since we relied on `server/build/gitlab-dc.postgres.yml` being there.

https://github.com/mattermost/mattermost-plugin-calls/blob/1720eb5ab348bb358869369045b194f8c461a84b/.github/workflows/e2e.yml#L170-L171

It's not a big deal as we can create a copy on our side, but if anything is a sign that more unification work across core plugins would be valuable.

**Comment by mvitale1989** [comment]
> @mvitale1989 FYI, this PR has caused Calls e2e tests pipeline to fail since we relied on `server/build/gitlab-dc.postgres.yml` being there.
> 
> https://github.com/mattermost/mattermost-plugin-calls/blob/1720eb5ab348bb358869369045b194f8c461a84b/.github/workflows/e2e.yml#L170-L171
> 
> It's not a big deal as we can create a copy on our side, but if anything is a sign that more unification work across core plugins would be valuable.

Ah, sorry for the disruption Claudio, I assumed the monorepo E2E tests were the only users of that file.
I agree that more unification would be good, the files I removed differed only a bit from `server/build/docker-compose.common.yml`, which is also why I removed them. I'll add a ticket on our backlog to look into the best approach here.

**Pull request merged**
