### PR TITLE
[MM-57877] Fix issue #26841

### PR DESCRIPTION
**Pull request by MeHow25**
#### Summary
Display a clear and user-friendly message when the user tries to create a new team on an already existing URL.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/26841
Jira https://mattermost.atlassian.net/browse/MM-57877

#### Screenshots
|  before  |  after  |
|----|----|
| image| image|

#### Release Note
```release-note
Fix GH-26841
```

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM :+1: 

Thanks for the contribution

**Review by hmhealey — APPROVED** [review]
Thanks for the PR! This looks good to me. I was expecting this to be changed on the client-side because I thought the error was coming from a different method, but it makes more sense to me to handle it this way

**Review by yasserfaraazkhan — CHANGES_REQUESTED** [review]
@hmhealey 
I'm seeign this error message `This URL is taken or unavailable. Please try another.` when I try to create a team with same url.

image

**Comment by MeHow25** [comment]
@yasserfaraazkhan Have you used the steps from the link below to reproduce this bug?

https://github.com/mattermost/mattermost/issues/26841#issuecomment-2077841818
> 1. Create User No. 1.
> 2. Create a team with the URL “/lorem” using that user, but do not invite anyone.
> 3. Create User No. 2.
> 4. As User No. 2, attempt to create a new team with the same URL “/lorem.”
> 5. An error message stating “Must call update for existing team” will be displayed.

**Review by yasserfaraazkhan — APPROVED** [review]
@MeHow25 
thank you! the error message is showing up.

image

**Comment by MeHow25** [comment]
@hmhealey Hi, I see that the "Enterprise CI/tests" is failing, but I don't have access there. Should I fix something?

**Comment by hmhealey** [comment]
It's failing because `en.json` is out of order because of the new string you added, but since we missed it during reviews, I should be able to just fix it now.

Thanks again for the PR for this!

**Pull request merged**
