### PR TITLE
Misc SuggestionBox cleanup

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
While working on https://github.com/mattermost/mattermost/pull/26857, I ended up making a bunch of changes to try to make the component easier to reason about. There's still some more coming like trying to migrate `SuggestionBox` to TypeScript, but here's some fairly small things to clean up. They are:

1. Removing a fix for mobile web on iOS. ~~I tested Community on my phone, and the logic that that code is supposed to fix is broken already.~~ **Edit:** Actually, it seemingly works now on both Community and on the local branch. I'm not sure what I did before to think it was broken.
2. I removed an unneeded `setTimeout` that I thought was causing `this.pretext` to get out of sync and cause the bug from the other PR.
3. This one is a bigger change, but it's one that we could've done better to begin with. Instead of whatever weird state the component is in immediately after switching channels, the component is now remounted completely when switching channels. There doesn't seem to be any effect on the user by doing this.
4. We never changed the `suggestionDate` prop, so I just replaced it with its default value.
5. The `onSearchTypeChanged` prop was never used

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by harshilsharma63 — APPROVED** [review]

**Review by larkox — APPROVED** [review]

**Comment by hmhealey** [comment]
Of the E2E test failures, I think `tests/integration/channels/messaging/autocomplete_shown_each_channel_spec.js` is the only that is caused by this PR. The rest of those that I tested locally seem to either pass for me or to be existing issues that aren't related to these changes

**Comment by larkox** [comment]
@hmhealey heads up there is a failing test.

**Comment by hmhealey** [comment]
I added "Awaiting Submitter Action" because there's something that seems to be weird here about how the autocomplete behaves when the textbox is focused. Most of the logic in here wants the autocomplete to not appear until the user starts typing, even if there's a draft in the textbox, but `autocomplete_shown_each_channel_spec.js` wants the autocomplete to appear as soon as the textbox is focused on channel change.

From what I can tell, the autocomplete wouldn't appear any other time that the textbox is focused, until https://github.com/mattermost/mattermost/pull/25639 would makes it appear `onMouseUp`. Since I removed that in https://github.com/mattermost/mattermost/pull/26857, these are now back to behaving inconsistently.

I've gone down too much of a rabbit hole here since I think this goes back to https://github.com/mattermost/mattermost-webapp/pull/2155 being based on an assumption that the autocomplete should appear on channel change, so I'm going to pause work on finishing this for a bit

**Pull request closed without merging**
