### PR TITLE
[MM-60826] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/quick_switch_modal/quick_switch_modal.tsx' with FormattedMessage

### PR DESCRIPTION
**Pull request by gvarma28**
#### Summary

Replace FormattedMarkdownMessage in 'webapp/channels/src/components/quick_switch_modal/quick_switch_modal.tsx' with FormattedMessage

#### Ticket Link
Fixes: #28500
Jira [MM-60826](https://mattermost.atlassian.net/browse/MM-60826)

#### Release Note

```release-note
NONE
```

[MM-60826]: https://mattermost.atlassian.net/browse/MM-60826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by yasserfaraazkhan — APPROVED** [review]
image

**Review by rahimrahman — APPROVED** [review]
Understood changes in en.json.  Thanks @M-ZubairAhmed

**Pull request merged**
