### PR TITLE
[MM-57298] Fix context cancellation for integration requests

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
https://github.com/mattermost/mattermost/pull/23805 did introduce a regression, which caused interactive messages to no longer function. The root cause is that `DoActionRequest` cancels the `context.Context` before the caller reads the response body.

Please note that I was unable to reproduce [the reported bug ](https://forum.mattermost.com/t/interactive-mesasage-update-does-not-work-since-last-mattermost-upgrades/18167/7) via a custom integration. I was also unable to reproduce the race condition via a go test. Hence, this PR doesn't contain a test. I would love to hear ideas on how to trigger the bug in a test.

But it's clear from various online sources that an `http.Request` should not get cancelled before reading `http.Response.Body`.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-57298

#### Release Note
```release-note
Fix context cancellation for integration requests
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]

**Review by mickmister — APPROVED** [review]

**Comment by DHaussermann** [comment]
@hanzei or @mickmister any thoughts on testing this? Based on what Ben put in the summary is there anything I can do beound regression testing and spot checking?

**Comment by hanzei** [comment]
@DHaussermann I was not able to find a way to reproduce the issue and hence I think we are limited to regression testing.

**Comment by DHaussermann** [comment]
@hanzei I have performed the regression testing on the integrations timeout and it still functions as expected. 

For this PR, does it seem like we can be reasonably confident the issue has been solved?
I'm curious on if getting an advanced built to a affected customer may be an option here.

**Comment by hanzei** [comment]
I've reached out to the community member who reported the bug and asked if they are open to testing it: https://forum.mattermost.com/t/interactive-mesasage-update-does-not-work-since-last-mattermost-upgrades/18167/9?u=hanzei

**Comment by hanzei** [comment]
@DHaussermann The community member confirmed that the fix works for them (https://forum.mattermost.com/t/interactive-mesasage-update-does-not-work-since-last-mattermost-upgrades/18167/12?u=hanzei). I think we are good to merge the PR.

**Review by DHaussermann — APPROVED** [review]
Tested and passed. 
This bug could not be reproduced but I have regression tested the functionality of the original PR with integration response timeouts.
No issues found.

LGTM!

**Comment by hanzei** [comment]
@amyblais I wonder if we want to cherry-pick this PR into v9.5. It's fixes a regression introduced in v9.5 via https://github.com/mattermost/mattermost/pull/23805. What do you think about backporting the fix?

**Comment by vish9812** [comment]
@hanzei Can this issue be backported to version 9.7.x as well?
cc: @amyblais

**Comment by vish9812** [comment]
@amyblais This fix will be available in v9.7.4?

**Comment by amyblais** [comment]
Yes, v9.7.4 and v9.8.0.

**Comment by amyblais** [comment]
> And this v9.7.4 will release along with v9.8.0 on 16th?

v9.7.4 doesn't have a date yet, but I'll keep you in the loop.

**Pull request merged**
