### PR TITLE
[MM-47055] Migrate "components/advanced_create_post/advanced_create_post.test.jsx" to Typescript

### PR DESCRIPTION
**Pull request by Sudhanva-Nadiger**
- Migrate "components/advanced_create_post/advanced_create_post.test.jsx" to Typescript"
- fixes: #21139

#### Summary

The testfile for `components/advanced_create_post/advanced_create_post.tsx` was in javascript. 
So migrated `components/advanced_create_post/advanced_create_post.test.jsx` to `components/advanced_create_post/advanced_create_post.test.tsx`

#### Ticket Link

JIRA: https://mattermost.atlassian.net/browse/MM-47055

#### Release Note

```release-note
None
```

### CODE REVIEW

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
Can we remove `any` from this PR and be specific

**Comment by Sudhanva-Nadiger** [comment]
hi @M-ZubairAhmed ! I have removed the any type wherever i got to know what are the types are !

and one more doubt ! 
image
The property `isMarkeDownEnabled`  is not present in the props of `advanced_create_post`! i dono why its being used

**Comment by Sudhanva-Nadiger** [comment]
making it protected does not work !

**Comment by Sudhanva-Nadiger** [comment]
@M-ZubairAhmed any other way to resolve this?

**Comment by M-ZubairAhmed** [comment]
> @M-ZubairAhmed any other way to resolve this?
> 
> Wherever there is usage of ref in test file its been used with `any` type ! so should i do the same?

Yes i think this is one of the those exception case,

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
Lets add that exception case for `any`

**Comment by M-ZubairAhmed** [comment]
> Lets add that exception case for `any`

@Sudhanva-Nadiger i meant lets add `any` in only those test cases where the refs are being used for others we can leave the type assertion which you previously wrote as is

**Review by M-ZubairAhmed — APPROVED** [review]
Its looks good, thank you for this change 🎉

**Comment by M-ZubairAhmed** [comment]
@Sudhanva-Nadiger can you please check the CI failures

**Comment by M-ZubairAhmed** [comment]
@devinbinnie gentle ping on this one

**Comment by Sudhanva-Nadiger** [comment]
All test-ci passed 🎉  
image

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @Sudhanva-Nadiger!

**Comment by Sudhanva-Nadiger** [comment]
Thanks @M-ZubairAhmed and @devinbinnie !

**Pull request merged**
