### PR TITLE
Update schemes.yaml

### PR DESCRIPTION
**Pull request by ewwollesen**
Changed required field from `name` to `dipslay_name`.

The docs at api.mattermost.com incorrectly listed `name` as a required field when `display_name` was the actual require field. I also kept `name` in the scheme object section because even though it's not required, leaving it out will cause `name` to be created as a random string similar to the `Id` value.

### CODE REVIEW

**Comment by ewwollesen** [comment]
@hanzei Here is the PR we were discussing the other day.

**Review by hanzei — APPROVED** [review]

**Comment by hanzei** [comment]
Thanks for fixing the docs @ewwollesen :tada:

**Review by cwarnermm — APPROVED** [review]
Thanks, @ewwollesen!!

**Comment by hanzei** [comment]
@ewwollesen Feel free to merge the PR at your convenience.

**Comment by ewwollesen** [comment]
> @ewwollesen Feel free to merge the PR at your convenience.

@hanzei I don't believe I have permission to merge. At least I don't see a way to do it.

**Pull request merged**
