### PR TITLE
[MM-61441] Don't overwrite plugin secret settings with fake values

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
https://github.com/mattermost/mattermost/pull/27986 introduced the capabilities for plugins to mark settings as secrets, obfuscating them in the system console. Due to a bug, the obfuscated values did get written to the config store, making the plugin unusable.

Please note that this bug only manifests if a plugin that makes use of the new `secret` settings is installed. No such plugin has been officially released.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-61441

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]

**Comment by hanzei** [comment]
@Kshitij-Katiyar @raghavaggarwal2308 Gentle reminder to review the PR :wink:

**Review by raghavaggarwal2308 — APPROVED** [review]
LGTM 👍🏽

**Comment by hanzei** [comment]
@AayushChaudhary0001 can you please test this PR given that you also tested https://github.com/mattermost/mattermost/pull/27986? Thanks! I would like to include the change in v10.3.0.  For that, it need to get merged by next Tuesday.

**Comment by AayushChaudhary0001** [comment]
@hanzei Sure, will do this today.

**Review by AayushChaudhary0001 — APPROVED** [review]
I have tested this PR and the OAuth flow works fine and the user is able to connect and disconnect even after the configs are changed. The testing is done for Github plugin and I am assuming that the change will work the same for all the plugins, LGTM. Approved.

**Comment by hanzei** [comment]
@amyblais I wonder if we should cherry-pick this change for v10.1 and v10.2. The bug is nasty but currently only manifests with unrelated plugins.

> Please note that this bug only manifests if a plugin that makes use of the new secret settings is installed. No such plugin has been officially released.

Do you think it's worth patching these two releases?

**Pull request merged**
