### PR TITLE
Removed blank space in sidebar display in compact view mode

### PR DESCRIPTION
**Pull request by ShlokJswl**
#### Summary
In compact view mode, when "Recent mentions" or "Saved posts" are displayed in the sidebar, there is a blank space on the left side.

**Steps to reproduce**

- Login to Mattermost 7.10.0
- Set "Settings-Display-Message Display" to "Compact".
- Display "Recent mentions" or "Saved posts".

**Expected behaviour**

As with threads, no unnecessary blank space should be there

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/23039

#### Screenshots
image

#### Release Note
```
NONE
```

### CODE REVIEW

**Comment by ShlokJswl** [comment]
> @ShlokJswl please sign the CLA :)

Hello I have signed the CLA. Can you proceed with the review process now?

**Comment by ShlokJswl** [comment]
Dear Reviewers @koox00 @AshishDhama and @M-ZubairAhmed, I have done this as an evaluative assignment for a course in my college. Would it be possible for you to review this before tomorrow, as my marks depend on it?

**Review by koox00 — CHANGES_REQUESTED** [review]
@ShlokJswl thanks for contributing! 
While this seems to fix the issue, it's creating another in center channel.
We need the 77px on post's just not when those posts appear in a thread.

Can you see if you can apply the `post--thread` `className` in the post component for the case of pinned/mentions/search etc, as well?
I think that would be `Locations.SEARCH`

**Comment by ShlokJswl** [comment]
> @ShlokJswl thanks for contributing! While this seems to fix the issue, it's creating another in center channel. We need the 77px on post's just not when those posts appear in a thread.
> 
> Can you see if you can apply the `post--thread` `className` in the post component for the case of pinned/mentions/search etc (I think that would be `Locations.SEARCH`), as well?

Hi @koox00 I have added a change on line no. 267 and that has fixed the issue you pointed out could you please review it once more?

**Comment by ShlokJswl** [comment]
> @ShlokJswl I don't see any new commits :/

WhatsApp Image 2023-04-26 at 7 27 55 PM

these are the changes made by me

**Comment by koox00** [comment]
> > @ShlokJswl I don't see any new commits :/
> 
> WhatsApp Image 2023-04-26 at 7 27 55 PM
> 
> these are the changes made by me

This though would apply that class to all posts, not just rhs ones.
I think it would be better to do something like:

```ts
'post--thread': props.location === Locations.RHS_COMMENT || props.location === Locations.RHS_ROOT || props.location ==== Locations.SEARCH,
```

or better, since we have `isRHS` var in the same file you could:

```ts
'post--thread': isRHS,
```

haven't tested the code.

**Comment by ShlokJswl** [comment]
> > > @ShlokJswl I don't see any new commits :/
> > 
> > 
> > WhatsApp Image 2023-04-26 at 7 27 55 PM
> > these are the changes made by me
> 
> This though would apply that class to all posts, not just rhs ones. I think it would be better to do something like:
> 
> ```ts
> 'post--thread': props.location === Locations.RHS_COMMENT || props.location === Locations.RHS_ROOT || props.location ==== Locations.SEARCH,
> ```
> 
> or better, since we have `isRHS` var in the same file you could:
> 
> ```ts
> 'post--thread': isRHS,
> ```
> 
> haven't tested the code.

I made the changes as per your suggestion and it is working. I'll push the changes right now.

**Comment by ShlokJswl** [comment]
@koox00 I have pushed the changes based on the above feedback. Thanks.

**Review by koox00 — APPROVED** [review]
Thanks @ShlokJswl seems to work as intended now!

**Comment by ShlokJswl** [comment]
Sorry I clicked on re-request review by mistake.

**Review by koox00 — APPROVED** [review]

**Review by AshishDhama — APPROVED** [review]

**Comment by ShlokJswl** [comment]
Hi @furqanmlk could you please review this ?

**Comment by ShlokJswl** [comment]
Hi @furqanmlk, if you could take some time to look at this, it would be of great help.

**Review by furqanmlk — APPROVED** [review]
Working as expected

Before
image


After

image

**Comment by ShlokJswl** [comment]
how can this be merged?

**Comment by hanzei** [comment]
@lindalumitchell Would you mind giving this a review?

**Comment by lindalumitchell** [comment]
Apologies for the delay; somehow just seeing this now. Will try to update and run e2es and review.

**Comment by lindalumitchell** [comment]
Also, I noticed that Malik already tested this and validated the fix. I'll still try to run e2es if I can, but it looks like the specific fix has already been verified.

**Review by lindalumitchell — APPROVED** [review]
Again, apologies for all of the delays. I'm not sure how this kept falling out of my workflow. No issues found in the e2es. 👍

**Review by hanzei — APPROVED** [review]

**Pull request merged**
