### PR TITLE
[MM-56572] Preview doesn't work when editing a channel header

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-56572

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]

**Review by marianunez — COMMENTED** [review]
Is there a setting to be able to view the preview option in the edit channel header? I don't see it in the test server. Is this something we need to take into account in the cases for the unit tests so the snapshot would've catched this bug?

**Review by marianunez — APPROVED** [review]

**Comment by marianunez** [comment]
> No it is CSS change it cannot be captured in the snapshot testing

Ah thanks for clarifying. This is then probably a candidate for a E2E test then to check the Preview link is shown. 
 
> > is there a setting to be able to view the preview option in the edit channel header
> 
> Yes i have enabled it

Curious, what is the setting?

**Review by yasserfaraazkhan — CHANGES_REQUESTED** [review]
@johndavidlugtu  @M-ZubairAhmed @marianunez 
if Channel header is Closed or cancelled when it's in Preview mode. Re-opening channel header to Edit, user will have again click on `Edit header`. It seems redundant given user selects `Edit Channel Header` option from channel menu. Just checking if this is expected flow.

image

image


https://github.com/mattermost/mattermost/assets/15979783/480b0fa5-7409-4ea4-8327-529f59d33bb9


created a task for e2e: https://mattermost.atlassian.net/browse/MM-56820

**Comment by M-ZubairAhmed** [comment]
> @johndavidlugtu @M-ZubairAhmed @marianunez if Channel header is Closed or cancelled when it's in Preview mode. Re-opening channel header to Edit, user will have again click on `Edit header`. It seems redundant given user selects `Edit Channel Header` option from channel menu. Just checking if this is expected flow.
> image image
> Screen.Recording.2024-02-12.at.12.44.34.PM.mov
> 
> created a task for e2e: https://mattermost.atlassian.net/browse/MM-56820

You are correct @yasserfaraazkhan the text over there seems to be redundant since the user is aware that they are in the edit channel modal. I have replaced it with just 'Edit'

**Review by yasserfaraazkhan — APPROVED** [review]
image

🎉

**Pull request merged**
