### PR TITLE
Removed Post Priority feature flag

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Remove the Post Priority feature flag. This is no longer needed as it has been enabled for a while and it now relies on the ServiceSettings.PostPriority config setting

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48931

#### Related PRs
https://github.com/mattermost/mattermost-mobile/pull/7433

#### Release Note

```release-note
None
```

### CODE REVIEW

**Review by vish9812 — APPROVED** [review]

**Comment by yasserfaraazkhan** [comment]
Hi @marianunez ,
the feature is working. Able to post the DM, channel, GM

Screenshot 2023-06-14 at 9 05 28 PM

the `Request acknowledge` section was missing, would this be another feature flag ?

Screenshot 2023-06-14 at 9 07 23 PM

**Comment by marianunez** [comment]
> Hi @marianunez , the feature is working. Able to post the DM, channel, GM
> 
> the `Request acknowledge` section was missing, would this be another feature flag ?
> 

Thanks @yasserfaraazkhan! It seems Post Acknowledgement is a Professional feature so you should be able to see it if you apply a license or start a trial. 

We also want to make sure the feature is not available if the it's disabled in the System Console > Posts section:
Screen Shot 2023-06-14 at 11 53 23 AM

**Review by yasserfaraazkhan — APPROVED** [review]
thank you Maria, changes are working as expected.

Screenshot 2023-06-14 at 9 40 58 PM

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Comment by marianunez** [comment]
> @marianunez Do we also need to do changes in mobile?

Yes, great catch! We do need it as the feature is available in mobile. I'll make a PR for that and wait to merge them together.

**Pull request merged**
