### PR TITLE
feat: Decouple reporting from actual testing

### PR DESCRIPTION
**Pull request by toninis**
#### Summary

Completely decouple reporting from CI since it needs elevated permissions.  
Use webhook events to trigger the reporting pipeline automatically with the required permissions .  

#### Ticket Link

https://mattermost.atlassian.net/browse/CLD-8698

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by saturninoabril — APPROVED** [review]
Thanks @toninis!

**Comment by saturninoabril** [comment]
Feedback to E2E test requirement: Changes like this shouldn't require it. Maybe limit to server/webapp and E2E code changes only?

**Comment by mvitale1989** [comment]
> Feedback to E2E test requirement: Changes like this shouldn't require it. Maybe limit to server/webapp and E2E code changes only?

Good point Saturn, thanks for the feedback. We have an opportunity for automation here. I have created a ticket to tackle automated E2E overriding for this kind of PRs: https://mattermost.atlassian.net/browse/CLD-8705

**Comment by toninis** [comment]
cc: @agnivade This change will probably also fix the issue were results were published under random status checks .

**Review by lieut-data — APPROVED** [review]

**Review by agnivade — APPROVED** [review]
I don't have detailed knowledge on this. But the idea sounds good. This is just a stamp approval :)

**Pull request merged**
