### PR TITLE
Add E2E retries support for Automation Dashboard

### PR DESCRIPTION
**Pull request by mvitale1989**
#### Summary

Fix E2E results reporting to the Automation Dashboard: send result of last attempt, instead of the first.

Additionally:
- Finally tracked a nasty bug down: demoted `password_settings_spec.js`, which was sneakily causing failures in _other tests_ that ran afterwards on the same worker (possibly a restricted system admin cannot un-restrict themselves)
  * Affected [other PRs](https://github.com/mattermost/mattermost/pull/29017#issuecomment-2488426209) and [master branch](https://automation-dashboard.vercel.app/cycles/e6a65cce-d5ac-491f-a949-3ef8f11ecf24)
- A couple more unstable test demotions

#### Ticket Link

https://mattermost.atlassian.net/browse/CLD-8301

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by mvitale1989** [comment]
Enabling Firefox/ipad Playwright runs is not trivial, tests are failing (1 for ipad, many for Firefox): https://github.com/mattermost/mattermost/actions/runs/11918887016/job/33217463597
I'll open a separate ticket for that

**Review by saturninoabril — APPROVED** [review]
Good catch, thanks Mario!

**Pull request merged**
