### PR TITLE
[MM-32406] Introduce trace logging level for LDAP messages

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
See https://github.com/mattermost/enterprise/pull/1577

Based on https://github.com/mattermost/mattermost/pull/24873

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-55125

#### Release Note
```release-note
Introduce trace logging level for LDAP messages
```

### CODE REVIEW

**Review by wiggin77 — COMMENTED** [review]
LGTM :+1:

**Review by wiggin77 — APPROVED** [review]

**Comment by hanzei** [comment]
Rebased on top of https://github.com/mattermost/mattermost/pull/24873

**Review by DHaussermann — APPROVED** [review]
Tested and passed
Followed steps provided by Ben to have LDAP logs written to a file in the file system
Performed LDAP sync new LDAP user login etc...

I can see trace logs such as `LDAPTrace [2023-11-02 12:41:26.296 -04:00] Closing network connection path=/api/v4/users/login ...` now being written to the file.

LGTM!

**Comment by DHaussermann** [comment]
Checked with @hanzei `Do Not Merge/Awaiting PR` label can be removed as dependent PRs are now merged.

**Pull request merged**
