### PR TITLE
Update minimum supported Safari and Firefox versions

### PR DESCRIPTION
**Pull request by amyblais**
Harrison requested to bump the versions to use some new accessibility features of the browser.

```release-note
Updated minimum Safari version to 17.4+ and minimum Firefox version to 119+.
```

### CODE REVIEW

**Comment by amyblais** [comment]
@hmhealey What would be the next step to address the failing E2E test?

**Review by larkox — APPROVED** [review]

**Comment by larkox** [comment]
@amyblais It looks like a flaky test. @yasserfaraazkhan Can you confirm it is a flaky test? Should we just re-run the job?

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by yasserfaraazkhan** [comment]
yes, its flaky one.

**Review by hmhealey — APPROVED** [review]
Thanks @amyblais! Do we also need a PR to update https://docs.mattermost.com/install/software-hardware-requirements.html as well?

**Comment by amyblais** [comment]
> Do we also need a PR to update https://docs.mattermost.com/install/software-hardware-requirements.html as well?

Yes, they will be updated once we get closer to v10.5 release.

**Pull request merged**
