### PR TITLE
MM-52174 - Syntax error in tsquery when autocompleting with &

### PR DESCRIPTION
**Pull request by MattSilvaa**
#### Summary

Adds & as one of the characters that must be treated as spaces for fulltext query
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/23723
JIra https://mattermost.atlassian.net/browse/MM-52174
#### Screenshots

[demo.webm](https://github.com/mattermost/mattermost/assets/20505926/f32a94e6-b278-47d1-8bb0-2564584f29c5)

#### Release Note

```
NONE
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]
LGTM, but I wonder if we should somehow fix this at server level, instead of keep adding characters to this list.

**Review by lieut-data — APPROVED** [review]
Thanks, @MattSilvaa!

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by larkox** [comment]
@MattSilvaa Thank you for your contribution!

**Pull request merged**
