### PR TITLE
Add a proper fall back handling when clipboard.writeText() failed

### PR DESCRIPTION
**Pull request by youtsumi**
#### Summary
Fix not to fail a clipboard copy when plain http is being used.

The original code didn't check if clipboard.writeText() was succeeded or not. When clipboard failed to write, the following workaround did not get executed. This PR fixes so that the failure is handled as intended.

#### Ticket Link
None, but being discussed in the community channel: https://community.mattermost.com/core/pl/8pusigqqipncmctzoqecd5chfa

#### Screenshots
None

#### Release Note
```release-note
Added a proper fall back handling when clipboard write failed
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@youtsumi as you mentioned in the comment https://community.mattermost.com/core/pl/ktap9kmj5bga7fb3hmdnw3jmkh this still doesn't solve the problem of invitePeople link, are you looking at other alternatives at the moment?

**Comment by youtsumi** [comment]
Correct.

**Comment by M-ZubairAhmed** [comment]
@youtsumi sure let me know when you find it and we can continue with improvements :)

**Comment by youtsumi** [comment]
This change hasn't been proved to fix the issue. I didn't have an intention to propagate this to the main repository. Sorry for making a trouble...

**Comment by M-ZubairAhmed** [comment]
> This change hasn't been proved to fix the issue. I didn't have an intention to propagate this to the main repository. Sorry for making a trouble...

Sure feel free to close the PR or if you do want want to submit you can keep working on the PR :)

**Pull request closed without merging**
