### PR TITLE
MM-60975 - Message export: Add startTime and endTime to export folder name

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Add the startTime and endTime to export folder name to help sysadmins tell at a glance what time range the export covered.
- Old format: `export/compliance-export-2024-10-17-17h42m`
- New format: `export/compliance-export-2024-10-17-17h42m-172920100000-1729201352588` (for example)
- This was a customer request, and is also implemented on the CLI: https://github.com/mattermost/mattermost-compliance-export/pull/20
- This will require a docs change and notice because it will affect all compliance exports after the feature branch is merged (for next ESR).

cc/ @nab-77 @sadohert @Dbellu23 

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-60975

#### Release Note

Release note will be handled when the feature branch is merged.

```release-note
NONE
```

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]

**Comment by streamer45** [comment]
This is more of a high-level question, but if the purpose is to be human-readable (targeting the sysadmin), how do the raw timestamps help?

**Comment by cpoile** [comment]
@streamer45 This was by request (though we're getting final confirmation so maybe that will change). I'm assuming it's so they can tell the timestamps at a glance without having to go into the directory and look at the first and last batch filenames.

**Comment by streamer45** [comment]
> @streamer45 This was by request (though we're getting final confirmation so maybe that will change). I'm assuming it's so they can tell the timestamps at a glance without having to go into the directory and look at the first and last batch filenames.

Gotcha. My concern is that this change will affect every customer using this feature, not just the one requesting it so I'd like to ensure we are making an optimal decision here. @nab-77 could you provide guidance?

**Comment by streamer45** [comment]
> @streamer45 Tbh, we're changing a lot of things for everyone in this feature branch. I think we have at least 3 paths:
> 
> 1. Present the changes as a fait accompli and provide good documentation and guidance,
> 2. Put user-facing changes behind a setting flag, "NewExportBehavior" or something
> 3. Do interviews and try to get a consensus around what everyone would prefer.
> 
> 1 would be ideal, 2 is doable but will require more dev time, 3 is time-consuming and maybe not worth it, imo.

I'd like to think there's an option where we think about this a bit longer (internally) with the help of UX and Product and come up with either a decision that unix timestamps (in milliseconds) are optimal for this use case or an improved way to solve the real problem (quickly identifying exports?).

**Review by streamer45 — APPROVED** [review]
Approving from a technical perspective not to block this if it's urgent but I think we could use more discussion on the product/UX side.

**Comment by nab-77** [comment]
> I'd like to think there's an option where we think about this a bit longer (internally) with the help of UX and Product and come up with either a decision that unix timestamps (in milliseconds) are optimal for this use case or an improved way to solve the real problem (quickly identifying exports?).

Second this @streamer45. We can review proposed changes with some known users but this will not be 100% coverage. Right now I favour a version of option 2. We should discuss.

**Comment by cpoile** [comment]
For a bit more context -- originally the job output a `jobId.zip`, and the sibling folders (and the folders inside the zip) were simply `startime-endtime`. The customer was using the sibling folders for their analysis, so this keeps the `startTime-endTime` aspect of the folder name that people seemed to be relying on.

**Comment by nab-77** [comment]
@cpoile getting feedback from customers that will utilise the `cli `export tool need to be tracked to ensure our new default folder/file naming has widest adoption. Right now the new proposal aligns with feedback. Thanks.

**Review by nab-77 — APPROVED** [review]
As discussed @cpoile feedback ahead of `10.5` is key here.

**Comment by cpoile** [comment]
@nab-77 What will next steps for gathering feedback be? Who's got responsibility for each step? Just want to make sure we get this assigned now because 10.5 is approaching quick and this feels like it's going to need some lead time. Thanks!

**Pull request merged**
