### PR TITLE
[MM-55086] db/migrations: drop nextsyncat and description columns from SharedChannelsRemotes table.

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
We should remove the unused columns, it already caused a few migration issues for a community member. I couldn't recall the reasoning but I've checked and these fields are also not being used in the model structs.

I think this migration complies with https://developers.mattermost.com/contribute/more-info/server/schema-migration-guide/ as this table is very small.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-55086

#### Release Note

```release-note
NextSyncAt and Description columns are removed from the SharedChannelsRemotes table. Migration impact considered to be minimal considering the possible table size.
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
> I think this migration complies with https://developers.mattermost.com/contribute/more-info/server/schema-migration-guide/ as this table is very small.

Migration looks good. But note that the table size is irrelevant. What we cannot do are blocking migrations. Even if the table had 1 row, we cannot do a blocking migration.

**Review by wiggin77 — APPROVED** [review]
LGTM :+1: 

> it already caused a few migration issues for a community member.

I'm curious what migration issue(s) this caused.  I would think a few unused columns would be innocuous.

**Comment by isacikgoz** [comment]
> I'm curious what migration issue(s) this caused. I would think a few unused columns would be innocuous.

I linked the issue to the ticket but it's a small portion of a long post. In a nutshell, we are not migrating the schema while doing the MySQL to PostgreSQL migration, hence any diff between two schemas throws an error. It was a trivial error though.

**Comment by amyblais** [comment]
@isacikgoz Should this document be filled in for this change https://docs.google.com/document/d/18lD7N32oyMtYjFrJKwsNv8yn6Fe5QtF-eMm8nn0O8tk/edit#heading=h.1ozc9hcotgot?

**Comment by isacikgoz** [comment]
@amyblais this is a non-locking change on unused fields. I think just mentioning in the release notes should be fine.

**Pull request merged**
