### PR TITLE
MM-56892- Update prepackaged calls to v0.25.0

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Prepackage Calls v0.25.0

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-56892

#### Release Note

```release-note
Prepackage Calls version v0.25.0
```

### CODE REVIEW

**Comment by cpoile** [comment]
I'll test manually

**Review by amyblais — APPROVED** [review]

**Review by streamer45 — APPROVED** [review]

**Comment by cpoile** [comment]
Confirmed 0.25.0 installs and works

**Comment by cwarnermm** [comment]
@cpoile - Are there any product or dev documentation updates needed for this PR?

**Comment by cpoile** [comment]
@cwarnermm Nothing specific to this PR, other than the usual that we put for an upgrade to the prepackaged calls (if any?). Thanks.

**Pull request merged**
