### PR TITLE
Excludes remote channels from channel search

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
This is done through a new body parameter in the SearchAllChannels endpoint that allows to search for local only channels, which are either channels that are shared but marked as homed locally, or channels that are not shared at all.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-60870

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by lindy65** [comment]
Hey @mgdelacroix - can the shared channels test servers be updated with this fix or should I wait until this is merged to test?

**Review by sbishel — APPROVED** [review]
LGTM

**Comment by calebroseland** [comment]
https://shared-channels-b.test.mattermost.cloud/ is now running this PR. Login: https://hub.mattermost.com/abc/pl/zmuki8896brmfmekz9w7ckduxe

**Comment by mgdelacroix** [comment]
> Hey @mgdelacroix - can the shared channels test servers be updated with this fix or should I wait until this is merged to test?

@calebroseland has kindly updated `shared-channels-b` to run this PR (thanks!!), so you should be able to test the changes there

**Review by calebroseland — APPROVED** [review]
Tested and working good 👍

**Review by asaadmahmood — APPROVED** [review]
Does not show me remote channels.
But does this mean that I can share local channels with multiple connections?

**Review by lindy65 — APPROVED** [review]
Thanks @mgdelacroix - looks good to me (used updated B server to verify the fix with connections to Caleb's other test servers)

**Pull request merged**
