### PR TITLE
Replace Hard-coded HTTP Verbs with Constants

### PR DESCRIPTION
**Pull request by enzowritescode**
#### Summary
Replace hard-coded HTTP Verbs with constants from `net/http`

#### Ticket Link
N/A

#### Screenshots
N/A

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
@enzowritescode - are you sure you signed the CLA in the link?

**Comment by agnivade** [comment]
Also, the openAPISync vet check seems to break because of this. Let me ping @lieut-data for that.

**Comment by lieut-data** [comment]
:wave: @enzowritescode! Our vet check for the API is housed over at [github.com/mattermost/mattermost-govet](https://github.com/mattermost/mattermost-govet/blob/new/openApiSync/openApiSync.go). It's a bit clunky at present, with a primary purpose of ensuring we don't forget to document newly endpoints. Right now, it's using reflection and expecting to see `PUT`, `POST`, etc. and doesn't know how to handle the string constants. 

Would you be open to updating it to handle these constants? (There are unit tests that should make it easy to iterate in that repository, after which a merged `new` branch should apply automatically here with a rebuild.)

**Comment by enzowritescode** [comment]
@lieut-data I should be able to look into that in the coming days

**Comment by enzowritescode** [comment]
> @enzowritescode - are you sure you signed the CLA in the link?

I think I did the other day or during on-boarding. How do we double check?

**Comment by agnivade** [comment]
> I think I did the other day or during on-boarding. How do we double check?

You can click the "details" link in the failed CI check. I don't see your username in the list.

**Comment by streamer45** [comment]
@enzowritescode Are you waiting on our review or looking to work on more checks?

**Comment by enzowritescode** [comment]
> @enzowritescode Are you waiting on our review or looking to work on more checks?

@streamer45 the Vet tests need to be fixed as per @lieut-data's comments. I haven't had time to look into it.

**Review by lieut-data — APPROVED** [review]

**Comment by lieut-data** [comment]
Looks good! This would be a good API to run the full E2E suite on, but I can't find the label to trigger that -- pinged over at https://hub.mattermost.com/private-core/pl/xsec161tapyq3bu1e6g1c6d13y.

**Comment by phoinixgrr** [comment]
> Looks good! This would be a good API to run the full E2E suite on, but I can't find the label to trigger that -- pinged over at https://hub.mattermost.com/private-core/pl/xsec161tapyq3bu1e6g1c6d13y.

The label is "[EETests](https://github.com/mattermost/mattermost/labels/EETests)"  🚀 
Initiated the tests https://github.com/mattermost/enterprise/actions/runs/9896065518

**Review by streamer45 — APPROVED** [review]
Looks good :+1:

**Comment by lieut-data** [comment]
@lindy65, given the successful e2e pass above as well as the nature of this change, I don't think any explicit QA is required. Can you let us know your thoughts?

**Review by lindy65 — APPROVED** [review]
Agree @lieut-data - I'm good to pass this from the QA side 👍

**Comment by lieut-data** [comment]
Thanks, @lindy65! Feel free to merge when ready, @enzowritescode :)

**Pull request merged**
