### PR TITLE
MM-56925: Fix unnecessary cache invalidation of pinned post count

### PR DESCRIPTION
**Pull request by agnivade**
invalidateCacheForChannelPosts invalidated the pinned post count
and the lastPostTime cache.

But not all endpoints actually pins or unpins the post. That's only
possible via the UpdatePost or PatchPost methods. Therefore, we remove
the unnecessary cache invalidation.

This is also important because this gets called for every single
channel load, and every new post would invalidate this cache.

https://mattermost.atlassian.net/browse/MM-56925
```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
I spent several hours trying to write a test for this. But then realized it required far too much effort. Currently, there is no store mock available with caching enabled. That was easy enough to add. But then the initialization of the cache layer required pre-mocking some methods.

After doing that, I realized that the main issue is that each cache store stores its own references to the sub-stores like ChannelStore, PostStore etc. which requires mocking each of these separately and also exposing mechanism to override each of them.

While it's certainly possible, it would take way too much time and effort to do this in a way that's extensible and usable by future tests as well. I don't want to add one-off code just for a single test. 

Please let me know if you see a reasonable way to add a test. cc @jespino

**Review by isacikgoz — APPROVED** [review]

**Comment by agnivade** [comment]
@jespino - PTAL

**Review by jespino — APPROVED** [review]

**Comment by agnivade** [comment]
Merging as all tests passed.

**Pull request merged**
