### PR TITLE
[MM-54834]  Convert LocalizedInput of `mfa/setup/setup.tsx` to regular input component

### LINKED ISSUE #24822: Convert LocalizedInput of 'mfa/setup/setup.tsx' to regular input component
The LocalizedInput component is a functional component that injects the React Intl context into a regular input component. However, the use of this component encourages the use of a custom ‘soon-to-be-deprecated' ‘t' function. Hence, we are campaigning to convert LocalizedInput to a regular input component.

This ticket pertains to converting the usage of 'LocalizedInput' in 'webapp/channels/src/components/mfa/setup/setup.tsx' to a regular input component.

Task List:

1. Identify where the component is used and familiarise with its functionality.
1. Convert all occurrences of 'LocalizedInput' in the above-mentioned component.
1. Ensure all previous props are correctly passed to the new input component.
1. If the component uses translated strings as titles or placeholders, use the correct React-Intl API, such as the 'formattedMessage' hook or the 'injectIntl' higher-order component.
1. Verify that the conversion did not alter the design or user experience of the component.
1. Confirm that the component's functionality remains unchanged and works as before.

For Reference, please check this PR https://github.com/mattermost/mattermost/pull/24818     

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-54834

### PR DESCRIPTION
**Pull request by dipandhali2021**
#### Summary
Replaces the 'LocalizedInput' component in `webapp/channels/src/components/mfa/setup/setup.tsx` to a regular input component

#### Ticket Link
Fixes #24822

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@dipandhali2021 can you please the CI before we can start the review process

**Comment by dipandhali2021** [comment]
> @dipandhali2021 can you please fix CI before we can start the review process

Screenshot 2023-10-16 224152
I conducted the test on my local environment, and this is the resulting output. I'm having difficulty pinpointing where the test is failing.

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @dipandhali2021!

**Review by M-ZubairAhmed — APPROVED** [review]
Hey another awesome PR @dipandhali2021 thank you

**Review by yasserfaraazkhan — APPROVED** [review]
tested the '/mfa/setup' page and the code works.

**Pull request merged**
