### PR TITLE
MM-53679 - Update prepackaged calls to v0.18.0

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Calls v0.18.0

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-53679

#### Release Note

```release-note
Prepackage Calls version v0.18.0
```

### CODE REVIEW

**Comment by cpoile** [comment]
Tested and confirmed it's loading up v0.18.0 and calls are working.

**Comment by angeloskyratzakos** [comment]
FYI, testing functionality of CWS and cloud test server

**Review by lieut-data — APPROVED** [review]

**Review by streamer45 — APPROVED** [review]
Thanks :+1:

**Pull request merged**
