### PR TITLE
chore: migrate AWS SDK for JavaScript v2 APIs to v3 in e2e-tests

### PR DESCRIPTION
**Pull request by trivikr**
#### Summary

This PR migrates AWS SDK for JavaScript v2 APIs to v3 using [aws-sdk-js-codemod](https://www.npmjs.com/package/aws-sdk-js-codemod).

```console
$ npx aws-sdk-js-codemod@0.26.1 -t v2-to-v3 e2e-tests/cypress/utils/artifacts.js
```

#### Ticket Link

From AWS SDK for JavaScript v2 [README](https://github.com/aws/aws-sdk-js):
> We are formalizing our plans to make the Maintenance Announcement (Phase 2) for AWS SDK for JavaScript v2 in 2023.

#### Screenshots

N/A

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by saturninoabril** [comment]
@trivikr Thanks for your contribution! Let us know once this is ready for review.

**Comment by trivikr** [comment]
> Let us know once this is ready for review.

It's ready for review!

**Comment by saturninoabril** [comment]
Previous test failed to upload artifacts due to missing region. I now set `AWS_REGION` and will see how it goes.

**Review by saturninoabril — APPROVED** [review]
Thanks @trivikr, LGTM.

**Review by M-ZubairAhmed — APPROVED** [review]
This was great effort with care to small details 🔬

**Comment by M-ZubairAhmed** [comment]
Oh didn't knew you were the maintainer of JS AWS SDK 👍🏽

**Pull request merged**
