### PR TITLE
Adds a feature flag to control availability of DMs in shared channels

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
Controls de availability of DMs with remote users, effectively gating the logic introduced in https://github.com/mattermost/mattermost/pull/28855 and https://github.com/mattermost/mattermost/pull/28861

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-61265

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by lindy65 — APPROVED** [review]
Thanks @mgdelacroix - I'll test this post-merge

**Comment by mgdelacroix** [comment]
Adding the `Do Not Merge` label to update the PR and change the feature flag to be `DisableSharedChannelsDMs`. The code will be a bit more difficult to read, but it makes more sense and it's easier to document and reason about

**Review by calebroseland — APPROVED** [review]

**Comment by esethna** [comment]
@cwarnermm can we please have your help to work with Miguel to ensure this is documented? High level, DMs are not yet stable, so as we introduce Shared Channels in "beta" we will have them disabled by default. However, to ensure there isn't an unrecoverable breaking change for existing instances using shared channels in experimental where DMs were available, this feature flag allows admins to re-enable DMs if desired. cc// @mgdelacroix

**Comment by mgdelacroix** [comment]
@amyblais yup, working on it right now, thanks for the heads up!

**Pull request merged**
