### PR TITLE
[MM-54848] Remove deprecated LocalizedInput component

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
1. [login_mfa.tsx](https://github.com/mattermost/mattermost/pull/25052/files#diff-616962b1ec4e450331f20a5759e946f7480d7b8c4cb646fe096cb87ef78cae6b) to accept reactNodes and default props re-arrangement with formatMessage
1. From [searchable_channel_list.tsx](https://github.com/mattermost/mattermost/pull/25052/files#diff-00435008b49da5ebca53321a8208b7576148e3813d90e1e3bc21a69869b2ab35) removed t function and usage of LocalizedInput, similar for [searchable_user_list.tsx](https://github.com/mattermost/mattermost/pull/25052/files#diff-a2e7e74147657993b19f8b070c1890db62052bf0ef748f4be52ac2c5ae4b95ed) as well
1. t function removal from other places as seen in the diff
1. Removal of LocalizedInput component
1. Update of mmjstool tool as per https://github.com/mattermost/mattermost-utilities/pull/80

#### Ticket Link
Jira https://mattermost.atlassian.net/browse/MM-54848

#### Screenshots
none

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Review by sinansonmez — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
tested login, mfa setup, mfa login, switching to ladp.

**Pull request merged**
