### PR TITLE
MM-62046 Associate most labels with controls and enable label-has-associated-control ESLint rule

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
[This rule](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/7566e13531f09a040daee4c16d0cba0c28d321c4/docs/rules/label-has-associated-control.md) triggers if we have a `<label>` that either doesn't contain a control (usually an `input`) or refer to a control with its `for` attribute (`htmlFor` in React). Associating a label to a control helps accessibility tools, and it makes it so that clicking on the label focuses the input.

The individual commits explain more of what's happening in each file if it's at all interesting, but each change falls into one of a few categories:
1. Adding `htmlFor` to an element to cause it to focus its corresponding control.
2. Changing somewhere that we use a `label` element incorrectly for error text. I don't know why we ended up doing that everywhere, but it's a pattern that's been copied around the code A LOT.
    - Way back, I made a `FormError` component, and that could ideally be used in most of these places, but there's enough subtle styling differences that I didn't want to use that everywhere. We'll ideally revisit this later to use a similar component everywhere, although we'll have to fix `FormError` as well since it uses `label` too 😅
3. In the System Console, using a `fieldset` with a `legend` instead of a `label` for things which aren't a single input like file upload controls or various lists. `SettingSet` that I added in https://github.com/mattermost/mattermost/pull/29453 ended up being useful again here!

**Note:** The ESLint plugin doesn't report cases where we use a label and pass an arbitrary prop into it. This means we can miss some cases where it should be used and some cases where it shouldn't (ie. more error text). I want to do a followup to review those, but I have to look into more of the other cases reported by ESLint first.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-62046

#### Screenshots

|Before|After|Changes?
|-|-|-|
1 AddUserToChannelModal before|1 AddUserToChannelModal now|Minor spacing
|2 BleveSettings before|2 BleveSettings now|
3 BrandImageSettings before|3 BrandImageSettings now
4 DatabaseSettings before|4 DatabaseSettings now|
6 ElasticsearchSettings before|6 ElasticsearchSettings now
7 TeamEditionRightPanel 1 before|7 TeamEditionRightPanel 1 now
8 TeamEditionRightPanel 2 before|8 TeamEditionRightPanel 2 now|Fixed a bug
9 TrialBanner 1 bef|9 TrialBanner 1 now
10 TrialBanner 2 before|10 TrialBanner 2 now|Fixed some weird spacing
11 PasswordSettings before|11 PasswordSettings now
12 ChannelModeration before|12 ChannelModeration Now
13 MessageSubmitError before|13 MessageSubmitError now
14 AdvancedTextEditor before|14 AdvancedTextEditor now
15 RenameChannelModal before|15 RenameChannelModal now
16 SelectTeam 1 before|16 SelectTeam 1 now
17 SelectTeam 2 before|I forgot to take one last screenshot|Please just believe me that this didn't change. I don't want to take more screenshots :(

#### Release Note
```release-note
Improved accessibility of many form labels throughout the app
```

### CODE REVIEW

**Review by pvev — APPROVED** [review]
Nice changes @hmhealey ! one question is, I saw you review that the styles were preserved after the changes, but for the places you replaced label with div, do you think maybe were clicks expected on those elements that won't work after this change?

**Review by harshilsharma63 — APPROVED** [review]

**Comment by pvev** [comment]
> > Nice changes @hmhealey ! one question is, I saw you review that the styles were preserved after the changes, but for the places you replaced label with div, do you think maybe were clicks expected on those elements that won't work after this change?
> 
> @pvev No, I don't think so. In those cases, the `label` was either being used more like a heading or it was error text which isn't a label for it but instead describes the control.
> 
> Somewhat related to that, I found https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/ recently and learned more about how we should and shouldn't be using labels. I wrote a short version of it in the Web App channel and queued something for dev meeting to talk about it next week if people are around then.
> 
> https://community.mattermost.com/core/pl/m8gmujftyfdxud59u697p34f5y

awesome @hmhealey , thanks for clarifying this and for the article, will take a look and will look forward for your talk in the dev meeting 👍

**Comment by hmhealey** [comment]
I've overridden the E2E tests on this because the failing Playwright tests are for the profile popover which was not touched by these changes and that test passes for me locally. All of the Cypress tests pass which are the ones that cover more of the areas touched by these PRs.

I'm also skipping QA because I tested all of these changes manually while working on them.

**Pull request merged**
