### PR TITLE
MM-61897 - fix duplicated role dialog in boostrap modals

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
fix duplicated role dialog in bootstrap modals

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-61897

#### Screenshots
Screenshot 2024-12-06 at 10 15 02 AM
Screenshot 2024-12-06 at 10 16 33 AM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by pvev** [comment]
@hmhealey I had this in my pending todo list.  I took a break from other work I am doing and came back to this. Honestly, not sure if it is worth spending the time modifying our bootstrap library version for fixing this. This change took me less than one hour including validations.

**Review by hmhealey — APPROVED** [review]
I would've thought it would be easier to change it the other way, but I suppose that requires checking out our fork, getting the right branch, possibly finding out that the class is added by react-overlays (which we don't have a fork of), and submitting multiple PRs. None of sounds fun or easy, so I'm good with this solution since it improves accessibility all the same 🙂

**Comment by hmhealey** [comment]
@pvev Could you fix that outstanding test and then add the regular review labels?

**Review by devinbinnie — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
