### PR TITLE
📝 meta(community): add FOSDEM 2024 event details and create event template

### PR DESCRIPTION
**Pull request by azigler**
WIP to address https://github.com/mattermost/mattermost/issues/25792

### Changelog 🛠️ 
- FOSDEM 2024 event details have been added to the community events.
- Event template with frontmatter has been created to streamline the process of adding new events in the future.

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
I missed the discussion about the plan of adding events in monorepo. Can you please guide me to that link :)

**Comment by azigler** [comment]
Posting event details as committed thus far (this could be automated):

# FOSDEM 2024

**Event date:** Sat Feb 03 2024 to Sun Feb 04 2024

**Event location:** Brussels, Belgium

**Event URL:** <https://fosdem.org/2024/>

**Event description:** FOSDEM is a free event for software developers to meet, share ideas and collaborate. Every year, thousands of developers of free and open source software from all over the world gather at the event in Brussels. You don't need to register. Just turn up and join in!

## Mattermost Activities

### [Translations Devroom](https://fosdem.org/2024/schedule/track/translations/)

Tom De Moor (@ctlaltdieliet) will be talking about [Lessons learnt as a translation contributor the past 4 years](https://fosdem.org/2024/schedule/event/fosdem-2024-1906-lessons-learnt-as-a-translation-contributor-the-past-4-years/) the Sunday at 10:50am at the room [K.3.201](https://fosdem.org/2024/schedule/room/k3201/).

### [Go Devroom](https://fosdem.org/2024/schedule/track/go/)

Jesús Espino (@jespino) will be talking about [The secret life of a goroutine](https://fosdem.org/2024/schedule/event/fosdem-2024-1704-the-secret-life-of-a-goroutine/) the Saturday at 11am at the room [UD2.218A](https://fosdem.org/2024/schedule/room/ud2218a/).

## Reference

Source: <https://developers.events/feed-events.json>

```json
{
  "id": "https://fosdem.org/2024//1499",
  "content_html": "FOSDEM @ Brussels (Belgium) - Sat Feb 03 2024 00:00:00 GMT+0000 (Coordinated Universal Time)",
  "url": "https://fosdem.org/2024/",
  "title": "FOSDEM",
  "summary": "FOSDEM",
  "date_modified": "2023-12-20T10:40:34.997Z",
  "author": {
    "name": "developers.events",
    "url": "https://github.com/scraly/developers-conferences-agenda"
  }
}
```

**Comment by azigler** [comment]
Closing this PR, we can always merge in later if we add a collection of events.

**Pull request closed without merging**
