### PR TITLE
MM-56163 - Update prepackaged calls to v0.23.0

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Prepackage Calls v0.23.0

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-56164

#### Release Note

```release-note
Prepackage Calls version v0.23.0
```

### CODE REVIEW

**Comment by cpoile** [comment]
I'll do testing myself

**Review by amyblais — APPROVED** [review]

**Review by streamer45 — APPROVED** [review]
:+1:

**Comment by cpoile** [comment]
Works

**Comment by cwarnermm** [comment]
@cpoile - Are there product docs updates needed for this PR?

**Pull request merged**
