### PR TITLE
MM-57759: Bump mockery to version 2.42.2 to support go  1.22^

### PR DESCRIPTION
**Pull request by ezekielchow**
#### Summary

- Running `make mocks` for server when go version is 1.22 & above panics with `panic: runtime error: invalid memory address or nil pointer dereference` 
- Bump mockery to version 2.42.2 to support go 1.22^ to solve problem in the future

https://mattermost.atlassian.net/browse/MM-57759

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
Thanks!

**Review by isacikgoz — APPROVED** [review]

**Review by hanzei — APPROVED** [review]
Nice work, thanks :+1:

**Comment by ezekielchow** [comment]
> Merging this CI broke CI, see https://github.com/mattermost/mattermost/actions/runs/8659349219/job/23745036481.
> 
> @ezekielchow When I run `make mocks` locally, it introduces an update for `public/plugin/plugintest/hooks.go`. Could it be that you missed that file in this PR?

Let me check

**Comment by ezekielchow** [comment]
> Merging this CI broke CI, see https://github.com/mattermost/mattermost/actions/runs/8659349219/job/23745036481.
> 
> @ezekielchow When I run `make mocks` locally, it introduces an update for `public/plugin/plugintest/hooks.go`. Could it be that you missed that file in this PR?

I've tested `make mocks` locally using go 1.21.9 . Seems like there is no changes. Also there are changes already to that file included in the PR

**Comment by amyblais** [comment]
[@holopin-bot](https://github.com/holopin-bot) @ezekielchow Mattermost Most Valued Professional (MVP)

**Comment by amyblais** [comment]
@holopin-bot @ezekielchow Mattermost Most Valued Professional (MVP)

**Pull request merged**
