### PR TITLE
Switch to docker compose v2

### PR DESCRIPTION
**Pull request by KuSh**
#### Summary

Avoid following error on newly installed environment

```sh
$ LANG=C make run-server
Creating a go.work file
rm -f go.work
go work init
go work use .
go work use ./public
MMCTL already exists in bin/mmctl, not compiling.
Starting docker containers
docker-compose rm start_dependencies
make: docker-compose: No such file or directory
make: *** [Makefile:255: start-docker] Error 127
```

This should be compatible with actual environments as docker compose v2 is available since 2020 and included in all currently supported versions of Docker Desktop, see https://docs.docker.com/compose/migrate/

#### Ticket Link

I haven't found any tickets for this problem, but I've encountered it twice in one month.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM, any reason leaving e2e tests out? cc @mvitale1989

**Comment by KuSh** [comment]
> any reason leaving e2e tests out?

@isacikgoz I've double checked and the references in e2e-tests are not direct use of `docker-compose` command but just references in doc / comments. I wasn't sure it was worth but I can change it if wanted

The only other reference is in the `brew install docker docker-compose` in .github/workflows/e2e-tests-ci.yml but this one [is valid](https://formulae.brew.sh/formula/docker-compose) and correctly install the compose docker plugin

**Comment by isacikgoz** [comment]
>  install the compose docker plugin

Oh, I thought it was included into the docker CLI by default.

**Comment by mvitale1989** [comment]
Thanks @KuSh , and also @isacikgoz for the heads-up!
I can confirm that within the `e2e-tests` directory we're already using docker compose v2, and that other occurrences of `docker-compose` are mostly to refer to the compose YAML files as "docker-compose files", so there's no need to update them.

**Comment by hanzei** [comment]
@mvitale1989 Can we merge this PR then?

**Comment by mvitale1989** [comment]
Sounds good to me, but first let me do an E2E test run to ensure that there are no unexpected surprises

**Comment by mvitale1989** [comment]
LGTM @hanzei feel free to merge at any time!

**Comment by streamer45** [comment]
This was a breaking change on my system (Ubuntu 20.04). To fix I had to manually install the docker compose plugin (see steps below). I'd expect a few more developers to hit this so may be good to make an announcement or something.

```bash
mkdir -p ~/.docker/cli-plugins/
curl -SL https://github.com/docker/compose/releases/download/v2.23.1/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
chmod +x ~/.docker/cli-plugins/docker-compose
docker compose version
```

**Comment by KuSh** [comment]
I'm sorry to hear that @streamer45. It seems even for an old distro like ubuntu 20.04 this should be included as they provide version 20.10 by default, but [docker compose is not bundled](https://bugs.launchpad.net/ubuntu/+source/docker.io/+bug/2035328) and stand alone package [is the deprecated version](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1040417) (but that could be fixed in the near future)

On the other side all new docker installations were failing before that change. I could perhaps add a check to allow working with both of them. I didn't bother because I thought that change was old enough but it seems I was wrong :/

**Comment by streamer45** [comment]
Thanks @KuSh. I think the change is fine as the previous version is deprecated. We probably just need to make this a bit more visible so that devs running on slightly older systems like mine are aware of it. I am planning to bring up this in our upcoming [Developers Meeting](https://community.mattermost.com/core/pl/bt74kmpwfpym5piwjxoxsqxg6c).

**Pull request merged**
