### PR TITLE
[MM-58492] Remove subsequent check for team permissions on open channels

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
We had an extra check after checking for channel permissions in `/api/v4/posts/ids`. The extra check would allow posts that were on open channels and where users had team permissions to read the posts, regardless of whether compliance was enabled and/or the channel was archived.

This check is already taken care of as part of `SessionHasPermissionToReadChannel`, so it was redundant anyways and the aforementioned function takes all cases into account, so I've removed the extra check.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-58492

```release-note
NONE
```

### CODE REVIEW

**Review by enzowritescode — APPROVED** [review]

**Review by Rajat-Dabade — APPROVED** [review]

**Comment by Rajat-Dabade** [comment]
@devinbinnie some test care failing. Can you please check?

**Review by harshilsharma63 — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
