### PR TITLE
[MM-56294] Convert `./components/admin_console/group_settings/group_details/group_profile.tsx` from Class Component to Function Component

### PR DESCRIPTION
**Pull request by Syed-Ali-Abbas-Zaidi**
#### Summary

Convert `./components/admin_console/group_settings/group_details/group_profile.tsx` from Class Component to Function Component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/25756
Jira https://mattermost.atlassian.net/browse/MM-56294

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]
Great work, looks great!

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Comment by larkox** [comment]
@Syed-Ali-Abbas-Zaidi There seems to be a test failing. Could you take a look?

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
> @Syed-Ali-Abbas-Zaidi There seems to be a test failing. Could you take a look?

Done.

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
