### PR TITLE
HeaderIconWrapper: pass wrapped icon as a children

### PR DESCRIPTION
**Pull request by KuSh**
#### Summary
It seems so counterintuitive to pass the wrapped element as a prop
This is a cleanup patch I made during preparatory work on https://github.com/mattermost/mattermost/issues/22467

#### Release Note
```release-note
NONE
```
Jira ticket: https://mattermost.atlassian.net/browse/MM-27291

### CODE REVIEW

**Review by jespino — APPROVED** [review]
I think you are 100% right. Looks good to me. Thanks! :tada:

**Review by lieut-data — APPROVED** [review]
Makes sense to me, thank you @KuSh!

**Comment by lieut-data** [comment]
@lindy65, could you help us identify required next steps for QA review? Test coverage already looks updated, but I suspect we should kick of e2e tests as well as spot check the few components this touches. @KuSh, can you help point @lindy65 at the components that got changed?

**Comment by lindy65** [comment]
Hey @lieut-data - I believe E2E tests are triggered after `QA-done` label is added. Looks like the channel header and channel info components were changed but @KuSh can confirm. I'll do a smoke test of those areas once confirmed

**Comment by lindy65** [comment]
Thanks @KuSh - I'll go ahead and smoke test those areas

**Review by lindy65 — APPROVED** [review]
Thanks @KuSh - tested as per the components you listed and looks good to me 👍 

cc// @lieut-data

**Comment by lieut-data** [comment]
Thanks again @KuSh & @lindy65!

**Pull request merged**
