### PR TITLE
[MM-54836] Convert LocalizedInput of 'compliance_reports.tsx' to regular input component

### PR DESCRIPTION
**Pull request by akbarkz**
#### Summary

Replace `LocalizedInput` component in `webapp/channels/src/components/admin_console/compliance_reports/compliance_reports.tsx` to a regular input.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/24825
Jira https://mattermost.atlassian.net/browse/MM-54836

#### Screenshots

image

#### Release Note
```
NONE
```

### CODE REVIEW

**Comment by akbarkz** [comment]
@M-ZubairAhmed not sure why did the test CI fail, I don't see any connection between my changes and the failed test tbh. Could it be flakiness? Can we re-run the job?

**Review by M-ZubairAhmed — APPROVED** [review]
Its another banger PR 🥁

**Review by yasserfaraazkhan — APPROVED** [review]
image

**Review by larkox — APPROVED** [review]

**Pull request merged**
