### PR TITLE
Adds Shared Channel related API endpoints

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
New endpoints for the following routes are added:

- Get Shared Channel Remotes by Remote Cluster at `GET /api/v4/remotecluster/{remote_id}/sharedchannelremotes`
- Invite Remote Cluster to Channel at `POST /api/v4/remotecluster/{remote_id}/channels/invite`
- Uninvite Remote Cluster to Channel at `POST /api/v4/remotecluster/{remote_id}/channels/uninvite`

These endpoints are planned to be used from the system console, and gated through the `manage_secure_connections` permission.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-58476
https://mattermost.atlassian.net/browse/MM-58477
https://mattermost.atlassian.net/browse/MM-58478
https://mattermost.atlassian.net/browse/MM-59999

#### Release Note
```release-note
* Adds new API endpoints to manage shared channels
```

### CODE REVIEW

**Comment by wiggin77** [comment]
@mgdelacroix it looks like this one is built on top of the Remote Clusters PR.  As soon as that is merged I'll review this one.

**Comment by mgdelacroix** [comment]
@wiggin77 @calebroseland this PR is now ready for review

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:   Great work!

**Review by calebroseland — APPROVED** [review]

**Pull request merged**
