### PR TITLE
[MM-53057] Disallow malformed channel names for DMs

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
It's possible to rename the channel `Name` of a DM from `$USER1__$USER2` to something else. This breaks some places in the code, including the DM notification. The latter led to the panic from the JIRA tickets.

This PR prohibits changing the DM name to something that doesn't fit the pattern by changing the `IsValid()` check. This means existing DMs that have a broken "name" will throw an error the next time they get updated.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-53057

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Looks good! I'm surprised this was even possible to begin with since this must've dated back for ages

**Comment by hanzei** [comment]
Yes, the code has been that way since forever :tm:

**Review by harshilsharma63 — APPROVED** [review]

**Comment by harshilsharma63** [comment]
Should't we be resetting the name in update/patch channel API?

**Comment by hanzei** [comment]
> Should't we be resetting the name in update/patch channel API?

Yes, we could be more forgiving here. I'm hesitant to go that route as it's not something we usually do in the codebase. And to get a malformed channel name for a DM, the user already has to use the API. I assume it's a rare case.

**Comment by hanzei** [comment]
@DHaussermann, I've left QA test steps in the JIRA ticket. Please let me know if you need any clarification.

**Comment by DHaussermann** [comment]
@hanzei it seems there maybe an extra condition to testing this.
"_It's possible to rename the channel Name of a DM from $USER1__$USER2 _to something else_" 
That is not what is happening for me. I get an error message even when the value I try and patch even if the name would be valid and match the existing format. 
image

Steps:
- Deployed `master` branch loacally
- Used Postman to create a valid channel patch request and tested it on a non-DM channel successfully
- Attempted to rename a DM channel 

Perhaps this works on older server version? Let me know if you have any follow-up suggestions.

**Comment by hanzei** [comment]
@DHaussermann Good catch :+1: 

https://github.com/mattermost/mattermost/pull/24199 beat me to it. The issue that my PR is trying to fix is already solved. I removed the product changes from my PR. Now, it only contains test cleanups, which we can merge without further QA reivew.

**Pull request merged**
