### PR TITLE
Used limited reader in user invite

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Used limited reader in user invite to team and channel.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-55968

#### Release Note
```release-note
None
```

### CODE REVIEW

**Comment by jupenur** [comment]
Eva should be able to cover the security review, but can we get a second dev reviewer on this?

**Review by larkox — APPROVED** [review]

**Review by sbishel — CHANGES_REQUESTED** [review]
Actually, can we add unit tests for `StructFromJSONLimited`. It will be used going forward.

**Review by esarafianou — APPROVED** [review]
LGTM once tests for the `StructFromJSONLimited` are added as Scott pointed out.

**Comment by harshilsharma63** [comment]
@sbishel I've added the tests now.

**Review by sbishel — APPROVED** [review]
Thanks.

**Pull request merged**
