### PR TITLE
Prevent HEAD requests to a sub-path from infinite redirects

### PR DESCRIPTION
**Pull request by Aryakoste**
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27886
Jira https://mattermost.atlassian.net/browse/MM-58042

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by Aryakoste** [comment]
@lieut-data I have been told by @agnivade to add you as reviewer.

**Review by agnivade — CHANGES_REQUESTED** [review]
Please add a test for this.

**Comment by Aryakoste** [comment]
Where is the test for this located @agnivade

**Comment by agnivade** [comment]
There isn't an existing test. You'll have to add one. You can see some of the existing tests in web/handlers_test.go.

**Comment by Aryakoste** [comment]
So I will have to add new static_test.go right. For static.go

**Comment by agnivade** [comment]
Yes.

**Comment by Aryakoste** [comment]
Ok Thanks

**Review by lieut-data — CHANGES_REQUESTED** [review]
Just requesting changes to remove myself from the review -- feel free to re-request when ready :)

**Comment by Aryakoste** [comment]
Ok

**Comment by Aryakoste** [comment]
Hello @lieut-data @agnivade The unsupportedBrowserScriptHandler function uses templates.GetTemplateDirectory() to get the templateDirectory but there is no setTemplateDirectory method. How to proceed this. How should i setup mock template directory.

**Comment by agnivade** [comment]
I'll have to take a look and let you know.

**Comment by agnivade** [comment]
@Aryakoste - this is still on my radar. I'll get to it hopefully soon.

**Comment by Aryakoste** [comment]
Ok

**Comment by agnivade** [comment]
I've added the test for you @Aryakoste. Please take a look and let me know if everything is clear.

**Review by agnivade — APPROVED** [review]

**Comment by agnivade** [comment]
PTAL @lieut-data

**Comment by Aryakoste** [comment]
I thought i had to create a new test file for the whole static.go. But adding just the test for handling head request in web_test.go could work too. Yeah everything is clear. Thanks @agnivade

**Comment by agnivade** [comment]
That's what I initially thought as well, without looking at the code. However, looking at some other tests, I realized that we already test some of this, in another file. Therefore, it is fine to keep adding more tests in the same place.

**Comment by SteveEdiger** [comment]
Our organization depends on use of the mobile versions of Mattermost and it has not been working for some time.  It seems that all the work has been done except for the final signoff and integration into the next release.  We hope that this is soon. Thanks @Aryakoste for tracking it down and fixing it.

**Comment by Aryakoste** [comment]
You're Welcome. @SteveEdiger

**Comment by agnivade** [comment]
@cpoile - Since you looked into this briefly, would you be able to give it a review since Jesse is on PTO?

**Review by cpoile — APPROVED** [review]
Thanks @Aryakoste ! Thanks for the test @agnivade, tested and works.

**Comment by agnivade** [comment]
We have done this: https://github.com/mattermost/mattermost/pull/26047 in the past, and Juho had no issues with it. I think it should be fine.

**Review by esarafianou — APPROVED** [review]

**Comment by agnivade** [comment]
E2E tests passed. Merging. Thank you @Aryakoste for your patience.

**Comment by agnivade** [comment]
@amyblais - I updated the release notes. This should go in the changelog.

**Comment by agnivade** [comment]
@amyblais - Requesting to backport this to 9.11 ESR. A lot of customers are stuck with this problem without any workaround, rendering their mobile app to be effectively useless. A backport will help those customers start using MM.

**Comment by agnivade** [comment]
@amyblais - Were you planning to CP to 9.11 branch later with other hotfixes?

**Comment by amyblais** [comment]
> Were you planning to CP to 9.11 branch later with other hotfixes?

@agnivade I was on PTO last week. I'm catching up will cherry-pick it this week.

**Comment by agnivade** [comment]
Woops, missed that. All good!

**Comment by amyblais** [comment]
@agnivade This seems to need a manual cherry-pick PR.

**Comment by agnivade** [comment]
Thanks, will take care of it.

**Pull request merged**
