### PR TITLE
Display error in Direct Channels Modal

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
If a DirectMessage or GroupMessage cannot be created. Display the error message in the Modal.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-61152
Fixes https://mattermost.atlassian.net/browse/MM-61202

#### Screenshots
Screenshot 2024-10-22 at 4 30 45 PM

Screenshot 2024-10-22 at 3 30 24 PM

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by sbishel** [comment]
Tomorrow, I will add some unit tests...

**Comment by lindy65** [comment]
Hey @sbishel - I was wondering about the error message wording of "channel" as opposed to "message" as we typically refer to Direct and Group messages. Thoughts?

**Comment by sbishel** [comment]
@mgdelacroix @calebroseland Unit tests included, ready for review.

**Review by lindy65 — APPROVED** [review]
Code looks good @sbishel - I'll test the change once merged

**Comment by calebroseland** [comment]
https://shared-channels-f.test.mattermost.cloud/ is now running this PR

Access: https://hub.mattermost.com/abc/pl/zmuki8896brmfmekz9w7ckduxe

**Pull request closed without merging**
