### PR TITLE
[GH-25050] Typo in AddEmoji component

### PR DESCRIPTION
**Pull request by ARJ2160**
Fixed Issue - #25050

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@ARJ2160 please follow instructions https://github.com/mattermost/mattermost/pull/25051#issuecomment-1774038670 CLA

**Review by M-ZubairAhmed — APPROVED** [review]
Thank you

**Review by larkox — APPROVED** [review]
Thanks!

**Pull request merged**
