### PR TITLE
[MM-55333] Convert `./components/post_view/floating_timestamp/floating_timestamp.tsx` from Class Component to Function Component

### PR DESCRIPTION
**Pull request by Syed-Ali-Abbas-Zaidi**
#### Summary

Convert `./components/post_view/floating_timestamp/floating_timestamp.tsx` from Class Component to Function Component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/25362
Jira https://mattermost.atlassian.net/browse/MM-55333

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]
Great work! Thanks for the contribution!

**Review by M-ZubairAhmed — APPROVED** [review]
Thanks Ali

**Review by lindy65 — APPROVED** [review]
Thanks @Syed-Ali-Abbas-Zaidi - looks good :)

cc @larkox

**Pull request merged**
