### PR TITLE
MM-61231 Fix Hidden Menus in System Roles Page

### PR DESCRIPTION
**Pull request by matthewbirtch**
#### Summary
Fixes an issue where menus were getting cut off in the system roles screen.

#### Ticket Link
Jira: https://mattermost.atlassian.net/browse/MM-61231
Jira: https://mattermost.atlassian.net/browse/MM-61235

#### Screenshots
|  before  |  after  |
|----|----|
| image | image |

#### Release Note
```release-note
NONE
```

Additional note: created [another ticket](https://mattermost.atlassian.net/browse/MM-61235) for the issue with the menu text not wrapping properly. I didn't want to affect all menus inadvertently with this PR.

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]

**Comment by lindy65** [comment]
Hey @matthewbirtch - testing as per steps in Jira ticket, I'm seeing text cut off in the pop-up that appears when clicking on the drop-down to the right of `Read only` for Guest Access

In fact, clicking on the drop-down to the right of `Read only` for all 8 sub-sections shows the same defect - text does not wrap


image

**Comment by matthewbirtch** [comment]
> I'm seeing text cut off in the pop-up that appears when clicking on the drop-down to the right of Read only for Guest Access. In fact, clicking on the drop-down to the right of Read only for all 8 sub-sections shows the same defect - text does not wrap

Thanks @lindy65 I did mention this in the PR description. I created another ticket for the wrapping issue 

> Additional note: created [another ticket](https://mattermost.atlassian.net/browse/MM-61235) for the issue with the menu text not wrapping properly. I didn't want to affect all menus inadvertently with this PR.

I wanted to fix the identified issue first, but didn't want to impact all menu items by trying to fix that since that's used in a lot of places. @calebroseland @Willyfrog I was going to remove `white-space: nowrap;` from the menu item text, but I was worried that would affect too much across the product. I assumed we have the `nowrap` rule for a reason?

**Comment by lindy65** [comment]
Oh sorry @matthewbirtch! Missed that in the description!

**Review by lindy65 — APPROVED** [review]
Thanks @matthewbirtch - looks good to me

**Review by calebroseland — APPROVED** [review]
>  @calebroseland @Willyfrog I was going to remove white-space: nowrap; from the menu item text, but I was worried that would affect too much across the product. I assumed we have the nowrap rule for a reason?

Yes, that `white-space: nowrap` is for buttons and anchors in the deprecated menu that's used here, so I'd be cautious about removing it globally as that might cause regressions elsewhere.

The ideal quick-fix would be to target the specific menu here via `system_role_permissions.scss`. The long term fix would be to migrate to use the new menu component.

**Comment by matthewbirtch** [comment]
> The ideal quick-fix would be to target the specific menu here via `system_role_permissions.scss`. 

Thanks @calebroseland that's a good solution for now. Added that to this PR.

**Comment by lindy65** [comment]
Thanks @matthewbirtch - I'll give it a quick once-over as soon as the branch update is done

**Review by calebroseland — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Thanks @matthewbirtch - looks good 👍

**Pull request merged**
