### PR TITLE
Cypress/E2E: Fixed failed e2e tests

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Fixed failed e2e tests

#### Ticket Link
https://mattermost.atlassian.net/browse/CLD-5824
Found at https://github.com/mattermost/mattermost/pull/23660

#### Screenshots
Screenshot 2023-06-14 at 5 34 15 PM
Screenshot 2023-06-14 at 5 34 00 PM
Screenshot 2023-06-14 at 5 33 44 PM
Screenshot 2023-06-14 at 5 33 21 PM
Screenshot 2023-06-14 at 5 32 51 PM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by mvitale1989 — APPROVED** [review]

**Comment by mvitale1989** [comment]
LGTM! I see the gitlab pipeline partially failed, but that seems to be a hiccup that's unrelated to these changes

**Comment by saturninoabril** [comment]
Yup, I agree. I 'm merging this now.

**Comment by saturninoabril** [comment]
Yup, I agree.

**Review by yasserfaraazkhan — APPROVED** [review]
🎉

**Pull request merged**
