### PR TITLE
MM-54774 - update session roles when promote/demote guests

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
A function call already exists to update active session information when a user is promoted/demoted. Update that function to update the Session Roles from the promoted/demoted user.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-54774

#### Release Note

```release-note
Update session roles when user/guest is promoted/demoted.
```

### CODE REVIEW

**Review by enahum — APPROVED** [review]

**Review by isacikgoz — APPROVED** [review]
Thanks, LGTM!

**Review by esarafianou — APPROVED** [review]
LGTM

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - looks good to me 👍

**Pull request merged**
