### PR TITLE
[MM-54515] Fix textarea not working in interactive dialog

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary
Fix a regression making plugin developers unable to create a textarea in interactive dialogs.

### QA

[Using the demo plugin](https://github.com/mattermost/mattermost-plugin-demo), use the slash command: `/dialog`. the textarea should appear as a textarea (before, was a simple input)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-54515

#### Screenshots
N/A

#### Release Note
```release-note
* Fix a regression making plugin developers unable to create a textarea in interactive dialogs.
```

### CODE REVIEW

**Comment by JulienTant** [comment]
@amyblais we might want to backport this to release-8.0 and 8.1

**Review by pvev — APPROVED** [review]
LGTM! thanks @JulienTant :shipit:

**Comment by gyp5y** [comment]
Please merge. Most of our plugins stopped working due to this issue

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by hanzei** [comment]
@DHaussermann Gentle ping on the PR

**Review by DHaussermann — APPROVED** [review]
Tested and passed using the Demo plugin text area.
- Confirmed on a recent server build it comes up as a generic `<input>` with a type of `text`
- Deployed this build and confirmed that the filed is now a `<textarea>` tag

LGTM!

Thanks @JulienTant

**Pull request merged**
