### PR TITLE
[MM-55974] Theme is not used in notification selector box in user notification settings

### PR DESCRIPTION
**Pull request by ZubairImtiaz3**
#### Summary
The changes made ensure that the notification selector box now correctly adopts the same theme.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/25678
Jira https://mattermost.atlassian.net/browse/MM-55974

#### Screenshots
Before:
<a href="https://ibb.co/qW0dBjG">Screenshot-2023-12-12-012019</a>

After:
<a href="https://ibb.co/cTdLT9T">Screenshot-2023-12-12-012644</a>
#### Release Note
```release-note
Fix theme issue in the notification settings.
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]
Looks great. Thanks!

**Comment by matthewbirtch** [comment]
@abhijit-singh could you review this one?

**Comment by M-ZubairAhmed** [comment]
@ZubairImtiaz3 can you please verify against the figma design if we are using the correct colour tokens?

https://www.figma.com/file/uCB99F0PaTZyNosQlfE4rV/MM-53100-Keyword-Highlight%2FNotification-Improvements?type=design&node-id=1%3A7&mode=design&t=DTCA25CeZu3FqaL6-1

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
@ZubairImtiaz3 I went through the UI and we should update the following colors for the input box and chips:

1. The input box should have `border: rgba(var(--center-channel-color-rgb), 0.16`
    - on hover, it should be `border: rgba(var(--center-channel-color-rgb), 0.48`
3. The chips should have the following changes:
    - `background: rgba(var(--center-channel-color-rgb),0.08);`
    - `color: var(--center-channel-color);`
    - The `x` in the chip should be `color: rgba(var(--center-channel-color-rgb),0.32);`
    - And on hover the `x` should be `color: rgba(var(--center-channel-color-rgb),0.56);`

**Comment by ZubairImtiaz3** [comment]
@matthewbirtch Update the styles as mentioned above. You can take a look now.

**Comment by matthewbirtch** [comment]
@ZubairImtiaz3 It looks like the `center-channel-color` theme variable is not getting properly applied to the text label within the chips. This is how it's displaying with the onyx theme

image

**Comment by ZubairImtiaz3** [comment]
You were right, Update the styles. You can take another look. Thank you. @matthewbirtch 

image

**Review by matthewbirtch — APPROVED** [review]
That did the trick @ZubairImtiaz3. Thanks! Looks good now.

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by larkox** [comment]
@M-ZubairAhmed friendly reminder to review this.

**Review by M-ZubairAhmed — APPROVED** [review]

**Pull request merged**
