### PR TITLE
[MM-54118] Special mentions (`@here`, `@channel`) are not formatted correctly in the RHS. 

### PR DESCRIPTION
**Pull request by tanmaythole**
#### Summary

This PR fixes the styling of special mentions (`@here` & `@channel`) in the RHS.

#### Ticket Link

Fixes: https://github.com/mattermost/mattermost/issues/24645

#### Release Note

```release-note
Fixed special mentions formatting in the RHS.
```

### CODE REVIEW

**Comment by harshilsharma63** [comment]
Screenshot 2023-10-09 at 9 43 57 AM

Thank @tanmaythole for the PR!

While the `@here` and `@channel` text is now visible, the help text is still cut off. 

@abhijit-singh what do you recommend we should do?

**Comment by abhijit-singh** [comment]
Thanks for the contribution @tanmaythole! 

@harshilsharma63 This is already an improvement and the only other thing I'd recommend is adding an indication (three dots at the end '...') to convey that the text is truncated. It's okay if that's done as a follow up though. Here's a screenshot showing it - 
image

**Comment by tanmaythole** [comment]
> Thanks for the contribution @tanmaythole!
> 
> @harshilsharma63 This is already an improvement and the only other thing I'd recommend is adding an indication (three dots at the end '...') to convey that the text is truncated. It's okay if that's done as a follow up though. Here's a screenshot showing it - image

Okay, Thanks @abhijit-singh 

I will update it

**Comment by M-ZubairAhmed** [comment]
@tanmaythole can you please fix the CI, its blocking the test server from being created

**Comment by M-ZubairAhmed** [comment]
@abhijit-singh the test server is up now

**Review by harshilsharma63 — APPROVED** [review]

**Review by abhijit-singh — APPROVED** [review]
Looks great, thanks @tanmaythole!

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
works as expected in hrs, threads view, after resizing window.

Screenshot 2023-10-26 at 2 11 05 AM
Screenshot 2023-10-26 at 2 11 10 AM

**Pull request merged**
