### PR TITLE
[MM-52976] Increase width of announcement banner tooltip

### LINKED ISSUE #24959: Increase width of announcement banner tooltip
Summary

When hovering on the announcement banner, the tooltip could better utilize the space available

> **Design Notes**
> We can expand the tooltip width to upto 600px but that should only apply to this tooltip and NOT to all tooltips everywhere. 
> 
> Ideally, we should also only increase the width if there are more than a certain number of characters, say ~128.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-52976

### PR DESCRIPTION
**Pull request by Gauravpadam**
#### Summary
Closes #24959 
Jira https://mattermost.atlassian.net/browse/MM-52976

These changes should locally target our tooltip's context on announcement bar, Just as we'd like to address over this issue

```release-note
This widens the tooltip on announcement bar of the admin console
```

### CODE REVIEW

**Comment by Gauravpadam** [comment]
Lint tests were failing, I corrected them over latest commit

**Comment by abhijit-singh** [comment]
@M-ZubairAhmed How do we get a test server running here?

**Comment by M-ZubairAhmed** [comment]
> @M-ZubairAhmed How do we get a test server running here?

i rebased, lets try again when the CI is greeen

**Comment by M-ZubairAhmed** [comment]
> Mattermost test server created! 🎉
> 
> Access here: https://mattermost-pr-24964.test.mattermost.cloud
> 
> Account Type	Username	Password
> Admin	sysadmin	Sys@dmin123
> User	user-1	User-1@123

@abhijit-singh take a look

**Review by abhijit-singh — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]
Thank you @Gauravpadam

**Comment by Gauravpadam** [comment]
Thank you so much for the reviews @abhijit-singh @M-ZubairAhmed! 🙌

**Review by yasserfaraazkhan — APPROVED** [review]
image

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Pull request merged**
