### PR TITLE
[MM-54744] 'Customize your experience' point points to Settings icon in header

### PR DESCRIPTION
**Pull request by akbarkz**
#### Summary

Point "Customize your experience" tour's pulsating point to Setting icon

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/24843
Jira https://mattermost.atlassian.net/browse/MM-54744

#### Screenshots

Screenshot 2023-10-21 at 07 42 05

#### Release Note
```
NONE
```

### CODE REVIEW

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
thanks for the contribution @akbarkz. Can we nudge the tour point down so the settings icon is still visible?

Something like this:

image

**Comment by akbarkz** [comment]
@matthewbirtch fixed

**Review by matthewbirtch — APPROVED** [review]
Much better @akbarkz! Thanks again for the contribution!

**Review by M-ZubairAhmed — APPROVED** [review]
Thanks @akbarkz for another great piece of work 🎺

**Comment by akbarkz** [comment]
The failing test seems to be flaky. Maybe worth increasing the timeout here: https://github.com/mattermost/mattermost/actions/runs/6602631084/job/17934894080?pr=25032#step:4:1122

**Comment by umrkhn** [comment]
@M-ZubairAhmed I was assigned this issue, how come @akbarkz made a PR and got it approved?

**Comment by umrkhn** [comment]
P.S i've also made a PR that fixes the overlayPunchOut position https://github.com/mattermost/mattermost/pull/25053

**Review by yasserfaraazkhan — COMMENTED** [review]
tested this on chrome, Win desktop, re-sizing screen size.
works as expected. 
image

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @akbarkz!

**Comment by akbarkz** [comment]
@yasserfaraazkhan can you please approve?

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
