### PR TITLE
[MM-55999] Bring the revoke sessions button to the admin header and improve the styling of the header

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
- Added a new button type "terniary danger"
- Moved the revoke all sessions button to admin header
- Minor style adjustment of the admin header
- Moved RevokeSessionButton into separate component

#### Ticket Link

Jira https://mattermost.atlassian.net/browse/MM-55999

#### Screenshots
image

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by asaadmahmood — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
@M-ZubairAhmed just 1 test failing related to revoklesession.

tested this change to revoke session from web, desktop and mobile.

**Review by harshilsharma63 — APPROVED** [review]

**Review by sbishel — APPROVED** [review]
Just a question regarding role vs permission.

**Pull request merged**
