### PR TITLE
MM-54924: Update pdfjs to version 3.11.174

### PR DESCRIPTION
**Pull request by KuSh**
#### Summary

Update pdfjs to version 3.11.174 to better manage PDF forms

The problem is visible on latest Firefox version, but I've also checked that it works on Firefox 102.15.1esr

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/24895
Jira https://mattermost.atlassian.net/browse/MM-54924

#### Screenshots

|  before  |  after  |
|----|----|
| image | image |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Thanks for the PR, @KuSh! I figured there would be breaking changes with how we use the library, but I guess it's just because it requires a new version of Firefox.

I tested this locally and confirmed that we can update the minimum version of Firefox, so this looks good to me!

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
