### PR TITLE
MM-61297 - remove unused code

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
MM-61297 - remove unused code

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-61297

#### Screenshots
n/a

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by larkox — COMMENTED** [review]
On `channels/app/notify_admin.go` line 138 we still have code that can create `pl_notification` post type. Is this also dead code? Or no longer needed? If no longer needed, should we remove the custom post type on line 150 of that same file?

**Comment by pvev** [comment]
> On `server/channels/app/notify_admin.go` line 138 we still have code that can create `pl_notification` post type. Is this also dead code? Or no longer needed? If no longer needed, should we remove the custom post type on line 150 of that same file?

nice catch! that code must be removed too.

**Review by larkox — APPROVED** [review]

**Review by JulienTant — APPROVED** [review]
Thanks @pvev

**Pull request merged**
