### PR TITLE
MM-56579: Include deactivated users from DM posts

### PR DESCRIPTION
**Pull request by agnivade**
There were 2 separate bugs here:
1. We were not including deactivated users while fetching posts from
DM channels.
2. We were not respecting the includeArchivedChannels flag while
fetching DM channels.

We fix both of these issues here.

```release-note
Include posts from deactivated users in DM channel export. Also
respect the --include-archived-channels flag for DM channels.
```

https://mattermost.atlassian.net/browse/MM-56579

### CODE REVIEW

**Comment by agnivade** [comment]
I realized that there is no way to archive a DM channel through the UI, so handling the flag probably didn't make any difference. But it's still possible someone might update the DB manually. So I don't see a big harm in keeping it.

**Review by isacikgoz — APPROVED** [review]
LGTM

**Review by pvev — APPROVED** [review]
LGTM! thanks @agnivade

**Comment by DHaussermann** [comment]
@agnivade I can see point 1. seems to be resolved with respect to not fetching the users. 

But for point 2 with Archived DM channels I see no difference in the exported data for DM.
I was a bit curious what would happens if only 1 of the members was archived but the results I saw where the same. Even if both members are deactivated the channel and DM posts are included in the export regardless of the `includeArchivedChannels ` flag. 

Steps:
- Invite 2 new users to the server
- Have the 2 users DM each other 
- Archive both of the users
- Run the Bulk Export without the `includeArchivedChannels`
**Observed**: The posts created above are included in the export file

Maybe there is something I've misunderstood here?

**Comment by agnivade** [comment]
@DHaussermann  You haven't misunderstood anything. See my comment here: https://github.com/mattermost/mattermost/pull/25985#issuecomment-1903502065.

You cannot even archive a DM channel via the UI. So that's why the flag has no effect until you actually modify the DB and set a `DeleteAt` to a non-zero value.

**Review by DHaussermann — APPROVED** [review]
Thanks @agnivade I forgot that detail and was still considering the channel archived from the UI terminology by mistake. 
 
Tested and passed
- I have confirmed both issues are resolved. 
- The flag is now respected for DM as well as other channel types

LGTM!

**Comment by cwarnermm** [comment]
@agnivade - Just want to confirm that there isn't dev/product docs impact for this PR. It appears to be a change we're making "under the hood".

**Comment by agnivade** [comment]
Yep, mainly under the hood. No new features getting added here.

**Pull request merged**
