### PR TITLE
Remove usage of mattermost-redux from Cypress

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
I noticed that the Cypress tests already had `@mattermost/types` in most places, and the only thing they still used from `mattermost-redux` was the `Client4` class which is now in `@mattermost/client`. Getting rid of the `mattermost-redux` actually massively speeds up the install time of dependencies for Cypress, bringing the time down from over a minute to 5-6 seconds.

Since this is in the monorepo, we can also change the E2E tests to use the local version instead of downloading those packages, but I don't think that really matters unless we need the latest version of those packages immediately. It might actually make this slower because it would have to download their dependencies and then build them.

#### Screenshots
Before and after of the output of `npm install`
Screenshot 2023-09-29 at 5 28 51 PM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by hmhealey** [comment]
@saturninoabril I had to add a preprocessor to run the `node_modules` through Webpack because the Client package uses some newer JS stuff that isn't supported by the version of Webpack that our current version of Cypress uses. Hopefully it won't slow the tests down too much.

Alternatively, we might be able to fix the version by upgrading Cypress, but since we're moving towards Playwright, I assumed this would be a better option than that

**Comment by saturninoabril** [comment]
Thanks @hmhealey!

Yes, we're moving towards Playwright but we'll to continue maintaining Cypress -- atleast package/server/client4 dependencies. Actually I prepared a PR (now ready for review) for upgrading Cypress - https://github.com/mattermost/mattermost/pull/24594

> ..., we can also change the E2E tests to use the local version instead of downloading those packages, but I don't think that really matters ...

True. Not in Cypress but we're doing this in Playwright.

**Review by saturninoabril — APPROVED** [review]
Thanks @hmhealey! LGTM.

**Pull request merged**
