### PR TITLE
MM-53222 - Fix: Calls Ringing sometimes controllable with media keys

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- I noticed that sometimes after a call notification rang, the computer's media keys would control the ringing sound (starting it after it was finished).
- Intermittently reproducible (not 100% of the time):
  1. In the notifications settings panel, if you pressed the media pause key while the 5-second test notification was ringing, it would pause the notification ring, then you could start and stop it with the media pause key even after the settings panel had closed.
  1. While testing (using https://github.com/mattermost/mattermost-plugin-calls/pull/445), on the same computer, User A calls User B, User B hears ringing, User A stops call, now pressing the media key can sometimes make the ringing sound start/stop.
- ~~With this fix, you sometimes are able to make 1 happen again, but only the very first time (Chrome). After the sound has gone through a start/stop cycle, you can't control it again with the media keys. I'm guessing: Chrome marks the sound element as "will be removed" once it happens once, so doesn't allow the the media keys to control it. (otherwise any recent "ding" could be replayed with the media keys) Firefox is not as good -- it seems to let you pause the ringing while it's happening, even after the first time. But at least once it's removed the media keys can't control it.~~
- Now pressing the pause media key will stop the sound and remove it, so that pressing the key again does not affect the notification sound.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-53222

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by streamer45** [comment]
Would listening on events like `pause` and cleanup help here? Is there any reason we should allow the audio to be resumed?

**Comment by cpoile** [comment]
Thank you @streamer45 nice suggestion, that fixes the edge case problems. As an added benefit, you can now use the media pause button to stop a notification sound if you can't find the dismiss button quick enough. Nice. Pressing it again will start whatever you had last played (not the notification sound).

**Review by streamer45 — APPROVED** [review]
Looks good!

**Review by hmhealey — APPROVED** [review]

**Comment by cpoile** [comment]
@amyblais Would we be able to get this cherry picked for 8.0?

**Comment by amyblais** [comment]
@cpoile This looks good to merge.

**Pull request merged**
