### PR TITLE
[MM-62111] Avoid SELECT * in outgoing_oauth_connection_store.go

### PR DESCRIPTION
**Pull request by Honsei901**
#### Summary
Avoid SELECT * in outgoing_oauth_connection_store.go

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/29527
Jira MM-62111

#### Release Note

```release-note
NONE

```

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
This is great, thanks @Honsei901!

**Comment by lieut-data** [comment]
@Honsei901, our CI pipeline isn't reporting the results here automatically, but it looks like these changes might be failing one or more tests:

CleanShot 2024-12-11 at 15 28 42@2x

Could you take a peek by running these tests locally?

**Comment by Honsei901** [comment]
@lieut-data 
I've run all the tests, and all of them passed

**Comment by lieut-data** [comment]
Sounds good, thanks @Honsei901! Looks like a CI issue on our end -- I'll get this across the line and merged :)

**Comment by toninis** [comment]
@lieut-data Worked like a charm 🚀 . Thanks for the patience . 
cc: @mattermost/core-build-engineers

**Pull request merged**
