### PR TITLE
Replace Ex with E.g. in UI strings and comments

### PR DESCRIPTION
**Pull request by jdhoek**
Align with pre-existing dominant usage within project and generally write proper English.

#### Summary

Replaces all instances of `Ex.` with `E.g.,` in the UI and the English locale. As well as two comments.

#### Ticket Link

*None.*

#### Screenshots

|  before  |  after  |
|----|----|
| Screenshot from 2023-07-11 09-11-26  | *None yet* |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by jdhoek** [comment]
Note that `Ex:` is used in the `pt-BR` (Brazilian Portuguese), `ro` (Romanian), and `sv` (Swedish) translations files in `webapp/channels/src/i18n/` too. I've left those alone — I am not familiar with these three languages.

Due to the webapp code being imported from another repo, I can't tell which developer used `Ex:` in the admin console configuration UI. It might be good to send them a heads-up to prevent this happening again.

**Comment by M-ZubairAhmed** [comment]
thank you @jdhoek i will have @cwarnermm have final say on this

**Comment by cwarnermm** [comment]
@mgdelacroix - I'm not sure of the impact of extending terminology updates to code comments. Are you open to reviewing this PR for potential code/product impact, please?

**Comment by cwarnermm** [comment]
@jdhoek - Are you open to resolving the conflicts on this PR?

**Comment by jdhoek** [comment]
@cwarnermm Done.

**Review by mgdelacroix — APPROVED** [review]
Apologies for my late review.

> @mgdelacroix - I'm not sure of the impact of extending terminology updates to code comments. Are you open to reviewing this PR for potential code/product impact, please?

There should not be any impact caused by updating those comments.

If we want to propagate these changes to other languages, we'll have to do it through weblate directly tho.

**Comment by hanzei** [comment]
@jdhoek Would you please merge `master` into your PR?

**Comment by hanzei** [comment]
Closing the PR due to inactivity. @jdhoek please reopen it if you want to continue working on it.

**Pull request closed without merging**
