### PR TITLE
[MM-58492][MM-58523] Cherry-pick of #27409 to release-9.10

### PR DESCRIPTION
**Pull request by devinbinnie**
Cherry-pick of #27409 to release-9.10

```release-note
NONE
```

### CODE REVIEW

**Comment by devinbinnie** [comment]
@amyblais I have a failing test in enterprise unrelated to this PR - not sure if you're aware/know who could fix that

**Comment by amyblais** [comment]
> I have a failing style check in enterprise unrelated to this PR - not sure if you're aware/know who could fix that

Yes, there is an open ticket: https://mattermost.atlassian.net/browse/MM-59940

**Review by amyblais — APPROVED** [review]

**Pull request merged**
