### PR TITLE
Admin console definition to typescript

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
As part of the effort of migrating to Typescript, this was one of the stoppers
because migrating such a big file can be painful. I wrote the original version,
so I had good understanding of the reasons behind the current implementation,
so I was in good position to migrate it.

I migrated it with very small change in the approach about subsections, using a
specific field for that (making the typing better).

Reopened from #24658 to get through QA (was accidentally merged without QA and we reverted it)

#### Ticket Link
[MM-54855](https://mattermost.atlassian.net/browse/MM-54855)

#### Release Note
```release-note
NONE
```

[MM-54855]: https://mattermost.atlassian.net/browse/MM-54855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jespino** [comment]
@larkox @M-ZubairAhmed @hmhealey This is the same PR already reviewed reopenend to get reviewed by QA

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by larkox — APPROVED** [review]

**Comment by jespino** [comment]
For QA I would expect a relatively deep smoke testing in the admin console.

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
Here's the results of running the E2E tests on the original PR. There's no failures relating to the System Console at least

https://automation-dashboard.vercel.app/cycle/376955

**Comment by M-ZubairAhmed** [comment]
@lindy65 gentle ping on this one

**Comment by lindy65** [comment]
Hi @jespino - I've done a good smoke test of the system console and found one issue:

image

**Comment by jespino** [comment]
@lindy65 Great! thanks, I'll fix it and fix also the conflicts

**Comment by lindy65** [comment]
Great, thanks @jespino - please ping me when ready to retest :)

**Comment by lindy65** [comment]
@jespino - still some conflicts to resolve :)

**Comment by jespino** [comment]
@lindy65 was a new one... merging it with main.

**Comment by lindy65** [comment]
Hi @jespino - still seem to be some conflicts? Please take a look?

**Comment by jespino** [comment]
@lindy65 that is a new one :facepalm: looks like everybody is touching that file lately.

**Comment by jespino** [comment]
@lindy65 merged again and fixed the conflicts

**Comment by lindy65** [comment]
@jespino - I'm having a problem setting up a spinwick, can you take a look please?

**Comment by jespino** [comment]
@lindy65 I'm not able to run the cloud test server either :disappointed:

**Comment by jespino** [comment]
@lindy65 I'm trying to setup cloud test server with `CWS`, to see if that works, it shouldn't be a problem for testing this, right?

**Comment by jespino** [comment]
@lindy65 the test is not failing locally, and I think it shouldn't be failing in the CI, I'm re-running the tests.

**Comment by jespino** [comment]
@lindy65 anyway, I'm not able to make it run the spinwick, I don't know why

**Comment by lindy65** [comment]
> @lindy65 anyway, I'm not able to make it run the spinwick, I don't know why

I believe the spinwick will only build once all checks pass

**Comment by lindy65** [comment]
OK, if it doesn't build after these checks have passed, I'll ask Cloud devs to take a look

**Comment by lindy65** [comment]
Have asked for help [here](https://community.mattermost.com/private-core/pl/yrjth67d4bgg8cqmnmqafb6ebh) @jespino

**Comment by andrleite** [comment]
@jespino The server fails to initialize when trying to create /data and the container doesn't have permission. It doesn't run privileged.
```
Error: failed to initialize platform: Bleveengine.Start: bleveengine.create_post_index.error, mkdir /data: permission denied
{"timestamp":"2023-10-30 16:27:05.953 Z","level":"info","msg":"Server is initializing...","go_version":"go1.20.7"}
{"timestamp":"2023-10-30 16:27:05.953 Z","level":"info","msg":"EXPERIMENTAL: Starting Bleve"}
{"timestamp":"2023-10-30 16:27:05.954 Z","level":"error","msg":"failed to initialize platform: Bleveengine.Start: bleveengine.create_post_index.error, mkdir /data: permission denied","stacktrace":[{"Function":"github.com/mattermost/mattermost/server/v8/cmd/mattermost/commands.runServer","File":"github.com/mattermost/mattermost/server/v8/cmd/mattermost/commands/server.go","Line":76},{"Function":"github.com/mattermost/mattermost/server/v8/cmd/mattermost/commands.serverCmdF","File":"github.com/mattermost/mattermost/server/v8/cmd/mattermost/commands/server.go","Line":58},{"Function":"github.com/spf13/cobra.(*Command).execute","File":"github.com/spf13/cobra@v1.7.0/command.go","Line":940},{"Function":"github.com/spf13/cobra.(*Command).ExecuteC","File":"github.com/spf13/cobra@v1.7.0/command.go","Line":1068},{"Function":"github.com/spf13/cobra.(*Command).Execute","File":"github.com/spf13/cobra@v1.7.0/command.go","Line":992},{"Function":"github.com/mattermost/mattermost/server/v8/cmd/mattermost/commands.Run","File":"github.com/mattermost/mattermost/server/v8/cmd/mattermost/commands/root.go","Line":14},{"Function":"main.main","File":"github.com/mattermost/mattermost/server/v8/cmd/mattermost/main.go","Line":20},{"Function":"runtime.main","File":"runtime/proc.go","Line":250},{"Function":"runtime.goexit","File":"runtime/asm_amd64.s","Line":1598}]}
```

**Comment by andrleite** [comment]
@jespino we raised a new PR based on master to test spinwick and it worked. I'm wondering if there's sth different on your PR that can be breaking it, maybe from another change.

**Comment by jespino** [comment]
@andrleite it shouldn't, can @lindy65 test in the other PR spinwick? I think that should be enough.

**Pull request closed without merging**
