### PR TITLE
[MM-59895] Migrate tooltips of 'components/channel_header/channel_header.tsx' to WithTooltip

### PR DESCRIPTION
**Pull request by Gesare5**
#### Summary

Replaces OverlayTrigger and Tooltip, with WithTooltip in channel_header component

#### Ticket Link

Fixes  [#27786](https://github.com/mattermost/mattermost/issues/27786)
Jira  [https://mattermost.atlassian.net/browse/MM-59895](https://mattermost.atlassian.net/browse/MM-59895)

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
Can you check the failing CI

**Comment by Gesare5** [comment]
@M-ZubairAhmed , I can see a test is failing, this particular test was addressed in the contributor channel, and it was mentioned that sometimes it passes other times it fails, for reasons unknown, it is in no way related to my changes from what I can see. He said to ignore it. Let me see if I can find it and tag you on it on the channel.

**Comment by M-ZubairAhmed** [comment]
> @M-ZubairAhmed , I can see a test is failing, this particular test was addressed in the contributor channel, and it was mentioned that sometimes it passes other times it fails, for reasons unknown, it is in no way related to my changes from what I can see. He said to ignore it. Let me see if I can find it and tag you on it on the channel.

Yes they seems to be just flaky tests

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by yasserfaraazkhan — APPROVED** [review]

**Review by Rajat-Dabade — APPROVED** [review]

**Pull request merged**
