### PR TITLE
[MM-55097] Replace usage of LocalizedIcon in 'channel_header.tsx' with i/span tags

### PR DESCRIPTION
**Pull request by js029**
#### Summary
Replace LocalizedIcon with i tag in channel_header.tsx

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/25113
https://mattermost.atlassian.net/browse/MM-55097

#### Screenshots
|  Before  |
|Before 

| After |
After|

Icon comes up on channel header hover

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
Another amazing piece of work @js029 🎺 🎺

**Comment by M-ZubairAhmed** [comment]
@yasserfaraazkhan just checked they are not

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
