### PR TITLE
Bump prepackage Github plugin version to 2.2.0

### PR DESCRIPTION
**Pull request by ayusht2810**
#### Summary
Prepackage Github plugin v2.2.0.

#### Release Note
```release-note
Prepackage Github plugin version [v2.2.0](https://github.com/mattermost/mattermost-plugin-github/releases/tag/v2.2.0).
```
Prepackage Github plugin [v2.2.0](https://github.com/mattermost/mattermost-plugin-github/releases/tag/v2.2.0).

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
I'm unsure if we already should prepackage the plugin, given that it has just been released.

**Comment by mickmister** [comment]
@hanzei An RC was running on community for a while that contains all changes other than https://github.com/mattermost/mattermost-plugin-github/pull/735 and https://github.com/mattermost/mattermost-plugin-github/pull/729. Thoughts on merging based on this?

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
Seeing an error in CI related to the changes in the PR

```
cp /home/runner/work/mattermost/mattermost/server/bin/darwin_amd64/mattermost /home/runner/work/mattermost/mattermost/server/bin/darwin_amd64/mmctl dist/osx_amd64/mattermost/bin # from cross-compiled bin dir
cp: cannot stat 'tmpprepackaged/mattermost-plugin-github-v2.2.0-osx-amd64.tar.gz': No such file or directory
cp: cannot stat 'tmpprepackaged/mattermost-plugin-github-v2.2.0-osx-amd64.tar.gz.sig': No such file or directory
tar: dist/osx_amd64/mattermost/prepackaged_plugins/mattermost-plugin-github-v2.2.0-osx-amd64.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Contains  in mattermost-plugin-github-v2.2.0-osx-amd64.tar.gz but needs dist/plugin-darwin-amd64
```

This was brought up here but I thought maybe it's not an issue https://github.com/mattermost/mattermost-marketplace/pull/414#discussion_r1490413214

There must have been an issue during the cutplugin process? @hanzei Wondering what you think are next steps for debugging the issue, i.e. logs to look at for this. Or who should look into this

**Comment by cwarnermm** [comment]
@mickmister - Are there any product or dev documentation updates needed for this PR?

**Pull request merged**
