### PR TITLE
Pre-package Playbooks v1.37.0

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Pre-package Playbooks v1.37.0.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-53316

#### Release Note
```release-note
Pre-package Playbooks v1.37.0
```

### CODE REVIEW

**Review by crspeller — APPROVED** [review]

**Comment by lieut-data** [comment]
Some of the matrix tests appear to not have Playbooks running, failing some of the e2e tests. I'm going to run it again to see what happens, but unfortunately we don't currently keep the corresponding server logs so it's hard to track down what's going on.

**Comment by lieut-data** [comment]
@saturninoabril, I'm having trouble figuring out how to proceed with the E2E tests above. In short, it looks like on a handful of the runners, Playbooks never starts, and thus all related tests fail (usually with a 404 on some API endpoint). But other tests on other runners are definitely passing.

I suspect something is causing Playbooks to fail to startup on each runner, but it seems like we don't preserve the logs from the running Docker containers. Any suggestions on how to proceed?

**Comment by saturninoabril** [comment]
I'll take a look. Not sure if you've seen but there is an artifact available as `mattermost.log` - https://git.internal.mattermost.com/qa/cypress-ui-automation/-/jobs/1594458/artifacts/file/logs/mattermost.log. Looking at one of the logs, I can see an error related to Playbooks (see attached).
[mattermost.log](https://github.com/mattermost/mattermost/files/11900733/mattermost.log)

**Comment by lieut-data** [comment]
Thank you for the assist, @saturninoabril!

> About the logs, how about the following error...

That particular warning is normal in contexts where the client looks for a playbook run where one doesn't exist. I think we could do more to prevent the client from even trying to make this request, but it's fairly normal at present.

What I'm primarily looking for is an answer to why paths like `/plugins/playbooks/playbooks` return a 404 on some job runs. To my knowledge, that can only happen if the plugin isn't even running. I'll take a look at the debug logs once this next run is done.

**Comment by lieut-data** [comment]
Ooh, another find, @saturninoabril  -- https://github.com/mattermost/mattermost/pull/23882 has an e2e test run with the same symptoms: random jobs where Playbooks isn't even running. That's "Good News" in so far that it isn't related to this playbooks version upgrade. I'm inclined to merge this as-is and investigate what's going on with Playbooks in our suite asynchronously. Any concerns?

**Review by saturninoabril — APPROVED** [review]
I tried locally including replicating the same succession of spec files of particular job (assuming there could be side-effect from other tests) and it passed without issue. No concerns from me from merging this. Let me know what you found out after your investigation and if there's anything I need to do.

**Pull request merged**
