### PR TITLE
[MM-52171] webapp: Make rhs_card reloading when card body is changed

### PR DESCRIPTION
**Pull request by kaakaa**
#### Summary

If there are changes to `post.props.card`, it triggers updating `rhs_card` component.

This PR includes another fixes to a tiny bug that deleting `post.props` returns the following js error:
```
react_devtools_backend_compact.js:2367 Warning: Failed prop type: The prop message is marked as required in Markdown, but its value is undefined.
at Markdown (webpack-internal:///./src/components/markdown/markdown.tsx:37:1)
at ConnectFunction (webpack-internal:///../node_modules/react-redux/es/components/connectAdvanced.js:232:68)
at div
```

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/22961
Jira https://mattermost.atlassian.net/browse/MM-52171

#### Screenshots

https://github.com/mattermost/mattermost/assets/1453749/90ed2d31-9f58-45e3-8945-428b9b818ede

#### Release Note
```release-note
Fixed a bug not to reload RHS Card when card body is updated
```

### CODE REVIEW

**Review by calebroseland — APPROVED** [review]
LGTM, thanks @kaakaa!

**Comment by lindy65** [comment]
@kaakaa or @crspeller Can you help add Matterpoll to the spinwick so I can test this fix please?

**Comment by kaakaa** [comment]
@lindy65 
The version of Matterpoll used in the video above has not released to Marketplace yet ([in progress](https://github.com/mattermost/mattermost-marketplace/issues/367)), so [`Upload Plugin`](https://docs.mattermost.com/configure/plugins-configuration-settings.html#upload-plugin) setting must be set to true. Is it possible? If not, I think it would be necessary to update the contents of the card by REST API to test this. Is that valid?

```bash
# Get token to call REST API
$ curl -i -d '{"login_id":"user-1","password":"User-1@123"}' https://mattermost-pr-23612.test.mattermost.cloud/api/v4/users/login
...
token: a1y9u13oejrf5jkywwjibcjpda
...

# Create a post with card
$ curl -i -H 'Authorization: Bearer a1y9u13oejrf5jkywwjibcjpda' -d '{"channel_id":"1u5xq8m8yibwbnny5h6wgqesgw", "message":"test", "props":{"card":"before"}' https://mattermost-pr-23612.test.mattermost.cloud/api/v4/posts

# With the card open, update the contents of the card
$ curl -i -X PUT -H 'Authorization: Bearer a1y9u13oejrf5jkywwjibcjpda' -d '{"id":"${POST_ID}", "props":{"card":"after"}}' https://mattermost-pr-23612.test.mattermost.cloud/api/v4/posts/${POST_ID}
```

**Comment by lindy65** [comment]
Thank you so much @kaakaa - unfortunately "upload plugin setting" must be set via the config - not sure whether @crspeller is able to do this on the spinwick?

I don't have a local dev set-up so am not able to test via the REST API.  If Christopher is not able to update the spinwick's "upload plugin setting" via the config, I'll "QA defer" this PR and test after merging and once the Matterpoll plugin has been updated in the Marketplace.

**Comment by kaakaa** [comment]
Since Matterpoll was dropped from Mattermost In-App Marketplace and Mattermost doesn't have a feature to update card body, there are no way to test this fix on spinwick server... Are there any way to progress this?

**Review by lindy65 — APPROVED** [review]
Thanks @calebroseland for your help with test steps! Tested per your instructions via DM and this is working as expected now.

Thanks for the contribution @kaakaa :)

**Comment by hanzei** [comment]
Thanks for the contribution @kaakaa :tada:

**Pull request merged**
