### PR TITLE
[MM-60814] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/authorize/authorize.tsx' with FormattedMessage 

### PR DESCRIPTION
**Pull request by Camillarhi**
#### Summary

Replace FormattedMarkdownMessage in `webapp/channels/src/components/authorize/authorize.tsx` with FormattedMessage 
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28466
Jira https://mattermost.atlassian.net/browse/MM-60814
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by Rajat-Dabade** [comment]
@Camillarhi Ci tests are failing. Can you please take a look? Thank you.

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Comment by varghesejose2020** [comment]
I would like to Test this PR @lindy65

**Comment by lindy65** [comment]
Hi @varghesejose2020 - I have set up a test server - credentials above. Please see testing instructions on the Jira ticket: https://mattermost.atlassian.net/browse/MM-60814

**Comment by varghesejose2020** [comment]
@lindy65 PR changes workingnas expected..

**Comment by lindy65** [comment]
Thanks @varghesejose2020 - counted towards Hacktoberfest

**Review by Rajat-Dabade — APPROVED** [review]

**Pull request merged**
