### PR TITLE
Fixed API return type in documentation

### PR DESCRIPTION
**Pull request by Aryakoste**
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28058
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by cpoile — APPROVED** [review]
Looks good, thanks @Aryakoste !

**Comment by Aryakoste** [comment]
@hanzei

**Comment by hanzei** [comment]
Sorry for the delay @Aryakoste. We are good to merge this PR.

**Pull request merged**
