### PR TITLE
[MM-55412] Use go-style error handling in team_controller

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Instead of using `try` and `catch` use a go-style of returning actually errors for anticipated issues and let exceptions happen for things that are - well- exceptionally.

I tried adding a snapshot test to ensure the component renders as expected when `initializeTeam` or `joinTeam` throws, but it's hard to mock all the props.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-55412

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
Thanks for taking a look at this! Mocking those out is definitely a pain, so I can understand not being able to write tests for that. I definitely want to figure out how to rewrite this sort of initialization and routing logic in a way that's easier to follow and easier to test

**Review by M-ZubairAhmed — APPROVED** [review]
try/catchs are such a black holes, it absorbes any erros

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
