### PR TITLE
MM-59406- Fix wrong property set

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Fix in SAMLFeature discovery where the wrong property name was being used.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-59406

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]

**Review by marianunez — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - this is fixed

**Pull request merged**
