### PR TITLE
fix so dropping on card has latest cards objects

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Fixes issue when dropping on cards. Most recent Cards object is not being used resulting in data loss.

#### Ticket Link

  Fixes https://github.com/mattermost/focalboard/issues/4719

#### Release Note

```release-note
fixed boards issue where dropping on card object could result in losing latest edits.
```

### CODE REVIEW

**Review by mgdelacroix — APPROVED** [review]
LGTM! :+1: 

CI error seems unrelated to the change

**Comment by lindy65** [comment]
Hi @sbishel - I'm not able to create a board on the spinwick and am getting the error below. Please take a look? Thanks!

image

**Pull request closed without merging**
