### PR TITLE
MM-57096 replaced hardcoded value with a color variable

### PR DESCRIPTION
**Pull request by sohzm**
#### Summary
`Jump to recents` toast text isn't clearly visible due to background and it having less contrast in Quartz Theme. Replaced the hardcoded value with a variable, but havent verified the changes work hence added WIP.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/26394
Jira https://mattermost.atlassian.net/browse/MM-57096

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by matthewbirtch** [comment]
Adding @abhijit-singh instead for the UX review since he worked on this feature.

**Review by abhijit-singh — CHANGES_REQUESTED** [review]
Thanks @sohzm for the contribution! I'm afraid the change here would not solve the issue in all themes. I would recommend changing the background color and the text color to match that of a `primary button`.

image

- Background color of the button should use the variable `--button-bg`.
- Color for the arrow icon and the text can be `--button-color-rgb`.
  - Color for the cross icon `x` can be `--button-color-64`

Please note that the hover states will also be need to be updated. You should be able to find reference CSS for the colors under  the `.btn .btn-primary` class.

Also, here's a link to the design file for reference - [Figma file](https://www.figma.com/file/gbnx8ydTX0bTFIbJ8NWGfR/MM-53360-Scroll-to-bottom-of-chat?type=design&node-id=153-99038&mode=design&t=ldiYMqZLxr7z7lv9-4).

**Comment by matthewbirtch** [comment]
@sohzm are you still working on this or should we re-assign?

**Comment by sohzm** [comment]
@matthewbirtch Hey, sorry for the delay. I got caught up with personal issues. I'll create the updated PR this week. Thanks for your patience!

**Comment by sohzm** [comment]
@matthewbirtch I've done the changes, can you suggest better colors for hover state (if current ones dont look good)

**Comment by matthewbirtch** [comment]
@abhijit-singh can you review this one again?

**Comment by abhijit-singh** [comment]
Thanks for the changes @sohzm! I see that the colors still aren't quite right. 
image

Here's a couple additional things we can add that fill fix it for all themes: 
1. In the Jump to recents toast, let's also add the classes `btn` and `btn-primary` where we currently just have `scroll-to-bottom-toast`. These are existing classes that will also take care of the hover state.
image


2. To fix the color of the arrow icon svg, we need to make a change in the css for the class `.scroll-to-bottom-toast svg` where the fill value should be `fill: rgb(var(--button-color-rgb));` instead of the current `fill: var(--button-color-rgb);`
image


I've checked it in all themes with the above changes and it seems to be working fine. Do let me know if you have any questions.

**Comment by sohzm** [comment]
@abhijit-singh ptal

**Review by abhijit-singh — APPROVED** [review]
Looks good to me! Thank you @sohzm!

**Review by pvev — CHANGES_REQUESTED** [review]
hey @sohzm thanks for your contribution 🎉 , we are almost there, but please use rgba  i.e: `rgba(var(--button-bg-rgb), 0.88)`to add opacity where you need it since the variables --button-bg-88 and --button-color-64 are dynamically generated CSS variables created by Mattermost's theming engine and can't be used as static variables. Thanks!

**Comment by matthewbirtch** [comment]
Any update on this one? Looks like we're close

**Comment by sohzm** [comment]
@pvev PTAL

**Review by pvev — APPROVED** [review]
thank you @sohzm 🎉 , great work here 🚀

**Comment by pvev** [comment]
@harshilsharma63 could you please review this one. Thanks!

**Review by harshilsharma63 — APPROVED** [review]

**Pull request merged**
