### PR TITLE
MM-53879: Fix duplicate loading of license

### PR DESCRIPTION
**Pull request by agnivade**
We take a second stab at fixing the issue. Last time,
we were a bit too aggressive in trying to fix a lot of stuff.

I believe changing the cluster event handler had an edge case
somewhere which caused things to fail. Taking a very conservative
approach this time to only fix what is obviously wrong.

Also tested locally in a HA setup.

https://mattermost.atlassian.net/browse/MM-53879
```release-note
NONE
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
Make sense :+1:

**Comment by agnivade** [comment]
Gentle ping @nickmisasi

**Review by nickmisasi — APPROVED** [review]
Sorry for the delay. LGTM!

**Comment by agnivade** [comment]
@yasserfaraazkhan - It's a redo of the earlier PR which was reverted. Last time, we missed out on testing in HA envs. Please test this in HA along with all the license related scenarios that we did last time. Thanks!

**Comment by agnivade** [comment]
@yasserfaraazkhan - Were you able to perform the testing on this?

**Comment by yasserfaraazkhan** [comment]
> @yasserfaraazkhan - Were you able to perform the testing on this?

Hi @agnivade , I have generated selfhosted license from portal. and uploaded.
it take a bit time to reflect values correctly and sometimes needs 2 or more times license to be uploaded. 

- license was uploaded, upon returning to systemconsole, the license page was empty
https://github.com/mattermost/mattermost/assets/15979783/8be2f0fb-8ad1-4f6f-aad0-661307412095

- on license upload, it shows, invalid date, but on second upload it displayed the values correctly
https://github.com/mattermost/mattermost/assets/15979783/d582fe11-0824-4d13-b948-2b8cd15b13f9

would these be normal expected cases ?
(I'll email the test license I am using)

**Comment by agnivade** [comment]
Can you check the behavior with master?

**Comment by agnivade** [comment]
@yasserfaraazkhan - I have been noticing the same behavior that you saw in this PR to be on master as well. I don't _think_ this PR has anything to do with the behavior that we are seeing.

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
