### PR TITLE
MM-53250 Revert changes to target browser in Babel config

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
We recently updated our officially supported version of Safari to 16.2 since that's available on all versions of MacOS that we support, but that may have been a bit aggressive from the code side since other recent versions may mostly work. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-53250

#### Release Note
```release-note
Update Babel config to keep some support for older versions of Safari
```

### CODE REVIEW

**Comment by amyblais** [comment]
From Maria: Still having the same issue. Tried in incognito and same error and blank page.

**Comment by hmhealey** [comment]
Okay, in that case, I'm just going to revert that part of my change entirely then. I don't think it makes a big difference to keep the Babel environment back where it was before, and we can revisit this if we ever find that it does matter

**Comment by lindalumitchell** [comment]
https://mattermost-pr-23817.test.mattermost.cloud/ loads fine for me on two different older Safari clients (v14.x and v15.x, including in the Rainforest environment), so the fix looks good to me. 👍

**Review by lindalumitchell — APPROVED** [review]

**Comment by hmhealey** [comment]
> wow we reverted to way back versions but I think we can revisit later

Yeah, I was going to mention that to you. If we find that there's actually a big benefit to bumping the target browser, then we can do it, but we've now found that I shouldn't just update it randomly

**Review by crspeller — APPROVED** [review]
Maybe some comparative performance tests would be in order to see if there is a benefit?

**Comment by hmhealey** [comment]
> Maybe some comparative performance tests would be in order to see if there is a benefit?

Yeah, I'd definitely like to do that, but it's not a high priority at the moment. I'm sure I'll be back focusing on the web app toolchain again at some point

**Pull request merged**
