### PR TITLE
Stabilize users_reactivation_spec.js E2E testcase

### PR DESCRIPTION
**Pull request by mvitale1989**
#### Summary

Stabilize `users_reactivation_spec.js`: make it retry-ready

#### Ticket

https://mattermost.atlassian.net/browse/CLD-8719

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by mvitale1989** [comment]
cc @lieut-data the testcase should be fine now :+1:

**Review by lieut-data — APPROVED** [review]
Oh, fascinating -- thanks @mvitale1989!

As an aside, do we track retried tests to potentially triage as "flaky"? This looks to solve problem #2 from https://github.com/mattermost/mattermost/pull/29656#issuecomment-2557261597 but still curious about the wobbly scrolling bit.

(I also imagine retrying lots of tests constantly costs $$$, but don't know what the scale of the issue is.)

**Comment by mvitale1989** [comment]
That's a good idea @lieut-data , we do have a plan to [track E2E results over time](https://mattermost.atlassian.net/browse/CLD-8413), I have added your suggestion to also track retries to the ticket.
Retries were added mostly as a dev experience improvement in preparation for enforcing the E2E runs on PRs, but getting more value out of them sounds great :+1: 

The good news is that E2E tests run on Github-hosted runners since a few months, which are completely free for public repositories. So retries do not add any cost.

**Pull request merged**
