### PR TITLE
CLD-798 Add support for MM_ENV, various fixes

### PR DESCRIPTION
**Pull request by mvitale1989**
#### Summary

This PR implements the following changes:
- Support setting `MM_ENV` in the E2E fulltest. This is required to trigger the E2E tests through comments
- Add number of failures and Dashboard URL to the status check description
- Fix the `BUILD_ID` syntax, to reflect what the automation dashboard is expecting ([reference on this](https://github.com/saturninoabril/automation-dashboard/blob/175891781bf1072c162c58c6ec0abfc5bcb3520e/lib/common_utils.ts#L3-L23))
  - This is relevant for the correct tracking of flaky/known tests by the automation dashboard
  - Required some shuffling of the logic around (e.g. move ref resolution out of the template), to clean who is responsible to process which information bit
  - Includes option to specify `PR_NUMBER` instead of `ref` to trigger the tests, and simplification of BRANCH naming
- Fix dependencies in template: have the commit status updater depend on tests themselves ([example bad behaviour](https://github.com/mattermost/mattermost/actions/runs/8283001009))
- Other minor fixes and optimizations

#### Ticket Link

https://mattermost.atlassian.net/browse/CLD-7198

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by mvitale1989** [comment]
Sample pipeline started by specifying a branch in the `ref` parameter (see [this pipeline](https://github.com/mattermost/mattermost/actions/runs/8467345274)):
- The branch name is used as-is to populate `BRANCH`: https://github.com/mattermost/mattermost/actions/runs/8467345274/job/23198053459#step:4:15
- Resulting test cycle on the dashboard: https://automation-dashboard.vercel.app/cycles/373a5e62-22d0-4396-acfc-ca69883569f0
- Resulting report in the community instance: https://community.mattermost.com/core/pl/d8w67uyi1jnn3po56rpmt5t8eh
  * The webhook currently makes assumption about the branch name, and doesn't work in it. But you can see that the image tag in that message matches this run's `BUILD_ID`

Note that in [another run](https://github.com/mattermost/mattermost/actions/runs/8464996074) I also tested the `MM_ENV` variable passing, and it works as expected: https://github.com/mattermost/mattermost/actions/runs/8464996074/job/23190837199#step:5:10

**Comment by mvitale1989** [comment]
Sample pipeline started by specifying the `PR_NUMBER` parameter (see [this pipeline](https://github.com/mattermost/mattermost/actions/runs/8469098378)):
- The server PR number is used to populate `BRANCH`: https://github.com/mattermost/mattermost/actions/runs/8469098378/job/23203683844#step:4:15
- The automation dashboard URL: https://automation-dashboard.vercel.app/cycles/be4e63ed-5fa7-4fe0-9780-9afff8378e0f
  * It should also be reachable by clicking in the `E2E Test/test` status check's `Details` link. But there seems to be a problem on the side of the action. You can verify that the [target URL parameter](https://github.com/mattermost/mattermost/actions/runs/8469098378/job/23205126294#step:2:9) is built and passed correctly though
  * Also here it correctly picks up the known/flaky tests
- Resulting report on the community instance: https://community.mattermost.com/core/pl/8twnfe1ksjbhbkefa8bssntq1h
  * All links in that message work

**Review by toninis — APPROVED** [review]

**Review by saturninoabril — APPROVED** [review]
Thanks Mario!

**Pull request merged**
