### PR TITLE
[MM-56000] Add LDAP job command to mmctl

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
The PR adds a `job` subcommand to `mmctl ldap`. The command allows one to list all LDAP sync jobs and view individual ones by ID. The two commands are:
- `mmctl ldap job list`
- `mmctl ldap job show` (This one supports shell completion via ID)

The PR targets https://github.com/mattermost/mattermost/pull/26214 as it makes use of the shell completion feature added there.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-56000

#### Release Note
```release-note
Add LDAP job command to mmctl
```

### CODE REVIEW

**Comment by hanzei** [comment]
cc @ewwollesen since you are starting to get into the mmctl code base

**Review by vish9812 — APPROVED** [review]
LGTM.

**Review by BenCookie95 — APPROVED** [review]

**Comment by DHaussermann** [comment]
@hanzei I have a silly question here. How exactly is the shell completion supposed to work?

By way of example, if I know I have a job tat starts with an ID of `6fp...`  When I type `go run ./cmd/mmctl ldap job show 6fp` and then hit the `TAB` key, I expected it to start cycling through job ids but instead it just does what it always did and cycles through the relevant files in the file system that are in the working directory.

image

I feel like I've misunderstood how to use this. Also note that a I did rebuild MMCTL to test.

**Comment by hanzei** [comment]
@DHaussermann Did you setup shell completion using the [documentation](https://docs.mattermost.com/manage/mmctl-command-line-tool.html#installing-shell-completions)?

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- The new autocomplete functionality is working as expected 
- Tested various job IDs 
No issues found.

LGTM!

I will create a Jira ticket to follow-up and see of it's possible to support this in `-- local` mode.

**Pull request merged**
