### PR TITLE
[MM-55103] Replace usage of LocalizedIcon in 'rhs_card_header.tsx' with i/span tags

### PR DESCRIPTION
**Pull request by dipandhali2021**
#### Summary
This PR converts the LocalizedIcon in `rhs_card_header.tsx` to I tag

#### Ticket Link
fixes: #25107
https://mattermost.atlassian.net/browse/MM-55103

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — COMMENTED** [review]
This is incredible work, waiting for the CI

**Review by M-ZubairAhmed — APPROVED** [review]
@dipandhali2021  We're grateful for this work 🙏🏽

**Comment by dipandhali2021** [comment]
> @dipandhali2021 We're grateful for this work 🙏🏽

Thank you for your appreciation!

**Comment by M-ZubairAhmed** [comment]
@jespino gentle ping on this

**Review by jespino — APPROVED** [review]
This looks good to me. Thanks @dipandhali2021! :tada:

**Comment by jespino** [comment]
@M-ZubairAhmed sorry for the delay, I was in a conference the whole week. Now I'm back :)

**Pull request merged**
