### PR TITLE
MM-62060/MM-62276 Remove video from onboarding checklist and turn iframe-has-title ESLint rule to error

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
This replaces https://github.com/mattermost/mattermost/pull/29487 because, since I went and added a proper accessible title to that video, we decided to remove it. Even though we only now use an iframe for YouTube embeds, I still turned on the ESLint rule in case we add any more in the future.

#### Ticket Link
MM-62060
MM-62276

#### Screenshots
Screenshot 2024-12-17 at 3 27 51 PM

#### Release Note
```release-note
Removed the video from the onboarding checklist
```

### CODE REVIEW

**Review by pvev — APPROVED** [review]
LGTM! 🚀

**Review by marianunez — APPROVED** [review]
LGTM. However, for cherrypicking we probably need to exclude the linter rule change as those are not in previous versions

**Comment by hmhealey** [comment]
> LGTM. However, for cherrypicking we probably need to exclude the linter rule change as those are not in previous versions

Good point. In retrospect, I shouldn't have included it because of that, but at this point, it's just as easy to do that cherry-pick manually

**Pull request merged**
