### PR TITLE
Pre-package Playbooks v1.38.0

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
Pre-package Playbooks v1.38.0.

#### Ticket Link
Fixes: https://mattermost.atlassian.net/browse/MM-53678

#### Release Note
```release-note
Pre-package Playbooks v1.38.0
```

### CODE REVIEW

**Review by sbishel — APPROVED** [review]

**Comment by lieut-data** [comment]
All e2e tests passed, and smoketest of cloud server confirms upgraded version.

**Comment by lieut-data** [comment]
@saturninoabril, anything else you'd like to see before we merge (see e2e test comments above).

**Review by cpoile — APPROVED** [review]

**Pull request merged**
