### PR TITLE
[MM-40045] add checks for admin user in PermanentDeleteUser

### PR DESCRIPTION
**Pull request by titanventura**
#### Summary

Check if the user's email exists in any of the team table's email field before deleting the user.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/19997
Jira https://mattermost.atlassian.net/browse/MM-43447

#### Release Note

```release-note
NONE

```

### CODE REVIEW

**Comment by titanventura** [comment]
@isacikgoz @Haliax please take a look at this

reference: https://community.mattermost.com/core/pl/n361swdsmb8hurkrpzbbhqizsa

**Comment by hanzei** [comment]
@titanventura Would you please fix the linter issues? I will request developer reviews, once that is done.

**Comment by hanzei** [comment]
@titanventura Heads up that some tests are failing.

**Comment by titanventura** [comment]
refer pull #25813

**Pull request closed without merging**
