### PR TITLE
Removes the backslash in migrations.list

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
The use of the backslash was causing issues between different versions of make.

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
CI fails. I think you have to fix this at the CI level somewhere.

**Comment by mgdelacroix** [comment]
I have a second low hanging fruit approach, let me see if this works...

**Comment by mgdelacroix** [comment]
It doesn't strictly find a fix for the issue with the backslash, but it does fix the problem between different `make` versions dealing with it :)

Let me know what you think

**Review by agnivade — APPROVED** [review]
Neat :)

**Review by isacikgoz — APPROVED** [review]
lgtm!

**Pull request merged**
