### PR TITLE
Fix MM:24226

### PR DESCRIPTION
**Pull request by yash2189**
Remove unnecessary debug statements as a fix for [24226](https://github.com/mattermost/mattermost/issues/24226)

#### Summary

This PR removes debug statement added [here](https://github.com/mattermost/mattermost/blob/e39b485c4b769ec3c89d2490eee67fcc07b7ae88/server/channels/app/platform/cluster_handlers.go#L162 ) which is not required.
#### Ticket Link

https://mattermost.atlassian.net/browse/MM-53957
#### Release Note

```release-note
```

### CODE REVIEW

**Comment by yash2189** [comment]
Closes https://github.com/mattermost/mattermost/issues/24226

**Comment by hanzei** [comment]
@yash2189 Test are running :runner:

**Review by isacikgoz — APPROVED** [review]

**Pull request merged**
