### PR TITLE
Improve E2E tests README for readability

### PR DESCRIPTION
**Pull request by armmanvaillancourt**
#### Summary

Sorry for being pedantic, but I was reading the README before contributing to updating some tests. I noticed that the README could use some light stylistic improvements for spelling and readability.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by saturninoabril — APPROVED** [review]
Thanks @armmanvaillancourt, LGTM!

**Comment by hanzei** [comment]
@cwarnermm Gentle reminder to review the PR :wink:

**Review by cwarnermm — APPROVED** [review]
Thank you, @armmanvaillancourt!!

**Pull request merged**
