### PR TITLE
MM-61782 - fix invalid time when changing to today after 9 am

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
Validate if the hour for today is before 9:a.m.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-61782

#### Screenshots
https://github.com/user-attachments/assets/3c205f8c-47f1-4fc4-a756-db31604ffc04

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by pvev** [comment]
@harshilsharma63 this is just an attempt to solve that bug, but I am not sure this is not going to add regressions to the changes you made on https://github.com/mattermost/mattermost/pull/29215.

**Comment by harshilsharma63** [comment]
The CI error will be fixed by https://github.com/mattermost/mattermost/pull/29283

**Review by harshilsharma63 — APPROVED** [review]
I've pushed a change to reset time if current time is ahead of selected time, instead of depending on hardcoded 9 am.

**Review by larkox — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
