### PR TITLE
Simplify request generation in store tests

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
In the future, a lot more methods in store will use `request.CTX`. To simplify the creation of a request context, the root function of the store tests  `StoreTest` takes care of the creation and passes the context down to the actual tests. https://github.com/mattermost/mattermost/pull/25422/commits/6a4908d1c26593454947d3ee608eeebafac653b4 contains these changes. The commit is 99% find and replace.

https://github.com/mattermost/mattermost/pull/25422/commits/2b71fd5c3a3a71524a44cdd7f1b769417d98319f contains manual cleanup. Most calls to  `request.TestContext` were removed as the context generation happens at the root test.

Lastly, https://github.com/mattermost/mattermost/pull/25422/commits/29ba72b05062e16be85fb2a99e5845d693bffb7b contains a cleanup for `TestBatchMigrationWorker`.

Please note that the PR only touches tests; no production code is changed.

#### Ticket Link
NONE

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by fmartingr — APPROVED** [review]
👌  Looks good and consistent, thank you!

**Review by agnivade — APPROVED** [review]
Lots of great work there Ben!

**Comment by amyblais** [comment]
The PR touches tests, but I think we can take this into v9.4 unless there is a specific reason we want to include this in v9.3 - let me know!

**Comment by hanzei** [comment]
@amyblais, I mistakenly added the PR to v9.3. v9.4 is totally fine.

**Pull request merged**
