### PR TITLE
MM-61731 - enhance failed sent system bot message

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
Enhance the message details for the system-bot message sent during the failed scheduled messages event.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-61731

#### Screenshots
Screenshot 2024-11-13 at 19 55 31
Screenshot 2024-11-13 at 21 09 48

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by harshilsharma63 — APPROVED** [review]
LGTM!

**Review by yasserfaraazkhan — COMMENTED** [review]
thank you @pvev

I checked for 
- achieved channel ✅ 
- read only✅ 
- deactivated user✅ 
- private channel✅ 
- deleted root thread✅ 
Please let me know if anyother scenarios we need to check.

@pvev @asaadmahmood 
In case of Private Channel.

If a user is removed from a Private channel, where they had a scheduled message. The system bot will expose the Private channel name.

example : It will say  `1 in channel Private-Top-Secret-channel. Reason: No permission to post in channel`

should it say something else and not expose the Private channel name

**Comment by pvev** [comment]
> thank you @pvev
> 
> I checked for
> 
> * achieved channel ✅
> * read only✅
> * deactivated user✅
> * private channel✅
> * deleted root thread✅
>   Please let me know if anyother scenarios we need to check.
> 
> @pvev @asaadmahmood In case of Private Channel.
> 
> If a user is removed from a Private channel, where they had a scheduled message. The system bot will expose the Private channel name.
> 
> example : It will say `1 in channel Private-Top-Secret-channel. Reason: No permission to post in channel`
> 
> should it say something else and not expose the Private channel name

Thanks @yasserfaraazkhan , nice catch about the private channel name exposed. I'd say we should say something like unknown error and no expose the channel name. Will wait for confirmation from @asaadmahmood before applying that change.

**Review by devinbinnie — APPROVED** [review]

**Pull request merged**
