### PR TITLE
Update store badges on README.md

### PR DESCRIPTION
**Pull request by aayushborkar14**
#### Summary

This PR updates the Play Store and Apple App Store badges on README.md. Google has suggested at [their website](https://play.google.com/intl/en_us/badges/) to not use outdated logos:
Untitled

The updated logos are:
google-play-badge_trim
Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917

#### Screenshots
|  before  |  after  |
|----|----|
| image | image |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by jespino** [comment]
@aayushborkar14 to be able to apply this changes we need you to sign the CLA, it is explain in the previous comment and it is a very straight forward process.

**Review by jespino — APPROVED** [review]
Really nice improvement. Thanks @aayushborkar14! :tada:

**Review by jasonblais — APPROVED** [review]
Well done, thank you for your contribution!

**Comment by jasonblais** [comment]
@jespino would you have visibility on how we can unblock merging this PR?

**Comment by jespino** [comment]
Let me see if I can get this merged

**Comment by jespino** [comment]
@saturninoabril you faced a similar problem lately, right?

**Comment by saturninoabril** [comment]
Yup, I'm seeing that too but honestly, didn't know how it's fixed. I'll look at this.

**Pull request merged**
