### PR TITLE
[MM-57071] Use bool for license_is_trial in Support Packet

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
The PR updates the support packet in a couple of small ways:
- https://github.com/mattermost/mattermost/pull/26378/commits/67275a82e66e82485ec37553f0caba3d91f05fb0 converts `license_is_trial` from a `string` to a `bool` which makes it easier to parse.
- https://github.com/mattermost/mattermost/pull/26378/commits/8ab7a4d591833065c386f6e776533872befbbfad groups the server stats code together so it's easier to read from where things get fetched
- https://github.com/mattermost/mattermost/pull/26378/commits/aa6465c8d6fee865d285bbe6ee444046741c7dc4 adds error checks for a couple of methods that previously didn't get checked.
- https://github.com/mattermost/mattermost/pull/26378/commits/86bb22af716a695ee8c2635013c15a200146754e removes `omitempty` from `BuildHash` and `LicenseSupportedUsers`. These fields should always be present.
- https://github.com/mattermost/mattermost/pull/26378/commits/23dfc131c35ef2ceb0c11a3e8d718b382373c89d updates the code style to be uniform with other parts in the same file. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-57071

#### Release Note
```release-note
Use bool for license_is_trial in Support Packet
```

### CODE REVIEW

**Review by vish9812 — APPROVED** [review]
LGTM

**Review by JulienTant — APPROVED** [review]
LGTM

**Comment by hanzei** [comment]
@DHaussermann There are not a lot of "material" changes in the PR. It's mostly about rendering and cleaning up code. The only user-facing change is that the `license_is_trial` field is now a boolean, which is covered by tests. Do you think this PR requires manual QA testing?

**Review by DHaussermann — APPROVED** [review]
Sorry for the delay @hanzei. Yes, I think it's fine for this PR to merge now and I will manually test post-merge. 

Please merge when you have chance.

**Pull request merged**
