### PR TITLE
Revert "MM-53879: Fix recursive loading of license"

### PR DESCRIPTION
**Pull request by agnivade**
Reverts mattermost/mattermost#24200

The PR missed testing in HA scenarios and introduced a regression. Reverting for now.

@agarciamontoro - We can probably pin to the exact version of 8.1 you are using to prevent regressing to the old behavior again.

https://mattermost.atlassian.net/browse/MM-54442

### CODE REVIEW

**Review by nickmisasi — APPROVED** [review]
Thanks @agnivade!

**Review by streamer45 — APPROVED** [review]

**Comment by agnivade** [comment]
I will send a manual cp to 8.1

**Pull request merged**
