### PR TITLE
MM-55973: Make keyboard shortcuts modal content div accessible via keyboard

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Make keyboard shortcuts modal content div accessible via keyboard

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-55973

#### Screenshots

https://github.com/mattermost/mattermost/assets/16203333/f78e7161-eb08-4c0c-a09d-03ac4d6aab96

#### Release Note

```release-note
UI: Make keyboard shortcuts modal content div accessible via keyboard
```

### CODE REVIEW

**Review by marianunez — APPROVED** [review]
Thanks @AshishDhama!

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Comment by lindy65** [comment]
Hi @AshishDhama 

While testing on the spinwick, I'm seeing weird behavior where somehow, the left/right key and PageUp/Down actions stop working after some time (the cursor seems to lose focus/disappear from the modal?)

My steps:
1. Open shortcut key modal using CTRL/CMD+/
2. Use down arrow key to move all the way to the bottom of the modal
3. Use the up arrow key to move all the way to the top of the modal
4. Press PageDown to the bottom of the modal
5. Press PageUp to the top of the modal
6. Try using the down arrow key to move down in the modal (also try using the PageDown key)

Observed: Down/Up arrow keys no longer work, nor do PageUp/Down keys work

The only thing I see in the js.console is
image

**Comment by AshishDhama** [comment]
@lindy65 
Was the Modal content div highlighted like here, I have used a tab to make it accessible via the up/down arrow.

https://github.com/mattermost/mattermost/assets/16203333/19ab6d4a-46ae-4f62-abbe-d6bb53b657a1

**Comment by lindy65** [comment]
No, nothing is highlighted within or around the modal
image

Can you try my steps on the spinwick Ashish?

Is this a desktop app only fix?  I am testing on Win/Chrome/browser

**Comment by lindy65** [comment]
Hey @marianunez - I was having issues testing this on the spinwick and Ashish and I chatted and shared screen captures offline in MM.

I'm concerned that the flow of how this works is not obvious to the end-user because it was not obvious to me. These are the steps Ashish told me to use:
1. CTRL/CMD+/ to open the modal
2. TAB to activate the modal contents
These steps work but how does the user know to do this? Do you think that (in a separate PR) some help text can be added at the top of the modal that tells the user how to navigate with the keyboard?

I also found that after navigating around the modal for some time using up/down arrows and PageUp/Down keys there's a certain point (probably after 20 or so up/down arrow and Pageup/Down usages) the functionality no longer works and neither up/down arrow keys nor PageUp/Down works anymore. Ashish is looking into this as he doesn't seem to be able to replicate on the spinwick what I am seeing.  I'm testing on Win10/Chrome/browser.

**Comment by marianunez** [comment]
> * CTRL/CMD+/ to open the modal
> * TAB to activate the modal contents
>   These steps work but how does the user know to do this?

Agreed that this intuitive to need to Tab to set focus. Also, if you open the modal by clicking the help menu > keyboard shortcuts, the arrow keys don't work until you click on the modal to bring focus. The original ticket mentioned they clicked to open the menu. We should auto focus the dialog as soon as it's opened either by the key commands or clicking in the menu so the navigation with the keyboard is ready to be used. cc// @matthewbirtch for any other UX input on this

**Comment by AshishDhama** [comment]
@matthewbirtch Are you suggesting this?

https://github.com/mattermost/mattermost/assets/16203333/f080beb2-a2aa-40eb-84f4-37c9e88acad6

There will be some edge cases here as well.
About autofocusing, it will not work if the user clicks somewhere outside.
https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/
I checked the scrollable Modal example: They are overflowing the whole modal instead of scrolling inside the modal.

**Comment by AshishDhama** [comment]
@matthewbirtch As per w3cag solution is this.

Uploading Screen Recording 2024-06-21 at 10.04.56 PM.mov…

Based on codepen example here https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/

cc// @hmhealey

**Comment by matthewbirtch** [comment]
> @matthewbirtch As per w3cag solution is this.
> 
> Uploading Screen Recording 2024-06-21 at 10.04.56 PM.mov…
> 
> Based on codepen example here https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/
> 
> cc// @hmhealey

Looks like the video didn't finish uploading @AshishDhama. Could you retry?

**Comment by lindy65** [comment]
Thanks @marianunez and @matthewbirtch.  I did not realise this was an accessibility fix only so I was not testing with JAWS or similar tool.

Confirm once Ashish has done the necessary changes that PageUp/Down should also still work in the modal?

**Comment by AshishDhama** [comment]
https://github.com/mattermost/mattermost/assets/16203333/3b387b95-9655-40cb-bdb2-34cc3b464de9

**Comment by AshishDhama** [comment]
@hmhealey @matthewbirtch Could you please suggest the path forward here.

**Comment by matthewbirtch** [comment]
Ok, @AshishDhama doing some reading and more research on this, I'm sorry if I misdirected you. I'm still learning stuff about accessibility here. 

So here's what I propose:
- Since the content within the modal is non-interactive, making each shortcut tabbable isn't necessary. Apologies for that. The content can all be read using the standard screen reader shortcuts, so I think we're good on that without having them tabbable.
- If we can make the UP/DOWN arrows and PAGE UP/PAGE DOWN keys scroll without having to hit TAB first that would be best, but I'm not sure that's possible. If we have to TAB to it first, that's still an improvement.

**Comment by AshishDhama** [comment]
@matthewbirtch @lindy65 

https://github.com/mattermost/mattermost/assets/16203333/f78e7161-eb08-4c0c-a09d-03ac4d6aab96

**Comment by matthewbirtch** [comment]
Looks good in the video @AshishDhama. Will test it out

**Review by matthewbirtch — APPROVED** [review]
Works great @AshishDhama. Thanks for making this improvement

**Review by lindy65 — APPROVED** [review]
Thanks for all your hard work on this one @AshishDhama. Looks good to me now, no issues with up/down arrow keys or PageUp/Down 👍

**Pull request merged**
