### PR TITLE
remove Stripe CSP from server

### PR DESCRIPTION
**Pull request by nickmisasi**
#### Summary
Removes the Stripe CSP from server as it's no longer necessary.

#### Ticket Link
https://mattermost.atlassian.net/browse/CLD-8552
#### Release Note

```release-note
None
```

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
Nice! (Tests /might/ need to be updated?)

**Comment by nickmisasi** [comment]
@lieut-data yep! I had *test* filtered in my editor when I searched :P thanks!

**Review by gabrieljackson — APPROVED** [review]
LGTM

**Pull request merged**
