### PR TITLE
[MM-60843]  Replace FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/plugin_management/plugin_management.tsx' with FormattedMessage

### PR DESCRIPTION
**Pull request by Aryakoste**
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28591
Jira https://mattermost.atlassian.net/browse/MM-60843
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Comment by M-ZubairAhmed** [comment]
@Aryakoste please update snapshots of test

**Review by Rajat-Dabade — APPROVED** [review]
Apart from @M-ZubairAhmed comments, LGTM.

**Pull request merged**
