### PR TITLE
[MM-58440] Migrate tooltips of 'components/post_view/post_flag_icon' to WithTooltip

### LINKED ISSUE #27177: Migrate tooltips of 'components/post_view/post_flag_icon' to WithTooltip
The purpose of this ticket is to eliminate the usage of **OverlayTrigger** from “components/overlay_trigger” and \***Tooltip**\* of “components/tooltip” in the file `webapp/channels/src/components/post_view/post_flag_icon/post_flag_icon.tsx` . These should be replaced with the \***WithTooltip**\* component from “components/with_tooltip”. 
For reference, please follow these PRs: 

- https://github.com/mattermost/mattermost/pull/26458

- https://github.com/mattermost/mattermost/pull/27146
- https://github.com/mattermost/mattermost/pull/27145

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-58440

### PR DESCRIPTION
**Pull request by ZubairImtiaz3**
#### Summary
The changes ensure that the tooltip in "components/post_view/post_flag_icon" now utilizes the WithTooltip component, replacing the previous usage of OverlayTrigger and Tooltip.

#### Ticket Link
Fixes #27177
Jira: [MM-59329]( https://mattermost.atlassian.net/browse/MM-58440)

### Screenshot
<a href="https://ibb.co/nMSqCDT">Screenshot-2024-07-17-164042</a>

#### Release Note

```release-note
NONE
```

[MM-59329]: https://mattermost.atlassian.net/browse/MM-59329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by Rajat-Dabade — APPROVED** [review]

**Comment by ZubairImtiaz3** [comment]
@M-ZubairAhmed I've noticed that the CI test is failing on src/utils/performance_telemetry/reporter.test.ts with the test PerformanceReporter › should report some marks to the server as counters. However, I think this test is unrelated to the changes introduced in this PR.

Additionally, when I run the same test locally, it passes without any issues. Could you please advise me how to proceed with this?

<a href="https://ibb.co/tDWHyWy">Screenshot-2024-07-19-181948</a>

<a href="https://ibb.co/j4kVL7R">Screenshot-2024-07-19-185355</a>

**Comment by M-ZubairAhmed** [comment]
> @M-ZubairAhmed I've noticed that the CI test is failing on src/utils/performance_telemetry/reporter.test.ts with the test PerformanceReporter › should report some marks to the server as counters. However, I think this test is unrelated to the changes introduced in this PR.
> 
> Additionally, when I run the same test locally, it passes without any issues. Could you please advise me how to proceed with this?
> 
> [Screenshot-2024-07-19-181948](https://ibb.co/tDWHyWy)
> 
> [Screenshot-2024-07-19-185355](https://ibb.co/j4kVL7R)

Yeah it looks like a flaky test here, i will report internally

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
