### PR TITLE
Update index.ts (Filter archived channel from dropdown)

### PR DESCRIPTION
**Pull request by TheInvincibleRalph**
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28311

```release-note
NONE
```

### CODE REVIEW

**Comment by TheInvincibleRalph** [comment]
Hi @BenCookie95, here is the updated pull request based on your review, Thank you!

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @TheInvincibleRalph!

**Review by BenCookie95 — APPROVED** [review]
LGTM, thanks!

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by TheInvincibleRalph** [comment]
Thank you, @BenCookie95, @devinbinnie and @yasserfaraazkhan!

**Comment by TheInvincibleRalph** [comment]
Did a check on the test server and it's all working fine (archived channels are no longer included in the dropdown).

**Comment by BenCookie95** [comment]
Merged, thanks for the contribution @TheInvincibleRalph

**Pull request merged**
