### PR TITLE
fix: Fix about modal version for cloud installations

### PR DESCRIPTION
**Pull request by toninis**
#### Summary

Fix about cloud modal cloud.

#### Related PR
https://github.com/mattermost/mattermost/pull/25370
 
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by toninis** [comment]
@amyblais We will only have to cherry pick this to 9.2 release 😄

**Comment by amyblais** [comment]
@toninis Do we need another dot release for v9.2?

**Comment by toninis** [comment]
> @toninis Do we need another dot release for v9.2?

If we want this fix to the cloud servers unfortunately yes 😔

**Comment by amyblais** [comment]
I'm thinking we don't need to do a dot release just for this. We can either queue this for v9.3, or for a v9.2 dot release if there is a dot release needed to backport security fixes.

**Comment by toninis** [comment]
> I'm thinking we don't need to do a dot release just for this. We can either queue this for v9.3, or for a v9.2 dot release if there is a dot release needed to backport security fixes.

Agreed ✅ . We are going to deploy 9.3 to cloud in a month . Seems legit 😄

**Review by saturninoabril — APPROVED** [review]
Thanks @toninis!

@amyblais I agree that this is aesthetic change only but might be confusing for Cloud users (specifically in webapp/desktop) to see the "ci" version especially as they referenced it when reporting an issue. Now that we're releasing on monthly unless another dot release is required, it will take longer before it's replace with the new one.

**Comment by amyblais** [comment]
> Now that we're releasing on monthly unless another dot release is required, it will take longer before it's replace with the new one.

There are some upcoming security fixes that need to be backported, so I'm confident that there will be a dot release before next month.

**Review by lieut-data — APPROVED** [review]
No changes needed, but I'd be interested in possibly just eliminating the `_cloud` version of this altogether -- cc @nickmisasi in case you know if this is viable?

**Comment by marianunez** [comment]
> No changes needed, but I'd be interested in possibly just eliminating the `_cloud` version of this altogether -- cc @nickmisasi in case you know if this is viable?

The About cloud modal shows a subset of information than the self-hosted modal, it gets the customer name differently as well as it depends on the subscription and also doesn't show the terms and policy links in cloud (can't remember the details why). I think we probably still need to keep it, see the differences below: 

Self-hosted: 
Screen Shot 2023-11-10 at 1 27 48 PM



Cloud: 

Screen Shot 2023-11-10 at 1 27 58 PM

**Review by marianunez — APPROVED** [review]

**Pull request merged**
