### PR TITLE
MM-59347 Fix spacing issue in data retention card headers

### PR DESCRIPTION
**Pull request by matthewbirtch**
#### Summary
Fixes a display issue where buttons aren't properly aligned/spaced in the data retention screen in the system console

#### Ticket Link
Jira https://mattermost.atlassian.net/browse/MM-59347

#### Screenshots
|  before  |  after  |
|----|----|
| image | image |

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by JulienTant — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Thanks @matthewbirtch - ‘Add policy’ and ‘Run Deletion job Now’ buttons are right-aligned within the container

**Review by calebroseland — APPROVED** [review]

**Comment by matthewbirtch** [comment]
@calebroseland or @JulienTant could you help merge this? Reviews are complete, but I don't have access to merge myself

**Comment by matthewbirtch** [comment]
Sorry to bug again, but @calebroseland or @JulienTant could I ask your help to merge?

**Comment by calebroseland** [comment]
On it, @matthewbirtch. Sorry this slipped through the cracks.

**Pull request merged**
