### PR TITLE
Missing french translations for at here and group members

### PR DESCRIPTION
**Pull request by Boruus**
#### Summary
Add missing translations in french for at here (missing plural) in a channel and group member translation where missing in french.

#### Screenshots
|  Before  |  After  |
|----|----|
| image |  image  |
| image | image |
| | |

#### Release Note

```release-note
Missing french translations for at here and group members
```

### CODE REVIEW

**Comment by Boruus** [comment]
> Hello @Boruus,
> 
> Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).
> 
> Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.
> 
> **Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?** Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.
> 
> This is a standard procedure for many open source projects.
> 
> Please let us know if you have any questions.
> 
> We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

/check-cla

**Comment by ctlaltdieliet** [comment]
Hi @boruus,
thank you for your contributions. 
Our translations are done trough [Weblate.](https://translate.mattermost.com_
You need to create an account for that and for French which is a shipped language, you initially can only make suggestions but I can promote you to translator. 

You can find more information at [our handbook](https://handbook.mattermost.com/contributors/join-us/localization)

Feel free to join our [l10n-channel](https://community.mattermost.com/core/channels/localization) at the Mattermost community server.

**Comment by Boruus** [comment]
> Hi @Boruus, thank you for your contributions. Our translations are done trough [Weblate.](https://translate.mattermost.com_ You need to create an account for that and for French which is a shipped language, you initially can only make suggestions but I can promote you to translator.
> 
> You can find more information at [our handbook](https://handbook.mattermost.com/contributors/join-us/localization)
> 
> Feel free to join our [l10n-channel](https://community.mattermost.com/core/channels/localization) at the Mattermost community server.

Thank you for your reply and the information, I'm interested in becoming a translator so that I can offer translations directly in french. I will also check the handbook and join the channel.

**Comment by ctlaltdieliet** [comment]
Thank you @Boruus 
I found your account in Weblate and granted you permissions to translate French.

**Pull request closed without merging**
