### PR TITLE
Cypress/E2E: fix tests

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Fixed E2E tests

#### Ticket Link
none

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by yasserfaraazkhan — APPROVED** [review]
tests have passed

**Comment by saturninoabril** [comment]
@mvitale1989 Gentle pin, if you get a chance. TIA.

**Review by mvitale1989 — APPROVED** [review]
LGTM, thanks Saturn! And nice gif :smile:

**Pull request merged**
