### PR TITLE
Update file_helper_test.go (fix errcheck issue)

### PR DESCRIPTION
**Pull request by TheInvincibleRalph**
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28925

```release-note
NONE
```

### CODE REVIEW

**Comment by TheInvincibleRalph** [comment]
Hi, @hanzei. Is there something I need to do on my side concerning the failing test?

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Review by fmartingr — APPROVED** [review]
👍 thank you!

**Pull request merged**
