### PR TITLE
MM-57079 - Fixing extra spacing in blockquote

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-57079 - Fixing extra spacing in blockquote

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-57079

#### Screenshots
CleanShot 2024-11-05 at 21 36 28@2x

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]

**Review by larkox — APPROVED** [review]

**Comment by lindy65** [comment]
Hi @asaadmahmood - there are some failing checks, the spinwick will not build without them passing. Please check, thanks!

**Comment by lindy65** [comment]
Hey @asaadmahmood 

In your screenshots, the quoted text is left-aligned in both the post and preview

I'm not seeing the quoted text left-aligned in my post or preview

image

image

**Review by lindy65 — APPROVED** [review]
Chatted to Asaad offline and what I'm seeing with the alignment is expected, approving.

**Pull request merged**
