### PR TITLE
Mm 24857 specific logger in post go

### PR DESCRIPTION
**Pull request by js029**
#### Summary
Replace global mlog with local c.Logger
Additionally, replace SetInvalidParam with SetInvalidParamWithErr where relevant

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/24857

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by hanzei — APPROVED** [review]

**Comment by hanzei** [comment]
Thanks for the contribution @js029 :+1:

**Review by isacikgoz — APPROVED** [review]
LGTM!

**Comment by hanzei** [comment]
Thanks for the contribution @js029 :tada:

**Pull request merged**
