### PR TITLE
MM-61503 Updated golangci.yml configuration

### PR DESCRIPTION
**Pull request by willypuzzle**
#### Summary
Removed a line from the golangci.yml file that was excluding a specific go file from linting. This will now allow the linter to check this file for any potential issues.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/29107
Jira https://mattermost.atlassian.net/browse/MM-61503

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by willypuzzle** [comment]
Please, would you assign me this PR?

**Comment by willypuzzle** [comment]
@hanzei could you rerun the failed job, it's not relevant for PR

**Comment by willypuzzle** [comment]
in the "Server CI PR / pr-ci / Postgres with binary parameters / Postgres with binary parameters (pull_request)" there is this error:

`{"timestamp":"2024-11-13 16:33:07.813 Z","level":"error","msg":"Error while invalidating channel member cache","caller":"platform/web_hub.go:524","user_id":"muwszr3i37nu9payorza66xtay","error":"failed to find ChannelMembers, TeamScheme and ChannelScheme data: pq: relation \"channelmembers\" does not exist"}`

It seems like some migration is undone. But I haven't touched any code.

**Review by hanzei — APPROVED** [review]
It seems like the errors got fixed in the meantime. LGTM

**Pull request merged**
