### PR TITLE
MM-56583 - Updating settings css for only centre content scroll

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-56583 - Updating settings css for only centre content scroll

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-56583
Fixes https://mattermost.atlassian.net/browse/MM-56637

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by amyblais** [comment]
@calebroseland Let me know if you're able to help prioritize this PR review before Friday (we can also request a review from another dev as needed if the timeline is too short).

**Comment by calebroseland** [comment]
> @calebroseland Let me know if you're able to help prioritize this PR review before Friday (we can also request a review from another dev as needed if the timeline is too short).

Hi @amyblais, yes, I'll get this reviewed shortly here

**Review by larkox — APPROVED** [review]

**Comment by larkox** [comment]
@asaadmahmood Does this need QA review? (I don't see the label, so doublechecking)

**Comment by asaadmahmood** [comment]
@lindy65 Can you also test this on different browsers on your end too to make sure its working?

**Review by lindy65 — APPROVED** [review]
Thanks @asaadmahmood - tested on Chrome and Firefox and looks good to me 👍

**Pull request merged**
