### PR TITLE
[MM-60262] Respect config store option when creating platform service

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
I considered adding a test, but it isn't easy to abstract away the unnecessary initialization parts.
In a way, https://github.com/mattermost/mattermost-compliance-export/pull/5 works as a test, as that's why I ran into this bug.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-60262

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
Makes sense. Thanks for taking care of this!

**Review by agnivade — COMMENTED** [review]
On a deeper look, this is still not 100% problem-free. Not that this PR added a new problem, but it already existed.

See L120: you can already set `ps.configStore` via `sc.ConfigStore`, and you can do the same thing again with a `platform.Option`!

Looking at the code, I see this is only used in tests, in a mixed up way. I think we should remove `ConfigStore` field from `ServiceConfig` and allow it to be only set from `Option`.

For example, this code in notification_push_test.go will change from:

```go
s.platform, err = platform.New(
		platform.ServiceConfig{
			ConfigStore: memoryStore,
		},
		platform.SetFileStore(&fmocks.FileBackend{}),
		platform.SetExportFileStore(&fmocks.FileBackend{}),
		platform.StoreOverride(mockStore))
```

to 

```go
s.platform, err = platform.New(
		platform.ServiceConfig{},
		platform.ConfigStore(memoryStore),
		platform.SetFileStore(&fmocks.FileBackend{}),
		platform.SetExportFileStore(&fmocks.FileBackend{}),
		platform.StoreOverride(mockStore))
```

**Review by agnivade — APPROVED** [review]
Nice!

**Comment by agnivade** [comment]
Feel free to merge at your convenience, Ben.

**Pull request merged**
