### PR TITLE
ICU Fixathon - clean up React.Fragment old syntax

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
This PR enhances code readability and aligns with modern React best practices by refactoring all instances of `<React.Fragment>` to the concise `<>` syntax.

#### Ticket Link
n/a

#### Screenshots
n/a

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Makes sense to me. I wonder if there's an ESLint rule we can use to force this, but I don't think that it's something we need to enforce

**Comment by KuSh** [comment]
> ESLint

There's https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md

**Comment by hmhealey** [comment]
> > Makes sense to me. I wonder if there's an ESLint rule we can use to force this, but I don't think that it's something we need to enforce
> 
> There's https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md

Perfect, thanks!

@pvev Could you enable that rule in `webapp/platform/eslint-plugin` to ensure people stick with this?

**Comment by pvev** [comment]
@hmhealey lint rule enforced:

when key is needed, won't enforce the rule.
Screenshot 2024-11-07 at 17 09 29

will enforce usage of short version
Screenshot 2024-11-07 at 17 09 44

**Review by devinbinnie — APPROVED** [review]
I much prefer this syntax as well, nice fix :)

**Pull request merged**
