### PR TITLE
Added badges in readme

### PR DESCRIPTION
**Pull request by barbarian360**
## Updation in readme

Added some badges in readme to provide more effective look of readme.

## Screenshot
image

### CODE REVIEW

**Comment by pvev** [comment]
@barbarian360 please, complete the cla signature process. Thanks.

**Comment by barbarian360** [comment]
> @barbarian360 please, complete the cla signature process. Thanks.

DONE.

**Comment by lieut-data** [comment]
Hi @barbarian360 -- I appreciate the effort you put into setting this up!

At this time, we are not looking to adopt this style for our README.md. The GitHub chrome itself offers much of this information already, and I think it would detract from our styling to duplicate this.

In general, I'd encourage you to raise an issue or ask over at https://community.mattermost.com/core/channels/developers if you want to get feedback on an idea before putting in any work.

**Pull request closed without merging**
