### PR TITLE
[MM-58518] Migrate tooltips of "components/copy_text.tsx" to WithTooltip

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/27228
https://mattermost.atlassian.net/browse/MM-58518

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by Rajat-Dabade — APPROVED** [review]

**Review by yasserfaraazkhan — CHANGES_REQUESTED** [review]
Screenshot 2024-06-20 144618

a couple of cypress tests related to copy icon are failing. Seems a locator should be updated

**Review by mickmister — APPROVED** [review]

**Comment by M-ZubairAhmed** [comment]
> Screenshot 2024-06-20 144618
> 
> a couple of cypress tests related to copy icon are failing. Seems a locator should be updated

Affected E2E are now fixed

**Review by yasserfaraazkhan — APPROVED** [review]
Thank you Zubair

**Pull request merged**
