### PR TITLE
[MM-54750] Theme color sidebarHeaderTextColor is used with different backgrounds

### PR DESCRIPTION
**Pull request by abdesslamhouioui**
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-54750

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by abdesslamhouioui** [comment]
@M-ZubairAhmed 
image

**Comment by abdesslamhouioui** [comment]
@M-ZubairAhmed 
image

**Review by matthewbirtch — APPROVED** [review]
Looks good to me. Thanks @abdesslamhouioui! Are you willing to submit a PR for mobile as well as [described in the issue](https://github.com/mattermost/mattermost/issues/25702#issuecomment-1915790402)?

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by abdesslamhouioui** [comment]
@M-ZubairAhmed 
who has the authorization to merge my pull request ?

**Review by larkox — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
