### PR TITLE
Update user limits error code

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Update user limits error code text to reference safety limits within free version. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-56318 

#### Release Note

```release-note
None
```

### CODE REVIEW

**Comment by marianunez** [comment]
@amyblais this is a small text change we need to include for v9.5 - should have no major risks as it's only wording change

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by harshilsharma63 — APPROVED** [review]
Looks good!

**Review by johndavidlugtu — APPROVED** [review]

**Comment by marianunez** [comment]
@yasserfaraazkhan I've made a small text change to the banner error code in this PR. Can you do a quick pass in v9.5 once it lands after the cherry pick to validate the new text?

**Comment by yasserfaraazkhan** [comment]
Sure @marianunez
will update once test installations are updated.

**Pull request merged**
