### PR TITLE
MM-54555 - Include channel name in error

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary

Fixes ephemeral message when adding a user to a different channel. 

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-54555

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by sbishel** [comment]
Screenshot 2023-09-27 at 12 50 26 PM

**Comment by amyblais** [comment]
@calebroseland @BenCookie95 Please help prioritize reviews ahead of this Friday's v9.1 code freeze deadline.

**Review by BenCookie95 — APPROVED** [review]

**Review by saturninoabril — APPROVED** [review]
Thanks! Tested and passed.

**Pull request merged**
