### PR TITLE
[MM-56824] Componentize the Mobile and Desktop section headers in the user settings modal.

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
- The modal section header in mobile view is extracted into common component `SettingMobileHeader` and used in all tabs
- The modal section header in desktop view is extracted into common component `SettingDesktopHeader` and used in all tabs
- `user_settings/index.tsx` is converted to functional component

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-56824

#### Screenshots
none

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
