### PR TITLE
[MM-55180] Cut off text in the Position field in the profile modal

### PR DESCRIPTION
**Pull request by umrkhn**
#### Summary
This PR fixes the position field text not wrapping to the next line in profile modal.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/25243
Jira https://mattermost.atlassian.net/browse/MM-55180

#### Screenshots

|  before  |  after  |
|----|----|
| before | after |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by asaadmahmood — APPROVED** [review]
LGTM! Nice clean fix.

**Review by calebroseland — APPROVED** [review]
👍

**Comment by umrkhn** [comment]
@M-ZubairAhmed can we merge this?

**Review by yasserfaraazkhan — APPROVED** [review]
image

**Pull request merged**
