### PR TITLE
MM-51013 Remove unneeded code from original version of Markdown hotkeys

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
So this old code was intended to make it so that, when you hit the italicize hotkey with some text selected, the user's text selection is modified to not include the underscores surrounding the text. I don’t know why it seems to have started causing issues more recently or why this happens, but that code calls `e.preventDefault()` on the textarea's `select` event, and for some reason, hitting cmd+a and then cmd+c without releasing the cmd key in between causes the browser to never try to copy the text.

Since the text editor now handles updating the user's selection itself as part of it's Markdown handling, this logic isn't needed and can just be removed. In retrospect, I don't know why we did this on `select` instead of as part of the hotkey itself to begin with.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51013

#### Release Note
```release-note
Fixed an issue where text wouldn't be copied from the post textbox
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
Isn't removing code the best

**Comment by hmhealey** [comment]
> Isn't removing code the best

Especially when it fixes a bug without having to add anything new 😀

**Comment by hmhealey** [comment]
@amyblais I put this as a cherry-pick candidate since it's to fix an issue I reported that a customer also ran into

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
