### PR TITLE
[MM-60216] Migrate tooltips of admin_consoles "admin_settings", "schema_admin_settings" & "permission_description" to WithTooltip

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-60216

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by Rajat-Dabade — APPROVED** [review]
LGTM 🚀

**Review by devinbinnie — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
- verified error is displayed in the footer 
- verified the tooltip is visible for the items in permission schema

image

**Pull request merged**
