### PR TITLE
MM-58253  Ensure remotes can only update users belonging to them

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary
This PR is a re-working of a[ previous PR](https://github.com/mattermost/mattermost/pull/27203) to address the ticket below.  

For Shared Channels, when a remote is creating or updating a user, three things are now enforced

- ensure new users get correct remoteID
- ensure remotes can only update users belonging to them
- ensure user remoteIDs cannot be changed once set

**Note:  No release note is needed as it is covered by the previous PR, which has not been part of a release yet.**

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-58253

```release-note
NONE
```

### CODE REVIEW

**Review by jupenur — APPROVED** [review]

**Review by fmartingr — APPROVED** [review]

**Review by mgdelacroix — APPROVED** [review]

**Comment by amyblais** [comment]
@wiggin77 Would you be able to help open a manual cherry-pick PR for ``release-9.5`` branch?

**Pull request merged**
