### PR TITLE
Fixing accessiblity on search input

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
The search input wasn't as accessible at it should be. This PR fixes that.

#### Ticket Link
[MM-61234](https://mattermost.atlassian.net/browse/MM-61234)

#### Release Note
```release-note
Fixing accessibility problem in the new search input
```

[MM-61234]: https://mattermost.atlassian.net/browse/MM-61234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Comment by amyblais** [comment]
@jespino Some tests are failing here.

**Review by hmhealey — CHANGES_REQUESTED** [review]
It looks like switching this to a `button` element isn't actually going to work because the Popover is rendering the contents of the search popout inside of the `NewSearchContainer` instead of portalling them to somewhere else in the DOM like a modal does. That's what's causing the test to fail as well.

In that case, we can probably go back to having it be a `div` element but using a `button` role instead of the `search` role that it has.

The search role should also be removed from the `NewSearchContainer` because that's removing the "accessible name" that screen readers and other tools will refer to it as. You can use Chrome's dev tools to see what the accessible name of an element is without having to use a screen reader.
|`role='search'`|`role='button'`|
|-|-|
|Screenshot 2024-11-28 at 4 15 29 PM|Screenshot 2024-11-28 at 4 15 45 PM|

I showed that off a couple weeks ago in Web Guild, but I should share that more since it's so much quicker to check that way than having to turn on a screen reader.

**Review by hmhealey — APPROVED** [review]
Looks good to me now. We might need to look again later at how the popover part is contained in the "button" div in the future, but this fixes the immediate issues

**Review by lindy65 — APPROVED** [review]
Thanks @jespino - looks good to me 👍

**Pull request merged**
