### PR TITLE
[MM-53333] Modified the delete category modal to contain a cancel button #24290

### PR DESCRIPTION
**Pull request by ZubairImtiaz3**
#### Summary
Added a cancel button in the delete category modal.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/24290
Jira https://mattermost.atlassian.net/browse/MM-53333

#### Screenshots
Before:

<a href="https://ibb.co/HK3xxjj">Screenshot-2023-08-20-210013</a>

After:

<a href="https://ibb.co/Gvz404L">Screenshot-2023-08-20-203104</a>

```release-note
Added a cancel button to the delete category modal
```

### CODE REVIEW

**Comment by pvev** [comment]
@ZubairImtiaz3 do you need any help for what is missing in this PR?

**Comment by pvev** [comment]
@ZubairImtiaz3 this PR still has a problem with the identation:

```
mattermost/mattermost/webapp/channels/src/components/delete_category_modal/delete_category_modal.tsx
Error:   44:1  error  Expected indentation of 8 spaces but found 4  @typescript-eslint/indent
Error:   44:1  error  Expected indentation of 8 spaces but found 4  indent
```

Where you able to run the `make fix-style`command? Could you please take a look at it?
Thanks!

**Comment by ZubairImtiaz3** [comment]
@pvev Run the command from the webapp directory and I got 2k+ changes. Now fixed it manually, pretty sure it'll work this time.

Can you please look into it like why it brings 2k+ changes? That would be a great help when contributing in the future. Thanks. 

<a href="https://ibb.co/TbGXTpm">Screenshot-2023-08-25-024612</a>

**Review by pvev — APPROVED** [review]
LGTM! thank you @ZubairImtiaz3 👍 :shipit:

**Comment by pvev** [comment]
> @pvev Run the command from the webapp directory and I got 2k+ changes. Now fixed it manually, Can you please give the build one more try, pretty sure it'll work this time.
> 
> Can you please look into it like why it brings 2k+ changes? That would be a great help when contributing in the future. Thanks.
> 
> [Screenshot-2023-08-25-024612](https://ibb.co/TbGXTpm)

the problem is that you run `npm run fix`, you needed to run `make fix-style`

**Review by BenCookie95 — APPROVED** [review]

**Comment by BenCookie95** [comment]
Thank you @ZubairImtiaz3!

**Pull request merged**
