### PR TITLE
Migration typescript/team.js

### LINKED ISSUE #21615: Migrate /support/ui/team.js to TypeScript
Convert the following file(s) under e2e/cypress/tests/support/ui to TypeScript:

  * team.js

This file also needs (better) comments, and definitions added to the file.

**Below is a checklist of items you should be doing to migrate:**

  1. Rename the file(s) to their associated TypeScript extensions (ie. `js` to `ts`)
  1. Move over all the types from the declaration (`d.ts`) files into the matching TypeScript file, and delete the declaration file, if necessary (see the Support Migration PR link below for reference) 
image
  1. Fix any errors generated by the TypeScript compiler.
  1. Navigate to the `/e2e/cypress` folder and run `npm run check-types` to display any errors.
  1. Run `/e2e-run` from the PR and make sure all migrated and existing tests have passed. Automation results can be seen here in the [Automation Dashboard](https://automation-dashboard.vercel.app/cycles).

#### **Note:**

  * Please update `types` in the declaration files (`d.ts`) if they are out of date, or mismatch with actual usage.
  * Please migrate `support` files to TypeScript if the new TypeScript files depend on them (*you will see compilation errors if this is the case*).
    * team.js is a `support` file that has not been moved to TypeScript yet; if another issue/PR does this in conjunction with converting other files (like tests/spec files) to TypeScript, this issue can be safely removed.

#### References

📗 **Support Files Migration Reference**

[Support Migration PR](https://github.com/mattermost/mattermost-webapp/pull/10910)

📘 **Spec File Migration Reference**

[account_settings/profile tests migration PR](https://github.com/mattermost/mattermost-webapp/pull/11254)

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-48237

### PR DESCRIPTION
**Pull request by hereje**
#### Summary

refactor: convert file team.js to ts

- convert file to typescript
- create types in file

#### Ticket Link

Fixes #21615

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @hereje!

**Comment by hanzei** [comment]
@saturninoabril Can we merge this PR?

**Comment by saturninoabril** [comment]
Thank you @hereje!

**Pull request merged**
