### PR TITLE
[MM-55266] Fix AdvancedLoggingConfig validation

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
`AdvancedLoggingConfig` can contain a filespec. The code didn't account for that.

Fix the validation by removing the check for the deprecated `AdvancedLoggingConfig` setting and only validate `AdvancedLoggingJSON`.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-55266

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:   FYI - the `AdvancedLoggingJSON` field was supposed to allow either JSON or a filename , but that has created confusion.  I'm going to un-deprecate the `AdvancedLoggingConfig` field and let that continue be used for files.

**Comment by hanzei** [comment]
Do we really need a way to fetch a log config from a file? It seems like an anti-pattern for Kubernetes at least, and surely adds more complexity.

**Review by BenCookie95 — APPROVED** [review]

**Comment by hanzei** [comment]
@DHaussermann Gentle reminder that this PR is for v9.3. Please take a look soon.

**Review by DHaussermann — APPROVED** [review]
Tested and passed

I switched to this branch and confirmed the server starts up when I pass in a file in the field. 

@hanzei the server checks to ensure the file exists and that the file contains a log json object for a log pattern. Based your comment above, this is the intended functionality.

LGTM!

**Pull request merged**
