### PR TITLE
[MM-57076] Stop removing local drafts when calling `removeDraft` for servers with synced drafts

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
When calling `removeDraft` (ie. after clicking delete on a draft or posting a message that had a draft), we were explicitly calling `removeGlobalitem` to delete the local draft, before other tabs were synced up. This would cause rehydration to sync drafts from other tabs (if open) back to the original tab, thus leaving the orphaned draft still in storage.

This PR defers that call to only do this when synced drafts are disabled, which should stop the bug from happening with server-synced drafts, and reduce it for local drafts (or at least only make it happen ephemerally).

The better solution going forward might be to rework the way we handle drafts when server syncing is turned on. It's unfortunately very hard to reproduce since it relies on the rehydration completing before the server can successfully delete the draft and send a websocket connection.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-57076
Closes https://github.com/mattermost/mattermost/issues/26373

```release-note
NONE
```

### CODE REVIEW

**Comment by hmhealey** [comment]
Have you checked to confirm that this won't break the fix added by https://github.com/mattermost/mattermost/pull/25715 when synced drafts are enabled?

Also, we might want a release note for this since this is fixing a bug that affects users

**Comment by devinbinnie** [comment]
> Have you checked to confirm that this won't break the fix added by #25715 when synced drafts are enabled?
> 
> Also, we might want a release note for this since this is fixing a bug that affects users

Yep, it was done in response to that fix. The change just avoid the draft being repopulated by rehydrate after the websocket event deletes it.

**Review by hmhealey — APPROVED** [review]
Ah, I missed that the WebSocket message triggers the draft to be deleted. Makes sense.

This is definitely another case where we could really use the ability for the tab which triggered a WS event not receive that event. It's annoying how often these issues come up

**Review by marianunez — APPROVED** [review]
Thanks for the quick fix @devinbinnie!

**Review by yasserfaraazkhan — APPROVED** [review]
followed the qa steps. the drafts did not appear after posting in channel

**Pull request merged**
