### PR TITLE
[GH-25298] Place the text centered in default profile picture

### PR DESCRIPTION
**Pull request by Utsav-Ladani**
#### Summary
- The text in the default profile picture is not aligned with the center. 
- Used the `Ascent` and `Descent` differences to calculate the vertical position.
- Used text width from font face using the `golang.org/x/image/font` library to calculate horizontal position.

#### Steps to check
Create a new user OR set the profile picture to default by clicking the close button in the edit profile picture section.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/25298

#### Screenshots

|  before  |  after  |
|----|----|
| Screenshot 2023-11-06 at 10 10 00 PM | Screenshot 2023-11-06 at 10 10 11 PM |

#### Release Note
```release-note
Fix the text position in the default profile picture.
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM, thanks @Utsav-Ladani!

**Review by DHaussermann — APPROVED** [review]
Tested and passed. 

I was able to deploy this locally and verify.
Confirmed When a user is created, the default profile image now has the letter vertically and horizontally centred.
image

LGTM!
Thanks @Utsav-Ladani for this enhancement!

**Comment by DHaussermann** [comment]
@matthewbirtch does this require UX review?

**Comment by matthewbirtch** [comment]
> @matthewbirtch does this require UX review?

It looks like it might be slightly off-centered to me?

image

**Comment by Utsav-Ladani** [comment]
@matthewbirtch @DHaussermann

I've made further attempts to address the alignment issue by exploring alternative methods and successfully resolved the vertical alignment. However, the horizontal alignment remains skewed to the right. Despite trying various approaches, consulting documentation, and delving into different methods, the root cause of the problem was traced back to the font itself.

Upon closer examination of the attached image, it's evident that there's an uneven distribution of space around the letter D. Notably, the left side exhibits more space compared to the right side. This asymmetry prevents us from achieving precise center alignment. My investigation revealed that this alignment discrepancy is consistent across various fonts I examined.

Screenshot 2023-12-06 at 8 25 15 PM


To achieve exact center alignment, a potential solution involves compiling the font ourselves and utilizing a custom .ttf file for image generation. However, it's crucial to acknowledge that this workaround may be considered a suboptimal practice and I would suggest not doing so

I would appreciate hearing your insights and thoughts on this matter. 💡

**Comment by matthewbirtch** [comment]
> @matthewbirtch @DHaussermann
> 
> I've made further attempts to address the alignment issue by exploring alternative methods and successfully resolved the vertical alignment. However, the horizontal alignment remains skewed to the right. Despite trying various approaches, consulting documentation, and delving into different methods, the root cause of the problem was traced back to the font itself.
> 
> Upon closer examination of the attached image, it's evident that there's an uneven distribution of space around the letter D. Notably, the left side exhibits more space compared to the right side. This asymmetry prevents us from achieving precise center alignment. My investigation revealed that this alignment discrepancy is consistent across various fonts I examined.
>
> To achieve exact center alignment, a potential solution involves compiling the font ourselves and utilizing a custom .ttf file for image generation. However, it's crucial to acknowledge that this workaround may be considered a suboptimal practice and I would suggest not doing so
> 
> I would appreciate hearing your insights and thoughts on this matter. 💡

I appreciate you diving deeper into this @Utsav-Ladani. I wondered if this might be the case. Ultimately, the average eye will not notice the slight off-center alignment of the letter and I don't think it's worth diving any deeper on this. I just wasn't sure if there was a trivial way to accomplish it, but it sounds like there isn't. So, I'm good with this as-is. I'll approve the PR

**Review by matthewbirtch — APPROVED** [review]

**Comment by hanzei** [comment]
@DHaussermann Can you please do another round of testing on this PR given that [`1d005e6` (#25324)](https://github.com/mattermost/mattermost/pull/25324/commits/1d005e6087d0114171c61dadc52fe5f426004ef0) included additional changes?

**Review by DHaussermann — APPROVED** [review]
Tested and passed based on testing done above ☝️ 
LGTM!


@Utsav-Ladani Sorry, I missed the comments left by Matt and thought there was work outstanding here. My mistake.     

This can be merged.

**Comment by Utsav-Ladani** [comment]
Thank you

**Pull request merged**
