### PR TITLE
[MM-61518] Fixed errcheck issues in channels/app/plugin_api_tests/manual.test_serve_metrics_plugin/main.go

### PR DESCRIPTION
**Pull request by pranay-0512**
#### Summary
Fixed `errcheck` issues in `channels/app/plugin_api_tests/manual.test_serve_metrics_plugin/main.go`

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/29258
Jira https://mattermost.atlassian.net/browse/MM-61518

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by pranay-0512** [comment]
@hanzei, any more issues to work on?

**Review by Rajat-Dabade — APPROVED** [review]
LGTM 🚀

**Comment by pranay-0512** [comment]
should i resolve the conflicts? @hanzei

**Comment by hanzei** [comment]
Yes, please @pranay-0512

**Comment by pranay-0512** [comment]
@hanzei, pls look at [this pull req](https://github.com/mattermost/mattermost/pull/29289)

**Pull request closed without merging**
