### PR TITLE
[MM-55299] Migrate server/channels/app/notification.go to make use of GenericStoreResult

### PR DESCRIPTION
**Pull request by Paul-Stern**
#### Summary
Make use of GenericStoreResult.
Introduce new result variables to workaround the IncompatibleAssign error.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/25314
Jira https://mattermost.atlassian.net/browse/MM-55299

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Nice work :+1: Thanks, @Paul-Stern

**Review by larkox — APPROVED** [review]

**Comment by larkox** [comment]
@hanzei Does this needs QA review? If so, who should we assign?

**Comment by hanzei** [comment]
@larkox No, I don't think this PR needs QA review.

**Pull request merged**
