### PR TITLE
MM-53688 Remove boards dataretention

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Updates for removal of boards data retention

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-53688

#### Related PRs
https://github.com/mattermost/enterprise/pull/1526
#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]

**Comment by sbishel** [comment]
@crspeller - Miguel is out the next couple days...could you have a look. Thanks.

**Review by crspeller — APPROVED** [review]

**Comment by sbishel** [comment]
@lindy65 - Not sure how much there is to test here. Other than making sure the boards plugin can still be installed and run, which I did on the test spinwick. Feel free to destroy and recreate or just validate the existing one.

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - tested on the spinwick and looks good to me 👍

**Comment by amyblais** [comment]
@sbishel A kind note to also merge the enterprise PR https://github.com/mattermost/enterprise/pull/1526.

**Pull request merged**
