### PR TITLE
[MM-58341] db/migrations: mysql-8.4 fix for 000027_create_status

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
MySQL v8.4 introduces a new reserved work for `Manual` hence it was causing errors during creating the new `Status` table. This issue was affecting new installations using mysql-8.4. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-58341

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
MySQL is dead. Long live MySQL.

**Review by harshilsharma63 — CHANGES_REQUESTED** [review]
While this fixes the migration, we also need to make the same change wherever we're querying this column in SQL store. For example, running this branch generates this error on opening webapp when the server tries to update user's status-

```JSON
{
  "timestamp": "2024-05-23 09:04:18.344 +05:30",
  "level": "warn",
  "msg": "Failed to save status",
  "caller": "platform/status.go:288",
  "user_id": "ctgbai6zc3fyupk6zpynzdrsme",
  "error": "failed to upsert Status: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Manual,LastActivityAt,DNDEndTime,PrevStatus) VALUES (?,?,?,?,?,?) ON DUPLICATE K' at line 1"
}
```

So, we need to handle this in other places as well.

**Comment by agnivade** [comment]
Ah nice catch Harshil

**Review by harshilsharma63 — APPROVED** [review]

**Pull request merged**
