### PR TITLE
[MM-51551] Add new Trial Form to Playbooks trial requests

### PR DESCRIPTION
**Pull request by nickmisasi**
#### Summary
Updates Playbooks to call the start trial form modal when activating a self hosted trial. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-51551

#### Screenshots
image

#### Release Note

```release-note
None
```

### CODE REVIEW

**Review by ConorMacpherson — APPROVED** [review]

**Comment by nickmisasi** [comment]
No design review required for this one as it just leverages https://github.com/mattermost/mattermost-server/pull/22620 (which did have a review)

**Comment by yasserfaraazkhan** [comment]
tested it locally,
Screenshot 2023-03-28 at 3 47 53 PM

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
