### PR TITLE
[MM-60834] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/select_team/select_team.tsx' with FormattedMessage

### LINKED ISSUE #28600: Replace FormattedMarkdownMessage in 'webapp/channels/src/components/select_team/select_team.tsx' with FormattedMessage
The goal of this task is to remove all instances of “FormattedMarkdownMessage” (imported from “components/formatted_markdown_message”) in the file `webapp/channels/src/components/select_team/select_team.tsx`. These should be replaced with the “FormattedMessage” component from the “react-intl” library.

Ensure that rich text formatting is preserved by following the implementation guidelines in the react-intl (https://formatjs.io/docs/react-intl/components#rich-text-formatting) documentation. Make sure to change the message ID after the update as the current extraction tool does not automatically detect changes in the messages. Once done, make sure to run `npm run i18n-extract` in the “webapp/channels” directory to pick up the new messages. For guidance refer to the example pull request - https://github.com/mattermost/mattermost/pull/28438

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-60834

### PR DESCRIPTION
**Pull request by ZubairImtiaz3**
#### Summary
This PR replaces all instances of FormattedMarkdownMessage with FormattedMessage from the react-intl library in select_team.tsx, ensuring rich text formatting is preserved. The message IDs have been updated, and npm run i18n-extract was executed to capture the new messages.

#### Ticket Link
Fixes #28600 
Jira: [MM-60834](https://mattermost.atlassian.net/browse/MM-60834)

#### Release Note

```release-note
NONE
```

[MM-60834]: https://mattermost.atlassian.net/browse/MM-60834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ZubairImtiaz3** [comment]
@M-ZubairAhmed I’ve made the changes based on your advice. You can take a look now. Thank you!

**Review by hmhealey — APPROVED** [review]
@ZubairImtiaz3 Thanks for the PR and for helping get rid of that component! This looks good to me

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
