### PR TITLE
[MM-53636] Add channel/team name back for the Saved Posts view

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
A change I made recently [here](https://github.com/mattermost/mattermost/pull/23649) caused an issue where the Saved Posts section would not show the Channel/Team names at all.

This PR restores those specifically for the Saved Posts view.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-53636

#### Screenshots
Screenshot 2023-07-25 at 11 55 54 AM

-->
```release-note
Fixed an issue where the Saved Posts section would not show the channel and team names
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by lindalumitchell — APPROVED** [review]
Verified channel/team name is back for the Saved Posts view as expected. Also double-checked it still does not appear where not expected (on the post in center or reply RHS, on post in thread view, in search results RHS), and still appears as expected on recent mentions RHS.

E2Es look fine; no failures related to this PR.

**Review by marianunez — APPROVED** [review]
Thanks @devinbinnie! Any tests we can add for this case ?

**Comment by devinbinnie** [comment]
> Thanks @devinbinnie! Any tests we can add for this case ?

Let me look into it.

**Comment by amyblais** [comment]
> > Thanks @devinbinnie! Any tests we can add for this case ?
> 
> Let me look into it. @lindalumitchell Does QA have a test case for this? I can write an E2E test but I'd like to know where it goes :)

cc @lindalumitchell The comment was edited so you may have missed a notification for this.

**Comment by lindalumitchell** [comment]
> > Thanks @devinbinnie! Any tests we can add for this case ?
> 
> Let me look into it. @lindalumitchell Does QA have a test case for this? I can write an E2E test but I'd like to know where it goes :)

Ah thank you Maria and great question Devin! The Rainforest test that uncovered the bug was actually verifying a different functionality, but there is this test case: https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T3352 with Cypress coverage here: e2e/cypress/integration/messaging/post_pre_header_spec.js

Maybe that is a good place for a test for this one as well?

**Pull request merged**
