### PR TITLE
[MM-58856] Migrate tooltips of "components/copy_button.tsx" to WithTooltip

### PR DESCRIPTION
**Pull request by ningthoujamSwamikumar**
#### Summary

Migrated the use of "Tooltip" and "OverlayTrigger" into "WithTooltip" in "copy_button.tsx" component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27414
https://mattermost.atlassian.net/browse/MM-58856

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by ningthoujamSwamikumar** [comment]
@M-ZubairAhmed Can you please review this and assign another reviewer, so th

**Comment by ningthoujamSwamikumar** [comment]
@M-ZubairAhmed Can you please review this and assign another reviewer? So, this can be merged.

**Comment by M-ZubairAhmed** [comment]
@hmhealey do you have any opinions on this one since you last modified this component?

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Comment by ningthoujamSwamikumar** [comment]
@hmhealey Hi. Can you please review this PR?

**Review by hmhealey — APPROVED** [review]
Thanks for the help with these migrations, @ningthoujamSwamikumar! This looks good to me.

**Comment by ningthoujamSwamikumar** [comment]
@yasserfaraazkhan Hi. Can you please review this PR?

**Review by yasserfaraazkhan — CHANGES_REQUESTED** [review]
@ningthoujamSwamikumar @M-ZubairAhmed 

can you point where this Button is in UI?

Also, maybe unrelated to the PR, seeing screen crash when we go to user details page.

Screenshot 2024-06-30 144802

**Comment by ningthoujamSwamikumar** [comment]
> @ningthoujamSwamikumar @M-ZubairAhmed
> 
> can you point where this Button is in UI?
> 
> Also, maybe unrelated to the PR, seeing screen crash when we go to user details page.
> 
> Screenshot 2024-06-30 144802

Hi @yasserfaraazkhan . Found multiple usages of this component. One such usage is Copy Button in code blocks in message [ screenshot attached ]. 
Screenshot 2024-07-02 173759 
Since, it is not breaking in this page. I think this component is not the problem in the mentioned crash.

**Comment by M-ZubairAhmed** [comment]
> @ningthoujamSwamikumar @M-ZubairAhmed
> 
> can you point where this Button is in UI?
> 
> Also, maybe unrelated to the PR, seeing screen crash when we go to user details page.
> 
> Screenshot 2024-06-30 144802

As mentioned by @ningthoujamSwamikumar this should have been fixed in the recent PRs. Thanks @ningthoujamSwamikumar for pointing out the components usage

**Review by yasserfaraazkhan — APPROVED** [review]
🎉

**Pull request merged**
