### PR TITLE
[MM-57884] Layout issues with initial tool selection and invite screens in workspace

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
- Sideimage of workspace fixed on viewport
- title of one of the item in workspace made uniform

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-57884

#### Screenshots
CleanShot 2024-04-30 at 16 14 16@2x
CleanShot 2024-04-30 at 16 13 25@2x
CleanShot 2024-04-30 at 16 12 38@2x

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by matthewbirtch** [comment]
@abhijit-singh can I ask you to review this one?

**Review by JulienTant — APPROVED** [review]
Looks good, thanks @M-ZubairAhmed

**Comment by M-ZubairAhmed** [comment]
@abhijit-singh gentle ping on this one

**Review by abhijit-singh — APPROVED** [review]
Looks good, thanks @M-ZubairAhmed!

**Review by marianunez — APPROVED** [review]
Thanks @M-ZubairAhmed !

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
