### PR TITLE
fix nil channel issue

### PR DESCRIPTION
**Pull request by coder-abdo**
#### Summary
Fix if the channel is `null` or the unmarshalled item is  `null` .

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/24246
Jira https://mattermost.atlassian.net/browse/MM-54024

#### Release Note

```release-note
Fix nil if the channel itself is nil or the unmarshalled item is nil
```

### CODE REVIEW

**Comment by hanzei** [comment]
@coder-abdo Thanks for taking a look a the ticket. There are a lot of unrelated commits in your branch. Would you please remove any unrelated changes? Thanks!

**Comment by coder-abdo** [comment]
@hanzei 
could you please, illustrate with more details what are the unrelated commits that I need to remove?

**Comment by hanzei** [comment]
@coder-abdo As you can see in the header, your PR adds 283 commits to `master`:
Screenshot from 2023-08-22 09-33-26

E.g. https://github.com/mattermost/mattermost/pull/24303/commits/bb4d1c41ba16d1bb0d8f38fddae2da5f11291dc5 is one of them.

**Comment by hanzei** [comment]
@coder-abdo Your PR has been stale for quite some time. I'm going to close it and open the HW ticket for another community member.

**Pull request closed without merging**
