### PR TITLE
Custom status tooltip position fixed in channel switcher items

### PR DESCRIPTION
**Pull request by Aryakoste**
#### Summary

The custom status tooltip was not positioned correctly because the span tag was taking full width. I have fixed it, now the tooltip is positioned correctly.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27183
Jira https://mattermost.atlassian.net/browse/MM-58435
#### Screenshots

|  before  |  after  |
|----|----|
| custom tooltip before  |  custom tooltip after  |
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by Aryakoste** [comment]
I can pass in spanStyle if the css style given here is affecting somewhere else. I have looked at all the files it will take effect . Two files  where this css can take effect is at_mention_suggestion.tsx and switch_channel_provider.tsx. That also too for CustomStatusEmoji component which is the main aim of this issue.

**Review by matthewbirtch — APPROVED** [review]
Thank you @Aryakoste. Looks good to me

**Comment by matthewbirtch** [comment]
@calebroseland @JulienTant are you both able to review this one?

**Review by calebroseland — APPROVED** [review]

**Review by JulienTant — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Thanks @Aryakoste - looks good 👍

**Pull request merged**
