### PR TITLE
Fixing modal styles for some modals

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
Fixing modal styles for some modals

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-57311
Fixes https://mattermost.atlassian.net/browse/MM-57092
Fixes https://mattermost.atlassian.net/browse/MM-57141

#### Screenshots
CleanShot 2024-04-01 at 17 10 27@2x
CleanShot 2024-04-02 at 18 04 10@2x
CleanShot 2024-04-11 at 14 51 38@2x

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by matthewbirtch — APPROVED** [review]
Looks great to me Asaad. One quick question that maybe QA can help with. How can we test the in-product notices? I was able to verify the threads modal and the groups modal, but not the in-product notices.

**Comment by asaadmahmood** [comment]
@matthewbirtch Probably Lindy knows.

**Review by larkox — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by lindy65** [comment]
I'm not actually sure how to test the notices but I believe @yasserfaraazkhan does.  Can you please test the notices section for me Yasser?  I'd be grateful if you can make notes as you go so that I can learn for next time :) Thank you!

**Review by lindy65 — APPROVED** [review]
Thanks @asaadmahmood - I've tested the user groups and threads modals and they look good to me.

I've added Yasser as a reviewer for the notices part of the review.

**Review by yasserfaraazkhan — APPROVED** [review]
Hi @lindy65 
I just downloaded lower version of desktop and setup the spin wick server.
For PRs if its just Modal's appearance we need to check then, this is a easy way.

image

**Comment by larkox** [comment]
@asaadmahmood From the screenshot from @yasserfaraazkhan it seems there is still too much air at the top of the modal, right? Or is it intended?

**Comment by asaadmahmood** [comment]
@larkox yup it does seem like its a bit more. Maybe there's a margin on that specific one explicitly, will check.

**Comment by asaadmahmood** [comment]
Spoke to Devin and looks like that server notice modal is outdated. And not something current, so won't be looking at that as part of this PR.
CleanShot 2024-04-12 at 13 16 42@2x

**Comment by matthewbirtch** [comment]
> Spoke to Devin and looks like that server notice modal is outdated. And not something current, so won't be looking at that as part of this PR.

Thanks for the update @asaadmahmood. Were we able to test the other in-product notices to make sure they don't look like that one?

**Comment by matthewbirtch** [comment]
> @matthewbirtch Do you have an example of one that we want to test out? I don't think we were able to test anything apart from the threads one.

@asaadmahmood the active notices are in this file: https://github.com/mattermost/notices/blob/master/notices.json, but I don't know how to test them locally. And the only notice that could make sense is the one below, but I don't know of a way to force these notices to display so we can test them since they mostly target specific server versions.

```
{
    "id": "server_upgrade_v9.6",
    "conditions": {
      "audience": "sysadmin",
      "clientType": "all",
      "serverVersion": ["<9.6"],
      "instanceType": "onprem",
      "displayDate": ">= 2024-03-15T00:00:00Z"
    },
    "localizedMessages": {
      "en": {
        "title": "Mattermost 9.6 is here!",
        "description": "Mattermost v9.6 includes multiple new improvements and bug fixes, including additional user statistics under User Management. [Upgrading](https://docs.mattermost.com/upgrade/upgrading-mattermost-server.html) only takes a few minutes.",
        "image": "https://raw.githubusercontent.com/mattermost/notices/master/images/server_upgrade.png",
        "actionText": "Learn more",
        "actionParam": "https://docs.mattermost.com/deploy/mattermost-changelog.html/?utm_source=inapp-self-hosted&utm_medium=popup&utm_campaign=mattermost-7-5-&utm_id=nov-notifications&utm_content=7-5-available"
      }
    }
  },
```

**Comment by asaadmahmood** [comment]
Here are the updates inproduct notices.
CleanShot 2024-04-12 at 20 11 20@2x
CleanShot 2024-04-12 at 20 11 14@2x
CleanShot 2024-04-12 at 20 11 26@2x

**Pull request merged**
