### PR TITLE
Make postgres and mysql migrations naming consistent for version 92

### PR DESCRIPTION
**Pull request by stafot**
#### Summary
Make postgres and mysql migrations naming consistent for version 92

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-54548

#### Release Note

```release-note
Make postgres and mysql migrations naming consistent for version 92
```

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
Actually, the mysql one is correct. The postgres one is missing an `m`. We should do the reverse here.

**Comment by agnivade** [comment]
@isacikgoz - could we invert the migration name in the docs above?

**Comment by isacikgoz** [comment]
I think best way to handle this (considering the current customers on postgres) is just leaving it as is. It's not as simple as renaming the files unfortunately. We check migrations with both version and the name hence we would require to add a new migration to fix the issue and it can still prone to errors.

Fixing this is not bringing much benefit IMHO rather than aesthetics. Because migration workflow already creates the schema as identical as any other postgres schemas like before.

**Comment by agnivade** [comment]
Closing, as per above.

**Pull request closed without merging**
