### PR TITLE
As per your need I converted this class component into functional com…

### PR DESCRIPTION
**Pull request by sankettank66**
As per your need I converted this class component into functional component

#### Summary
I converted this class component into functional component and changed test cases also.

#### Ticket Link
N/A

#### Screenshots
N/A

#### Release Note
None

```release-note
As per your need I converted this class component into functional component
```

### CODE REVIEW

**Comment by larkox** [comment]
@sankettank66 Great work! But you seem to have updated many of the styles inadvertently. Can you run `npm run fix` to get them back to how they were before?

**Comment by larkox** [comment]
@sankettank66 Are you still working on this?

**Comment by M-ZubairAhmed** [comment]
@sankettank66 can you fix the conflicts?

**Comment by larkox** [comment]
@sankettank66 I saw that this was already solved by another contributor. Sorry for the mistake.

That being said, in the future make sure you comment on the original issue (https://github.com/mattermost/mattermost/issues/27901) and link it in the PR description, so only one person is working on the same ticket at the same time.

**Pull request closed without merging**
