### PR TITLE
Update prepackaged Jira plugin 4.0.0

### PR DESCRIPTION
**Pull request by mickmister**
#### Ticket Link

https://github.com/mattermost/mattermost-plugin-jira/pull/966

```release-note
Prepackage Jira plugin v4.0.0
```

### CODE REVIEW

**Comment by mickmister** [comment]
@DHaussermann I've tested the generated MM Cloud server and did a sanity check with connecting to Jira Cloud OAuth. LGTM. What's the criteria to merge the PR?

**Review by hanzei — COMMENTED** [review]
Are we ready to do that yet? Why are we pushing the update so quickly?

**Comment by mickmister** [comment]
@hanzei Mainly because of https://mattermost.atlassian.net/browse/MM-44185

**Review by hanzei — APPROVED** [review]

**Pull request merged**
