### PR TITLE
[MM-56174] Account for archived channels in channel member for post permission check

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
When checking if a user has access to a post on a specific channel, we weren't accounting for the fact that the channel might be archived, as we were just fetching the channel member, irrespective of the setting allowing/denying users to view archived channels.

This PR adds a parameter to the store call to remove archived channels from the fetched member list, and uses the view archived channel setting in the permission check to toggle this on or off.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-56174

```release-note
Fixed an issue where users could access archived channels when `Allow users to view archived channels` was set to false.
```

### CODE REVIEW

**Review by hmhealey — CHANGES_REQUESTED** [review]
Could you add a test or two for the methods in `app/authorization` to confirm that they respect that setting?

**Review by isacikgoz — APPROVED** [review]
Nicely done 👌

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
