### PR TITLE
fix css

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Move css fix to be more specific and not affect marketplace.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-57477

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by harshilsharma63 — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - this is fixed 👍

**Review by hmhealey — APPROVED** [review]
Looks good to me. I checked the team and user settings modals with this, and I can't see anywhere that this change seems to have caused specificity issues.

The user settings modal is messed up in mobile web view, but that's a pre-existing issue

**Pull request merged**
