### PR TITLE
[MM-55135] Show header status width despite long header

### PR DESCRIPTION
**Pull request by otilor**
#### Summary

This basically shows the user status despite long header in DMs

#### Ticket Link

Jira https://mattermost.atlassian.net/browse/MM-55135
#### Screenshots

Screenshot 2023-10-25 at 10 08 18

#### Release Note

```release-note

```

### CODE REVIEW

**Review by hmhealey — CHANGES_REQUESTED** [review]
Thanks for the PR, @otilor! This fixes the bug for me, but would you mind fixing the order of those CSS rules since the linter is complaining.

You can verify that that order is correct by running `npm run check`

**Review by harshilsharma63 — CHANGES_REQUESTED** [review]
Looks fine but CI errors need to be fixed.

**Comment by marianunez** [comment]
@otilor just checking in and see if you have any questions to fix the CI issue

**Comment by otilor** [comment]
###

**Comment by otilor** [comment]
Hi @marianunez I've updated it.

**Review by matthewbirtch — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Review by harshilsharma63 — APPROVED** [review]

**Pull request merged**
