### PR TITLE
MM-59864 Add E2E test for keyboard navigation in the threads list

### PR DESCRIPTION
**Pull request by hmhealey**
#### Summary
The corresponding bug is actually fixed on the latest master, so I added a test to ensure that it doesn't regress in the future

#### Ticket Link
MM-59864

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
this File doesnt have `Stage: @prod` tag. Its not picked up in the CI.
Ive check this locally. It passes.

**Comment by larkox** [comment]
@yasserfaraazkhan Before merging... should it have the `Stage: @prod` tag? Or in order to promote these to prod there is a different process?

**Comment by yasserfaraazkhan** [comment]
@larkox we can add the `Stage: @prod`.
I think there was a job to run all tests in gitlab and promote once the feature is in production & tests are non flaky. I realise this might not be there now.

**Pull request merged**
