### PR TITLE
Remove Global Drafts Feature Flag

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Remove Global Drafts feature flag. Without this feature flags there is no way to disable the feature and the only option is to disable is server synching of draft messages. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49054

#### Release Note

```release-note
None
```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]

**Review by yasserfaraazkhan — COMMENTED** [review]
tested general messaging and drafts functionality in web and Android app (pointing to server). working as expected.
 
Screenshot 2023-07-05 at 4 54 35 PM

**Review by devinbinnie — APPROVED** [review]

**Pull request merged**
