### PR TITLE
MM-55060 - Calls: Add PushTypeCalls for calls-specific push notifications

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- This is to support calls-specific push notifications, see also:
  - https://github.com/mattermost/mattermost-push-proxy/pull/110
  - https://github.com/mattermost/mattermost-plugin-calls/pull/561
  - https://github.com/mattermost/mattermost-mobile/pull/7623
- I tagged Agniva on these because he was doing the push-proxy recently, but please review these too @enahum if you wish.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-55060

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]

**Comment by agnivade** [comment]
It's a bit weird to see a constant added without being used. Is it planned to be used in a later PR?

**Comment by streamer45** [comment]
> It's a bit weird to see a constant added without being used. Is it planned to be used in a later PR?

@agnivade It's used by the [plugin side](https://github.com/mattermost/mattermost-plugin-calls/blob/e94a314be624284f18039f1f2629af1e35442be3/server/push_notifications.go#L65) that handles push notifications for calls.

**Review by streamer45 — APPROVED** [review]

**Comment by agnivade** [comment]
If it's only the plugin using it, do we even need to add it here? 0/5 overall.

**Comment by streamer45** [comment]
@cpoile Is that constant the only reason we need to bump the server dependency?

**Comment by cpoile** [comment]
@streamer45 Yes. I thought it would be most correct to put the constant here, so that everyone knows "calls" is a type of push notification (in case someone needs to refactor in the future). Otherwise it would be hidden in the plugin and forgotten about.
I'm fine with just adding this, but then using our own const string in Calls... But it feels wrong.

**Comment by streamer45** [comment]
Yes, I think it makes sense to keep it on this side. We are still relying on `model` anyway so even if not used directly it's part of the public API we expose.

**Comment by agnivade** [comment]
In that case, maybe worth adding a comment to clarify that it's used from the calls plugin? Sometimes linters might complain if they see an unused constant.

**Comment by cpoile** [comment]
Asking for re-review to update everyone on the new approach -- @enahum made a good point in https://github.com/mattermost/mattermost-push-proxy/pull/110#issuecomment-1809365167 which I didn't realize (but should have): adding a new push notification message type will break older mobile clients. iOS will be mostly okay, but Android isn't -- calls notification messages using the new `calls` message type will be displayed without a body.

The solution I settled on was to add a `sub_type` field to the push notification payload. Here are the conditions (old means pre-this batch of PRs -- so calls < 0.21.1, push proxy < 5.27.0, MM server < 9.3.0, mobile client < 2.11.0)
- old calls plugin, old MM server, old push proxy, old mobile client: original behavior
- new calls plugin, old MM server, old push proxy, old mobile client: calls plugin sends new `sub_type`, server ignores it, original behavior
- new calls plugin, new MM server,  old push proxy, old mobile client: calls plugin sends new `sub_type`, server sends it to push proxy, push proxy ignores it, original behavior
- new calls plugin, new MM server,  new push proxy, old mobile client: calls plugin sends new `sub_type`, server sends it to push proxy, push proxy sends it to mobile, mobile ignores it, original behavior
- new calls plugin, new MM server,  new push proxy, new mobile client: new behavior

Any newer part of the chain won't receive the new `sub_type` so will proceed processing the push notification like a regular `type: message`.  Hope that makes sense?

**Review by agnivade — APPROVED** [review]

**Review by streamer45 — APPROVED** [review]

**Comment by cpoile** [comment]
@amyblais Can this be included in 9.3? Minor change but is needed for a bunch of dependencies in the future and would be nice to have it in as early as possible.

**Comment by amyblais** [comment]
I think we can add this to v9.4 instead of v9.3, unless it will cause issues if we don't include it in v9.3. Let me know!

**Comment by cpoile** [comment]
@amyblais Ultimately it's up to you, but I would argue that the change is about as minor as you can get (it won't break anything) and will prevent some reduced functionality in the future for 9.3 users. But again, up to you of course. :)

**Pull request merged**
