### PR TITLE
[MM-49084] public/model/config: elasticsearch: add ingore option to some indexes to purge

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Add a new configuration to ignore some indexes to purge. See also: https://github.com/mattermost/enterprise/pull/1452

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49084

#### Release Note

```release-note
Now you can specify index names to ignore while purging indexes from Elasticsearch with the ElasticsearchSettings.IgnoredPurgeIndexes setting.
```

### CODE REVIEW

**Comment by spirosoik** [comment]
@isacikgoz could you give more context on what was the underline issue?

**Comment by spirosoik** [comment]
thanks for the details @isacikgoz. let's fix the broken CI too

cc @mattermost/cloud-sre

**Review by agnivade — COMMENTED** [review]
We'd need an UI option for this as well in the system console.

**Comment by isacikgoz** [comment]
> We'd need an UI option for this as well in the system console.

Done. 

resim

**Comment by agnivade** [comment]
@isacikgoz - When I put in just `opendistro` in the UI and try to purge, it gives a 

```
error [2023-06-02 12:00:48.740 +02:00] Elastic Search PurgeIndexes Error             caller="elasticsearch/elasticsearch.go:1192" error="elastic: Error 404 (Not Found): no such index [opendistro] [type=index_not_found_exception]"
error [2023-06-02 12:00:48.740 +02:00] Failed to delete Elasticsearch index          caller="web/context.go:117" path=/api/v4/elasticsearch/purge_indexes request_id=tsd6wm4t5tf55cgcgq7o1huaza ip_addr="::1" user_id=9fusgigzctf7xdckgajqcrchdh method=POST err_where=Elasticsearch.PurgeIndexes http_code=500 error="Elasticsearch.PurgeIndexes: Failed to delete Elasticsearch index, elastic: Error 404 (Not Found): no such index [opendistro] [type=index_not_found_exception]"
```

What am I doing wrong?

**Comment by isacikgoz** [comment]
> What am I doing wrong?

@agnivade it's interesting that probably looking an exact match if you don't use `*` and failing to find index as it's not a usual index. It doesn't error when you provide `opendistro*` etc. What we can do is, either document it or first list indexes with given values, if not found, discard from the purge list.

**Review by agnivade — APPROVED** [review]

**Comment by agnivade** [comment]
cc @spirosoik / @stylianosrigas  - Could someone from your team give this a review? We took this up as a high priority request but it's been sitting idle for a week.

**Comment by spirosoik** [comment]
> cc @spirosoik / @stylianosrigas - Could someone from your team give this a review? We took this up as a high priority request but it's been sitting idle for a week.

sorry I was out Agniva. I am checking right away

**Review by spirosoik — APPROVED** [review]
I don't have much knowledge here, though LGTM based on the other related PRs for this.

**Review by stylianosrigas — APPROVED** [review]

**Pull request merged**
