### PR TITLE
MM-54489 restrict mobile oauth/saml redirect to native app schemes

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Added restriction to mobile oauth / saml redirection to match the `NativeAppSettings.AppCustomURLSchemes` config setting

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-54489

#### Release Note
```release-note
Added restriction to mobile oauth / saml redirection to match the `NativeAppSettings.AppCustomURLSchemes` config setting
```

### CODE REVIEW

**Review by sbishel — APPROVED** [review]
Thanks Elias for jumping on this.
Do we need to document the config setting to update if another schema is needed. (or is there no reason for any other schema.) Since its a config setting I assume there may be.

**Comment by enahum** [comment]
In theory that should only be set if you change the default auth schemes in the mobile app, I guess at this point you know what you are doing cause you have to modify the source code of the mobile app at this point to achieve it. I guess it has never been documented but so far no one has really asked about this afaik

**Review by esarafianou — APPROVED** [review]
LGTM

**Review by lindy65 — APPROVED** [review]
@enahum - I'm going to `QA defer` this PR and test after merging as it's difficult to set up oauth/saml on spinwick

**Pull request merged**
