### PR TITLE
[MM-52926] Deprecating work templates

### PR DESCRIPTION
**Pull request by JulienTant**
#### Summary

- All the backend code is removed
- CI checks have been removed
- Frontend code + images have been removed
- The onboarding Role page that was depending on work template has been removed too.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-52926

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by yasserfaraazkhan** [comment]
Hi @JulienTant 
a great number of e2e are failing, and the spinwick is not coming up to verify the UI. can you help in having spinwick run?

**Review by pvev — APPROVED** [review]
LGTM @JulienTant ! this was awesome implementation, great code and worked as a charm. RIP 😢

**Comment by JulienTant** [comment]
> Hi @JulienTant a great number of e2e are failing, ~and the spinwick is not coming up to verify the UI. can you help in having spinwick run?~

I'll try to restart the tests, I can't see a link between all those failing tests and this change. As far as I know, there's not a single test that has been made for work templates.

**Review by yasserfaraazkhan — APPROVED** [review]
hi @JulienTant ,
e2e-test cmd is timing out.  I've run few tests related to channel creating, DM, centre messages.
the work template creation is not available.

just to double change, We get some options on `/preparing-workspace` screen to select. Like, `QA`, `Agile` , even this screen is not expect right ? _(its not coming up, just confirming if its expected to not show up)_

**Comment by JulienTant** [comment]
hey @yasserfaraazkhan; yes indeed @johndavidlugtu decided to get rid of this page too - it was using the work templates categories to fill the content of this page

**Pull request merged**
