### PR TITLE
MM-55524: Include deactivated users in DM export

### PR DESCRIPTION
**Pull request by agnivade**
We were incorrectly excluding deactivated users
while getting channel members for a DM channel, whereas
we were actually exporting all users in the users array.

We fix this and also correctly honor the includeArchivedChannels
flag as well.

https://mattermost.atlassian.net/browse/MM-55524

```release-note
NONE
```

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Review by BenCookie95 — APPROVED** [review]

**Comment by agnivade** [comment]
@DHaussermann - test steps are in the JIRA ticket

**Comment by DHaussermann** [comment]
@agnivade This does work and archived DMs can be preserved and re-imported. However, I have two points to raise here but maybe neither of them are blocking. 

1. Your change always exports the archived DMs posts and includes them in the file. I want to confirm that this is the desired business logic. The alternative would be to only include them only when I export with the flag `--include-archived-channels`. Thoughts?

2. Not about your PR but if you can help, Intermittently I can't pull the data back in. 
Steps:
- Create a fresh DB and start the server
- Create a prime admin account **who's unsername and email matches the previous admin** before the DB was wipedout
- Use the new admin account to login to `MMCTL` and run the import
**Observed** : The import stops because the email is already in use in the DB and I don't get my posts imported.
image
 
 This does not happen every time and I can't see what I'm doing differently. I have seen it stop on username match before. Why would it throw an error? it seems like normal use would be that the admin running the import may have already re-created their admin account. Especially true when doing this via MMCTL.

**Comment by agnivade** [comment]
1. That seems weird because the PR does exactly what you want. It exports archived channels only when the `include_archived_channels` flag is set to true. See here: https://github.com/mattermost/mattermost/pull/25695/files#diff-97cf2ca1d5b2c2193b7000d94aec3d298ebbc72ae6036db11099c6340b9b9eeaR4119

What it does always is get the complete list of users, including archived users, to match with the archived DM channels. And that's fine because we were anyways exporting the full user list.

2. Yeah this is tricky if you are not using `--local` mode and then you can run into issues with existing email address. Let's track this separately. I think there's a reason why we don't continue on matching email addresses.

**Comment by DHaussermann** [comment]
Thanks @agnivade I'm still investigating what's happening here. 0/5 I'm seeing an unrelated issue. Either I'm simply doing something wrong or something odd is happening with `MMCTL`.  I tried this again, this time exporting without the flag and then with the flag. 
image

Both files I grabbed from the S3 bucket seem identical and this time do **not** include the DM channels so, it seems something else may be happening that affecting the results. I'll troubleshoot this.

**Comment by DHaussermann** [comment]
@agnivade I'm not able to see this work. I'm not sure what is happening. After coming back to this a couple times and several attempts... The export now only shows archived channel post but never archived DM posts. 

I am quite confused because at one point last week I know it worked and I have the export file showing it works as user have a value set for `deleted_at` and their DM posts are included.  (see attached)   
[import-shows-arch-dm.txt](https://github.com/mattermost/mattermost/files/13941399/import-shows-arch-dm.txt)

- I have made certain I have the `fixDMExport` checked out and I see your commit when I run `git log` 
- I have rebuilt the MMCTL tool (Though I suspect that is not relevant)

Do you have any other suggestions for why I may not be getting the archived DM posts in the export? Or how I can further isolate this?

Steps:
- Setup an MM server
- Invite 2 or 3 other users
- Have sys-admin post in all DM channels
- Deactivate 1 or 2 users
- Create a new channel make a post and archive it (optional to ensure the flag in the export is working)
- run `./mmctl export create --include-archived-channels --local`
- Download and unzip th
e file from the s3 bucket
**Observed**: Archive channel post shows however `"direct_post"` only shows for the user(s) who are not deactivated.

**Comment by agnivade** [comment]
@DHaussermann - Are you favoriting the DM? The steps are: 
- create a DM channel between user A and B. 
- Favorite the DM channel from user B.
- Deactivate user B
- Export data including archived channels. 

Let me know if this doesn't work.

**Comment by agnivade** [comment]
I just tried it again and could repro the issue. I am attaching the files. 

[bad_export.zip](https://github.com/mattermost/mattermost/files/13945621/bad_export.zip)

[good_export.zip](https://github.com/mattermost/mattermost/files/13945626/good_export.zip)

Good export is generated from this PR. Bad export is generated from master. 

If I diff the import.jsonl, I get this:

```
1c1
< {"type":"version","version":1,"info":{"generator":"mattermost-server","version":"9.5.0 (e0dd8e3d3e694eec40910712f94f956cb261d062, enterprise: true)","created":"2024-01-16T10:23:43.668243698+05:30"}}
---
> {"type":"version","version":1,"info":{"generator":"mattermost-server","version":"9.5.0 (e0dd8e3d3e694eec40910712f94f956cb261d062, enterprise: true)","created":"2024-01-16T10:21:32.954176508+05:30"}}
362c362
< {"type":"direct_channel","direct_channel":{"members":["sysadmin","sysadmin"],"favorited_by":["testuser-3"],"header":""}}
---
> {"type":"direct_channel","direct_channel":{"members":["sysadmin","testuser-3"],"favorited_by":["testuser-3"],"header":""}}
```

You can also see the direct post:
```
{"type":"direct_post","direct_post":{"channel_members":["sysadmin","testuser-3"],"user":"sysadmin","type":"","message":"really","props":{},"create_at":1705380583053,"edit_at":0,"flagged_by":null,"reactions":null,"replies":null,"attachments":null}}
```

Happy to jump on a call to show you.

**Comment by pvev** [comment]
thanks for the heads up @agnivade 👍

**Comment by DHaussermann** [comment]
@agnivade I have reported the export bug I was seeing here https://mattermost.atlassian.net/browse/MM-56579 and moved on to your actual PR to address the error on import. 

I now see a new error on import. The message is now related to the `deleted_at` field. Note that I did not create a new export file from your branch. I created the export file from `master` and then tried to import while on you branch to see the error resolve. Given my understanding of the problem I should be acceptable to use an existing export file. Please advise if there is a known limitation here.

image

The odd part is... **line 5 is not about the channel type under test**. It's just a generic archived public channel I created to test the export flag. 
`{"type":"channel","channel":{"team":"apple","name":"arch-chan","display_name":"Arch Chan","type":"O","header":"","purpose":"","deleted_at":1705333862292}}`

Could this also be unrelated? 
For reference I have attached a `.txt` version of the file I'm trying to import.
[sample-export.txt](https://github.com/mattermost/mattermost/files/13969044/sample-export.txt)

**Comment by agnivade** [comment]
> I created the export file from master and then tried to import while on you branch to see the error resolve. Given my understanding of the problem I should be acceptable to use an existing export file.

Ah no that won't work. The error happens during import, but the code change is in the export file. So if you create an export file from master, and import using my branch, it will still fail. You have to always export from my branch, then you can import in master or my branch doesn't matter.

And yes, the error you are seeing is unrelated and actually not an error. It is happening because you already have the same channel ID in your destination DB. So it's trying to update the existing channel, but there is a check where the channel being updated cannot be already deleted. 

```go
if channel.DeleteAt != 0 {
	return nil, store.NewErrInvalidInput("Channel", "DeleteAt", channel.DeleteAt)
}
```

If you import to a fresh DB, I think you'll avoid the problem.

**Comment by DHaussermann** [comment]
@agnivade after doing another round of testing I think we can merge this 
- Archived users and their channels are always included regardless of the use of the `--include-archived-channels` flag (as expected)
- When an archived DM channel is imported the import works fine even if the Archived DM was favorited. The issue is resolved. 
- Regression testing of the `--include-archived-channels` for non archived channels.

@agnivade  some last notes just to make sure I we understand all the details:
1. Reported https://mattermost.atlassian.net/browse/MM-56579 where only posts from active users are included in DMs.
2. Given the bug from 1. I now see my confusion from the 1st round of testing. Archived users and DMs are always imported regardless of the `--include-archived-channels` of the flag. And Within those channels posts for active users are always imported. So... due to the issue above, the `--include-archived-channels` functionally does nothing for DM channels right now. Am I missing anything?
3. There is probably no need to document that older exports won't work. I assume exports are taken frequently enough that this may not matter. Or is this worth explicitly stating.

**Comment by agnivade** [comment]
> So... due to the issue above, the --include-archived-channels functionally does nothing for DM channels right now. Am I missing anything?

You are totally right.

> There is probably no need to document that older exports won't work. 

Nope don't think so.

**Comment by agnivade** [comment]
Tests passed. Thanks @yasserfaraazkhan for the assist!

**Pull request merged**
