### PR TITLE
Removing empy zh_Han* files that are raising  an alert in Weblate

### PR DESCRIPTION
**Pull request by ctlaltdieliet**
#### Summary
With moving the WIP-languages to the shipped project, we got duplicate files for Traditional and Simplified Chinese.
Although zh_Hans and zh_Hant are more correct, it would require code-changes and existing Chinese users to chose their language again.
As these filenames are not visible, we can keep using these

#### Screenshots
webapp_zh

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by cwarnermm** [comment]
@ctlaltdieliet - Will any contributed translations be lost or overwritten with this PR?

**Comment by ctlaltdieliet** [comment]
No, it just removes two empty unused files

**Review by cwarnermm — APPROVED** [review]
Thanks, @ctlaltdieliet!

**Review by lieut-data — CHANGES_REQUESTED** [review]
@ctlaltdieliet. this seems likely to create a merge conflict when weblate pulls in the changes, and will get blocked shortly with [my CI changes](https://github.com/mattermost/mattermost/pull/25002) anyway. Can we do this on the weblate side instead and let it push this as a PR?

**Comment by ctlaltdieliet** [comment]
Hi @lieut-data ,
I don't know if/how we have write access to the Weblate repositroy. Maybe we can not send "git rm {file}" command through the Mattermost bot, else we have to do it through a PR risking a merge conflict.

**Review by lieut-data — APPROVED** [review]
Thanks for clarifying, @ctlaltdieliet! Agree that this is a case where we probably want to risk the conflict (if it even occurs), as I too couldn't find a way to delete the file.

**Pull request merged**
