### PR TITLE
Fix errcheck issues in server/channels/api4/team_test.go

### PR DESCRIPTION
**Pull request by azadDsync**
#### Summary
Fix errcheck issues in server/channels/api4/team_test.go
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28615

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by hanzei** [comment]
@azadDsync, did you intend to close this PR?

**Comment by azadDsync** [comment]
I mistakenly deleted the forked repo and encountered some errors, so I need to close this PR. I'm also new to GitHub and the open-source community, so it may take some time for me to get comfortable with it.

**Comment by azadDsync** [comment]
I am opening a new PR

**Comment by hanzei** [comment]
Please let me know if you need any help! Looking forward to your PR :rocket:

**Pull request closed without merging**
