### PR TITLE
[MM-61697] Date time picker - use localized date format and don't reset time when changing dates

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Made following changes to date time picker common component (used in custom status, post reminder and scheduled messages)-
1. Show date in date picker in user's localized format
2. Don't reset time when changing date.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-61697
Fixes https://mattermost.atlassian.net/browse/MM-61720
Fixes https://mattermost.atlassian.net/browse/MM-61719

#### Release Note
```release-note
none
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Comment by larkox** [comment]
Should we add / update unit tests for this?

**Review by yasserfaraazkhan — CHANGES_REQUESTED** [review]
Hi @harshilsharma63 @asaadmahmood 
I can see changing date doesnt change the time to midnight.

I wonder, if the time dropdown should start from the Selected Time.
Right now, though the dropdown does not default to midnight, User still has to scroll from 12:AM looking for the time in interest.


image

**Comment by harshilsharma63** [comment]
@yasserfaraazkhan I can do that. Will update the PR to do it.

**Comment by harshilsharma63** [comment]
@yasserfaraazkhan I notice that the date time picker uses a deprecated menu for displaying time and there is no support for scrolling to selected value. Since its deprecated, we should not make changes to it. We can switch to a different menu component later for this. So, I'm not fixing this part right now.

**Review by yasserfaraazkhan — APPROVED** [review]
Thank you Harshil

**Pull request merged**
