### PR TITLE
Update prepackage boards v7.10.1

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Update prepackage boards v7.10.1
#### Release Note
```release-note
Update prepackage boards v7.10.1
```

### CODE REVIEW

**Review by crspeller — APPROVED** [review]

**Comment by amyblais** [comment]
@sbishel Are these the fixes included in these backports?

1. https://mattermost.atlassian.net/browse/MM-51713
2. https://mattermost.atlassian.net/browse/MM-51062
3. https://mattermost.atlassian.net/browse/MM-51820
4. https://mattermost.atlassian.net/browse/MM-52814
5. https://github.com/mattermost/mattermost/pull/23032

**Review by mgdelacroix — APPROVED** [review]

**Comment by sbishel** [comment]
> @sbishel Are these the fixes included in these backports?
> 
> 1. https://mattermost.atlassian.net/browse/MM-51713
> 2. https://mattermost.atlassian.net/browse/MM-51062
> 3. https://mattermost.atlassian.net/browse/MM-51820
> 4. https://mattermost.atlassian.net/browse/MM-52814
> 5. [Updates the check for the schema_migrations information #23032](https://github.com/mattermost/mattermost/pull/23032)

yes

**Comment by sbishel** [comment]
Needs https://mattermost.atlassian.net/browse/CLD-5756 in order to build

**Pull request merged**
