### PR TITLE
Fix date picker placement

### PR DESCRIPTION
**Pull request by LeonardJouve**
#### Summary
This is a small pr fixing floating-ui usage in the date picker component.

Style and floating props were not applied to the correct component and used properly.
As a result, placement, fallback placement and placement reajustment on overflow were not handled.

You may refer to the PostPriorityPickerOverlay component as an example.

To test the changes, you can see some minor placement improvement on responsive mode when the date picker overflows in the reminder modal for example.
But this fix is more focused for some future DatePicker usage, like in the schedule draft modal, where the date picker is placed at the bottom of the screen. In such case, the user would now be able to use the date picker on a mobile device.

#### Screenshots
|  before  |  after  |
|----|----|
| Screenshot 2023-06-02 at 09 33 30 | Screenshot 2023-06-02 at 09 34 31 |
| Screenshot 2023-06-02 at 09 32 20 | Screenshot 2023-06-02 at 09 29 15 |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@abhijit-singh gentle ping on this one

**Review by BenCookie95 — APPROVED** [review]
LGTM, thanks @LeonardJouve

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by abhijit-singh — APPROVED** [review]

**Comment by M-ZubairAhmed** [comment]
@LeonardJouve can you please update your fork from `mattermost-server` to `mattermost`

**Comment by M-ZubairAhmed** [comment]
@LeonardJouve yes, you just have to `sync` the fork https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by yasserfaraazkhan** [comment]
changes work fine. waiting for CI to get unblocked. Team is working on it

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by M-ZubairAhmed** [comment]
@LeonardJouve thank you for finding these bugs and opening fixes and continuously improving Mattermost 💙 🥳

**Pull request merged**
