### PR TITLE
Translations update from Mattermost Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Mattermost Weblate](https://translate.mattermost.com) for [mattermost-languages-shipped/mattermost-server-monorepo](https://translate.mattermost.com/projects/mattermost/mattermost-server-monorepo/).

It also includes following components:

* [mattermost-languages-shipped/mattermost-webapp-monorepo](https://translate.mattermost.com/projects/mattermost/webapp-monorepo/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by ctlaltdieliet — APPROVED** [review]

**Comment by ctlaltdieliet** [comment]
@Willyfrog @lieut-data @cwarnermm 
Can you help approving this PR so it can be merged?

**Review by lieut-data — APPROVED** [review]

**Pull request merged**
