### PR TITLE
[MM-60250]Convert MessageExport query to squirrel

### PR DESCRIPTION
**Pull request by BenCookie95**
#### Summary
I converted this to squirrel in the CLI tool because there were too many args to keep track of in the args slice. Copied over to here so we keep parity

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-60250

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by agnivade — CHANGES_REQUESTED** [review]
Soo much better!

**Review by agnivade — APPROVED** [review]
Sorry, meant to approve!

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Comment by BenCookie95** [comment]
There are some failures in the e2e tests but nothing related to message export, merging

**Pull request merged**
