### PR TITLE
MM-53029 - Remove default (true) for channelExport and Apps plugin

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Removes setting the Channel Export and Apps plugin enabled by default.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-53029

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by crspeller — APPROVED** [review]

**Comment by amyblais** [comment]
@sbishel Michael is out of office until the end of June.

**Review by calebroseland — COMMENTED** [review]
Not really sure, but any of these need removing/disabling for dev/e2e?
- https://github.com/mattermost/mattermost/blob/MM-53029-prepackage-defaults/e2e-tests/playwright/support/server/default_config.ts#L622
- https://github.com/mattermost/mattermost/blob/MM-53029-prepackage-defaults/e2e-tests/playwright/test.config.ts#L50
- https://github.com/mattermost/mattermost/blob/MM-53029-prepackage-defaults/server/public/model/feature_flags.go#L87

**Comment by sbishel** [comment]
@calebroseland - I updated the first two, as I think your right, they shouldn't be set. The third one, pertains to the feature flag, which is still available for this feature as well. So, I would consider it to still be valid. Thanks.

**Review by calebroseland — APPROVED** [review]

**Comment by amyblais** [comment]
@M-ZubairAhmed Please help review by tomorrow's v8.0 feature complete.

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
