### PR TITLE
MM-57997: Fix bypass-upload in HA mode

### PR DESCRIPTION
**Pull request by agnivade**
Now we throw an error if the server is in HA. This is
because there is no guarantee that the server where the
request lands has access to the file locally.

https://mattermost.atlassian.net/browse/MM-57997
```release-note
Clarify that `mmctl import process --bypass-upload --local` doesn't work if the server is in HA.
```

### CODE REVIEW

**Comment by isacikgoz** [comment]
@agnivade In HA mode, how do we use `mmctl --local`? It's supposed to be used in the app node anyway, and the request should always land in that node. Was it another scenario (eg. connecting through proxy)?

**Comment by agnivade** [comment]
Oh you are right. But what happened was that in HA, the job server was scheduled in another node. That's why it couldn't access the file.

**Comment by isacikgoz** [comment]
I see, is there an easy way to force job to get scheduled on same node? Maybe it's beyond the scope but in any case WDYT?

**Comment by agnivade** [comment]
Yeah I don't think there's an easy way. Anyways, it's out of scope for this PR.

**Review by streamer45 — APPROVED** [review]

**Pull request merged**
