### PR TITLE
[MM-53491] Fix rendering of active call icon in sidebar's channel link

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

To make this fix, we need some minor changes on this side because of how elements are laid out.

I am removing this `truncated` class because I couldn't justify why we'd need to make it dynamic. I understand we show a tooltip in certain cases, but I think it makes sense to set the overflow properties of the text content from the start regardless so that it works naturally when needed. Let me know if you can think of any issues with this approach.

#### Design

https://www.figma.com/design/KAdDampXIcjzQ8oWMs7LpZ/MM-53491-Calls%3A-Rendering-of-LHS-active-call-icon?node-id=1-7&m=dev

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-53491

#### Related PR

https://github.com/mattermost/mattermost-plugin-calls/pull/754

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by cpoile — APPROVED** [review]
Thanks!

**Review by abhijit-singh — APPROVED** [review]
Looks good, thanks!

**Review by hmhealey — CHANGES_REQUESTED** [review]
Unfortunately, this breaks some behaviour the sidebar has where, if a channel name is too long, it's shown in a tooltip when you hover over the channel

Screenshot 2024-05-31 at 11 41 14 AM

That's a bit of a niche feature that predates the ability to resize the LHS though, so I'm not sure if we even need it any more. 

Alternatively, we might be able to solve this issue by moving the Pluggable outside of its current div. That would probably change the call icon to be right-aligned though.

@abhijit-singh Any thoughts on either of those options?

**Comment by streamer45** [comment]
@hmhealey Thanks for catching that. I think it was an oversight on my part as I specifically tested this behavior to avoid breaking it, but then I must have changed something without realizing it would cause a regression. I think it should work as before now, please take a look.

**Review by hmhealey — APPROVED** [review]
Thanks for fixing that. I'm always happy to see us get rid of a seemingly-unneeded div as well

**Comment by streamer45** [comment]
@DHaussermann, not much is needed here; some smoke testing around how the channel name labels in LHS render under different conditions, such as custom statuses, unreads, and a narrow sidebar.

**Comment by DHaussermann** [comment]
Tested the webapp changes with an updated build of the plugin 
- Channel name does truncate more aggressively now to leave a bit of "padding space" in he LHS between ... at the end of channel name and call icon
image
- Tested read channel
- Tested unread channel
- Tested unread channel with badge
- Test DM channel with combination of badge and/or custom status
- Check GM and Private channels as precaution
- Hover state - Truncation becomes more aggressive and calls icon moves to to the left slightly to make space for vertical 3 dot channel options icon  
- No issues with narrow resolution
- Mobile web view no longer shows cut-off icon when channel name is long 
- Updated branch with `master` as a precaution

I can approve this but would like to try and see E2E tests first.

**Comment by streamer45** [comment]
@amyblais This is fixing a long-standing UX bug for Calls. There's a requirement that this gets in with Calls v0.28, so asking for cherry-picking if possible.

**Comment by DHaussermann** [comment]
@streamer45 0/5 any chance this test failure could be related?
image

I'm currently investigating to see if this Cypress test failed before but you may have thoughts.

**Comment by streamer45** [comment]
@DHaussermann At first glance, it doesn't seem related to the changes, but it is hard to tell without looking into the steps further.

**Comment by DHaussermann** [comment]
@streamer45 sorry for the delay, normally I think tests just run against a nightly to check easily which failures are new but, the E2E test where non-functional recently.  

Given that this is slightly time sensitive and the pass rate is well within norms, as well as this test not being obviously related, I think we should proceed and merge. I will continue to investigate this and follow-up with you if I think there is new maintenance needed.

**Comment by streamer45** [comment]
Sounds good @DHaussermann

**Review by DHaussermann — APPROVED** [review]
Tested and passed based on testing above. 

LGTM!

I will follow up if maintenace is needed on 1 test mentioned. 

@streamer45 please merge when you have a chance.

**Pull request merged**
