### PR TITLE
[MM-59902] Migrate tooltips of 'components/global_header/right_controls/settings_button/settings_button.tsx' to WithTooltip

### PR DESCRIPTION
**Pull request by Camillarhi**
#### Summary

Migrate tooltips to use WithTooltip in  'components/global_header/right_controls/settings_button/settings_button.tsx' file
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27779
Jira https://mattermost.atlassian.net/browse/MM-59902

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
Can you check the failing CI

**Comment by M-ZubairAhmed** [comment]
> > Can you check the failing CI
> 
> I have resolved it

There still seems be another one failing, can you check again

**Comment by Camillarhi** [comment]
> I have resolved it

I have resolved failing lint

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by Rajat-Dabade — APPROVED** [review]

**Comment by amyblais** [comment]
@holopin-bot @Camillarhi Mattermost Most Valued Professional (MVP)

**Comment by Camillarhi** [comment]
> @holopin-bot @Camillarhi Mattermost Most Valued Professional (MVP)

Thanks 🎉

**Pull request merged**
