### PR TITLE
Rename System Roles to Delegated Granular Administration

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary
Rename System Roles to Delegated Granular Administration in System Console.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-57463

#### Screenshots
|  before  |  after  |
|----|----|
| Screenshot 2024-07-25 at 9 15 34 PM| Screenshot 2024-07-25 at 10 18 53 PM |

#### Release Note

```release-note
Rename System Roles to Delegated Granular Administration in System Console.
```

### CODE REVIEW

**Comment by marianunez** [comment]
@cwarnermm the long name seems to be OK by wrapping on the LHS. Let me know if we also want to change the reference of system roles in the help text in the feature discovery screen:

Screenshot 2024-07-25 at 10 18 53 PM

Screenshot 2024-07-25 at 10 18 26 PM

**Comment by esethna** [comment]
@cwarnermm my 2c is that throwing another capitalized term (System Roles) in the feature discovery help text can make it more confusing. If we want to keep the reference to the fact that these are "roles" perhaps we can word it like:  

"Assign customizable admin roles to give designated users..."

**Comment by cwarnermm** [comment]
Thanks, @esethna!

**Review by wiggin77 — APPROVED** [review]
Approving for correctness.  The new wording is bordering on sesquipedalian IMO.

**Comment by marianunez** [comment]
> Approving for correctness. The new wording is bordering on sesquipedalian IMO.

+1 - (had to google sesquipedalian 😄  but I agree )

**Comment by marianunez** [comment]
> . If we want to keep the reference to the fact that these are "roles" perhaps we can word it like:
> 
> "Assign customizable admin roles to give designated users..."

@esethna Updated 

Screenshot 2024-07-29 at 5 47 38 PM

**Review by esethna — APPROVED** [review]

**Comment by amyblais** [comment]
@cwarnermm Kind reminder for this PR review.

**Review by cwarnermm — APPROVED** [review]

**Pull request merged**
