### PR TITLE
[MM-61776] Fix errcheck issues in server/channels/app/platform/web_conn.go

### PR DESCRIPTION
**Pull request by Honsei901**
#### Summary
Fix errcheck issues in server/channels/app/platform/web_conn.go

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/29440
Jira [MM-61776](https://mattermost.atlassian.net/browse/MM-61776)

#### Release Note

```release-note
NONE
```

[MM-61776]: https://mattermost.atlassian.net/browse/MM-61776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Thanks for the PR @Honsei901 :+1: 

I think the changes are fine. @agnivade can you please double-check?

**Review by agnivade — COMMENTED** [review]
Some small comments. Nice work.

**Comment by Honsei901** [comment]
@agnivade
Thank you for your feedback.
I resolved.

**Review by agnivade — APPROVED** [review]
Nice work!

**Pull request merged**
