### PR TITLE
[MM-59063] Remove waiting for plugins and products before loading all the routes

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-59063

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]
Do we want / have tickets for the TODO comments? It is nice to have each TODO with a jira ticket assigned in code, so we know it is tracked. (e.g. `// TODO: Do something http://mattermost.atlassian.net/...`)

**Comment by M-ZubairAhmed** [comment]
> Do we want / have tickets for the TODO comments? It is nice to have each TODO with a jira ticket assigned in code, so we know it is tracked. (e.g. `// TODO: Do something http://mattermost.atlassian.net/...`)

Ah yes i have forgot to remove those, i already have ticket for those

**Comment by hmhealey** [comment]
Can you check that this doesn't cause any issues with refreshing the app with Playbooks backstage open or opening the expanded view for Calls? I don't think I actually tested that when we were discussing this earlier

**Comment by M-ZubairAhmed** [comment]
Closing as per conversation at https://mattermost.atlassian.net/browse/MM-59063

**Pull request closed without merging**
