### PR TITLE
Sanitize RemoteEmail user prop

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
If the server is configured to hide user emails, the "RemoteEmail" user property will be sanitized as well, effectively hiding the real email of remote users.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-58247

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by esarafianou — APPROVED** [review]

**Pull request merged**
