### PR TITLE
Cleans RemoteId when sanitizing post input from the API

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
This PR moves the sanitizing of posts to a specific function on the model and cleans the `RemoteId` field if set.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-58277

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by esarafianou — APPROVED** [review]

**Review by calebroseland — APPROVED** [review]

**Pull request merged**
