### PR TITLE
Adds a feature flag to control availability of DMs in shared channels (#28920)

### PR DESCRIPTION
**Pull request by mgdelacroix**
Cherry pick #28920

```release-note
NONE
```

### CODE REVIEW

**Review by calebroseland — APPROVED** [review]

**Comment by amyblais** [comment]
@mgdelacroix There are some failing tests here.

**Comment by mgdelacroix** [comment]
@amyblais on it. I'm rerunning the tests as it seems to be a flaky one, but I'll check the job and fix the tests if it happens again

**Pull request merged**
