### PR TITLE
[MM-55092] Replace usage of LocalizedIcon in 'admin_navbar_dropdown.tsx' with i/span tags

### PR DESCRIPTION
**Pull request by ARJ2160**
Fixes [Issue-#25081](https://github.com/mattermost/mattermost/issues/25081)
JIRA [Link](https://mattermost.atlassian.net/browse/MM-55092)

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@ARJ2160 please add screenshot
image

**Comment by ARJ2160** [comment]
Will update this PR with screenshots ASAP. I am having some troubles starting up the project locally.

**Review by M-ZubairAhmed — COMMENTED** [review]
This is awesome work @ARJ2160 , will wait for the CI to turn green.
Do reach out to us at https://community.mattermost.com/core/channels/developers for problems related to starting up

**Review by M-ZubairAhmed — APPROVED** [review]
Thank you for your remarkable contributions 🙏🏽 💟

**Comment by yasserfaraazkhan** [comment]
image

**Review by yasserfaraazkhan — APPROVED** [review]

**Review by larkox — APPROVED** [review]

**Pull request merged**
