### PR TITLE
Adding Vietnamese as a new language (beta)

### PR DESCRIPTION
**Pull request by ctlaltdieliet**
#### Summary
Adding Vietnamese as a new shipped language (beta)
@cwarnermm 
This PR is related to https://github.com/mattermost/mattermost-mobile/pull/7462 and to https://github.com/mattermost/desktop/pull/2872

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by Willyfrog** [comment]
> Lint fails because the translations aren't merged yet from Weblate

@ctlaltdieliet is that something we need to do here or in weblate?

**Comment by ctlaltdieliet** [comment]
It was added in Weblate that wants to be the one and only true source of translations but was removed after a rebase.
I can add it again and if we merge the translations into master it would be ok.
But we also have this [PR](https://github.com/mattermost/mattermost/pull/21327) that brings the WIP-languages under the shipped repository. So maybe there needs to be some coordination between this and that PR but I'm not sure.

**Comment by ctlaltdieliet** [comment]
I see that the vi.json file isn't pushed from Weblate to Master. Will be done probably Monday Oct 13th

**Comment by ctlaltdieliet** [comment]
cc @lieut-data Ready to be merged! :tada:

**Comment by lieut-data** [comment]
Thanks, @ctlaltdieliet! I'll take a look, but it also looks like some of the snapshots are out of date?

**Comment by ctlaltdieliet** [comment]
Hi @lieut-data ,
I'll need some help on this one. I updated the snapshots, one got updated but still the tests are failing. But the failing test is not related to my PR as far as I can see.

**Comment by lieut-data** [comment]
@lindalumitchell, can you help me find the right owner for QA'ing the addition of this supported language?

**Comment by lieut-data** [comment]
@ctlaltdieliet, I added Vietnamese as a server supported language (this is required because of the change to merge WIP languages but "hide" them from the server). Unfortunately, it looks like there might be a parsing error with the current translation?

```
Error: unable to load Mattermost translation files: unable to parse translation #934 because template: Không thể thêm tùy chọn kênh trực tiếp cho người dùng user_id = {{. UserId}}, team_id = {{. TeamId}}, err = {{. Error}}:1: function "UserId" not defined
map[id:api.user.add_direct_channels_and_forget.failed.error translation:Không thể thêm tùy chọn kênh trực tiếp cho người dùng user_id = {{. UserId}}, team_id = {{. TeamId}}, err = {{. Error}}]
```

**Comment by ctlaltdieliet** [comment]
Hi @lieut-data,
I checked the translation string but didn't see an error. I took the current vi.json from Weblate, removed the string from vi.json and added to this PR. But still no test-server spinning up

**Comment by lieut-data** [comment]
@ctlaltdieliet, actually removing that looks good! No more CI issues starting up the server, so I think we're good for a QA pass before merging.

**Review by lindalumitchell — APPROVED** [review]
Checked through e2es and no relevant failures found. Also ran through various pages in Vietnamese and a couple other languages with no issues found. LGTM!

**Comment by lieut-data** [comment]
Thank you, @lindalumitchell!

**Pull request merged**
