### PR TITLE
circleci/config.yml: comment out linter in the CI

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Skip linter for inconsistent findings. ~~We already disabled on `master` as well~~ Sorry, it's not being skipped in `master` anymore. Thanks for the clarification @agnivade.

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by amyblais — APPROVED** [review]

**Comment by agnivade** [comment]
There's a incorrect branch checkout issue or some other code related issue here. The error is confusing because golangci errors are bad, and that's why I moved vet before golangci [here](https://github.com/mattermost/mattermost/commit/c7295b01e56406c75b051f5ceb3c0d46986e8bf8).

But it looks like the error is coming from somewhere in the code. It's not a trivial one.

**Comment by isacikgoz** [comment]
> But it looks like the error is coming from somewhere in the code. It's not an ignorable one.

The one occurs in the EE tests, yes. I'm going to look into that, but the first error here was about linter I guess: [workflow](https://app.circleci.com/pipelines/github/mattermost/mattermost/41971/workflows/e03609ea-9cd3-448b-b3fa-a7921e8c438f/jobs/394702)

**Comment by mvitale1989** [comment]
That error looks like the one I had yesterday: https://community.mattermost.com/private-core/pl/afi1pbjeopgbpk9m5ndfcxpz7c

It seems that the wrong focalboard branch is being checked out, it's using `rolling-stable` instead of `release-7.8`: https://app.circleci.com/pipelines/github/mattermost/mattermost/41973/workflows/876da654-ddcf-4f75-9a2f-4cb2d5e9baeb/jobs/394714

**Comment by isacikgoz** [comment]
@mvitale1989 I updated my branch, it was out of date somehow. I think it's going to resolve the issue here.

**Comment by isacikgoz** [comment]
ping @agnivade

**Comment by isacikgoz** [comment]
Discussed offline, the issue is indeed checking out the incorrect branch of focalboard due to lack of an environment variable that we are using while trying to figure out focalboard branch. @amyblais manual cherry-picks should solve this issue. Hence closing this PR.

**Pull request closed without merging**
