### PR TITLE
[MM-59909] Migrate tooltips of 'components/user_group_popover/group_member_list/group_member_list.tsx' to WithTooltip

### PR DESCRIPTION
**Pull request by hereje**
#### Summary

replace SimpleTooltip with WithTooltip on group_member_list.tsx

- replace SimpleTooltip with WithTooltip
- update snapshot

#### Ticket Link
fixes: #27792

Jira https://mattermost.atlassian.net/browse/MM-59909

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@hereje thank you for working on this pr so quick. Can you please comment on the ticket next time to avoid confusion between contributors.

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
Can you check the CI for failing checks

**Comment by hereje** [comment]
> Can you check the CI for failing checks

Yes, sure.

**Comment by M-ZubairAhmed** [comment]
@hereje can you update the snapshots we have npm command for that `test:updatesnapshot`

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
