### PR TITLE
[GH-16800]: Use GetBuilder and SelectBuilder in group_store.go

### PR DESCRIPTION
**Pull request by djanda97**
#### Summary

This PR refactors some methods in group_store.go to use GetBuilder and SelectBuilder to remove some boilerplate.

#### Ticket Link

#16800

#### Release Note

```release-note

```

### CODE REVIEW

**Review by agnivade — APPROVED** [review]

**Review by isacikgoz — APPROVED** [review]
LGTM! Thanks for the contribution @djanda97 🚀

**Pull request merged**
