### PR TITLE
[MM-55117] Replace usage of LocalizedIcon in 'view_user_group_modal_header.tsx' with i/span tags

### PR DESCRIPTION
**Pull request by sapnasivakumar**
…ader.tsx with i/span tags

#### Summary
This PR is to be taken over by a core contributor to check if the changes included does'nt break the user group modal and add on any further code changes required to ship to production.
As discussed on a separate thread with core contributors, Community members can not work on task related to group as it requires a license as of now. It was agreed upon to take the above approach of handing over the code changes made so far to a core contributor.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/25093
Jira https://mattermost.atlassian.net/browse/MM-55117

#### Screenshots
Will have to attached by the core contributor taking over
#### Release Note
NONE

### CODE REVIEW

**Comment by sapnasivakumar** [comment]
@M-ZubairAhmed 
As discussed, I've pushed the changes I've made so far.
Do let me know if I can help further in any way

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
Please also take a look at CI failures

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
tested view group modal. Working as expected.

**Pull request merged**
