### PR TITLE
[MM-58445] Try deferring plugins scripts loading

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
What changed?
Plugins are now loaded by deferred script. 

What improved?
plugins defer script comparision

As seen the scripts now load a lot later than they previously would. That is better because the once the plugins scripts are loaded they do execute some long task depending on the plugins

CleanShot 2024-05-28 at 17 41 10@2x

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-58445

#### Screenshots
n/a

#### Release Note

```release-note
Added defer loading plugins scripts
```

### CODE REVIEW

**Review by mickmister — APPROVED** [review]
This is awesome 🚀   I think this will be a big improvement on deployments that have a lot of plugins installed like the community server

What are the implications here it terms of running things "in the right order"? Since plugins can already be installed/enabled asynchronously during runtime, I imagine deferring their asynchronous execution here is just as applicable.

LGTM :+1: Can we put this behind a feature flag somehow so we can test this selectively on community? If we think there is minimal risk to the change, we can merge as is.

**Comment by mickmister** [comment]
Does using the `async` attribute help with this as well? https://javascript.info/script-async-defer#async

**Review by hmhealey — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
Tested on spin wick with playbook and AI plugin. working as expected

**Comment by M-ZubairAhmed** [comment]
> This is awesome 🚀 I think this will be a big improvement on deployments that have a lot of plugins installed like the community server
> 
> What are the implications here it terms of running things "in the right order"? Since plugins can already be installed/enabled asynchronously during runtime, I imagine deferring their asynchronous execution here is just as applicable.
> 
> LGTM 👍 Can we put this behind a feature flag somehow so we can test this selectively on community? If we think there is minimal risk to the change, we can merge as is.

1. There isn't much of a difference if you observe from the above graph, there is a small gain here. This change however is supposed to effect the plugins loaded at initial load and on reconnect.
2. I agres since this is a minimal risk we can merge this as is.

**Pull request merged**
