### PR TITLE
Add Hacktoberfest 2024 Holopin badge to holopin.yml

### PR DESCRIPTION
**Pull request by azigler**
See https://github.com/mattermost/mattermost/pull/26808 for historical context

See https://github.com/marketplace/holopin for usage

### CODE REVIEW

**Comment by azigler** [comment]
@iyampaul @hanzei Could I enlist your help with reviews again?

cc @lindy65 @hannaparks @cwarnermm

**Review by hanzei — APPROVED** [review]
🚀

**Comment by lindy65** [comment]
Looks great! Thanks @azigler 🤗

**Review by iyampaul — APPROVED** [review]

**Comment by azigler** [comment]
@iyampaul Any sense of when this can be merged? Thanks for your help!

**Pull request merged**
