### PR TITLE
[MM-32770] Inform user that mentions added in edited posts won't trigger notifications for the receiving user

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
Add message in edit post "Editing this message with an '@mention' will not notify the recipient."
co-author: @Dhoni77
Note: This is based on discussion in https://github.com/mattermost/mattermost/pull/24920

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/24845
Jira https://mattermost.atlassian.net/browse/MM-32770

#### Screenshots
Screenshot 2024-06-16 at 5 29 50 PM

Screenshot 2024-06-16 at 5 30 00 PM

#### Release Note

```release-note
UI: Add message in edit post "Editing this message with an '@mention' will not notify the recipient."
```

### CODE REVIEW

**Comment by matthewbirtch** [comment]
@abhijit-singh could you please review this?

**Review by marianunez — APPROVED** [review]
Thanks @AshishDhama! 🎉 

Would you be open to add a E2E test (like [this one](https://github.com/mattermost/mattermost/blob/master/e2e-tests/cypress/tests/integration/channels/messaging/message_edit_post_clear_text_spec.js#L26)) ?

**Comment by AshishDhama** [comment]
@marianunez @yasserfaraazkhan I have added the e2e, but I think you need to create new e2e test id for this.

**Review by abhijit-singh — CHANGES_REQUESTED** [review]
Thanks @AshishDhama! Looks good functionally. 

Can we update the colour of the error message to `rgba(var(--center-channel-color-rgb), 0.75)` and the icon to `rgba(var(--center-channel-color-rgb), 0.64)`? Also, the font size and the icon size needs to be reduced to match the design - [Figma link](https://www.figma.com/design/diJr9UgrfuaOqgGGoRqmID/MM-32770-Edited-posts-won't-trigger-notifications?node-id=1001-49138&t=CFLUoyfYM1K48Zve-4).

**Review by yasserfaraazkhan — APPROVED** [review]
@AshishDhama thank you for adding the test.
there's a eslint error that's blocking cypress tests from running.

If possible can you add a step to verify the warning message in the RHS threads screen.

**Review by abhijit-singh — APPROVED** [review]
Awesome, thanks @AshishDhama!

**Review by M-ZubairAhmed — APPROVED** [review]

**Pull request merged**
