### PR TITLE
Fix updated error text

### PR DESCRIPTION
**Pull request by lindalumitchell**
Updated failing test's error text to new message `A channel with that name already exists on the same team.`

Test that has been failing: [MM-T882 Channel URL validation works properly](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T882)
Ticket with updated text: https://mattermost.atlassian.net/browse/MM-54713

Screen Shot 2023-11-29 at 6 28 56 PM

Screen Shot 2023-11-29 at 6 29 07 PM

### CODE REVIEW

**Comment by lindalumitchell** [comment]
e2es look good. The test that is fixed here no longer fails 🎉 , and no other issues found.

**Review by saturninoabril — APPROVED** [review]
Totally missed this, thanks @lindalumitchell!

**Review by mvitale1989 — APPROVED** [review]
LGTM, thanks for fixing Linda :rocket:

**Pull request merged**
