### PR TITLE
[MM-51521] Prevent adjusting password stength fields when set in environment

### PR DESCRIPTION
**Pull request by thinkGeist**
#### Summary
The GH issue and Jira ticket mention 3 separate issues, however only **2** is a real issue:
1. `Allow untrusted connections to` setting is erroneously not locking itself out when set with `MM_SERVICESETTINGS_ALLOWUNTRUSTEDINTERNALCONNECTIONS=`

    - Non-issue, could be reproduced locally but determined env variable mentioned is incorrect - using `MM_SERVICESETTINGS_ALLOWEDUNTRUSTEDINTERNALCONNECTIONS=` resolves the issue

2. **Password strength options aren't set/locked out by env variables**

    - **Visual bug, they appear configurable but the update requests to the server will make no changes. New admin input class required to model multiple "sub settings"**

3. Session length settings aren't locked out by env variables

    - Non issue, issue creator was erroneously using `MM_SERVICESETTINGS_SESSONLENGTHMOBILEINHOURS` instead of `MM_SERVICESETTINGS_SESSIONLENGTHMOBILEINHOURS`

This change addresses an issue where configuring a password strength environment variable such as:
- `MM_PASSWORDSETTINGS_UPPERCASE`
- `MM_PASSWORDSETTINGS_SYMBOL`

Would not properly grey out the field (though the server would still prevent the update).

To address this I have introduced a new admin "Setting" class - `CheckboxSetting` and made some adjustments so the password strength settings stay similarly styled to before.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/23719
Jira https://mattermost.atlassian.net/browse/MM-51521

#### Screenshots
Running the server with the following exported variables:
```
<user>:~/repos/mattermost-server/server$ printenv | grep '^MM' 
MM_PASSWORDSETTINGS_SYMBOL=false
MM_PASSWORDSETTINGS_LOWERCASE=true
MM_PASSWORDSETTINGS_NUMBER=true
MM_PASSWORDSETTINGS_UPPERCASE=false
```

|  before  |  after  |
|----|----|
| image | image |

#### Release Note
```release-note
Added support for checkbox type admin settings
Corrected an issue where password strength settings wouldn't be disabled if they were set through the environment
```

### CODE REVIEW

**Review by calebroseland — APPROVED** [review]
Everything looks good to me, thanks for fixing and looking into all of this, @thinkGeist! And thank you for your patience 🙏

**Review by lindy65 — APPROVED** [review]
Thanks @thinkGeist - Caleb has tested locally so I'm going to QA defer this PR and test after it's merged

**Review by crspeller — APPROVED** [review]

**Comment by thinkGeist** [comment]
Merge conflicts adjusted and branch updated from `master`

**Comment by hanzei** [comment]
Thanks for the contribution @thinkGeist :tada:

**Pull request merged**
