### PR TITLE
[skip ci] Enhance reporting, add shellcheck

### PR DESCRIPTION
**Pull request by mvitale1989**
#### Summary

This PR improves on error checking and reporting if the Automation Dashboard is used in a run: in such a case, the run results are pulled from the Automation Dashboard, to find out about expected failures (known/flaky/skipped specs) and avoid counting them as run failures, since those are usually unrelated to the changes contained in a PR.

This will allow us to increase our confidence in enabling `testcase_failure_fatal` in the future, netting out errors that are unrelated to the PR itself.

Additionally, this adds the shellcheck CI job to the E2E testing scripts.

#### Ticket Link

https://mattermost.atlassian.net/browse/CLD-7761

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by mvitale1989** [comment]
Triggering the full E2E test manually, to test out this branch's version of the workflow files

**Comment by mvitale1989** [comment]
For ease of review, ,this is the resulting run description at this point:
image

You can verify that [the Automation Dashboard was consulted](https://github.com/mattermost/mattermost/actions/runs/10957579132/job/30427484841#step:6:17) for producing the results, and the resulting output files (`ad_cycle.json` and `ad_specs.json`) may be found in the `e2e-test-results` artifact in [the workflow summary page](https://github.com/mattermost/mattermost/actions/runs/10957579132)

**Review by saturninoabril — APPROVED** [review]
Wow, thanks @mvitale1989!

**Review by toninis — APPROVED** [review]

**Pull request merged**
