### PR TITLE
[MM-40568] Do not strip notification text for all platforms

### PR DESCRIPTION
**Pull request by BarbUk**
#### Summary

This pull request proposes the removal of notification text trimming functionality specifically for Linux systems.
Notification size and trimming is handled at the notification server level, so mattermost can send the full notification for linux.

The current implementation of text trimming in notifications can result in important information being truncated,
leading to a less than optimal user experience.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/23314
Jira https://mattermost.atlassian.net/browse/MM-40568

#### Release Note

```release-note
Stopped truncating text in desktop notifications
```

### CODE REVIEW

**Comment by BarbUk** [comment]
This is a draft PR because I don't know if this is just a linux issue (all linked issue on github and jira are from linux users).

I have users on linux, macos and windows and will test this PR with them.

**Comment by BarbUk** [comment]
Mattermost desktop app now send full message notification:

image

The webapp too:

image

I still have a limit with a more complex notification:
```bash
curl --fail --connect-timeout 30 --max-time 60 -H 'Content-Type: application/json' --silent --show-error -X POST --data '{"attachments":[{"color":"danger","fallback":"\ud83d\udd34 PROBLEM: Lorem ipsum dolor  sit amet, consectetur adipiscing elit. Pellentesque venenatis dui et dolor sagittis, et posuere purus ultricies. ```CRITICAL - 302 slow queries in 60 seconds (5.03/sec)```","fields":[{"short":true,"title":"Host","value":"<https://rien.rien.nope/monitoring/host/show?host=vmtest.test|vmtest.test>"},{"short":true,"title":"Service","value":"<https://rien.rien.nope/monitoring/service/show?host=vmtest.test&service=Mysql slow queries|Mysql slow queries>"}],"footer":"Icinga Alerts","text":"```\nCRITICAL - 302 slow queries in 60 seconds (5.03/sec) \n```","title":"\ud83d\udd34 PROBLEM: Service Mysql slow queries transitioned from state WARNING to state CRITICAL","ts":1710581493}],"username":"monitoring"}' 'https://mattermost-pr-26536.test.mattermost.cloud/hooks/i5rag4kjcbyg5e78pg1rk1jf9a'
```

image

This is using the `fallback` text, I'll check this.

**Comment by BarbUk** [comment]
This seems to be a limit only on the `fallback` text.
Calling an incoming hook with a `text` and without a `fallback` field produce the correct output:

```bash
curl --fail --connect-timeout 30 --max-time 60 -H 'Content-Type: application/json' --silent --show-error -X POST --data '{"attachments":[{"color":"danger","fields":[{"short":true,"title":"Host","value":"<https://rien.rien.nope/monitoring/host/show?host=vmtest.test|vmtest.test>"},{"short":true,"title":"Service","value":"<https://rien.rien.nope/monitoring/service/show?host=vmtest.test&service=Mysql slow queries|Mysql slow queries>"}],"footer":"Icinga Alerts","text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque venenatis dui et dolor sagittis, et posuere purus ultricies. Mauris sem sem, suscipit sed placerat vitae, laoreet quis diam. Fusce et arcu metus. Suspendisse nunc urna, placerat sed libero at, semper molestie mauris. Mauris porttitor urna quam. Cras elementum tortor nec dapibus laoreet. In pharetra, urna ut dignissim pretium, lorem neque consectetur nulla, vel blandit enim sem a nulla. Aliquam auctor, dui vitae blandit mollis, enim erat feugiat ante, sed aliquet urna enim at orci. Ut quis ligula libero. Donec fringilla mattis lorem eget tempus. Suspendisse id nisi lacus. Nunc tempus nibh eu mauris faucibus gravida. Fusce ultricies tincidunt lectus, sit amet faucibus ante vulputate in. Morbi iaculis enim a augue porta, eu feugiat libero placerat.```\nCRITICAL - 302 slow queries in 60 seconds (5.03/sec) \n```","title":"\ud83d\udd34 PROBLEM: Service Mysql slow queries transitioned from state WARNING to state CRITICAL","ts":1710581493}],"username":"monitoring"}' 'https://mattermost-pr-26536.test.mattermost.cloud/hooks/i5rag4kjcbyg5e78pg1rk1jf9a'
```

image

**Comment by BarbUk** [comment]
Tested on windows:

Desktop app:
Capture2

Web app:
Capture

The scope of this PR was to send the full notification text under linux.
So it's ready for review.

**Comment by BarbUk** [comment]
Tested this morning with a colleague using linux mint:
image

**Comment by devinbinnie** [comment]
@BarbUk Thanks for this PR! So we had an internal discussion and decided that we are happy to just remove the truncation altogether for all OSes. Appreciate the upfront testing :)
Would you be able to just remove the truncation code altogether? Happy to review after that :)

**Comment by BarbUk** [comment]
> Would you be able to just remove the truncation code altogether?

Yes.

> Happy to review after that :)

Perfect, I'll let you know.

**Review by hmhealey — APPROVED** [review]
Thanks for the PR! The code for this looks good to me assuming we don't end up needing to change anything for any OSes.

@yasserfaraazkhan I submitted https://github.com/mattermost/mattermost/pull/26611 to try to generate a test server for this since I feel like those still have troubles with community forks

**Comment by hmhealey** [comment]
Test server: https://github.com/mattermost/mattermost/pull/26611#issuecomment-2022932828

**Review by devinbinnie — APPROVED** [review]
Thanks for updating the PR :) LGTM!

**Comment by hmhealey** [comment]
I've updated https://github.com/mattermost/mattermost/pull/26611 accordingly, so hopefully it updates the test server as well

**Review by yasserfaraazkhan — APPROVED** [review]
🎉

**Pull request merged**
