### PR TITLE
[MM-61361] Force reconnect handler to fetch channel categories on reconnect

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
When a user received a message in a new channel while they are not connected to the websocket, when they eventually reconnect, the mention/unread would show up in the titlebar, but not in the sidebar. This was caused by the sidebar not having up to date channel ids in categories, and thus not giving the sidebar a reason to re-render.

This PR forces the `reconnect` handler to fetch your channel categories on reconnection so that we keep those in sync, and thus the sidebar should have the up to date categories and channels.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-61361

```release-note
Fixed an issue where new messages from new channels wouldn't appear in the sidebar after reconnecting the websocket
```

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
GM appears in the mobile after the mobile data is turned back on and we opened the app

**Review by pvev — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
