### PR TITLE
 [MM-55994] Fix nbsp in group list modal

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
There are no tests for the modal. Given the small scale of the fix, I didn't take the time to write them from scratch.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-55994

#### Screenshots
|  before  |  after  |
|----|----|
| Screenshot from 2023-11-30 14-23-39 | Screenshot from 2023-11-30 14-35-25  |

#### Release Note
```release-note
Remove control character from group list modal
```

### CODE REVIEW

**Review by JulienTant — APPROVED** [review]

**Comment by hanzei** [comment]
@sbishel I currently don't have the capacity to work on the tests. What do you think about merging the PR as it is and I'm happy to file a follow up ticket to add the tests and mark that as HW?

**Review by sbishel — APPROVED** [review]
ok

**Comment by DHaussermann** [comment]
@hanzei I tried to reproduce this locally before deploying your code but I cannot get the non-breaking space to show in the group name. 
image
I cannot add the `&nbsp;` character to the team name on the LDAP side but it does seem from your steps that this character is coming from LDAP. 

Any thoughts you can share here?

**Comment by hanzei** [comment]
@DHaussermann I updated the steps to reproduce the issue in JIRA. Could you please take another look?

**Review by DHaussermann — APPROVED** [review]
Tested and passed
The `&nbsp` character that was leading the text has been removed
Briefly regression tested. 
No issues found 

LGTM!

**Comment by hanzei** [comment]
Opened https://mattermost.atlassian.net/browse/MM-57343

**Pull request merged**
