### PR TITLE
Skip racy subtest from TestUpdateChannelBookmarkSortOrder

### PR DESCRIPTION
**Pull request by mgdelacroix**
https://mattermost.atlassian.net/browse/MM-60499

```release-note
NONE
```

### CODE REVIEW

**Review by enahum — COMMENTED** [review]
What is causing the problem? Do. You know?

**Comment by mgdelacroix** [comment]
@enahum I'm afraid I don't, didn't have time to investigate on the spot

**Comment by enahum** [comment]
> @enahum I'm afraid I don't, didn't have time to investigate on the spot

Alright I'll have a look tomorrow and see if it can be fixed instead of skipped

**Comment by mgdelacroix** [comment]
Awesome, thanks. If I had to guess, either we're not triggering the WS event or it's firing outside the timeout window. The event firing after 5 seconds doesn't look right, I'd go with the first one

**Comment by enahum** [comment]
> Awesome, thanks. If I had to guess, either we're not triggering the WS event or it's firing outside the timeout window. The event firing after 5 seconds doesn't look right, I'd go with the first one

well the event is being broadcasted but is happening outside the time window. not sure what may be the problem here, but the actual call to UpdateChannelBookmarkSortOrder on my local machine is taking 22ms so my inclination is to bump the 5 seconds

**Review by enahum — APPROVED** [review]

**Pull request merged**
