### PR TITLE
MM-61525, MM-61868: Autohide channel bookmarks when empty

### PR DESCRIPTION
**Pull request by calebroseland**
#### Summary
Commits:
1. Enforce `add`, `order` permissions in UI
  a. 7df430e724c59bd3f65164165315a8971ba29045 disable drag/drop when no permission to re-order bookmarks
  b. c81aa4c20b85ab0f3788f4e91ff3ddc1ae2c417c hide bookmarks add menu when no permission to add bookmarks, make bookmark creation handlers reusable
2. 245c5245482329b56cc5da28acf93e195ef2ea5d hide bookmarks bar when empty
3. d9f36aabd84bbea2e15773fb595f0842b3dd8ff4 add bookmarks from channel menu
4. 59d14cf254eebd9c0b1ac4de87cb059ae9eccad0, 6cc9bf77f81cdf1e03ee5842358673f8ea3ae075 add e2e tests

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-62051
https://mattermost.atlassian.net/browse/MM-62052
https://mattermost.atlassian.net/browse/MM-61525
https://mattermost.atlassian.net/browse/MM-61868

#### Screenshots

https://github.com/user-attachments/assets/92613a4b-1344-4d55-b9b1-51802e37201a

CleanShot 2024-12-02 at 17 53 13

E2E added:
CleanShot 2024-11-28 at 01 07 30@2x

#### Release Note

```release-note
The channel bookmarks bar is now hidden when there are no bookmarks in the channel. Bookmarks can now be added from the channel menu.
```

### CODE REVIEW

**Review by enahum — APPROVED** [review]
Overall lgtm but there are some failing tests

**Comment by asaadmahmood** [comment]
@calebroseland I cannot add a bookmark, also the bookmark icon emoji button when adding a link is broken.
CleanShot 2024-12-03 at 17 23 57@2x
CleanShot 2024-12-03 at 17 24 23@2x
CleanShot 2024-12-03 at 17 23 51@2x

**Review by asaadmahmood — CHANGES_REQUESTED** [review]
See comment.

**Review by wiggin77 — CHANGES_REQUESTED** [review]
Code looks good to me.  I'll wait for fixes before approval.

**Comment by calebroseland** [comment]
@asaadmahmood @wiggin77 fixed the issue with the menu being available when there isn't a license — test server didn't have a license and that combo caused the save error. Both of those are fixed and this should be ready to review, now.

**Comment by asaadmahmood** [comment]
@calebroseland two minor things.
First one may be unrelated but it is slightly diverging form the designs.
If we need to add that padding when it overflows, lets only add it then.

CleanShot 2024-12-05 at 19 15 32@2x

CleanShot 2024-12-05 at 19 12 58@2x

**Review by asaadmahmood — APPROVED** [review]
Looks good for the most part, but please see those two issues.

**Review by asaadmahmood — CHANGES_REQUESTED** [review]
@calebroseland I just noticed we did not add bookmarks to the RHS neither the ability to add bookmarks from the channel RHS.

Is that coming soon?
image

**Comment by calebroseland** [comment]
@asaadmahmood 
1. Padding issue: added https://mattermost.atlassian.net/browse/MM-62112, will open a separate PR.
2. The submenu item height is the same as other submenus (Move To...), and is set to redo this whole menu, so this will be updated to the new design during that. (Either https://mattermost.atlassian.net/browse/MM-40156 or https://mattermost.atlassian.net/browse/MM-62112)
3. Adding bookmarks RHS deferred for now

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by lindy65 — APPROVED** [review]
Thanks @calebroseland - tested as per the 4 Jira tickets and looks good to me (Asaad's and your comments noted)

**Review by asaadmahmood — APPROVED** [review]
LGTM

**Pull request merged**
