### PR TITLE
MM-51700: Drop websocket slow/full warns to debug

### PR DESCRIPTION
**Pull request by grubbins**
#### Summary

Rather than sample `websocket.full|slow` warnings at one per minute, make them debug logging.

#### Ticket Link

A proposed change to MM-51700.

See also [this forum post](https://forum.mattermost.com/t/lots-of-warnings-since-upgrade-to-v7-7-1/14882/8).

Rationale is on the forum post, and also on this [comment on the original diff](https://github.com/mattermost/mattermost/commit/2287dff298b7d240ac095f7bc2cd9da6a56b472d#commitcomment-123771802).

### CODE REVIEW

**Comment by agnivade** [comment]
@grubbins - Thanks for the PR. The idea behind this was to prevent this log line from flooding the logs and reduce noise for the admin. Is the interval of one minute still too small for you? Have you run into issues with this in production? From your forum post, it looks like you haven't deployed it yet.

> With this change, the logging is even less informative since we discard most of the info and pick one random warning every minute

The user_id will always be the same. Only the event will be sampled at random, which I think is fine. We might even remove the event type to make all lines exactly the same. The event name isn't really important. The user_id is.

> This updated logging, while using fewer log lines, is even less actionable than before. Since site admins really can't act on this, then please let's make it Debug...

As I mentioned earlier, the purpose behind this was to reduce the spammy nature of the log. But it's still actionable. I don't think the frequency of a warn log should decide whether or not it's more or less actionable. All warn logs should be actionable. In this case, the admin should check the user_id and see if it's only a particular user who is facing problems or whether it's coming from all users. The difference might mean either the server is under load or something limited to a single user's network.

So unless the frequency of 1 minute is still too high, and your log lines are still flooding with this message, I would still lean on keeping this as a warning.

Let me know your thoughts.

**Comment by grubbins** [comment]
Hey, thanks for the response!

I had overlooked the fact that the filtering is actually applied per user,
sorry - I thought the idea was for lastLogTimeSlow to be global across all
web connections.

But, even if this is rate-limited per user, I have the same complaints:
1. We still lose the information of the count / rate of these events. I
personally find it just generally bad logging design to say in the log "one
event like this just happened, and there may be more, but I won't tell you
about any of them for another 60s". If we do it this way I would very much
rather report a count.
2. If there are, say, 20 users with slow connections, I will still have
1200 warnings per hour from this and I do think it's way too much.
Especially because...
3. ...this is just not actionable! When trying to push for a clean,
actionable log of warnings and errors, I think we're better off with this
as Debug. After all, if for some reason I'm looking into things at this
level of detail, I will just enable Debug logs - but the recommended course
of action is to ignore these anyway.

If you really want to *warn* a sys admin about the situation, surely better
to expose a metric, or perhaps gather hourly stats in the log as info, or
better still, offer a way to query for a user's connection stats?

Hope that clarifies!

Dave

**Comment by grubbins** [comment]
What are the relevant metric names? Are they on the standard grafana
dashboards that Mattermost suggest setting up (we have all of those)?

**Comment by agnivade** [comment]
They aren't. It's pending on me to add those panels to the [v2 monitoring dashboard](https://grafana.com/grafana/dashboards/15582-mattermost-performance-monitoring-v2/). 

Here they are if you want to add them right away:
1. `sum(mattermost_websocket_broadcast_buffer_size) by (instance)`
2. `sum(rate(mattermost_websocket_broadcasts_total[5m])) by (name)`
3. `sum(rate(mattermost_websocket_event_total{type=~"${websocket_event}"}[5m])) by (type)`

The last one points to a websocket_event variable which is declared with a query: `topk(20,sum(rate(mattermost_websocket_event_total{namespace="${namespace}"}[${__range_s}s])) by (type))` and filtered with a regex of `.*type="(?!custom_)(.*?)".*`.

**Comment by grubbins** [comment]
I have added these to our dashboard, although I couldn't get the topk in
the websocket_event query working (I can plot this as a set of time series,
but as a variable, it returns no values...)
So - which of these metrics would correspond to the websocket.slow warning
for a user? Does that only apply to broadcasts?

**Comment by agnivade** [comment]
Hey @grubbins - I have a strong feeling that most of the logs were spuriously generated due to https://github.com/mattermost/mattermost/commit/0e75982f2b832ab1378ff73bd26e8c367910b16a. This is available from 8.1.1 onwards. I'd suggest to upgrade to that version and report back if you still see a lot of logs.

I will go ahead and close this out.

**Pull request closed without merging**
