### PR TITLE
MM-53513 Update styles of slack attachment buttons

### PR DESCRIPTION
**Pull request by matthewbirtch**
#### Summary
This PR improves the styling for the slack attachment buttons and aligns them better with the new button classes that are now available since merging https://github.com/mattermost/mattermost/pull/24483#event-10460608133.

This also resolves theming issues that have been reported with dark themes for slack attachment buttons.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/23968
Jira https://mattermost.atlassian.net/browse/MM-53513

#### Screenshots

**Denim Theme**
<table>
<tr>
<td>Before</td>
<td>image</td>
</tr>
<tr>
<td>After</td>
<td>image</td>
</tr>
</table>

**Onyx Theme**
<table>
<tr>
<td>Before</td>
<td>image</td>
</tr>
<tr>
<td>After</td>
<td>image</td>
</tr>
</table>

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by matthewbirtch** [comment]
@mickmister @asaadmahmood I created a draft PR that resolves the theming issues and aligns the slack attachment buttons better with the new button classes. 

I could not figure out how to get the custom colors to also apply opacity changes to the custom colors on hover. I you have any brilliant ideas, I'm all ears.

**Comment by mickmister** [comment]
> I could not figure out how to get the custom colors to also apply opacity changes to the custom colors on hover. I you have any brilliant ideas, I'm all ears.

I think you can accomplish this with `styled-component`'s `createGlobalStyle` like so:

```ts
import {randomUUID} from 'crypto';
import {createGlobalStyle} from 'styled-components';

interface HoverStyleProps {
    id: string;
    color: string;
}

const HoverStyle = createGlobalStyle`
button#${(props: HoverStyleProps) => props.id}:hover {
    color: '${(props: HoverStyleProps) => changeOpacity(props.color, 0.25)}';
`;

function ActionButton() {
    const id = useMemo(() => 'action_button_' + randomUUID(), []);

    return (
        <>
            <HoverStyle
                id={id}
                color={color}
            />
            <button id={id}/>

        </>
    );
}
```

**Comment by matthewbirtch** [comment]
Thanks @mickmister @asaadmahmood I'll probably need help with that to be honest, it looks a bit beyond my knowledge

**Comment by mickmister** [comment]
After [discussing](https://community.mattermost.com/core/pl/tmoei53pyif1fxbcmbe73m6p7c) with @calebroseland on community, it seems using a `styled-components` button may make more sense:

```ts
interface HoverButtonProps {
    color: string;
}

const HoverButton = styled.button`
    &&&:hover {
        color: ${(props: HoverButtonProps) => changeOpacity(props.color, 0.25)};
    }
}`;
```

Then use `<HoverButton>` instead of `<button>` in the component's rendered output:

```ts
return (
    <HoverButton color={color}/>
)
```

**Comment by calebroseland** [comment]
> After [discussing](https://community.mattermost.com/core/pl/tmoei53pyif1fxbcmbe73m6p7c) with @calebroseland on community, it seems using a `styled-components` button may make more sense:
> 
> ```ts
> interface HoverButtonProps {
>     color: string;
> }
> 
> const HoverButton = styled.button`
>     &&&:hover {
>         color: ${(props: HoverButtonProps) => changeOpacity(props.color, 0.25)};
>     }
> }`;
> ```
> 
> Then use `<HoverButton>` instead of `<button>` in the component's rendered output:
> 
> ```ts
> return (
>     <HoverButton color={color}/>
> )
> ```

You could also move over the baseline colors from inline styling into the `styled-compoents` button; the colors on the styles attr are likely the main reason the hover color wasn't working.
https://github.com/mattermost/mattermost/pull/24628/files#diff-9ec2893ba18a5971b0a70314c446ac3a3cdcebc828caf152578c3bb2626cab38R62

**Comment by calebroseland** [comment]
Perhaps something like this (untested, some styled-component syntax may need tweaks)

```tsx
import styled, {css} from 'styled-components';
//...
type ActionBtnProps = {hexColor: string | null | undefined};
const ActionBtn = styled.button<ActionBtnProps>`
    ${({hexColor}) => hexColor && css`
        color: hexColor;
        border-width: 2px;
        border-color: ${() => changeOpacity(hexColor, 0.25)}
        &:hover {
            color: ${() => changeOpacity(hexColor, 0.25)};
        }
    `}
`;
```

```diff
-            <button
+            <ActionBtn
                 //...
-                style={customButtonStyle}
+                hexColor={hexColor}
            >
```

**Review by mickmister — APPROVED** [review]
LGTM

**Review by asaadmahmood — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
tested with the help of script 
image

**Review by calebroseland — CHANGES_REQUESTED** [review]
https://github.com/mattermost/mattermost/actions/runs/6346125929/job/17239203004?pr=24628#step:4:362


Looks like there are some failing tests. I'd wager that those styling tests are a little too rigid or granular, so we could relax them a bit while still testing for basic styling. Let me know if you have any questions!

**Comment by matthewbirtch** [comment]
> https://github.com/mattermost/mattermost/actions/runs/6346125929/job/17239203004?pr=24628#step:4:362
> 
> Looks like there are some failing tests. I'd wager that those styling tests are a little too rigid or granular, so we could relax them a bit while still testing for basic styling. Let me know if you have any questions!

Thanks @calebroseland. To be honest, I've never updated/edited these tests before. 

Would it be as simple as editing `action_button.test.tsx` from this:

```
expect(button).toHaveStyle(`borderColor: ${changeOpacity(Preferences.THEMES.denim.onlineIndicator, 0.25)}`);
expect(button).toHaveStyle('borderWidth: 2');
expect(button).toHaveStyle(`color: ${Preferences.THEMES.denim.onlineIndicator}`);
```

to this:

```
expect(button).toHaveStyle(`background: ${changeOpacity(Preferences.THEMES.denim.onlineIndicator, 0.08)}`);
expect(button).toHaveStyle(`color: ${Preferences.THEMES.denim.onlineIndicator}`);
```

And then do the same for the other samples in the test file?

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by matthewbirtch** [comment]
> > https://github.com/mattermost/mattermost/actions/runs/6346125929/job/17239203004?pr=24628#step:4:362
> > Looks like there are some failing tests. I'd wager that those styling tests are a little too rigid or granular, so we could relax them a bit while still testing for basic styling. Let me know if you have any questions!
> 
> Thanks @calebroseland. To be honest, I've never updated/edited these tests before.
> 
> Would it be as simple as editing `action_button.test.tsx` from this:
> 
> ```
> expect(button).toHaveStyle(`borderColor: ${changeOpacity(Preferences.THEMES.denim.onlineIndicator, 0.25)}`);
> expect(button).toHaveStyle('borderWidth: 2');
> expect(button).toHaveStyle(`color: ${Preferences.THEMES.denim.onlineIndicator}`);
> ```
> 
> to this:
> 
> ```
> expect(button).toHaveStyle(`background: ${changeOpacity(Preferences.THEMES.denim.onlineIndicator, 0.08)}`);
> expect(button).toHaveStyle(`color: ${Preferences.THEMES.denim.onlineIndicator}`);
> ```
> 
> And then do the same for the other samples in the test file?

I think I've resolved the failing test with the updated test file

**Review by calebroseland — APPROVED** [review]
LGTM! thanks @matthewbirtch, and sorry for not responding on the unit testing stuff, I was away part of last week.

**Pull request merged**
