### PR TITLE
[MM-54879] Goodbye, GraphQL -- Regards Webapp

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
Client side removal of parent PR https://github.com/mattermost/mattermost/pull/24850

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-54879

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
cc @agnivade @saturninoabril

**Review by larkox — APPROVED** [review]
LGTM. Just to confirm, we didn't add any dependency (e.g. apollo) when we added graphQL, right?

**Comment by M-ZubairAhmed** [comment]
> LGTM. Just to confirm, we didn't add any dependency (e.g. apollo) when we added graphQL, right?

No we didn't

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
Nice to see that this removal is fairly straightforward! It definitely could've been bad depending on how integrated it was into the code

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
