### PR TITLE
[MM-58409] Migrate tooltips of 'components/file_preview_modal/popover_bar/popover_bar' to WithTooltip

### PR DESCRIPTION
**Pull request by Camillarhi**
#### Summary

Migrate tooltips to use WithTooltip in 'components/file_preview_modal/popover_bar/popover_bar' file

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27154
Jira https://mattermost.atlassian.net/browse/MM-58409

#### Screenshots

image
| 
image
 |

#### Release Note

```
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
@Camillarhi can you please check the failing CI checks

**Comment by Camillarhi** [comment]
@M-ZubairAhmed  the failing checks has been resolved

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by yasserfaraazkhan — APPROVED** [review]

**Review by Rajat-Dabade — APPROVED** [review]

**Review by Rajat-Dabade — APPROVED** [review]

**Pull request merged**
