### PR TITLE
MM-27291: Extend channel header with parent as render prop

### PR DESCRIPTION
**Pull request by KuSh**
#### Summary

Extend channel header with parent as render prop

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/22467
Jira https://mattermost.atlassian.net/browse/MM-27291

#### Release Note

```release-note
Plugins: You can now conditionally hide and style ChannelHeaderButton registered via new registerParentAwareChannelHeaderButtonAction API
```

### CODE REVIEW

**Comment by KuSh** [comment]
@M-ZubairAhmed I think its a little bit too early for a review as I don't have implemented the core requested feature

On the other hand I've asked for some guidance on the [associated issue](https://github.com/mattermost/mattermost/issues/22467). If you or someone else can help with that, it would be greatly appreciated.

**Comment by larkox** [comment]
@lieut-data I think you were pretty involved with the original request. Do you remember the details of what did we want here?

**Comment by lieut-data** [comment]
@larkox, wow this reaches back a ways! I do remember the interaction, but am also uncertain if my proposal in https://github.com/mattermost/mattermost-webapp/pull/4606#issuecomment-654359076 is the "right path" anymore. I also know there's a compromise to be made between super powerful rendering options and a more declarative, but limited registration model.

If I had to a pick a path forward, I would probably suggest abandoning this ticket. Leave plugins to do whatever "hacks" are necessary when they want to do special things, and expand what we can do with a declarative API that sidesteps this problem more elegantly.

**Comment by larkox** [comment]
@jespino @mickmister Do you have any other feedback about this feature? If you both also agree with @lieut-data I think we can close the issue.

@KuSh if we finally close the ticket, really sorry for the effort you have put already here.

**Comment by KuSh** [comment]
No problem @larkox that's why I asked for guidance before puting too much time in it ^^
Anyway I think my preparatory work can be submitted as it is some code cleansing, you'll do whatever you want with it

**Pull request closed without merging**
