### PR TITLE
Update introduction.yaml

### PR DESCRIPTION
**Pull request by alejdg**
#### Summary
Fix links to Golang and Javascript WebSocket drivers in API documentation.

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by lieut-data — APPROVED** [review]
Thank you, @alejdg!

**Review by jespino — APPROVED** [review]
Good catch. Thank you! :sparkles:

**Comment by jespino** [comment]
@cwarnermm I don't think there is much to do here about review, but I added you to keep you informed, anyway I going to merge it right away.

**Review by cwarnermm — APPROVED** [review]
Thank you, @alejdg!

**Pull request merged**
