### PR TITLE
MM-58479 - Revert text changes on channel archive.

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Previously both Teams and Channels had the same text…so it all got updated…only the Teams text should have been changed.

This PR reverts the changes to the channels text.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-58479

#### Screenshots
Screenshot 2024-05-29 at 8 56 47 AM

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by JulienTant — APPROVED** [review]

**Review by calebroseland — APPROVED** [review]

**Comment by lindy65** [comment]
Hi @sbishel 

While I am seeing the changes you made in this PR which look good to me, I'm seeing a change at the start of a new channel which seems to have old UI.  

I've checked the `master.test.mattermost.com` test server and it doesn't have this old UI so I'm wondering whether something changed during your code change or if it was caused by another PR? (I added an enterprise test licence to the spinwick but the UI is the same with or without licence)

This is what I'm seeing:

image


This is what it should look like:

image

**Comment by sbishel** [comment]
This PR is simply a text change...it couldn't cause the issue your seeing. 
There is code that conditionally shows one view or the other [here](https://github.com/mattermost/mattermost/blob/master/webapp/channels/src/components/post_view/channel_intro_message/channel_intro_message.tsx#L471-L486)

**Review by lindy65 — APPROVED** [review]
Aah, thanks @sbishel - I was not aware of the code you mentioned.  Your change looks good to me 👍

**Pull request merged**
