### PR TITLE
update filename for en-AU

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
This is being caused due to a discrepancy between the filename being created by translate (en_AU.json) and the expected locale used in the server and webapp (en-AU). (Underscore vs Dash) 

The file name will be updated in Weblate, then this import will need updated.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-54003

#### Release Note

```release-note
Fixed issue that didn't allow en-AU language selection.
```

### CODE REVIEW

**Comment by sbishel** [comment]
This PR cannot be merged until the weblate file has been created and merged.

**Comment by ctlaltdieliet** [comment]
Hi @sbishel ,
I can't resolve the merge conflict. Are you able to help?
Thank you

**Comment by sbishel** [comment]
@ctlaltdieliet - I would suggest reverting the prior commit and merging those changes separately, as normal language update PR. 

Keeping this PR simply to the import file change.

**Comment by sbishel** [comment]
closing in favor of https://github.com/mattermost/mattermost/pull/26231

**Pull request closed without merging**
