### PR TITLE
[GH-24981] Fix: Manually selecting EST timezones is confused with daylight savings

### PR DESCRIPTION
**Pull request by Victor-Nyagudi**
#### Summary

Selecting certain timezones led to multiple items being highlighted in the timezone dropdown. 

This PR ensures only one item is highlighted after the user selects a timezone.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/24981
Jira https://mattermost.atlassian.net/browse/MM-50728

#### Screenshots

<details><summary>Before</summary>

https://github.com/user-attachments/assets/6416c92b-9fea-4944-8716-d09e59f97e6c

</details> 

<details><summary>After</summary>

https://github.com/user-attachments/assets/9b600042-23bf-4b89-848d-a77828a67c3f

</details> 

#### QA Review Steps

1. Click the Settings icon at the top right.
2. Click "Display" in the modal's sidebar then click "TImezone" in the main panel.
3. Uncheck "Automatic" if it's checked.
4. Select `UTC (-05:00) Eastern Time (US Canada)` from the dropdown.
5. Open the dropdown again and verify `UTC (-05:00) Eastern Time (US Canada)` is the only item highlighted.
6. Repeat steps 4 and 5 with `(UTC-07:00) Pacific Daylight Time (US & Canada)` and `(UTC) Edinburgh`.

#### Release Note

```release-note
Fixed bug where multiple timezones are highlighted when selecting certain timezones.
```

### CODE REVIEW

**Comment by Victor-Nyagudi** [comment]
> [!NOTE]
> Some useful information regarding the issue I'm fixing.

## Root Cause

The `value` of the timezone object is hard-coded to be the first item in the `utc` array.

https://github.com/mattermost/mattermost/blob/4620ab6ad309b9933d2b9e13462b000b3ef2fb27/webapp/channels/src/components/user_settings/display/manage_timezones/manage_timezones.tsx#L167-L170

This results in multiple timezones having the same `value` since some timezones have similar `utc` arrays if not the same. 

For example, the first item in the `utc` array of `UTC (-05:00) Eastern Time (US Canada)` is `America/Detroit` which is the same as the one for `UTC (-05:00) Eastern Daylight Time (US Canada)`. 

<details><summary>Screenshot</summary>

mattermost-eastern-time

</details> 


The dropdown rendered by `react-select` uses this `value` to [determine which item is selected](https://github.com/mattermost/mattermost/blob/4620ab6ad309b9933d2b9e13462b000b3ef2fb27/webapp/channels/src/components/user_settings/display/manage_timezones/manage_timezones.tsx#L220), and since there are two in the list with the same `value`, `react-select` sees it as the same item duplicated, so both items are styled as selected i.e. their `isSelected`  property is `true` (the correct one is sent to the back end, though).

This issue also exists when you select `(UTC-07:00) Pacific Daylight Time (US & Canada)`/`(UTC-08:00) Pacific Standard Time (US & Canada)`.

<details><summary>Screenshots</summary>

mattermost-pacific-multiple-selected

mattermost-pacific-time

</details> 

Same thing with `(UTC) Edinburgh, London`/`(UTC+01:00) Edinburgh, London`.

<details><summary>Screenshots</summary>

mattermost-edinburg-multiple-selected

mattermost-edinburg-time

</details> 

## Proposed Solution

Instead of hard-coding each timezone's `value`, we can update it dynamically based on whether a timezone already exists with that `value` in the dropdown. 

Since these timezones are right next to each other, we can compare the previous timezone's `value` with the current and increase the index of the `utc` array item such that the first timezone gets the first `utc` value, the second one gets the second `utc` value, etc. 

To do so, we'll first store the previous timezone in a variable called `previousTimezone` next to an `index` value that will be dynamically updated. These will be placed [above the loop](https://github.com/mattermost/mattermost/blob/4620ab6ad309b9933d2b9e13462b000b3ef2fb27/webapp/channels/src/components/user_settings/display/manage_timezones/manage_timezones.tsx#L165).

```javascript
let index = 0;
let previousTimezone: Timezone;
```

As we're looping through each timezone, we'll compare the first item of the current timezone's `utc` array to the previous one. If they don't match, return a regular timezone object like before and update the previous timezone.

It's safe to use the first item in the `utc` array at this point, so the `index` stays the same.

```javascript
if (timeObject.utc[index] === previousTimezone?.utc[index]) {
    index++;
} else {
    // * It's safe to use the first item since consecutive timezones
    // * don't have the same 'utc' array.
    index = index === 0 ? index : 0;
}

previousTimezone = timeObject;

return {
    value: timeObject.utc[index],
    label: timeObject.text,
};
```

If the current timezone's first `utc` array item matches the previous timezone's, we'll need to use a different `utc` item. This prevents highlighting two timezones in the dropdown because of the same `value`.

This is accomplished by increasing the `index` variable by 1 and then using that index to get the next item in the `utc` array. Since the `value` is only used to determine which item is selected in the dropdown and isn't shown to the user, a different city can be used (they all have the same time). The dropdown text will remain the same.

The `index` is reset to 0 if we don't find consecutive timezones with similar `utc` arrays. Timezones with similar `utc` arrays are grouped, so this is okay. 

If you're worried about the `index` going out of range, this won't happen because there are more cities in a timezone than timezones in a city. Multiple timezones can't have exactly one item in the `utc` array because it's extremely unlikely there's exactly one city in a timezone.

The `index` is reset before it goes out of range. The number of timezones on Earth is fixed, so we don't need to worry about cities randomly getting up and moving to another timezone. 

## Other Solutions Explored

I thought about comparing the entire array instead of just the first item in `utc`, but this didn't work for `(UTC-07:00) Pacific Daylight Time (US & Canada)` since the arrays are slightly different (see attached screenshot above).

I also tried using something different for the `value` like the timezone's label name, but that didn't work either.

## Additional Notes

This [method](https://github.com/mattermost/mattermost/blob/4620ab6ad309b9933d2b9e13462b000b3ef2fb27/webapp/channels/src/components/user_settings/display/manage_timezones/manage_timezones.tsx#L159-L160) is declared but isn't used anywhere, so it should be removed.

This console error appears when you click the Timezone option after opening the settings. 

```
Warning: Each child in a list should have a unique "key" prop.
```

This is occurring because the items in the [inputs array](https://github.com/mattermost/mattermost/blob/4620ab6ad309b9933d2b9e13462b000b3ef2fb27/webapp/channels/src/components/user_settings/display/manage_timezones/manage_timezones.tsx#L177) don't have a unique `key` property set. 

There are only three items in the array: [`automaticTimezoneInput`](https://github.com/mattermost/mattermost/blob/4620ab6ad309b9933d2b9e13462b000b3ef2fb27/webapp/channels/src/components/user_settings/display/manage_timezones/manage_timezones.tsx#L188), [`manualTimezoneInput`](https://github.com/mattermost/mattermost/blob/4620ab6ad309b9933d2b9e13462b000b3ef2fb27/webapp/channels/src/components/user_settings/display/manage_timezones/manage_timezones.tsx#L207), and a [message](https://github.com/mattermost/mattermost/blob/4620ab6ad309b9933d2b9e13462b000b3ef2fb27/webapp/channels/src/components/user_settings/display/manage_timezones/manage_timezones.tsx#L232).

These don't require a special `key`, so a simple object with different numbers should suffice in supplying all three with a unique value for the prop.

**Comment by Victor-Nyagudi** [comment]
A [thread](https://community.mattermost.com/core/pl/w6933bdktprtie8aeih3smzz4o) exists on why `check-types` is failing.

This PR is meant to address it.

- https://github.com/mattermost/mattermost/pull/29283

**Comment by marianunez** [comment]
> A [thread](https://community.mattermost.com/core/pl/w6933bdktprtie8aeih3smzz4o) exists on why `check-types` is failing.
> 
> This PR is meant to address it.
> 
> * [Add type annotation to generated language files map #29283](https://github.com/mattermost/mattermost/pull/29283)

Thanks @Victor-Nyagudi, if you update your branch from master then it should correct the failing CI.

**Comment by Victor-Nyagudi** [comment]
> Test server creation failed. Review the [error details here](https://hub.mattermost.com/private-core/channels/matterwick).

Is there anything I should do on my end to ensure the test server is created successfully?

By the way, the `/update-branch` is a nice command. It saves me from having to pull, rebase, and force push the rebased changes. 

Good job adding that to the workflow. 👍🏿

**Review by pvev — APPROVED** [review]
Thank you @Victor-Nyagudi , this is great work 🎉

**Review by harshilsharma63 — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
tested this locally. the dropdown does nott highlight 2 options.
image


Screenshot 2024-11-21 at 8 07 30 PM

**Pull request merged**
