### PR TITLE
[MM-52996] fix server ci after renaming the project

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Some renaming after the project rename

#### Ticket Link
[MM-52996](https://mattermost.atlassian.net/browse/MM-52996)

#### Release Note

```release-note
NONE
```

[MM-52996]: https://mattermost.atlassian.net/browse/MM-52996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by agnivade — APPROVED** [review]

**Review by wiggin77 — APPROVED** [review]
Approving to unblock PRs

**Comment by amyblais** [comment]
@isacikgoz Please help cherry-pick this to release-7.9 and release-7.8 branches. 
A PR exists for release-7.10 branch https://github.com/mattermost/mattermost/pull/23588.

**Comment by isacikgoz** [comment]
@amyblais I think we are good in release-7.8 and release-7.9  branches. CI passes on both w/o modification. Only release-7.8 failed on lint but it's unrelated to name change.

**Pull request merged**
