### PR TITLE
[MM-52969] Revert "MM-51482_Create Apps Category and link to bots DM (#22918)"

### PR DESCRIPTION
**Pull request by pvev**
#### Summary
Revert apps category and link bots support. Reverts https://github.com/mattermost/mattermost/pull/22918

#### Screenshots
n/a

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by JulienTant — APPROVED** [review]
👍🏻 thanks @pvev

**Comment by JulienTant** [comment]
Just thinking: had this been deployed anywhere? and if it did, are we supposed to do something with the created categories?

**Review by marianunez — COMMENTED** [review]
Thanks @pvev! Overall LGTM. However, we may also want to remove the feature flag introduced for this in https://github.com/mattermost/mattermost/pull/22766

**Comment by pvev** [comment]
@marianunez @JulienTant FF PR reverted too https://github.com/mattermost/mattermost/pull/23647/commits/a49ecc891ec6207cd21ee64ba7d14c755466b75c

**Review by yasserfaraazkhan — APPROVED** [review]
thank you for the changes.
Did not see app categories on the LHS in the spinwick

**Pull request merged**
