### PR TITLE
[MM-59908] Migrate tooltips of 'components/threading/global_threads/thread_pane/thread_pane.tsx' to WithTooltip

### PR DESCRIPTION
**Pull request by Camillarhi**
#### Summary

Migrate tooltips to use WithTooltip in 'components/threading/global_threads/thread_pane/thread_pane.tsx' file
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27793
Jira https://mattermost.atlassian.net/browse/MM-59908
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
Minor lint failures here as well

**Comment by M-ZubairAhmed** [comment]
@Camillarhi the lint check are still failing

**Comment by Camillarhi** [comment]
> This looks good :shipit: Thank you

Thanks

**Review by Rajat-Dabade — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
