### PR TITLE
Remove Permalink Preview Feature Flag

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Remove the Permalink Preview feature flag. This is no longer needed as it has been enabled for a while and it now relies on the `ServiceSettings.EnablePermalinkPreviews` config setting

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47874

#### Release Note

```release-note
None
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
Hi @marianunez 
tested this change with enabling/disabling website preview, message preview from console setting. 
the preview was working as expected.

**Comment by marianunez** [comment]
@BenCookie95 gentle ping on this review

**Review by BenCookie95 — APPROVED** [review]

**Pull request merged**
