### PR TITLE
Removed unused compliance job from packet

### PR DESCRIPTION
**Pull request by coltoneshaw**
#### Summary
Reviewing the packet and noticed an unused `compliance_jobs` that was being returned. Removed this. 

```release-note
none
```

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Good catch :+1:

**Review by pvev — APPROVED** [review]
LGTM! thanks @coltoneshaw

**Comment by coltoneshaw** [comment]
@hanzei / @pvev - could you merge this for me? I do not have perms

**Comment by pvev** [comment]
sure @coltoneshaw 👍

**Pull request merged**
