### PR TITLE
Disable preview button when Formatting Bar disabled

### PR DESCRIPTION
**Pull request by Aryakoste**
#### Summary

Now whenever the formatting bar/options are disable. We can't use Ctrl+Alt+P to toggle preview mode.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28011
Jira https://mattermost.atlassian.net/browse/MM-59407
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by harshilsharma63 — APPROVED** [review]

**Review by rahimrahman — APPROVED** [review]
@Aryakoste Thank you for your contribution.

Note: the variable names in the files are somewhat confusing (not your fault), but it is a bit harder for me to understand even simple changes.  I was expecting something like `showFormattingBar` be something like `canShowFormattingBar`, denoting that the component has the ability to show the formatting bar.  `showFormattingBar` is almost like `isFormattingBarDisplayed`.

Another like `isFormattingBarHidden` feels like a toggle, in which when somebody toggle the formatting bar in and out, but I don't think it is in this instance.

Anyway, just a note.  Coming from a reviewer with very little experience in these files.

**Comment by Aryakoste** [comment]
yeah the variable names in this file are somewhat confusing but for the showFormattingBar the can part that you said is basically added by considering it as boolean because showFormattingBar = true means it can and false cannot. But you are right it can be confusing means if we consider it calling canShowFormattingBar it will be more clear that this component has ability or not. And the isFormattingBarHidden is used when we press ctrl+alt+T and we can trigger the formattingBar so its hidden or not. As we also need to consider if the channel is readOnly or if we can chat in this channel. We have to take both isFormattingBarHidden and isDisabled into consideration. Hence this all variables can create confusion sometimes mixing it with each other. @rahimrahman. @hanzei what do you think do we need some refractoring here.

**Comment by rahimrahman** [comment]
@Aryakoste I think the goal is to get the conflicts resolved first.  Then if you have the time to quickly change the variable name to `canShowFormattingBar` from 'showFormattingBar`, then that would be great.  It's not as pressing as getting your changes out the door.

**Comment by lindalumitchell** [comment]
@harshilsharma63 @rahimrahman I have a couple questions about expected behavior please:

1. Should this keyboard shortcut work on MacOS to begin with? I see a tooltip on hover on Mac, but the keypresses do not toggle the preview as expected (also tested outside of this PR on an existing server). Note: Working as expected on Windows.
2. The ticket states that using keyboard shortcut with the formatting hidden can cause the post preview to overlap with the eye icon (preview button), but that button is already hidden if formatting on the post is hidden. Am I misunderstanding how to test this?

Thanks very much for the help!

**Comment by larkox** [comment]
@lindalumitchell The hotkey should work also on mac. If it doesn't it would be a different bug. Either some clash with some other system hotkey, or some mistake on implementation.

Regarding the testing, the meat of this ticket is that when you have formatting disabled, there is no eye icon to show the preview. But the hotkey is still working. So when you hit the hotkey, the preview shows, including the eye, which is where it shouldn't be.

This PR fixes that by making the hotkey not to work on that scenario.

**Review by lindalumitchell — APPROVED** [review]
Thank you @larkox! In that case, this looks good to me. Note that the e2e test failure was a phantom test failure that should be resolved in future PRs. Also, I'll investigate the Mac questions separately. Thanks!

**Comment by larkox** [comment]
Thank you @Aryakoste for the contribution!

**Pull request merged**
