### PR TITLE
Fixed errcheck issues in server/channels/app/onboarding_test.go

### PR DESCRIPTION
**Pull request by Aryakoste**
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/29046
Jira https://mattermost.atlassian.net/browse/MM-61447
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Review by agarciamontoro — CHANGES_REQUESTED** [review]
Thank you, @Aryakoste! It seems there are some conflicts in `server/.golangci.yml`, can you fix those?

**Comment by Aryakoste** [comment]
@agarciamontoro Done.

**Review by agarciamontoro — APPROVED** [review]
Thank you!

**Pull request merged**
