### PR TITLE
[MM-60839]  Remove unused 'webapp/channels/src/components/admin_console/billing/payment_details.tsx'

### PR DESCRIPTION
**Pull request by kom-senapati**
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28595
Jira https://mattermost.atlassian.net/browse/MM-60839

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by Willyfrog — CHANGES_REQUESTED** [review]
The code looks good, but can you provide a screenshot of how it looks now to verify that it is looking the same?

**Comment by kom-senapati** [comment]
@M-ZubairAhmed I'm unable to test it..

**Review by M-ZubairAhmed — APPROVED** [review]
Since there was no markdown in the messages here, so here changing from FormattedMarkdownMessage to FormattedMessage will not have any UX difference as is

**Comment by M-ZubairAhmed** [comment]
> The code looks good, but can you provide a screenshot of how it looks now to verify that it is looking the same?

It looks like this component is no longer used in the app. @nickmisasi can you please confirm?

**Comment by nickmisasi** [comment]
@M-ZubairAhmed Yes unused, likely just missed in cleanup. We can either accept @kom-senapati's fix and create a ticket to clean up the unused component later, or have @kom-senapati remove the component as part of this PR. Will leave it up to you

**Comment by M-ZubairAhmed** [comment]
@nickmisasi thank you for the context

@kom-senapati in this case i think its best to just remove the component instead of working on it. Would you be open to do that. I will change the ticket description.

**Comment by kom-senapati** [comment]
Yup will do it

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Comment by M-ZubairAhmed** [comment]
@kom-senapati can you run i18n-extract

**Comment by kom-senapati** [comment]
Done @M-ZubairAhmed

**Review by Willyfrog — APPROVED** [review]
LGTM! thanks!

**Comment by Willyfrog** [comment]
@lindy65 heads up that the ticket was changed in the process

**Comment by lindy65** [comment]
@M-ZubairAhmed - please update the Jira ticket to the correct one?

**Comment by Rutam21** [comment]
@lindy65 You can assign this issue to me for QA Testing. Thanks.

**Comment by lindy65** [comment]
Assigned to you for testing @Rutam21

**Comment by M-ZubairAhmed** [comment]
> @M-ZubairAhmed - please update the Jira ticket to the correct one?

Yes @lindy65 Jira ticket is correctly assigned. I have edited the same ticket itself.

@Rutam21 for testing this ticket, since the component was never used, so just a E2E verification should be good here

**Comment by lindy65** [comment]
Thanks @M-ZubairAhmed - we can consider QA review done then

@Rutam21 - counted towards Hacktoberfest!

**Pull request merged**
