### PR TITLE
MM-54569 : Update maximum password length on UI to 72 characters

### PR DESCRIPTION
**Pull request by aitorres**
#### Summary

Updated password max length to 72 characters on the web app UI. This will put the password character limit in sync between the server and the UI.

Test snapshots and test strings that referenced the previous limit have been changed accordingly, and a new unit test validates that the maximum length is enforced during password validation.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/24666
https://mattermost.atlassian.net/browse/MM-54569

#### Release Note

```release-note
* Increased maximum password limit from 64 to 72 characters on the UI.
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@aitorres do you need help in getting this to finish line?

**Review by calebroseland — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by lindy65** [comment]
@M-ZubairAhmed - do you know what the problem could perhaps be?

image

I'm changing sysadmin password from `Sys@dmin123` to `LindyIsherLindyIsherLindyIsherLindyIsherLindyIsherLindyIsherLindyIsher9#` (which is 72 characters)

Not sure whether the js.console error is helpful?

**Comment by M-ZubairAhmed** [comment]
> @M-ZubairAhmed - do you know what the problem could perhaps be?
> 
> image
> 
> I'm changing sysadmin password from `Sys@dmin123` to `LindyIsherLindyIsherLindyIsherLindyIsherLindyIsherLindyIsherLindyIsher9#` (which is 72 characters)
> 
> Not sure whether the js.console error is helpful?
> 
> To clarify, after trying to change the password, the fields reset / go blank and the error in red appears

Oh its bad request @aitorres can you take a look at this

**Comment by lindy65** [comment]
@aitorres - kind reminder to take a look please :)

**Pull request closed without merging**
