### PR TITLE
TEST PR for running /e2e-tests command

### PR DESCRIPTION
**Pull request by sinansonmez**
#### Summary
This PR opened to test if community members can run `/e2e-tests` command

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by toninis** [comment]
@mvitale1989 for reference . We are working on creating a process for this 😄

**Comment by mvitale1989** [comment]
I'm on it, i'll let you know when it's ready to be tested :+1:

**Comment by mvitale1989** [comment]
@sinansonmez This is now implemented, feel free to try running the `/e2e-test` yourself at any time :+1:

**Comment by sinansonmez** [comment]
Thanks @mvitale1989 it seems like it is working except wrong message from mattermost

**Comment by mvitale1989** [comment]
I'll go ahead and close this PR then, please let me know if you have any question around the `/e2e-test` command

**Pull request closed without merging**
