### PR TITLE
[MM-55212] Migrate server/channels/app/channel.go to make use of GenericStoreResult

### PR DESCRIPTION
**Pull request by fazil-syed**
#### Summary

Replaced the usage of StoreResult with GenericStoreResult with current type parameter.
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/25235
Jira https://mattermost.atlassian.net/browse/MM-55212
#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by hanzei** [comment]
@fazil-syed Please let me know when the PR is ready for review.

**Comment by fazil-syed** [comment]
@hanzei I think its ready

**Review by hanzei — APPROVED** [review]
LTM :+1:

**Review by agarciamontoro — APPROVED** [review]
Great, thank you for your work, @fazil-syed! :tada:

**Pull request merged**
