### PR TITLE
[MM-59811] Fix Incorrect "set custom status" Color

### PR DESCRIPTION
**Pull request by Gesare5**
#### Summary

Add color css property with a=0.73 to custom_status__container class, to reduce opacity of "set custom status" color

#### Ticket Link

Fixes  [#27724](https://github.com/mattermost/mattermost/issues/27724)
Jira  [https://mattermost.atlassian.net/browse/MM-59811](https://mattermost.atlassian.net/browse/MM-59811)

#### Screenshots

|  before  |  after  |
|----|----|
|
Screenshot from 2024-07-29 13-47-20
 |
Screenshot from 2024-07-29 13-48-11
|

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by pvev — APPROVED** [review]
the change looks good to me, thanks for your contribution @Gesare5 🚀

**Review by vish9812 — APPROVED** [review]
Thanks @Gesare5 LGTM :+1:

**Comment by pvev** [comment]
@asaadmahmood friendly reminder on this one :)

**Review by asaadmahmood — COMMENTED** [review]
Please make it 0.75

**Review by asaadmahmood — APPROVED** [review]
LGTM

**Comment by amyblais** [comment]
@holopin-bot @Gesare5 Mattermost Most Valued Professional (MVP)

**Pull request merged**
