### PR TITLE
[MM-52986] Add theming support to one of the dropdown input components

### PR DESCRIPTION
**Pull request by nickmisasi**
#### Summary
This dropdown input component wasn't displaying correctly when certain dark mode themes were activated because its default styles were not overridden by the theme variables. 

#### Screenshots
Before:
image
After:
image
 

#### Release Note

```release-note
None
```

### CODE REVIEW

**Review by JulienTant — APPROVED** [review]
thanks @nickmisasi - pulled the code locally because spinwicks won't start and it worked well on clear or dark themes!

**Review by harshilsharma63 — APPROVED** [review]
LGTM 👍

**Comment by matthewbirtch** [comment]
Seems like the Spinwick is not picking up the PR's changes: 
image

**Comment by nickmisasi** [comment]
@matthewbirtch something's up with the Spinwicks and it's pulling master rather than this branch. As discussed in DM, here are some screenshots of the modal with the various themes:

image
image
image
image

**Review by matthewbirtch — APPROVED** [review]
Screenshots look good. Thanks @nickmisasi

**Pull request merged**
