### PR TITLE
E2E/Playwright: Use node's native fetch, add ensureLicense flag and update snapshots

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
- Used node's native fetch
  - Removed `isomorphic-fetch`
  - Added `formdata-node` and `form-data-encoder` to build FormData
  - Updated Client Options to have `duplex` with "half" as only value per fetch specs for it's required when running from node client using ReadableStream but not in the browser.
  - Removed `--no-experimental-fetch` as node options
- Added ensureLicense flag
- Updated snapshots

#### Ticket Link
none

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by mvitale1989 — APPROVED** [review]
Thanks Saturn!

**Review by yasserfaraazkhan — APPROVED** [review]
🎉

**Pull request merged**
