### PR TITLE
Fix RHS scroll so AI plugin generation won't scroll off bottom

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary
Fixes new pinned to the bottom RHS scrolling so that AI posts stay pinned to the bottom.

Update to: https://github.com/mattermost/mattermost/pull/27162

#### Screenshots
https://github.com/user-attachments/assets/48c03668-83ca-469f-91da-5b4feda61fd3

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — DISMISSED** [review]
This seems to be breaking the virtualized post list for me because it seems to be breaking the logic that the component uses to determine which posts are supposed to be visible. The steps I went through to cause this was:
1. Make a post with 200+ replies (or however many are required to cause the list to stop rendering them when off screen)
2. Scroll to the top of the RHS so that the whole thread renders
3. Scroll back to the bottom

Once I've done that, it will render posts at the bottom of the RHS as blank divs since it thinks they're off screen
Screenshot 2024-08-08 at 4 30 13 PM

**Comment by hmhealey** [comment]
I'm also wondering if this bug affects more than the AI plugin. On my local instance, I also see that opening the edit box for a post or having another user edit one of their posts doesn't keep us on the bottom of the RHS, but on Hub, it stays at the bottom just fine

**Comment by crspeller** [comment]
@hmhealey New fix. It's not as visually pleasing as the other one because we are doing some jank within the `DynamicSizeList` setting scroll position.
We might consider a redo of the virtualized lists as the CSS solution is likely better for the center channel as well.

**Review by calebroseland — APPROVED** [review]

**Review by larkox — APPROVED** [review]

**Comment by crspeller** [comment]
@lindalumitchell Same testing regiment used on https://github.com/mattermost/mattermost/pull/27162 would be great. Want to make sure nothing tested there broke when fixing this.

**Comment by amyblais** [comment]
> Same testing regiment used on #27162 would be great. Want to make sure nothing tested there broke when fixing this.

@yasserfaraazkhan Would you be able to help test this while Linda is on PTO?

**Review by yasserfaraazkhan — APPROVED** [review]
verified the posts, threaded posts , the AI response is dispalyed on the bottom of the RHS
[Fixed an e2e test](https://github.com/mattermost/mattermost/pull/new/MM-45597)

**Pull request merged**
