### PR TITLE
[MM-55213] GenericStoreResult in channels (#25234)

### PR DESCRIPTION
**Pull request by Paul-Stern**
Make use of GenericStoreResult in channels/app/command.go

#### Summary
Make use of GenericStoreResult instead of StoreResult in channels/app/command.go

#### Ticket Link
Fixes: https://github.com/mattermost/mattermost/issues/25234
Jira: https://mattermost.atlassian.net/browse/MM-55213

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Nice work, thanks @Paul-Stern

**Review by agarciamontoro — APPROVED** [review]
Neat, thanks!

**Pull request merged**
