### PR TITLE
MM-59944 - FIxing playbooks scroll issue

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-59944 - FIxing playbooks scroll issue

#### Ticket Link
Jira https://mattermost.atlassian.net/browse/MM-59944

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by harshilsharma63 — APPROVED** [review]

**Review by larkox — APPROVED** [review]
Preemptively approving, but look like all the changes are just style changes, and nothing is really different. Am I missing something?

**Comment by asaadmahmood** [comment]
@larkox This is the only change.
CleanShot 2024-08-08 at 13 14 50@2x

**Comment by larkox** [comment]
@asaadmahmood Great, then looks good to me :smile:

**Review by lindy65 — APPROVED** [review]
Thanks @asaadmahmood - this is fixed, I can scroll in the Playbook outline and other screens 👍

**Pull request merged**
