### PR TITLE
[MM-24856] User request specific loggers in channels/api4/system.go

### PR DESCRIPTION
**Pull request by Ciggzy1312**
#### Summary

Replace global mlog with local c.Logger
Additionally, replace SetInvalidParam with SetInvalidParamWithErr where relevant

#### Ticket Link

Fixes -> #24856

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hanzei — CHANGES_REQUESTED** [review]
It seems like you missed https://github.com/Ciggzy1312/mattermost/blob/9379df16e35e8ba66a2608c2ce381494af501a76/server/channels/api4/system.go#L722.

Would you also fix that one?

**Comment by Ciggzy1312** [comment]
@hanzei updated

**Review by hanzei — APPROVED** [review]
LGMT :+1:

**Review by streamer45 — APPROVED** [review]
Nicely done :+1:

**Comment by hanzei** [comment]
Thanks for the contribution @Ciggzy1312 :tada:

**Pull request merged**
