### PR TITLE
Content-Type fixes in client4.ts and remote_cluster.go

### PR DESCRIPTION
**Pull request by calebroseland**
#### Summary
- Adds `Content-Type` check in `doFetchWithResponse` to prevent JSON deserialization errors when fetching non-JSON resources.
- changes content types of `deleteRemoteCluster` and `generateRemoteClusterInvite` to match returned content.

#### Ticket Link
- Prep for, relates to:
  - https://mattermost.atlassian.net/browse/MM-58845
  - https://mattermost.atlassian.net/browse/MM-58450

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by hmhealey** [comment]
I don't know how these APIs are used currently given they aren't , but it seems a bit odd to me that those seem like the only non-file APIs which return non-json data. Would this perhaps be a good time to change them to be consistent with other APIs and have them return a quoted string or `{status: 'OK'}` like the other APIs in the app? If we're worried about backwards compatibility with the older version of mmctl, perhaps we could use the `Accept` header to specify that the web app expects a json response from those APIs and have the server respect that.

0/5 though since I'm fine with the current approach as well

**Review by hmhealey — APPROVED** [review]

**Review by mgdelacroix — APPROVED** [review]
Good catch! LGTM :+1:

**Comment by mgdelacroix** [comment]
@hmhealey apologies, I missed your comment before my review. I agree that if there is a good time to update these APIs, it is now. What do you mean by non-file APIs?

I was leaning more towards standard API design with the status code and the response types, but I'm happy to change them if we prefer to keep consistency with other similar endpoints

**Comment by hmhealey** [comment]
By "non-file APIs", I mean all of the APIs that don't return binary data. Basically, everything except for `GET /api/v4/file/<id>`, `GET /api/v4/file/<id>/thumbnail`, and `GET /api/v4/users/<id>/profile_picture`. As far as I know, every other API returns some sort of JSON data (or `{status: 'ok'}` if they don't need to return anything else), so I'd expect these APIs to also return JSON data as well based on that

**Comment by calebroseland** [comment]
https://api.mattermost.com/#tag/schema also makes note that "All request and response bodies are `application/json`," so it would probably be prudent to make those adjustments to these two endpoints, rather than go against it.

Though I do think we should still add the content-type check to client, rather than trust an implicit default.

**Review by mgdelacroix — APPROVED** [review]

**Comment by calebroseland** [comment]
Thanks, @mgdelacroix

**Pull request merged**
