### PR TITLE
[GH-24745] Convert ./components/admin_console/setting.tsx from Class Component to Function Component

### PR DESCRIPTION
**Pull request by umrkhn**
#### Summary
This PR converts /components/admin_console/setting.tsx from Class Component to Function Component.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/24745

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by larkox — APPROVED** [review]
Looks great! Thanks!

**Comment by umrkhn** [comment]
@larkox sure go ahead, all yours now, thanks 👍

**Comment by Rutam21** [comment]
@lindy65 I would like to test this as the QA. You can assign this to me. Also, please let me know what all we are trying to test and confirm through this in the Web App and Desktop App. Thanks.

**Comment by lindy65** [comment]
Thank you @Rutam21 

image

Once the test server has been created, log in with the sysadmin credentials and go to the System Console from the Main Menu (grid icon) > Site Configuration > Customization. Change a few settings on the page and check whether Save works correctly.

**Comment by lindy65** [comment]
> Error trying to update the PR. Please do it manually.

Hi @umrkhn - please update your branch as I'm not able to - thanks!

**Comment by larkox** [comment]
@lindy65 Sorry, this PR is waiting on me. I have to fix a few things before it is ready to QA. I will let you and @Rutam21 know when this is ready to review.

**Comment by lindy65** [comment]
Aah, perfect, thanks @larkox !

**Comment by larkox** [comment]
Actually, once https://github.com/mattermost/mattermost/pull/24913 is merged, it should be fine without almost any changes.

**Comment by umrkhn** [comment]
@larkox do i need to update this branch?

**Comment by umrkhn** [comment]
@lindy65 in the meantime can you review this one instead as it has passed all the checks and requires your review. [#24809](https://github.com/mattermost/mattermost/pull/24809)

**Comment by larkox** [comment]
@umrkhn Yes, but we can wait until #24913 gets merged.

**Comment by Rutam21** [comment]
@lindy65 If #24913 needs a QA review, then I can work on that first and then can come back here once it's merged to complete this one.

**Comment by lindy65** [comment]
> @lindy65 If #24913 needs a QA review, then I can work on that first and then can come back here once it's merged to complete this one.

Will review soon @Rutam21 👍

**Comment by lindy65** [comment]
Actually @Rutam21 - would you like to QA [the PR](https://github.com/mattermost/mattermost/pull/24913)?

**Comment by Rutam21** [comment]
Yeah, Sure @lindy65

**Comment by larkox** [comment]
@umrkhn The PR is merged, so if you could merge master into this, and give it another go, it would be great. Thanks!

**Comment by larkox** [comment]
@Rutam21 Setting up the test server. When that is done, you should be ready to test this one :smile:

**Comment by umrkhn** [comment]
@larkox what's the status on this PR?

**Comment by lindy65** [comment]
> @larkox what's the status on this PR?

Hi @umrkhn - we are waiting on QA testing from @Rutam21 

Let me know if you're not able to test `Rutam21` and I'll go ahead and test for you.

**Comment by Rutam21** [comment]
@lindy65 I was away last week. But I will complete this today and update here soon.

**Comment by lindy65** [comment]
Awesome!  Thanks @Rutam21  :)

**Comment by Rutam21** [comment]
## I have tested the changes and it LGTM.

- We can make changes and save it.
- Changed Settings apply properly and are visible.

https://github.com/mattermost/mattermost/assets/47860497/c1fc35b2-d1b0-46a7-bb74-0948529b6309

cc: @lindy65

**Review by lindy65 — APPROVED** [review]
Thanks @umrkhn 👍 

Thanks for QA'ing @Rutam21 🎉 

cc @larkox

**Pull request merged**
