### PR TITLE
Minor refactor to simplify the getStateFromNotifyProps

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
This is just a minor refactor to simplify the logic around `getStateFromNotifyProps` in the Channel Notifications Modal.

There should be no changes in behavior, but I hope this is more resilient to edge cases.

#### Ticket Link
Fix https://mattermost.atlassian.net/browse/MM-54732

#### Release Note
None needed, just a refactor on a feature that releases in this release.
```release-note
NONE
```

### CODE REVIEW

**Comment by larkox** [comment]
@yasserfaraazkhan This is just a minor refactor on the way we get the information to populate the channel notification modal.

The idea to test this is to check again that all the information is as expected in all the corner cases we have already seen:
- New channel (GM or non GM) (for the case where the notify props are not initialized in the channel member)
- Channel notifications set to default and different user notifications
- Channel notifications set to different levels

This touches in particular three different pieces:
- Desktop notifications
- Push notifications
- Push threads notifications

Let me know if you think a ticket would be needed for tracking this for QA or the feature ticket is enough.

**Review by hmhealey — APPROVED** [review]

**Comment by yasserfaraazkhan** [comment]
@larkox I was not seeing desktop notification and mobile push notification appear. The messages come through as expected.
I'm trying this in 2.9.0 mobile and 5.5.1 desktop

**Comment by yasserfaraazkhan** [comment]
> @yasserfaraazkhan This PR does not change anything regarding how the notifications are sent. Just how the modal shows the information. Does this happen also on other PRs based from master?

Hi @larkox ,
I had same user opened in win desktop and mobile, that caused a little confusion.
I've tested it again. 
The GM functionality on different notification preferences is working as expected, for threads, mentions.

Just one observation like in [pr-24634](https://github.com/mattermost/mattermost/pull/24634#issuecomment-1746682185)

- IF user's global settings for desktop notification is **Never**
- A new GM will also have **Never**
- But the Channel Intro will say **For All activities**

would this be fixed by the other pr merging in master ? (I can check on master post merge)
Screenshot 2023-10-05 at 11 01 44 AM

**Comment by larkox** [comment]
@yasserfaraazkhan Yes, that one will be fixed in the other PR. When both are merged, it should be all fine.

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
