### PR TITLE
MM-60413: Fix issues due to incorrect cache provider

### PR DESCRIPTION
**Pull request by agnivade**
We were using a mock cache provider which mixed up LRU caches
with each other. This led to incorrect unmarshalling method calls.

We fix this by using the real cache provider.

https://mattermost.atlassian.net/browse/MM-60413

```release-note
NONE
```

### CODE REVIEW

**Review by agarciamontoro — APPROVED** [review]
Looks good! The other changes to use `model.UserMap` and to remove the special cases for  `*map[string]*model.User` are needed here or are simply additional independent changes?

**Comment by agnivade** [comment]
They will be additional independent changes.

**Review by streamer45 — APPROVED** [review]
Nice!

**Pull request merged**
