### PR TITLE
Translations update from Mattermost Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Mattermost Weblate](https://translate.mattermost.com) for [Mattermost/server](https://translate.mattermost.com/projects/mattermost/server/).

It also includes following components:

* [Mattermost/webapp](https://translate.mattermost.com/projects/mattermost/webapp/)

Current translation status:

Weblate translation status

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by ctlaltdieliet — APPROVED** [review]
lgtm

**Review by lieut-data — APPROVED** [review]

**Comment by ctlaltdieliet** [comment]
Hi @lieut-data 
Are the failing tests problematic? 
What can we do to resolve and to get the translations merged?

**Comment by lieut-data** [comment]
Indeed, there does appear to be something wrong with the translations -- is that something you can help with, @ctlaltdieliet?

CleanShot 2024-01-17 at 11 17 20@2x

**Review by lieut-data — APPROVED** [review]

**Pull request merged**
