### PR TITLE
Fix references from 'packages/*' to 'platform/*' in READMEs

### PR DESCRIPTION
**Pull request by mahaker**
#### Summary

webapp/packages does not exist.

#### Ticket Link

Nothing.

#### Screenshots

Nothing.

#### Release Note

Nothing.
```release-note

```

### CODE REVIEW

**Review by M-ZubairAhmed — CHANGES_REQUESTED** [review]
This is amazing thank you for doing it. Do you mind also including the change in https://github.com/mattermost/mattermost-server/blob/e300cb942adaea3c32d5e9f9ed71a7eae93392c2/webapp/README.md#L13-L14 webapp/Readme

**Comment by mahaker** [comment]
@M-ZubairAhmed 
Thank you for your review!
I've fixed that one too and force-pushed it.

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Review by harshilsharma63 — APPROVED** [review]

**Pull request merged**
