### PR TITLE
Update testlibrary helper.go to reflect Monorepo

### PR DESCRIPTION
**Pull request by sinansonmez**
#### Summary
Update testlibrary helper.go to reflect Monorepo

#### Ticket Link
None

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — COMMENTED** [review]
LGTM, though some dev environments may still have `mattermost-server` as root dir name. Shall we do a `os.Stat` to determine the root?

**Review by mgdelacroix — APPROVED** [review]
LGTM besides @isacikgoz's comment :+1:

**Comment by sinansonmez** [comment]
thanks @isacikgoz I used `os.Stat()` to determine the file path, please let me if I used it correctly

**Review by isacikgoz — APPROVED** [review]
Perfect, thanks @sinansonmez!

**Pull request merged**
