### PR TITLE
[MM-54128] api4/user: Deduplicate userids for getUsersByIds endpoint

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Add de-duplication for user ids for the `getUsersByIds` endoint

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-54128

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by streamer45 — APPROVED** [review]
Thanks @isacikgoz Could you create a follow up ticket for the more long-term solution, i.e. adding pagination support to this endpoint?

**Review by agarciamontoro — APPROVED** [review]
Neat!

**Review by jupenur — APPROVED** [review]

**Pull request merged**
