### PR TITLE
Fixed racy TestPanicLog test

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Fixed a racy test TestPanicLog

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-57377

#### Release Note
```release-note
none
```

### CODE REVIEW

**Comment by agnivade** [comment]
Updated the JIRA link which was incorrect.

**Review by agnivade — CHANGES_REQUESTED** [review]
@harshilsharma63 - Using `a.Log()` is correct. What we really need to fix is the test initialization code. SetLogger is being called _after_ server initialization which is the main mistake, especially when `SetLogger` is already an initialization option. Following code fixes the race:

```diff
--- a/server/channels/app/server_test.go
+++ b/server/channels/app/server_test.go
@@ -304,7 +304,6 @@ func checkEndpoint(t *testing.T, client *http.Client, url string) error {
 }

 func TestPanicLog(t *testing.T) {
-       t.Skip("MM-57377")
        // Creating a temp dir for log
        tmpDir, err := os.MkdirTemp("", "mlog-test")
        require.NoError(t, err, "cannot create tmp dir for log file")
@@ -323,16 +322,25 @@ func TestPanicLog(t *testing.T) {
        logSettings.FileLocation = &tmpDir
        logSettings.FileLevel = &mlog.LvlInfo.Name

-       cfg, err := config.MloggerConfigFromLoggerConfig(logSettings, nil, config.GetLogFileLocation)
+       logCfg, err := config.MloggerConfigFromLoggerConfig(logSettings, nil, config.GetLogFileLocation)
        require.NoError(t, err)
-       err = logger.ConfigureTargets(cfg, nil)
+       err = logger.ConfigureTargets(logCfg, nil)
        require.NoError(t, err)
        logger.LockConfiguration()

+       configStore, err := config.NewMemoryStore()
+       require.NoError(t, err)
+       store, err := config.NewStoreFromBacking(configStore, nil, false)
+       require.NoError(t, err)
+       cfg := store.Get()
+       cfg.SqlSettings = *mainHelper.GetSQLSettings()
+       store.Set(cfg)
+
        // Creating a server with logger
-       s, err := newServer(t)
+       s, err := NewServer(ConfigStore(store), SetLogger(logger))
        require.NoError(t, err)
-       s.Platform().SetLogger(logger)

        // Route for just panicking
        s.Router.HandleFunc("/panic", func(writer http.ResponseWriter, request *http.Request) {
```

You can revert the changes for `a.Log`

**Review by hanzei — CHANGES_REQUESTED** [review]
I agree with @agnivade that removing the calls to `a.Log()` is not the right way to fix the test.

**Review by agnivade — APPROVED** [review]
Thanks!

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Pull request merged**
