### PR TITLE
[MM-55095] Replace usage of LocalizedIcon in 'backstage_header.tsx' with i/span tags

### LINKED ISSUE #25084: Replace usage of LocalizedIcon in 'backstage_header.tsx' with i/span tags
Introduction

The purpose of this ticket is to eliminate the usage of LocalizedIcon in the `webapp/channels/src/components/backstage/components/backstage_header.tsx` file. LocalizedInput currently encourages the use of a custom 't' function, which deviates from the standard practices of the react-intl. We are transitioning to align all our translations with the principles and methods of react-intl, ensuring consistency throughout our codebase.

Before you start:

- Assignment Confirmation: Comment on this ticket to express your interest in owning it. This will help prevent task duplication.
- Environment Setup: Ensure your development environment is up and running. Follow the setup guide https://developers.mattermost.com/contribute/developer-setup
- Analyse: Navigate to the file referenced in this ticket and examine its usage within Mattermost. Capture screenshots of where and how LocalizedIcon(s) are used; these screenshots will be helpful for future comparisons in the PR.
- Best Practices: Familiarize yourself with the best practices for contributing to the Mattermost https://developers.mattermost.com/contribute/why-contribute

Guidelines During PR Development:

- Replace FormattedIcon Usage: If the LocalizedIcon has a prop-named `component` with the value `span` replace the component with a `<span/>` tag. Otherwise, use `<i/>` tag to replace the LocalizedIcon.
- Component Type: Determine whether the component you're modifying is a functional or a class component.
- For functional components, utilise the `useIntl` hook from react-intl to replace any instances of the `t` function with `formatMessage` for the component's title or aria label.
- For class components, apply the `injectIntl` Higher Order Component (HOC) from react-intl to use the `formatMessage` function. Replace any occurrences of the 't' function with `formatMessage` for the component's title or aria label.
- Testing: Visually verify that the changes didn't cause any alterations in the app's UI. Ensure any relevant tests are updated to reflect the changes made during this PR. In some cases, you might need to update snapshots. You can run `npm run test – -u` from the "channels" folder to update them.

Checklist Before PR Submission:

- Screenshots for Comparison: Capture screenshots of the places where you replaced LocalizedIcon. These screenshots will allow for a quick visual comparison within the PR, helping identify any unintended UI changes. Remember to include the screenshot you took earlier for a before-and-after comparison. Screenshots also make it easier for QA to locate and review the changes made to components.
- PR Title Format: Write the title of your PR using the following format: '[MM-jiraTicketNumber] Write the ticket title here'.
- CI Checks: Ensure all Continuous Integration checks have passed successfully. The review process can only commence when all CI checks are green.

For reference, you can follow this PR https://github.com/mattermost/mattermost/pull/25071

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-55095

### PR DESCRIPTION
**Pull request by sudheer121**
#### Summary

This MR resolves #25084 where the `LocalizedIcon` is replaced with `i` tag in `backstage_header` component

#### Ticket Link
JIRA: https://mattermost.atlassian.net/browse/MM-55095

#### Screenshots
|  before  |  after  |
|----|----|
| before |  after |
| before2 | after2 |

Not required

#### Release Note
- Replace the LocalizedIcon with i tag, update attributes with `react-intl` and update snapshots 
 

```release-note
NONE
```

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@sudheer121 as per the [instructions](https://github.com/mattermost/mattermost/issues/25084#issue-1958911211) please check the Checklist Before PR Submission for screenshots

**Comment by sudheer121** [comment]
> @sudheer121 as per the [instructions](https://github.com/mattermost/mattermost/issues/25084#issue-1958911211) please check the `Checklist Before PR Submission` for screenshots

oops, sorry for this @M-ZubairAhmed , went through the cheklist and added a screenshot 👍

**Review by M-ZubairAhmed — APPROVED** [review]
Outstanding work @sudheer121 🥁 🥁

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
