### PR TITLE
Fix errcheck issue in subpath_test.go

### PR DESCRIPTION
**Pull request by TheInvincibleRalph**
#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/28755

```release-note
NONE
```

### CODE REVIEW

**Comment by TheInvincibleRalph** [comment]
Fixed govet error

**Review by pvev — APPROVED** [review]
LGTM! thanks @TheInvincibleRalph 🎉

**Comment by TheInvincibleRalph** [comment]
All checks passed now @vish9812

**Review by vish9812 — APPROVED** [review]
LGTM! Thank you @TheInvincibleRalph :rocket:

**Pull request merged**
