### PR TITLE
Fail fast while connecting to replicas

### PR DESCRIPTION
**Pull request by agnivade**
Since we have the auto-retry mechanism for replicas,
there is not much benefit in trying 5 times before deciding
to move on.

In the earlier model, we would fail the server startup,
so it made sense to check as many times as possible.

Also reducing the sleep interval so that we can improve
the boot up time in case of a bad replica.
```release-note
NONE
```

### CODE REVIEW

**Review by isacikgoz — APPROVED** [review]
LGTM

**Review by streamer45 — APPROVED** [review]

**Comment by agnivade** [comment]
Finally!

**Pull request merged**
