### PR TITLE
Revert "MM-57759: Bump mockery to version 2.42.2 to support go  1.22^"

### PR DESCRIPTION
**Pull request by agnivade**
Reverts mattermost/mattermost#26761

Master CI started to fail because of:
```
go: github.com/vektra/mockery/v2@v2.42.2 requires go >= 1.22; switching to go1.22.2
```

We cannot automatically switch to 1.22.

### CODE REVIEW

**Comment by agnivade** [comment]
Sorry about that @ezekielchow. Looks like we can't use 1.22 yet.

**Review by hanzei — COMMENTED** [review]
Are you sure CI broke because of the go version? At least locally, I see that a file didn't got updated: https://github.com/mattermost/mattermost/pull/26761#issuecomment-2051324499

**Comment by agnivade** [comment]
Ah true, it's not because of the Go version. It's because of 

```go
diff --git a/server/public/plugin/plugintest/hooks.go b/server/public/plugin/plugintest/hooks.go
index 2586588a6d..69f8477c71 100644
--- a/server/public/plugin/plugintest/hooks.go
+++ b/server/public/plugin/plugintest/hooks.go
@@ -121,6 +121,10 @@ func (_m *Hooks) FileWillBeUploaded(c *plugin.Context, info *model.FileInfo, fil
 func (_m *Hooks) GenerateSupportData(c *plugin.Context) ([]*model.FileData, error) {
        ret := _m.Called(c)

+       if len(ret) == 0 {
+               panic("no return value specified for GenerateSupportData")
+       }
+
        var r0 []*model.FileData
        var r1 error
        if rf, ok := ret.Get(0).(func(*plugin.Context) ([]*model.FileData, error)); ok {
```

 But in any case, we cannot let the CI silently upgrade Go version because there might be other unforeseen effects.

**Comment by hanzei** [comment]
Actually, I was excited to see that `mockery` was installed using go1.22, as that is the selling point of the go toolchain changes. Every tool can freely pick its go version and run with it. Please note that it is only `mockery` gets installed using go1.22, not the MM binary.

This is an excellent demonstration of the flexibility that Go provides now. MM devs can use go1.22 locally while MM is still built using go1.21.

**Review by amyblais — APPROVED** [review]

**Review by hanzei — APPROVED** [review]
Let's merge this to fix `master`.

I still think using go1.22 for mockery is not an issue, and the original PR is valid. But we can disucss that later.

**Comment by agnivade** [comment]
> Please note that it is only mockery gets installed using go1.22, not the MM binary.

Ah you are right. I misunderstood the feature then. Happy to re-send another PR!

**Pull request merged**
