### PR TITLE
[MM-56798] Smoothen animation and lazy load User Settings

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
The user settings modal had the following problems
- They wrapped around with Redux Provider code
- The sidebar and the content both had separate code splitting leading to the jarring opening behavior on first load as seen in the screen grab.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-56798

#### Screenshots
Before

https://github.com/mattermost/mattermost/assets/17708702/3affeaa8-4cee-4d7f-b4b6-7e1b267f0f32

After

https://github.com/mattermost/mattermost/assets/17708702/de769f71-4e9e-4a20-bc3f-9597618b6fe8

#### Release Note

```release-note
Improved opening animation of user settings modal.
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]
Nice find. I know we tried adding lazy loading to stuff early on, and it was often done pretty randomly. It's odd to me that we split the modal and its sidebar when those are pretty tightly coupled, so I think it makes sense to load the whole modal at once.

I think you might want to note that we've improved the loading animation of this modal in the changelog message since this actually seems like the sort of improvement users would want to know about

**Comment by hmhealey** [comment]
Also it'd be a good idea to CC @AshishDhama on this since he's been making some improvements to these modals and there's a small chance that these might conflict since they're in the same area

**Review by yasserfaraazkhan — APPROVED** [review]
tested this on chrome and desktop 5.7 (the release candidate).

User settings, team setting, search, channel header edit, browse channel, create , invite, add members to channel and few more models work as expected.

User setting modal takes probably half a second to load for the very first time. Later on it opens quickly.

**Pull request merged**
