### PR TITLE
[MM-57521] Profile button on hover shouldn't be red

### PR DESCRIPTION
**Pull request by kalil0321**
#### Summary

When clicking your profile photo > then hovering over the profile button it isn't red anymore. Now there isn't any style on hover for the profile button. 

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/26915
Jira https://mattermost.atlassian.net/browse/MM-57521

#### Screenshots

|  before  |  after  |
|----|----|
| mattermost-old | mattermost-new |

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by hanzei** [comment]
@asaadmahmood Gentle reminder to review the PR :smiley:

**Review by asaadmahmood — APPROVED** [review]
LGTM

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by hmhealey** [comment]
Thanks again for the PR, @kalil0321! Now that this is merged, it should be in Mattermost 10.0 coming out in September

**Comment by kalil0321** [comment]
> Thanks for the fix, @kalil0321!
> 
> 
> 
> I'm a bit surprised that this is as straightforward of a change as it is. Usually this sort of bug involves some convoluted CSS that has a bunch of conflicting rules and edge cases, so it's funny to me that the CSS simply says "turn this red on hover" when it shouldn't. Regardless of that though, we still really appreciate the help with it!

Yes it was a really small fix.

**Pull request merged**
