### PR TITLE
Return error on already existing DMs and GMs

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary
Custom build that returns an error when attempting to create a DM or a GM that already exists.

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by agarciamontoro** [comment]
This is what I'm testing. It looks good locally. I'll test in the instance now.

**Comment by streamer45** [comment]
Would be interesting to test the webapp behaviour on the modded version and see if it goes crazy as soon as you reopen a closed DM or stuff like that.

**Comment by agarciamontoro** [comment]
> Would be interesting to test the webapp behaviour on the modded version and see if it goes crazy as soon as you reopen a closed DM or stuff like that.

Would that matter for the data generation?

**Comment by agnivade** [comment]
Looks good. Some i18n errors.

**Comment by streamer45** [comment]
> > Would be interesting to test the webapp behaviour on the modded version and see if it goes crazy as soon as you reopen a closed DM or stuff like that.
> 
> Would that matter for the data generation?

Nah, only if we were to make a change in product, unlikely at this point. Mostly curious to see if there's a reason to have it this way or else.

**Comment by agarciamontoro** [comment]
Closing this PR, which won't be merged.

**Pull request closed without merging**
