### PR TITLE
Centralize the GetPackagePath

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
As part of the change to [eliminate MM_SERVER_PATH](https://github.com/mattermost/mattermost/pull/24968), I thought I had properly tested plugins relying on the server for tests, but apparently not, as these tests were now failing trying to resolve the `i18n` directory.

To remedy this, and address feedback from the first PR, I've centralized a single `path.go` in the `server` root from which all other paths are built. The return value from this also gets added to the search paths for resolving asset directories at runtime. (Like `MM_SERVER_PATH` did before, but now unconditionally.)

Tested this time with the MS Teams plugin and can confirm the before and after effect of this PR.

#### Ticket Link
None.

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by lieut-data** [comment]
@agnivade & @wiggin77, despite my [claims](https://github.com/mattermost/mattermost/pull/24968#issuecomment-2102874089) otherwise, my changes to `MM_SERVER_PATH` did require some reworking (though thankfully only as the plugin updates dependencies).

I've re-tested this again with MS Teams, but would love your eyes again :)

**Review by agnivade — APPROVED** [review]

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:    One thing that comes to mind that I should have included in the previous review... the `GetPackagePath` implementation may break if the place it is called from gets inlined.  I think it's possible the result will be wrong if the inlined function is called from a different package.

**Comment by lieut-data** [comment]
Good call out, @wiggin77! I'll keep this in mind if we see unexpected breakage in the future.

**Pull request merged**
