### PR TITLE
Adding AI plugin to pre-packaged plugins

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary

Adding the Mattermost AI plugin https://github.com/mattermost/mattermost-plugin-ai to be a pre-packaged plugin.

#### Release Note

```release-note
Adding mattermost-plugin-ai to pre-packaged plugins.
```

### CODE REVIEW

**Comment by amyblais** [comment]
@crspeller There are failing tests here.

**Review by amyblais — APPROVED** [review]

**Comment by cwarnermm** [comment]
@esethna - Is the AI Plugin an Experimental or Beta release?

**Comment by crspeller** [comment]
@cwarnermm We have it tagged as "beta"

**Pull request merged**
