### PR TITLE
[MM-54357] Fixes Recent Mentions showing posts for other similar named users

### PR DESCRIPTION
**Pull request by vish9812**
#### Summary

- Fixes Recent Mentions showing posts for other similar named users.
- Recent Mention now sends first-name and username(even without `@`) within quotes.

#### Ticket Link

JIRA - https://mattermost.atlassian.net/browse/MM-54357
Previous related PR - https://github.com/mattermost/mattermost/pull/25010

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Great catch! I remember seeing that ticket and wondering how this was possible when we quoted the username without realizing that the issue could also be with the other mention keywords

**Review by harshilsharma63 — APPROVED** [review]
LGTM 🚀

**Comment by vish9812** [comment]
@lindalumitchell gentle reminder to test this one.

**Review by lindalumitchell — APPROVED** [review]
Thanks for the ping and apologies for the delay! Verified on the test server that recent mentions work as expected with the option `Your non case-sensitive username` in use, with two usernames that begin with the same characters `a-`. Verified with that setting on and off, and in combination with keywords that cause mentions as well. LGTM!

**Pull request merged**
