### PR TITLE
[MM-23413] webapp/channels: Migrate "components/list_modal.test.jsx" to Typescript

### PR DESCRIPTION
**Pull request by ivalkshfoeif**
#### Summary

Migrate "components/list_modal.test.jsx" to Typescript

#### Ticket Link

https://github.com/mattermost/mattermost/issues/23413
https://mattermost.atlassian.net/browse/MM-52847

#### Release Note

None

```release-note
None
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by ivalkshfoeif** [comment]
Hi, @M-ZubairAhmed, it seems that ee/circleci check failed for this PR, can you show me how to find the root cause? I can't access the details of this check.

**Comment by M-ZubairAhmed** [comment]
> Hi, @M-ZubairAhmed, it seems that ee/circleci check failed for this PR, can you show me how to find the root cause? I can't access the details of this check.

It runs the e2e test on closed source part of the mattermost code, hence its restricted. Dont worry I have re run it again.

**Review by harshilsharma63 — APPROVED** [review]

**Pull request merged**
