### PR TITLE
MM-53301 Add missing column-add for Configurations.SHA to ESR migration scripts.

### PR DESCRIPTION
**Pull request by wiggin77**
#### Summary
The ESR migration scripts are missing a script that adds the `Configurations` table and [adds SHA column to Configurations table](https://github.com/mattermost/mattermost/blob/release-7.8/config/migrations/mysql/000003_update_configurations_sha.up.sql).  The script was added for 6.7 therefore only the ESR's covering that version have been updated.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-53301

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by wiggin77** [comment]
@isacikgoz I think there is an additional problem in that the code [here](https://github.com/mattermost/mattermost/blob/5a540ea23ef0df2c32527cf4d59252e4d209626e/server/config/database.go#L238) can run before the migrations are completed.  This is why the server errored on startup.
```
Jun 22 13:29:16 lcht03va systemd[1]: Started Mattermost.
Jun 22 13:29:16 lcht03va mattermost[1006088]: Error: failed to load configuration: failed to create store: unable to load on store creation: failed to persist: failed to query active configuration: Error 1054 (42S22): Unknown column 'SHA' in 'field list'
Jun 22 13:29:16 lcht03va mattermost[1006088]: Usage:
Jun 22 13:29:16 lcht03va mattermost[1006088]:   mattermost [flags]
Jun 22 13:29:16 lcht03va mattermost[1006088]:   mattermost [command]
Jun 22 13:29:16 lcht03va mattermost[1006088]: Available Commands:
Jun 22 13:29:16 lcht03va mattermost[1006088]:   completion  Generate the autocompletion script for the specified shell
Jun 22 13:29:16 lcht03va mattermost[1006088]:   db          Commands related to the database
Jun 22 13:29:16 lcht03va mattermost[1006088]:   export      Export data from Mattermost
Jun 22 13:29:16 lcht03va mattermost[1006088]:   help        Help about any command
Jun 22 13:29:16 lcht03va mattermost[1006088]:   import      Import data.
Jun 22 13:29:16 lcht03va mattermost[1006088]:   jobserver   Start the Mattermost job server
Jun 22 13:29:16 lcht03va mattermost[1006088]:   server      Run the Mattermost server
Jun 22 13:29:16 lcht03va mattermost[1006088]:   version     Display version information
Jun 22 13:29:16 lcht03va mattermost[1006088]: Flags:
Jun 22 13:29:16 lcht03va mattermost[1006088]:   -c, --config string   Configuration file to use.
Jun 22 13:29:16 lcht03va mattermost[1006088]:   -h, --help            help for mattermost
Jun 22 13:29:16 lcht03va mattermost[1006088]: Use "mattermost [command] --help" for more information about a command.
```

**Review by agarciamontoro — CHANGES_REQUESTED** [review]
Good catch! Would you be willing to maintain the style of the files? Which comes down to a couple of things:
1.In both files, start the migration changes with the migration number of the file from where it was extracted, just for easier reference later on. With this I mean the comments that start with `/* ==> ` in the other parts of the file.
2. In the 5.37-7.8 file, follow the structure of the other migrations by merging all the queries related to a specific table in a single query. This is done in the rest of the file by building a single procedure for a table, and building the query inside of it by checking the different conditions.

Also, I think we don't need to create the `Configurations` and `ConfigurationFiles` table if the server is in 5.37 or in 6.3, right?

**Comment by wiggin77** [comment]
> I think we don't need to create the `Configurations` and `ConfigurationFiles` table

@agarciamontoro I saw somewhere where @isacikgoz said none of the `/config/migrations` scripts should be in the ESR scripts.  As such I think this PR will be closed without merging.   We're still left with the underlying issue that server start-up tries to use the missing field before the migration is complete.  I created a ticket for that:  https://mattermost.atlassian.net/browse/MM-53350

**Comment by isacikgoz** [comment]
> We're still left with the underlying issue that server start-up tries to use the missing field before the migration is complete.

This is the exact issue here, because ESR to ESR scripts should not be an issue for configurations. At least the issue that user had is very interesting and it requires some deep look.

Having said that, @wiggin77 I think we should still get the size of `Configurations` table as a good practice for large upgrade scenarios. Before `v6.7`(#19987), each configuration was being recorded to the DB w/o any cleanup. This led to millions of configuration records which made huge problems in MySQL due to interesting indexing issues. For context see: https://github.com/mattermost/mattermost/pull/19975#discussion_r849939741

**Comment by wiggin77** [comment]
> I think we should still get the size of `Configurations` table as a good practice for large upgrade scenarios.

Can you clarify what you mean by "get".  Do you meant check this in code before migration step?  If you mean ask the customer, then what will we do based on the answer, and why can't we just do that in code?

**Comment by wiggin77** [comment]
Based on @isacikgoz 's comment [here](https://mattermost.atlassian.net/browse/MM-53350?focusedCommentId=153474), I think we will merge this PR after all.

**Comment by agarciamontoro** [comment]
@wiggin77, heads-up that CI is not running the ESR tests per https://github.com/mattermost/mattermost/pull/23807 We need to fix https://mattermost.atlassian.net/browse/MM-53275 before enabling them again.

**Review by isacikgoz — APPROVED** [review]
Nothing to block from my side, thanks @wiggin77 for handling this.

**Comment by wiggin77** [comment]
Closing as the PR is becoming very out of date.

**Pull request closed without merging**
