### PR TITLE
Change dnd status and remind to next morning

### PR DESCRIPTION
**Pull request by svelle**
Finally found some time to move the changes proposed in this PR to the new monorepo.

https://github.com/mattermost/mattermost-webapp/pull/12349

#### Summary

This PR changes the timers in the dnd timer and post reminder modals to use "next day 8 am" instead of "24hrs from now" when selecting Tomorrow as the option since that would be a more common use case for these types if timers (i.e. don't bug me with notifications until my next workday starts or send me the reminder at the beginning of my next work day).

Not sure if we actually *need* release notes for this but added some just in case.

#### Screenshots

|  before  |  after  |
|----|----|
| remind_old | image (5) |
| dnd_old | dnd_new |

#### Release Note

```release-note
Changed the time for tomorrow in the dnd timer and post reminder to refer to the next day 9 am instead of 24hrs from the time of activation.
```

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
The code looks good to me. I fired off the E2E tests since I wouldn't be surprised if some of those need to be updated for the new behaviour, but we'll see how those go

**Comment by hmhealey** [comment]
And I swapped the second reviewer to Caleb since he was involved in the original PR. It looks to me like the feedback he had on that was addressed though.

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by M-ZubairAhmed** [comment]
@johndavidlugtu Would you know if it next day is 8AM, because i remember we have other tickets where next day was 9ish?

**Comment by johndavidlugtu** [comment]
Good callout @M-ZubairAhmed -- this should be default 9am @svelle 

https://mattermost.atlassian.net/browse/MM-54714

**Comment by calebroseland** [comment]
@svelle @marianunez Seems we have 2 PRs for this (other one: https://github.com/mattermost/mattermost/pull/24719, which has a couple nice additions, but may potentially need a unit test)

**Comment by Whoaa512** [comment]
What’s blocked on this? I’m eagerly waiting to not have to rebuild my local Mattermost for this change

**Comment by svelle** [comment]
sorry, totally missed the comment there @M-ZubairAhmed changed it to 9am instead and updated the snapshots

**Review by johndavidlugtu — APPROVED** [review]
Great stuff @svelle !

This would be good to demo in one of those R&D session

**Comment by svelle** [comment]
> Great stuff @svelle !
> 
> This would be good to demo in one of those R&D session

Thanks John, I'd be happy to!

**Review by calebroseland — APPROVED** [review]

**Comment by hmhealey** [comment]
@M-ZubairAhmed I reassigned you as reviewer since you previously wanted to review this, but feel free to dismiss the review request if you're busy. We already have 2 dev reviews on this anyway

**Review by yasserfaraazkhan — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]

**Pull request merged**
